//go:build physical

package main

import (
	"fmt"
	"strings"
	"testing"

	"github.com/polyspec/orm/internal/testcase"
	"github.com/polyspec/orm/internal/testdb"
)

// TestPhysicalPostgresCounterOwner restores PostgreSQL sequences by the table
// that owns them. A table name long enough that PostgreSQL truncates the name
// of its serial sequence (63 bytes) still restores, and a changed sequence
// that no table owns, or that an undeclared table owns, is refused.
func TestPhysicalPostgresCounterOwner(t *testing.T) {
	testcase.Start(t, testcase.Database)
	dsn := testdb.New(t, "postgres")
	db, err := openStateDatabase("postgres", dsn)
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	long := "conformance_counter_owner_" + strings.Repeat("x", 63-len("conformance_counter_owner_"))
	conformanceWriteTables[long] = true
	t.Cleanup(func() { delete(conformanceWriteTables, long) })
	for _, statement := range []string{
		fmt.Sprintf(`CREATE TABLE %s (seq bigserial PRIMARY KEY, label text)`, quoteIdentifier(long)),
		`CREATE TABLE task (seq bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, label text)`,
		`CREATE TABLE undeclared (seq bigserial PRIMARY KEY, label text)`,
		`CREATE SEQUENCE task_seq_seq_free`,
	} {
		if _, err := db.Exec(statement); err != nil {
			t.Fatal(err)
		}
	}
	var sequence string
	if err := db.QueryRow(`SELECT pg_get_serial_sequence($1, 'seq')`, quoteIdentifier(long)).Scan(&sequence); err != nil {
		t.Fatal(err)
	}
	if strings.Contains(sequence, long) {
		t.Fatalf("the sequence %s keeps the whole table name; the case needs a truncated one", sequence)
	}
	t.Logf("table %s owns sequence %s", long, sequence)
	before, err := readCounters(db, "postgres")
	if err != nil {
		t.Fatal(err)
	}
	insert := func(table string) {
		t.Helper()
		if _, err := db.Exec(fmt.Sprintf(`INSERT INTO %s (label) VALUES ('a'), ('b')`, quoteIdentifier(table))); err != nil {
			t.Fatal(err)
		}
	}
	insert(long)
	insert("task")
	if err := restoreCounters(db, "postgres", before); err != nil {
		t.Fatalf("restore the counters of declared tables: %v", err)
	}
	after, err := readCounters(db, "postgres")
	if err != nil {
		t.Fatal(err)
	}
	for name, value := range before {
		if after[name] != value {
			t.Errorf("counter %s is %+v after the restore, want %+v", name, after[name], value)
		}
	}
	insert("undeclared")
	if err := restoreCounters(db, "postgres", before); err == nil || !strings.Contains(err.Error(), "undeclared postgres counter changed") {
		t.Fatalf("a sequence of an undeclared table: %v", err)
	}
	if _, err := db.Exec(`SELECT setval('undeclared_seq_seq', 1, false)`); err != nil {
		t.Fatal(err)
	}
	if _, err := db.Exec(`SELECT nextval('task_seq_seq_free')`); err != nil {
		t.Fatal(err)
	}
	if err := restoreCounters(db, "postgres", before); err == nil || !strings.Contains(err.Error(), "owned by no table") {
		t.Fatalf("a sequence that no table owns: %v", err)
	}
}
