package generator

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/polyspec/orm/engine/runtimemodel"
	"github.com/polyspec/orm/internal/testcase"
)

func TestGenerateUsesCanonicalManifestForGoClient(t *testing.T) {
	testcase.Start(t, testcase.Compute)
	manifest := sampleModel(t)
	out := filepath.Join(t.TempDir(), "model")
	if err := Generate(Options{Model: manifest, OutputDir: out}); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(out, "sample.go")); err != nil {
		t.Fatalf("generated ORM client is missing: %v", err)
	}
}

func TestGenerateUsesRequestedGoPackageName(t *testing.T) {
	testcase.Start(t, testcase.Compute)
	manifest := sampleModel(t)
	out := t.TempDir()
	if err := Generate(Options{Model: manifest, OutputDir: out, PackageName: "storage"}); err != nil {
		t.Fatal(err)
	}
	body, err := os.ReadFile(filepath.Join(out, "sample.go"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(body), "// Code generated by orm-gen; DO NOT EDIT.\n\npackage storage\n") {
		t.Fatalf("generated client does not use requested package: %s", body[:min(len(body), 120)])
	}
	init, err := os.ReadFile(filepath.Join(out, "orm.go"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(init), "package storage") {
		t.Fatal("generated initializer does not use requested package")
	}
}

// sampleModel은 identity column 하나인 table의 runtime model이다.
func sampleModel(t *testing.T) *runtimemodel.Model {
	t.Helper()
	m, diagnostics := runtimemodel.LoadDocuments([]string{"dbspec 1 sample\n\ntable sample {\n  seq i64 identity\n  primary key (seq)\n}\n"})
	if len(diagnostics) > 0 {
		t.Fatal(runtimemodel.DiagnosticsError(diagnostics))
	}
	return m
}
