package generator

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/polyspec/orm/engine/schema"
)

func TestGenerateUsesCanonicalManifestForGoClient(t *testing.T) {
	document, err := schema.Parse(`erDiagram
  sample {
    bigint seq PK "auto"
  }
`)
	if err != nil {
		t.Fatal(err)
	}
	manifest, err := schema.Build(document)
	if err != nil {
		t.Fatal(err)
	}
	out := t.TempDir()
	if err := Generate(Options{Manifest: manifest, Language: Go, OutputDir: out}); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(out, "sample.go")); err != nil {
		t.Fatalf("generated ORM client is missing: %v", err)
	}
}

func TestGenerateUsesRequestedGoPackageName(t *testing.T) {
	document, err := schema.Parse("erDiagram\n  sample {\n    bigint seq PK \"auto\"\n  }\n")
	if err != nil {
		t.Fatal(err)
	}
	manifest, err := schema.Build(document)
	if err != nil {
		t.Fatal(err)
	}
	out := t.TempDir()
	if err := Generate(Options{Manifest: manifest, Language: Go, OutputDir: out, PackageName: "storage"}); err != nil {
		t.Fatal(err)
	}
	body, err := os.ReadFile(filepath.Join(out, "sample.go"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(body), "// Code generated by ormgen; DO NOT EDIT.\n\npackage storage\n") {
		t.Fatalf("generated client does not use requested package: %s", body[:min(len(body), 120)])
	}
	init, err := os.ReadFile(filepath.Join(out, "orm_init.go"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(init), "package storage") {
		t.Fatal("generated initializer does not use requested package")
	}
}
