// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/orm/compiler/v1/compiler.proto

package compilerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryKind int32

const (
	QueryKind_QUERY_KIND_UNSPECIFIED    QueryKind = 0
	QueryKind_QUERY_KIND_ONE            QueryKind = 1
	QueryKind_QUERY_KIND_ALL            QueryKind = 2
	QueryKind_QUERY_KIND_COUNT          QueryKind = 3
	QueryKind_QUERY_KIND_GROUP_COUNT    QueryKind = 4
	QueryKind_QUERY_KIND_COUNT_DISTINCT QueryKind = 5
	QueryKind_QUERY_KIND_SUM            QueryKind = 6
	QueryKind_QUERY_KIND_AVG            QueryKind = 7
	QueryKind_QUERY_KIND_MIN            QueryKind = 8
	QueryKind_QUERY_KIND_MAX            QueryKind = 9
	QueryKind_QUERY_KIND_PAGINATE       QueryKind = 10
	QueryKind_QUERY_KIND_INSERT         QueryKind = 11
	QueryKind_QUERY_KIND_UPDATE         QueryKind = 12
	QueryKind_QUERY_KIND_DELETE         QueryKind = 13
	QueryKind_QUERY_KIND_RAW            QueryKind = 14
)

// Enum value maps for QueryKind.
var (
	QueryKind_name = map[int32]string{
		0:  "QUERY_KIND_UNSPECIFIED",
		1:  "QUERY_KIND_ONE",
		2:  "QUERY_KIND_ALL",
		3:  "QUERY_KIND_COUNT",
		4:  "QUERY_KIND_GROUP_COUNT",
		5:  "QUERY_KIND_COUNT_DISTINCT",
		6:  "QUERY_KIND_SUM",
		7:  "QUERY_KIND_AVG",
		8:  "QUERY_KIND_MIN",
		9:  "QUERY_KIND_MAX",
		10: "QUERY_KIND_PAGINATE",
		11: "QUERY_KIND_INSERT",
		12: "QUERY_KIND_UPDATE",
		13: "QUERY_KIND_DELETE",
		14: "QUERY_KIND_RAW",
	}
	QueryKind_value = map[string]int32{
		"QUERY_KIND_UNSPECIFIED":    0,
		"QUERY_KIND_ONE":            1,
		"QUERY_KIND_ALL":            2,
		"QUERY_KIND_COUNT":          3,
		"QUERY_KIND_GROUP_COUNT":    4,
		"QUERY_KIND_COUNT_DISTINCT": 5,
		"QUERY_KIND_SUM":            6,
		"QUERY_KIND_AVG":            7,
		"QUERY_KIND_MIN":            8,
		"QUERY_KIND_MAX":            9,
		"QUERY_KIND_PAGINATE":       10,
		"QUERY_KIND_INSERT":         11,
		"QUERY_KIND_UPDATE":         12,
		"QUERY_KIND_DELETE":         13,
		"QUERY_KIND_RAW":            14,
	}
)

func (x QueryKind) Enum() *QueryKind {
	p := new(QueryKind)
	*p = x
	return p
}

func (x QueryKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_orm_compiler_v1_compiler_proto_enumTypes[0].Descriptor()
}

func (QueryKind) Type() protoreflect.EnumType {
	return &file_proto_orm_compiler_v1_compiler_proto_enumTypes[0]
}

func (x QueryKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryKind.Descriptor instead.
func (QueryKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{0}
}

type Projection_Mode int32

const (
	Projection_MODE_DEFAULT Projection_Mode = 0
	Projection_MODE_ALL     Projection_Mode = 1
	Projection_MODE_NONE    Projection_Mode = 2
)

// Enum value maps for Projection_Mode.
var (
	Projection_Mode_name = map[int32]string{
		0: "MODE_DEFAULT",
		1: "MODE_ALL",
		2: "MODE_NONE",
	}
	Projection_Mode_value = map[string]int32{
		"MODE_DEFAULT": 0,
		"MODE_ALL":     1,
		"MODE_NONE":    2,
	}
)

func (x Projection_Mode) Enum() *Projection_Mode {
	p := new(Projection_Mode)
	*p = x
	return p
}

func (x Projection_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Projection_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_orm_compiler_v1_compiler_proto_enumTypes[1].Descriptor()
}

func (Projection_Mode) Type() protoreflect.EnumType {
	return &file_proto_orm_compiler_v1_compiler_proto_enumTypes[1]
}

func (x Projection_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Projection_Mode.Descriptor instead.
func (Projection_Mode) EnumDescriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{2, 0}
}

type CompileRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IrVersion      uint32                 `protobuf:"varint,1,opt,name=ir_version,json=irVersion,proto3" json:"ir_version,omitempty"`
	SchemaHash     string                 `protobuf:"bytes,2,opt,name=schema_hash,json=schemaHash,proto3" json:"schema_hash,omitempty"`
	Kind           QueryKind              `protobuf:"varint,3,opt,name=kind,proto3,enum=orm.compiler.v1.QueryKind" json:"kind,omitempty"`
	Root           *QueryNode             `protobuf:"bytes,4,opt,name=root,proto3" json:"root,omitempty"`
	Set            []*Assignment          `protobuf:"bytes,5,rep,name=set,proto3" json:"set,omitempty"`
	OnDuplicate    []*Assignment          `protobuf:"bytes,6,rep,name=on_duplicate,json=onDuplicate,proto3" json:"on_duplicate,omitempty"`
	Optimistic     *Optimistic            `protobuf:"bytes,7,opt,name=optimistic,proto3" json:"optimistic,omitempty"`
	Raw            *Raw                   `protobuf:"bytes,8,opt,name=raw,proto3" json:"raw,omitempty"`
	ParameterCount uint32                 `protobuf:"varint,9,opt,name=parameter_count,json=parameterCount,proto3" json:"parameter_count,omitempty"`
	Aggregate      string                 `protobuf:"bytes,10,opt,name=aggregate,proto3" json:"aggregate,omitempty"`
	Debug          bool                   `protobuf:"varint,11,opt,name=debug,proto3" json:"debug,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompileRequest) Reset() {
	*x = CompileRequest{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileRequest) ProtoMessage() {}

func (x *CompileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileRequest.ProtoReflect.Descriptor instead.
func (*CompileRequest) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{0}
}

func (x *CompileRequest) GetIrVersion() uint32 {
	if x != nil {
		return x.IrVersion
	}
	return 0
}

func (x *CompileRequest) GetSchemaHash() string {
	if x != nil {
		return x.SchemaHash
	}
	return ""
}

func (x *CompileRequest) GetKind() QueryKind {
	if x != nil {
		return x.Kind
	}
	return QueryKind_QUERY_KIND_UNSPECIFIED
}

func (x *CompileRequest) GetRoot() *QueryNode {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *CompileRequest) GetSet() []*Assignment {
	if x != nil {
		return x.Set
	}
	return nil
}

func (x *CompileRequest) GetOnDuplicate() []*Assignment {
	if x != nil {
		return x.OnDuplicate
	}
	return nil
}

func (x *CompileRequest) GetOptimistic() *Optimistic {
	if x != nil {
		return x.Optimistic
	}
	return nil
}

func (x *CompileRequest) GetRaw() *Raw {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *CompileRequest) GetParameterCount() uint32 {
	if x != nil {
		return x.ParameterCount
	}
	return 0
}

func (x *CompileRequest) GetAggregate() string {
	if x != nil {
		return x.Aggregate
	}
	return ""
}

func (x *CompileRequest) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

type QueryNode struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Entity            string                 `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Columns           *Projection            `protobuf:"bytes,2,opt,name=columns,proto3" json:"columns,omitempty"`
	On                *Group                 `protobuf:"bytes,3,opt,name=on,proto3" json:"on,omitempty"`
	Where             *Group                 `protobuf:"bytes,4,opt,name=where,proto3" json:"where,omitempty"`
	Having            *Group                 `protobuf:"bytes,5,opt,name=having,proto3" json:"having,omitempty"`
	Joins             []*Join                `protobuf:"bytes,6,rep,name=joins,proto3" json:"joins,omitempty"`
	Relations         []*Relation            `protobuf:"bytes,7,rep,name=relations,proto3" json:"relations,omitempty"`
	Order             []*Order               `protobuf:"bytes,8,rep,name=order,proto3" json:"order,omitempty"`
	GroupBy           []string               `protobuf:"bytes,9,rep,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	GroupByExpression []*GroupExpression     `protobuf:"bytes,10,rep,name=group_by_expression,json=groupByExpression,proto3" json:"group_by_expression,omitempty"`
	Limit             *Limit                 `protobuf:"bytes,11,opt,name=limit,proto3" json:"limit,omitempty"`
	Distinct          bool                   `protobuf:"varint,12,opt,name=distinct,proto3" json:"distinct,omitempty"`
	ForceIndex        string                 `protobuf:"bytes,13,opt,name=force_index,json=forceIndex,proto3" json:"force_index,omitempty"`
	KeyBy             string                 `protobuf:"bytes,14,opt,name=key_by,json=keyBy,proto3" json:"key_by,omitempty"`
	Flatten           bool                   `protobuf:"varint,15,opt,name=flatten,proto3" json:"flatten,omitempty"`
	LimitPerParent    uint32                 `protobuf:"varint,16,opt,name=limit_per_parent,json=limitPerParent,proto3" json:"limit_per_parent,omitempty"`
	IfParent          *IfParent              `protobuf:"bytes,17,opt,name=if_parent,json=ifParent,proto3" json:"if_parent,omitempty"`
	DropChildKey      bool                   `protobuf:"varint,18,opt,name=drop_child_key,json=dropChildKey,proto3" json:"drop_child_key,omitempty"`
	NoCascadeDelete   bool                   `protobuf:"varint,19,opt,name=no_cascade_delete,json=noCascadeDelete,proto3" json:"no_cascade_delete,omitempty"`
	ScopeParameter    *uint32                `protobuf:"varint,20,opt,name=scope_parameter,json=scopeParameter,proto3,oneof" json:"scope_parameter,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QueryNode) Reset() {
	*x = QueryNode{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNode) ProtoMessage() {}

func (x *QueryNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryNode.ProtoReflect.Descriptor instead.
func (*QueryNode) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{1}
}

func (x *QueryNode) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *QueryNode) GetColumns() *Projection {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *QueryNode) GetOn() *Group {
	if x != nil {
		return x.On
	}
	return nil
}

func (x *QueryNode) GetWhere() *Group {
	if x != nil {
		return x.Where
	}
	return nil
}

func (x *QueryNode) GetHaving() *Group {
	if x != nil {
		return x.Having
	}
	return nil
}

func (x *QueryNode) GetJoins() []*Join {
	if x != nil {
		return x.Joins
	}
	return nil
}

func (x *QueryNode) GetRelations() []*Relation {
	if x != nil {
		return x.Relations
	}
	return nil
}

func (x *QueryNode) GetOrder() []*Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *QueryNode) GetGroupBy() []string {
	if x != nil {
		return x.GroupBy
	}
	return nil
}

func (x *QueryNode) GetGroupByExpression() []*GroupExpression {
	if x != nil {
		return x.GroupByExpression
	}
	return nil
}

func (x *QueryNode) GetLimit() *Limit {
	if x != nil {
		return x.Limit
	}
	return nil
}

func (x *QueryNode) GetDistinct() bool {
	if x != nil {
		return x.Distinct
	}
	return false
}

func (x *QueryNode) GetForceIndex() string {
	if x != nil {
		return x.ForceIndex
	}
	return ""
}

func (x *QueryNode) GetKeyBy() string {
	if x != nil {
		return x.KeyBy
	}
	return ""
}

func (x *QueryNode) GetFlatten() bool {
	if x != nil {
		return x.Flatten
	}
	return false
}

func (x *QueryNode) GetLimitPerParent() uint32 {
	if x != nil {
		return x.LimitPerParent
	}
	return 0
}

func (x *QueryNode) GetIfParent() *IfParent {
	if x != nil {
		return x.IfParent
	}
	return nil
}

func (x *QueryNode) GetDropChildKey() bool {
	if x != nil {
		return x.DropChildKey
	}
	return false
}

func (x *QueryNode) GetNoCascadeDelete() bool {
	if x != nil {
		return x.NoCascadeDelete
	}
	return false
}

func (x *QueryNode) GetScopeParameter() uint32 {
	if x != nil && x.ScopeParameter != nil {
		return *x.ScopeParameter
	}
	return 0
}

type Projection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          Projection_Mode        `protobuf:"varint,1,opt,name=mode,proto3,enum=orm.compiler.v1.Projection_Mode" json:"mode,omitempty"`
	Add           []string               `protobuf:"bytes,2,rep,name=add,proto3" json:"add,omitempty"`
	Remove        []string               `protobuf:"bytes,3,rep,name=remove,proto3" json:"remove,omitempty"`
	Aliases       map[string]string      `protobuf:"bytes,4,rep,name=aliases,proto3" json:"aliases,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Expressions   map[string]string      `protobuf:"bytes,5,rep,name=expressions,proto3" json:"expressions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Projection) Reset() {
	*x = Projection{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Projection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Projection) ProtoMessage() {}

func (x *Projection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Projection.ProtoReflect.Descriptor instead.
func (*Projection) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{2}
}

func (x *Projection) GetMode() Projection_Mode {
	if x != nil {
		return x.Mode
	}
	return Projection_MODE_DEFAULT
}

func (x *Projection) GetAdd() []string {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *Projection) GetRemove() []string {
	if x != nil {
		return x.Remove
	}
	return nil
}

func (x *Projection) GetAliases() map[string]string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *Projection) GetExpressions() map[string]string {
	if x != nil {
		return x.Expressions
	}
	return nil
}

type Join struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relation      string                 `protobuf:"bytes,1,opt,name=relation,proto3" json:"relation,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Query         *QueryNode             `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Join) Reset() {
	*x = Join{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Join) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Join) ProtoMessage() {}

func (x *Join) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Join.ProtoReflect.Descriptor instead.
func (*Join) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{3}
}

func (x *Join) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *Join) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Join) GetQuery() *QueryNode {
	if x != nil {
		return x.Query
	}
	return nil
}

type Relation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relation      string                 `protobuf:"bytes,1,opt,name=relation,proto3" json:"relation,omitempty"`
	Query         *QueryNode             `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relation) Reset() {
	*x = Relation{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relation) ProtoMessage() {}

func (x *Relation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relation.ProtoReflect.Descriptor instead.
func (*Relation) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{4}
}

func (x *Relation) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *Relation) GetQuery() *QueryNode {
	if x != nil {
		return x.Query
	}
	return nil
}

type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connector     string                 `protobuf:"bytes,1,opt,name=connector,proto3" json:"connector,omitempty"`
	Items         []*Item                `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{5}
}

func (x *Group) GetConnector() string {
	if x != nil {
		return x.Connector
	}
	return ""
}

func (x *Group) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type Item struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Item_Predicate
	//	*Item_Group
	//	*Item_Navigation
	Value         isItem_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{6}
}

func (x *Item) GetValue() isItem_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Item) GetPredicate() *Predicate {
	if x != nil {
		if x, ok := x.Value.(*Item_Predicate); ok {
			return x.Predicate
		}
	}
	return nil
}

func (x *Item) GetGroup() *Group {
	if x != nil {
		if x, ok := x.Value.(*Item_Group); ok {
			return x.Group
		}
	}
	return nil
}

func (x *Item) GetNavigation() *Navigation {
	if x != nil {
		if x, ok := x.Value.(*Item_Navigation); ok {
			return x.Navigation
		}
	}
	return nil
}

type isItem_Value interface {
	isItem_Value()
}

type Item_Predicate struct {
	Predicate *Predicate `protobuf:"bytes,1,opt,name=predicate,proto3,oneof"`
}

type Item_Group struct {
	Group *Group `protobuf:"bytes,2,opt,name=group,proto3,oneof"`
}

type Item_Navigation struct {
	Navigation *Navigation `protobuf:"bytes,3,opt,name=navigation,proto3,oneof"`
}

func (*Item_Predicate) isItem_Value() {}

func (*Item_Group) isItem_Value() {}

func (*Item_Navigation) isItem_Value() {}

type Navigation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connector     string                 `protobuf:"bytes,1,opt,name=connector,proto3" json:"connector,omitempty"`
	Relation      string                 `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	Group         *Group                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Navigation) Reset() {
	*x = Navigation{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Navigation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Navigation) ProtoMessage() {}

func (x *Navigation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Navigation.ProtoReflect.Descriptor instead.
func (*Navigation) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{7}
}

func (x *Navigation) GetConnector() string {
	if x != nil {
		return x.Connector
	}
	return ""
}

func (x *Navigation) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *Navigation) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type Predicate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connector     string                 `protobuf:"bytes,1,opt,name=connector,proto3" json:"connector,omitempty"`
	Column        string                 `protobuf:"bytes,2,opt,name=column,proto3" json:"column,omitempty"`
	Operator      string                 `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	Parameter     *uint32                `protobuf:"varint,4,opt,name=parameter,proto3,oneof" json:"parameter,omitempty"`
	Parameters    []uint32               `protobuf:"varint,5,rep,packed,name=parameters,proto3" json:"parameters,omitempty"`
	Reference     *ColumnReference       `protobuf:"bytes,6,opt,name=reference,proto3" json:"reference,omitempty"`
	Expression    string                 `protobuf:"bytes,7,opt,name=expression,proto3" json:"expression,omitempty"`
	MatchColumns  []string               `protobuf:"bytes,8,rep,name=match_columns,json=matchColumns,proto3" json:"match_columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Predicate) Reset() {
	*x = Predicate{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Predicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Predicate) ProtoMessage() {}

func (x *Predicate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Predicate.ProtoReflect.Descriptor instead.
func (*Predicate) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{8}
}

func (x *Predicate) GetConnector() string {
	if x != nil {
		return x.Connector
	}
	return ""
}

func (x *Predicate) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *Predicate) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *Predicate) GetParameter() uint32 {
	if x != nil && x.Parameter != nil {
		return *x.Parameter
	}
	return 0
}

func (x *Predicate) GetParameters() []uint32 {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *Predicate) GetReference() *ColumnReference {
	if x != nil {
		return x.Reference
	}
	return nil
}

func (x *Predicate) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *Predicate) GetMatchColumns() []string {
	if x != nil {
		return x.MatchColumns
	}
	return nil
}

type ColumnReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Column        string                 `protobuf:"bytes,2,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnReference) Reset() {
	*x = ColumnReference{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnReference) ProtoMessage() {}

func (x *ColumnReference) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnReference.ProtoReflect.Descriptor instead.
func (*ColumnReference) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{9}
}

func (x *ColumnReference) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ColumnReference) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Column        string                 `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	Expression    string                 `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	Descending    bool                   `protobuf:"varint,3,opt,name=descending,proto3" json:"descending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{10}
}

func (x *Order) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *Order) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *Order) GetDescending() bool {
	if x != nil {
		return x.Descending
	}
	return false
}

type GroupExpression struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expression    string                 `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupExpression) Reset() {
	*x = GroupExpression{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupExpression) ProtoMessage() {}

func (x *GroupExpression) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupExpression.ProtoReflect.Descriptor instead.
func (*GroupExpression) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{11}
}

func (x *GroupExpression) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *GroupExpression) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type Limit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint32                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Limit) Reset() {
	*x = Limit{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Limit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limit) ProtoMessage() {}

func (x *Limit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limit.ProtoReflect.Descriptor instead.
func (*Limit) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{12}
}

func (x *Limit) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Limit) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type IfParent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Column        string                 `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	Parameter     uint32                 `protobuf:"varint,2,opt,name=parameter,proto3" json:"parameter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IfParent) Reset() {
	*x = IfParent{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IfParent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfParent) ProtoMessage() {}

func (x *IfParent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfParent.ProtoReflect.Descriptor instead.
func (*IfParent) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{13}
}

func (x *IfParent) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *IfParent) GetParameter() uint32 {
	if x != nil {
		return x.Parameter
	}
	return 0
}

type Assignment struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Column               string                 `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	Parameter            *uint32                `protobuf:"varint,2,opt,name=parameter,proto3,oneof" json:"parameter,omitempty"`
	SetNull              bool                   `protobuf:"varint,3,opt,name=set_null,json=setNull,proto3" json:"set_null,omitempty"`
	Expression           string                 `protobuf:"bytes,4,opt,name=expression,proto3" json:"expression,omitempty"`
	ExpressionParameters []uint32               `protobuf:"varint,5,rep,packed,name=expression_parameters,json=expressionParameters,proto3" json:"expression_parameters,omitempty"`
	PlusParameter        *uint32                `protobuf:"varint,6,opt,name=plus_parameter,json=plusParameter,proto3,oneof" json:"plus_parameter,omitempty"`
	MinusParameter       *uint32                `protobuf:"varint,7,opt,name=minus_parameter,json=minusParameter,proto3,oneof" json:"minus_parameter,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{14}
}

func (x *Assignment) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *Assignment) GetParameter() uint32 {
	if x != nil && x.Parameter != nil {
		return *x.Parameter
	}
	return 0
}

func (x *Assignment) GetSetNull() bool {
	if x != nil {
		return x.SetNull
	}
	return false
}

func (x *Assignment) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *Assignment) GetExpressionParameters() []uint32 {
	if x != nil {
		return x.ExpressionParameters
	}
	return nil
}

func (x *Assignment) GetPlusParameter() uint32 {
	if x != nil && x.PlusParameter != nil {
		return *x.PlusParameter
	}
	return 0
}

func (x *Assignment) GetMinusParameter() uint32 {
	if x != nil && x.MinusParameter != nil {
		return *x.MinusParameter
	}
	return 0
}

type Optimistic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Column        string                 `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	Parameter     uint32                 `protobuf:"varint,2,opt,name=parameter,proto3" json:"parameter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Optimistic) Reset() {
	*x = Optimistic{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Optimistic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Optimistic) ProtoMessage() {}

func (x *Optimistic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Optimistic.ProtoReflect.Descriptor instead.
func (*Optimistic) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{15}
}

func (x *Optimistic) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *Optimistic) GetParameter() uint32 {
	if x != nil {
		return x.Parameter
	}
	return 0
}

type Raw struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	Parameters    []uint32               `protobuf:"varint,2,rep,packed,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Raw) Reset() {
	*x = Raw{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Raw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Raw) ProtoMessage() {}

func (x *Raw) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Raw.ProtoReflect.Descriptor instead.
func (*Raw) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{16}
}

func (x *Raw) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *Raw) GetParameters() []uint32 {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type CompileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*CompileResponse_Plan
	//	*CompileResponse_Error
	Result        isCompileResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileResponse) Reset() {
	*x = CompileResponse{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileResponse) ProtoMessage() {}

func (x *CompileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileResponse.ProtoReflect.Descriptor instead.
func (*CompileResponse) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{17}
}

func (x *CompileResponse) GetResult() isCompileResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CompileResponse) GetPlan() *Plan {
	if x != nil {
		if x, ok := x.Result.(*CompileResponse_Plan); ok {
			return x.Plan
		}
	}
	return nil
}

func (x *CompileResponse) GetError() *CompileError {
	if x != nil {
		if x, ok := x.Result.(*CompileResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCompileResponse_Result interface {
	isCompileResponse_Result()
}

type CompileResponse_Plan struct {
	Plan *Plan `protobuf:"bytes,1,opt,name=plan,proto3,oneof"`
}

type CompileResponse_Error struct {
	Error *CompileError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*CompileResponse_Plan) isCompileResponse_Result() {}

func (*CompileResponse_Error) isCompileResponse_Result() {}

type Plan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaHash    string                 `protobuf:"bytes,1,opt,name=schema_hash,json=schemaHash,proto3" json:"schema_hash,omitempty"`
	Kind          QueryKind              `protobuf:"varint,2,opt,name=kind,proto3,enum=orm.compiler.v1.QueryKind" json:"kind,omitempty"`
	Steps         []*PlanStep            `protobuf:"bytes,3,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plan) Reset() {
	*x = Plan{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{18}
}

func (x *Plan) GetSchemaHash() string {
	if x != nil {
		return x.SchemaHash
	}
	return ""
}

func (x *Plan) GetKind() QueryKind {
	if x != nil {
		return x.Kind
	}
	return QueryKind_QUERY_KIND_UNSPECIFIED
}

func (x *Plan) GetSteps() []*PlanStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

type PlanStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Sql           string                 `protobuf:"bytes,3,opt,name=sql,proto3" json:"sql,omitempty"`
	Binds         []*BindSlot            `protobuf:"bytes,4,rep,name=binds,proto3" json:"binds,omitempty"`
	Assemble      *Assemble              `protobuf:"bytes,5,opt,name=assemble,proto3" json:"assemble,omitempty"`
	Parent        *ParentReference       `protobuf:"bytes,6,opt,name=parent,proto3" json:"parent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanStep) Reset() {
	*x = PlanStep{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanStep) ProtoMessage() {}

func (x *PlanStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanStep.ProtoReflect.Descriptor instead.
func (*PlanStep) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{19}
}

func (x *PlanStep) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlanStep) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *PlanStep) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *PlanStep) GetBinds() []*BindSlot {
	if x != nil {
		return x.Binds
	}
	return nil
}

func (x *PlanStep) GetAssemble() *Assemble {
	if x != nil {
		return x.Assemble
	}
	return nil
}

func (x *PlanStep) GetParent() *ParentReference {
	if x != nil {
		return x.Parent
	}
	return nil
}

type BindSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Parameter     uint32                 `protobuf:"varint,2,opt,name=parameter,proto3" json:"parameter,omitempty"`
	Transform     string                 `protobuf:"bytes,3,opt,name=transform,proto3" json:"transform,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Step          uint32                 `protobuf:"varint,5,opt,name=step,proto3" json:"step,omitempty"`
	Column        string                 `protobuf:"bytes,6,opt,name=column,proto3" json:"column,omitempty"`
	HostStyles    []string               `protobuf:"bytes,7,rep,name=host_styles,json=hostStyles,proto3" json:"host_styles,omitempty"`
	ColumnType    string                 `protobuf:"bytes,8,opt,name=column_type,json=columnType,proto3" json:"column_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindSlot) Reset() {
	*x = BindSlot{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindSlot) ProtoMessage() {}

func (x *BindSlot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindSlot.ProtoReflect.Descriptor instead.
func (*BindSlot) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{20}
}

func (x *BindSlot) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *BindSlot) GetParameter() uint32 {
	if x != nil {
		return x.Parameter
	}
	return 0
}

func (x *BindSlot) GetTransform() string {
	if x != nil {
		return x.Transform
	}
	return ""
}

func (x *BindSlot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BindSlot) GetStep() uint32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *BindSlot) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *BindSlot) GetHostStyles() []string {
	if x != nil {
		return x.HostStyles
	}
	return nil
}

func (x *BindSlot) GetColumnType() string {
	if x != nil {
		return x.ColumnType
	}
	return ""
}

type KeyReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Column        string                 `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyReference) Reset() {
	*x = KeyReference{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyReference) ProtoMessage() {}

func (x *KeyReference) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyReference.ProtoReflect.Descriptor instead.
func (*KeyReference) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{21}
}

func (x *KeyReference) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *KeyReference) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type ParentReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          uint32                 `protobuf:"varint,1,opt,name=step,proto3" json:"step,omitempty"`
	IfParent      *ParentCondition       `protobuf:"bytes,4,opt,name=if_parent,json=ifParent,proto3" json:"if_parent,omitempty"`
	Keys          []*KeyReference        `protobuf:"bytes,5,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParentReference) Reset() {
	*x = ParentReference{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParentReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentReference) ProtoMessage() {}

func (x *ParentReference) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentReference.ProtoReflect.Descriptor instead.
func (*ParentReference) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{22}
}

func (x *ParentReference) GetStep() uint32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *ParentReference) GetIfParent() *ParentCondition {
	if x != nil {
		return x.IfParent
	}
	return nil
}

func (x *ParentReference) GetKeys() []*KeyReference {
	if x != nil {
		return x.Keys
	}
	return nil
}

type ParentCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Column        string                 `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Parameter     uint32                 `protobuf:"varint,3,opt,name=parameter,proto3" json:"parameter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParentCondition) Reset() {
	*x = ParentCondition{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParentCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentCondition) ProtoMessage() {}

func (x *ParentCondition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentCondition.ProtoReflect.Descriptor instead.
func (*ParentCondition) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{23}
}

func (x *ParentCondition) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *ParentCondition) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ParentCondition) GetParameter() uint32 {
	if x != nil {
		return x.Parameter
	}
	return 0
}

type Assemble struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        string                 `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	Columns       []*OutputColumn        `protobuf:"bytes,3,rep,name=columns,proto3" json:"columns,omitempty"`
	Children      []*Child               `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
	Key           []*KeyReference        `protobuf:"bytes,5,rep,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assemble) Reset() {
	*x = Assemble{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assemble) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assemble) ProtoMessage() {}

func (x *Assemble) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assemble.ProtoReflect.Descriptor instead.
func (*Assemble) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{24}
}

func (x *Assemble) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *Assemble) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Assemble) GetColumns() []*OutputColumn {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *Assemble) GetChildren() []*Child {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *Assemble) GetKey() []*KeyReference {
	if x != nil {
		return x.Key
	}
	return nil
}

type OutputColumn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Column        string                 `protobuf:"bytes,3,opt,name=column,proto3" json:"column,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Styles        []string               `protobuf:"bytes,5,rep,name=styles,proto3" json:"styles,omitempty"`
	Hidden        bool                   `protobuf:"varint,6,opt,name=hidden,proto3" json:"hidden,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputColumn) Reset() {
	*x = OutputColumn{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputColumn) ProtoMessage() {}

func (x *OutputColumn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputColumn.ProtoReflect.Descriptor instead.
func (*OutputColumn) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{25}
}

func (x *OutputColumn) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *OutputColumn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OutputColumn) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *OutputColumn) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OutputColumn) GetStyles() []string {
	if x != nil {
		return x.Styles
	}
	return nil
}

func (x *OutputColumn) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

type Child struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relation      string                 `protobuf:"bytes,1,opt,name=relation,proto3" json:"relation,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Step          uint32                 `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
	Flatten       bool                   `protobuf:"varint,10,opt,name=flatten,proto3" json:"flatten,omitempty"`
	Cascade       bool                   `protobuf:"varint,11,opt,name=cascade,proto3" json:"cascade,omitempty"`
	Assemble      *Assemble              `protobuf:"bytes,12,opt,name=assemble,proto3" json:"assemble,omitempty"`
	ParentKeys    []*KeyReference        `protobuf:"bytes,13,rep,name=parent_keys,json=parentKeys,proto3" json:"parent_keys,omitempty"`
	ChildKeys     []*KeyReference        `protobuf:"bytes,14,rep,name=child_keys,json=childKeys,proto3" json:"child_keys,omitempty"`
	Key           []*KeyReference        `protobuf:"bytes,15,rep,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Child) Reset() {
	*x = Child{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Child) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Child) ProtoMessage() {}

func (x *Child) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Child.ProtoReflect.Descriptor instead.
func (*Child) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{26}
}

func (x *Child) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *Child) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Child) GetStep() uint32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *Child) GetFlatten() bool {
	if x != nil {
		return x.Flatten
	}
	return false
}

func (x *Child) GetCascade() bool {
	if x != nil {
		return x.Cascade
	}
	return false
}

func (x *Child) GetAssemble() *Assemble {
	if x != nil {
		return x.Assemble
	}
	return nil
}

func (x *Child) GetParentKeys() []*KeyReference {
	if x != nil {
		return x.ParentKeys
	}
	return nil
}

func (x *Child) GetChildKeys() []*KeyReference {
	if x != nil {
		return x.ChildKeys
	}
	return nil
}

func (x *Child) GetKey() []*KeyReference {
	if x != nil {
		return x.Key
	}
	return nil
}

type CompileError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileError) Reset() {
	*x = CompileError{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileError) ProtoMessage() {}

func (x *CompileError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileError.ProtoReflect.Descriptor instead.
func (*CompileError) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{27}
}

func (x *CompileError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CompileError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataRequest) Reset() {
	*x = GetMetadataRequest{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataRequest) ProtoMessage() {}

func (x *GetMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{28}
}

type GetMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaHash    string                 `protobuf:"bytes,1,opt,name=schema_hash,json=schemaHash,proto3" json:"schema_hash,omitempty"`
	Dialect       string                 `protobuf:"bytes,2,opt,name=dialect,proto3" json:"dialect,omitempty"`
	IrVersion     uint32                 `protobuf:"varint,3,opt,name=ir_version,json=irVersion,proto3" json:"ir_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataResponse) Reset() {
	*x = GetMetadataResponse{}
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataResponse) ProtoMessage() {}

func (x *GetMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orm_compiler_v1_compiler_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetMetadataResponse) Descriptor() ([]byte, []int) {
	return file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP(), []int{29}
}

func (x *GetMetadataResponse) GetSchemaHash() string {
	if x != nil {
		return x.SchemaHash
	}
	return ""
}

func (x *GetMetadataResponse) GetDialect() string {
	if x != nil {
		return x.Dialect
	}
	return ""
}

func (x *GetMetadataResponse) GetIrVersion() uint32 {
	if x != nil {
		return x.IrVersion
	}
	return 0
}

var File_proto_orm_compiler_v1_compiler_proto protoreflect.FileDescriptor

const file_proto_orm_compiler_v1_compiler_proto_rawDesc = "" +
	"\n" +
	"$proto/orm/compiler/v1/compiler.proto\x12\x0form.compiler.v1\"\xe1\x03\n" +
	"\x0eCompileRequest\x12\x1d\n" +
	"\n" +
	"ir_version\x18\x01 \x01(\rR\tirVersion\x12\x1f\n" +
	"\vschema_hash\x18\x02 \x01(\tR\n" +
	"schemaHash\x12.\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1a.orm.compiler.v1.QueryKindR\x04kind\x12.\n" +
	"\x04root\x18\x04 \x01(\v2\x1a.orm.compiler.v1.QueryNodeR\x04root\x12-\n" +
	"\x03set\x18\x05 \x03(\v2\x1b.orm.compiler.v1.AssignmentR\x03set\x12>\n" +
	"\fon_duplicate\x18\x06 \x03(\v2\x1b.orm.compiler.v1.AssignmentR\vonDuplicate\x12;\n" +
	"\n" +
	"optimistic\x18\a \x01(\v2\x1b.orm.compiler.v1.OptimisticR\n" +
	"optimistic\x12&\n" +
	"\x03raw\x18\b \x01(\v2\x14.orm.compiler.v1.RawR\x03raw\x12'\n" +
	"\x0fparameter_count\x18\t \x01(\rR\x0eparameterCount\x12\x1c\n" +
	"\taggregate\x18\n" +
	" \x01(\tR\taggregate\x12\x14\n" +
	"\x05debug\x18\v \x01(\bR\x05debug\"\xf3\x06\n" +
	"\tQueryNode\x12\x16\n" +
	"\x06entity\x18\x01 \x01(\tR\x06entity\x125\n" +
	"\acolumns\x18\x02 \x01(\v2\x1b.orm.compiler.v1.ProjectionR\acolumns\x12&\n" +
	"\x02on\x18\x03 \x01(\v2\x16.orm.compiler.v1.GroupR\x02on\x12,\n" +
	"\x05where\x18\x04 \x01(\v2\x16.orm.compiler.v1.GroupR\x05where\x12.\n" +
	"\x06having\x18\x05 \x01(\v2\x16.orm.compiler.v1.GroupR\x06having\x12+\n" +
	"\x05joins\x18\x06 \x03(\v2\x15.orm.compiler.v1.JoinR\x05joins\x127\n" +
	"\trelations\x18\a \x03(\v2\x19.orm.compiler.v1.RelationR\trelations\x12,\n" +
	"\x05order\x18\b \x03(\v2\x16.orm.compiler.v1.OrderR\x05order\x12\x19\n" +
	"\bgroup_by\x18\t \x03(\tR\agroupBy\x12P\n" +
	"\x13group_by_expression\x18\n" +
	" \x03(\v2 .orm.compiler.v1.GroupExpressionR\x11groupByExpression\x12,\n" +
	"\x05limit\x18\v \x01(\v2\x16.orm.compiler.v1.LimitR\x05limit\x12\x1a\n" +
	"\bdistinct\x18\f \x01(\bR\bdistinct\x12\x1f\n" +
	"\vforce_index\x18\r \x01(\tR\n" +
	"forceIndex\x12\x15\n" +
	"\x06key_by\x18\x0e \x01(\tR\x05keyBy\x12\x18\n" +
	"\aflatten\x18\x0f \x01(\bR\aflatten\x12(\n" +
	"\x10limit_per_parent\x18\x10 \x01(\rR\x0elimitPerParent\x126\n" +
	"\tif_parent\x18\x11 \x01(\v2\x19.orm.compiler.v1.IfParentR\bifParent\x12$\n" +
	"\x0edrop_child_key\x18\x12 \x01(\bR\fdropChildKey\x12*\n" +
	"\x11no_cascade_delete\x18\x13 \x01(\bR\x0fnoCascadeDelete\x12,\n" +
	"\x0fscope_parameter\x18\x14 \x01(\rH\x00R\x0escopeParameter\x88\x01\x01B\x12\n" +
	"\x10_scope_parameter\"\xb3\x03\n" +
	"\n" +
	"Projection\x124\n" +
	"\x04mode\x18\x01 \x01(\x0e2 .orm.compiler.v1.Projection.ModeR\x04mode\x12\x10\n" +
	"\x03add\x18\x02 \x03(\tR\x03add\x12\x16\n" +
	"\x06remove\x18\x03 \x03(\tR\x06remove\x12B\n" +
	"\aaliases\x18\x04 \x03(\v2(.orm.compiler.v1.Projection.AliasesEntryR\aaliases\x12N\n" +
	"\vexpressions\x18\x05 \x03(\v2,.orm.compiler.v1.Projection.ExpressionsEntryR\vexpressions\x1a:\n" +
	"\fAliasesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10ExpressionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"5\n" +
	"\x04Mode\x12\x10\n" +
	"\fMODE_DEFAULT\x10\x00\x12\f\n" +
	"\bMODE_ALL\x10\x01\x12\r\n" +
	"\tMODE_NONE\x10\x02\"h\n" +
	"\x04Join\x12\x1a\n" +
	"\brelation\x18\x01 \x01(\tR\brelation\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x120\n" +
	"\x05query\x18\x03 \x01(\v2\x1a.orm.compiler.v1.QueryNodeR\x05query\"X\n" +
	"\bRelation\x12\x1a\n" +
	"\brelation\x18\x01 \x01(\tR\brelation\x120\n" +
	"\x05query\x18\x02 \x01(\v2\x1a.orm.compiler.v1.QueryNodeR\x05query\"R\n" +
	"\x05Group\x12\x1c\n" +
	"\tconnector\x18\x01 \x01(\tR\tconnector\x12+\n" +
	"\x05items\x18\x02 \x03(\v2\x15.orm.compiler.v1.ItemR\x05items\"\xba\x01\n" +
	"\x04Item\x12:\n" +
	"\tpredicate\x18\x01 \x01(\v2\x1a.orm.compiler.v1.PredicateH\x00R\tpredicate\x12.\n" +
	"\x05group\x18\x02 \x01(\v2\x16.orm.compiler.v1.GroupH\x00R\x05group\x12=\n" +
	"\n" +
	"navigation\x18\x03 \x01(\v2\x1b.orm.compiler.v1.NavigationH\x00R\n" +
	"navigationB\a\n" +
	"\x05value\"t\n" +
	"\n" +
	"Navigation\x12\x1c\n" +
	"\tconnector\x18\x01 \x01(\tR\tconnector\x12\x1a\n" +
	"\brelation\x18\x02 \x01(\tR\brelation\x12,\n" +
	"\x05group\x18\x03 \x01(\v2\x16.orm.compiler.v1.GroupR\x05group\"\xb3\x02\n" +
	"\tPredicate\x12\x1c\n" +
	"\tconnector\x18\x01 \x01(\tR\tconnector\x12\x16\n" +
	"\x06column\x18\x02 \x01(\tR\x06column\x12\x1a\n" +
	"\boperator\x18\x03 \x01(\tR\boperator\x12!\n" +
	"\tparameter\x18\x04 \x01(\rH\x00R\tparameter\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"parameters\x18\x05 \x03(\rR\n" +
	"parameters\x12>\n" +
	"\treference\x18\x06 \x01(\v2 .orm.compiler.v1.ColumnReferenceR\treference\x12\x1e\n" +
	"\n" +
	"expression\x18\a \x01(\tR\n" +
	"expression\x12#\n" +
	"\rmatch_columns\x18\b \x03(\tR\fmatchColumnsB\f\n" +
	"\n" +
	"_parameter\"=\n" +
	"\x0fColumnReference\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06column\x18\x02 \x01(\tR\x06column\"_\n" +
	"\x05Order\x12\x16\n" +
	"\x06column\x18\x01 \x01(\tR\x06column\x12\x1e\n" +
	"\n" +
	"expression\x18\x02 \x01(\tR\n" +
	"expression\x12\x1e\n" +
	"\n" +
	"descending\x18\x03 \x01(\bR\n" +
	"descending\"G\n" +
	"\x0fGroupExpression\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\"5\n" +
	"\x05Limit\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\rR\x06offset\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"@\n" +
	"\bIfParent\x12\x16\n" +
	"\x06column\x18\x01 \x01(\tR\x06column\x12\x1c\n" +
	"\tparameter\x18\x02 \x01(\rR\tparameter\"\xc6\x02\n" +
	"\n" +
	"Assignment\x12\x16\n" +
	"\x06column\x18\x01 \x01(\tR\x06column\x12!\n" +
	"\tparameter\x18\x02 \x01(\rH\x00R\tparameter\x88\x01\x01\x12\x19\n" +
	"\bset_null\x18\x03 \x01(\bR\asetNull\x12\x1e\n" +
	"\n" +
	"expression\x18\x04 \x01(\tR\n" +
	"expression\x123\n" +
	"\x15expression_parameters\x18\x05 \x03(\rR\x14expressionParameters\x12*\n" +
	"\x0eplus_parameter\x18\x06 \x01(\rH\x01R\rplusParameter\x88\x01\x01\x12,\n" +
	"\x0fminus_parameter\x18\a \x01(\rH\x02R\x0eminusParameter\x88\x01\x01B\f\n" +
	"\n" +
	"_parameterB\x11\n" +
	"\x0f_plus_parameterB\x12\n" +
	"\x10_minus_parameter\"B\n" +
	"\n" +
	"Optimistic\x12\x16\n" +
	"\x06column\x18\x01 \x01(\tR\x06column\x12\x1c\n" +
	"\tparameter\x18\x02 \x01(\rR\tparameter\"7\n" +
	"\x03Raw\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x12\x1e\n" +
	"\n" +
	"parameters\x18\x02 \x03(\rR\n" +
	"parameters\"\x7f\n" +
	"\x0fCompileResponse\x12+\n" +
	"\x04plan\x18\x01 \x01(\v2\x15.orm.compiler.v1.PlanH\x00R\x04plan\x125\n" +
	"\x05error\x18\x02 \x01(\v2\x1d.orm.compiler.v1.CompileErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\x88\x01\n" +
	"\x04Plan\x12\x1f\n" +
	"\vschema_hash\x18\x01 \x01(\tR\n" +
	"schemaHash\x12.\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1a.orm.compiler.v1.QueryKindR\x04kind\x12/\n" +
	"\x05steps\x18\x03 \x03(\v2\x19.orm.compiler.v1.PlanStepR\x05steps\"\xe2\x01\n" +
	"\bPlanStep\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x10\n" +
	"\x03sql\x18\x03 \x01(\tR\x03sql\x12/\n" +
	"\x05binds\x18\x04 \x03(\v2\x19.orm.compiler.v1.BindSlotR\x05binds\x125\n" +
	"\bassemble\x18\x05 \x01(\v2\x19.orm.compiler.v1.AssembleR\bassemble\x128\n" +
	"\x06parent\x18\x06 \x01(\v2 .orm.compiler.v1.ParentReferenceR\x06parent\"\xe0\x01\n" +
	"\bBindSlot\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1c\n" +
	"\tparameter\x18\x02 \x01(\rR\tparameter\x12\x1c\n" +
	"\ttransform\x18\x03 \x01(\tR\ttransform\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04step\x18\x05 \x01(\rR\x04step\x12\x16\n" +
	"\x06column\x18\x06 \x01(\tR\x06column\x12\x1f\n" +
	"\vhost_styles\x18\a \x03(\tR\n" +
	"hostStyles\x12\x1f\n" +
	"\vcolumn_type\x18\b \x01(\tR\n" +
	"columnType\"<\n" +
	"\fKeyReference\x12\x16\n" +
	"\x06column\x18\x01 \x01(\tR\x06column\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\"\xa3\x01\n" +
	"\x0fParentReference\x12\x12\n" +
	"\x04step\x18\x01 \x01(\rR\x04step\x12=\n" +
	"\tif_parent\x18\x04 \x01(\v2 .orm.compiler.v1.ParentConditionR\bifParent\x121\n" +
	"\x04keys\x18\x05 \x03(\v2\x1d.orm.compiler.v1.KeyReferenceR\x04keysJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04\"]\n" +
	"\x0fParentCondition\x12\x16\n" +
	"\x06column\x18\x01 \x01(\tR\x06column\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\x12\x1c\n" +
	"\tparameter\x18\x03 \x01(\rR\tparameter\"\xd6\x01\n" +
	"\bAssemble\x12\x16\n" +
	"\x06entity\x18\x01 \x01(\tR\x06entity\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x127\n" +
	"\acolumns\x18\x03 \x03(\v2\x1d.orm.compiler.v1.OutputColumnR\acolumns\x122\n" +
	"\bchildren\x18\x04 \x03(\v2\x16.orm.compiler.v1.ChildR\bchildren\x12/\n" +
	"\x03key\x18\x05 \x03(\v2\x1d.orm.compiler.v1.KeyReferenceR\x03key\"\x94\x01\n" +
	"\fOutputColumn\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06column\x18\x03 \x01(\tR\x06column\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x16\n" +
	"\x06styles\x18\x05 \x03(\tR\x06styles\x12\x16\n" +
	"\x06hidden\x18\x06 \x01(\bR\x06hidden\"\x89\x03\n" +
	"\x05Child\x12\x1a\n" +
	"\brelation\x18\x01 \x01(\tR\brelation\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04step\x18\x03 \x01(\rR\x04step\x12\x18\n" +
	"\aflatten\x18\n" +
	" \x01(\bR\aflatten\x12\x18\n" +
	"\acascade\x18\v \x01(\bR\acascade\x125\n" +
	"\bassemble\x18\f \x01(\v2\x19.orm.compiler.v1.AssembleR\bassemble\x12>\n" +
	"\vparent_keys\x18\r \x03(\v2\x1d.orm.compiler.v1.KeyReferenceR\n" +
	"parentKeys\x12<\n" +
	"\n" +
	"child_keys\x18\x0e \x03(\v2\x1d.orm.compiler.v1.KeyReferenceR\tchildKeys\x12/\n" +
	"\x03key\x18\x0f \x03(\v2\x1d.orm.compiler.v1.KeyReferenceR\x03keyJ\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\x06\x10\aJ\x04\b\a\x10\bJ\x04\b\b\x10\tJ\x04\b\t\x10\n" +
	"\"<\n" +
	"\fCompileError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x14\n" +
	"\x12GetMetadataRequest\"o\n" +
	"\x13GetMetadataResponse\x12\x1f\n" +
	"\vschema_hash\x18\x01 \x01(\tR\n" +
	"schemaHash\x12\x18\n" +
	"\adialect\x18\x02 \x01(\tR\adialect\x12\x1d\n" +
	"\n" +
	"ir_version\x18\x03 \x01(\rR\tirVersion*\xe2\x02\n" +
	"\tQueryKind\x12\x1a\n" +
	"\x16QUERY_KIND_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eQUERY_KIND_ONE\x10\x01\x12\x12\n" +
	"\x0eQUERY_KIND_ALL\x10\x02\x12\x14\n" +
	"\x10QUERY_KIND_COUNT\x10\x03\x12\x1a\n" +
	"\x16QUERY_KIND_GROUP_COUNT\x10\x04\x12\x1d\n" +
	"\x19QUERY_KIND_COUNT_DISTINCT\x10\x05\x12\x12\n" +
	"\x0eQUERY_KIND_SUM\x10\x06\x12\x12\n" +
	"\x0eQUERY_KIND_AVG\x10\a\x12\x12\n" +
	"\x0eQUERY_KIND_MIN\x10\b\x12\x12\n" +
	"\x0eQUERY_KIND_MAX\x10\t\x12\x17\n" +
	"\x13QUERY_KIND_PAGINATE\x10\n" +
	"\x12\x15\n" +
	"\x11QUERY_KIND_INSERT\x10\v\x12\x15\n" +
	"\x11QUERY_KIND_UPDATE\x10\f\x12\x15\n" +
	"\x11QUERY_KIND_DELETE\x10\r\x12\x12\n" +
	"\x0eQUERY_KIND_RAW\x10\x0e2\xb9\x01\n" +
	"\x0fCompilerService\x12L\n" +
	"\aCompile\x12\x1f.orm.compiler.v1.CompileRequest\x1a .orm.compiler.v1.CompileResponse\x12X\n" +
	"\vGetMetadata\x12#.orm.compiler.v1.GetMetadataRequest\x1a$.orm.compiler.v1.GetMetadataResponseB:Z8github.com/polyspec/orm/proto/orm/compiler/v1;compilerv1b\x06proto3"

var (
	file_proto_orm_compiler_v1_compiler_proto_rawDescOnce sync.Once
	file_proto_orm_compiler_v1_compiler_proto_rawDescData []byte
)

func file_proto_orm_compiler_v1_compiler_proto_rawDescGZIP() []byte {
	file_proto_orm_compiler_v1_compiler_proto_rawDescOnce.Do(func() {
		file_proto_orm_compiler_v1_compiler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orm_compiler_v1_compiler_proto_rawDesc), len(file_proto_orm_compiler_v1_compiler_proto_rawDesc)))
	})
	return file_proto_orm_compiler_v1_compiler_proto_rawDescData
}

var file_proto_orm_compiler_v1_compiler_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_orm_compiler_v1_compiler_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_proto_orm_compiler_v1_compiler_proto_goTypes = []any{
	(QueryKind)(0),              // 0: orm.compiler.v1.QueryKind
	(Projection_Mode)(0),        // 1: orm.compiler.v1.Projection.Mode
	(*CompileRequest)(nil),      // 2: orm.compiler.v1.CompileRequest
	(*QueryNode)(nil),           // 3: orm.compiler.v1.QueryNode
	(*Projection)(nil),          // 4: orm.compiler.v1.Projection
	(*Join)(nil),                // 5: orm.compiler.v1.Join
	(*Relation)(nil),            // 6: orm.compiler.v1.Relation
	(*Group)(nil),               // 7: orm.compiler.v1.Group
	(*Item)(nil),                // 8: orm.compiler.v1.Item
	(*Navigation)(nil),          // 9: orm.compiler.v1.Navigation
	(*Predicate)(nil),           // 10: orm.compiler.v1.Predicate
	(*ColumnReference)(nil),     // 11: orm.compiler.v1.ColumnReference
	(*Order)(nil),               // 12: orm.compiler.v1.Order
	(*GroupExpression)(nil),     // 13: orm.compiler.v1.GroupExpression
	(*Limit)(nil),               // 14: orm.compiler.v1.Limit
	(*IfParent)(nil),            // 15: orm.compiler.v1.IfParent
	(*Assignment)(nil),          // 16: orm.compiler.v1.Assignment
	(*Optimistic)(nil),          // 17: orm.compiler.v1.Optimistic
	(*Raw)(nil),                 // 18: orm.compiler.v1.Raw
	(*CompileResponse)(nil),     // 19: orm.compiler.v1.CompileResponse
	(*Plan)(nil),                // 20: orm.compiler.v1.Plan
	(*PlanStep)(nil),            // 21: orm.compiler.v1.PlanStep
	(*BindSlot)(nil),            // 22: orm.compiler.v1.BindSlot
	(*KeyReference)(nil),        // 23: orm.compiler.v1.KeyReference
	(*ParentReference)(nil),     // 24: orm.compiler.v1.ParentReference
	(*ParentCondition)(nil),     // 25: orm.compiler.v1.ParentCondition
	(*Assemble)(nil),            // 26: orm.compiler.v1.Assemble
	(*OutputColumn)(nil),        // 27: orm.compiler.v1.OutputColumn
	(*Child)(nil),               // 28: orm.compiler.v1.Child
	(*CompileError)(nil),        // 29: orm.compiler.v1.CompileError
	(*GetMetadataRequest)(nil),  // 30: orm.compiler.v1.GetMetadataRequest
	(*GetMetadataResponse)(nil), // 31: orm.compiler.v1.GetMetadataResponse
	nil,                         // 32: orm.compiler.v1.Projection.AliasesEntry
	nil,                         // 33: orm.compiler.v1.Projection.ExpressionsEntry
}
var file_proto_orm_compiler_v1_compiler_proto_depIdxs = []int32{
	0,  // 0: orm.compiler.v1.CompileRequest.kind:type_name -> orm.compiler.v1.QueryKind
	3,  // 1: orm.compiler.v1.CompileRequest.root:type_name -> orm.compiler.v1.QueryNode
	16, // 2: orm.compiler.v1.CompileRequest.set:type_name -> orm.compiler.v1.Assignment
	16, // 3: orm.compiler.v1.CompileRequest.on_duplicate:type_name -> orm.compiler.v1.Assignment
	17, // 4: orm.compiler.v1.CompileRequest.optimistic:type_name -> orm.compiler.v1.Optimistic
	18, // 5: orm.compiler.v1.CompileRequest.raw:type_name -> orm.compiler.v1.Raw
	4,  // 6: orm.compiler.v1.QueryNode.columns:type_name -> orm.compiler.v1.Projection
	7,  // 7: orm.compiler.v1.QueryNode.on:type_name -> orm.compiler.v1.Group
	7,  // 8: orm.compiler.v1.QueryNode.where:type_name -> orm.compiler.v1.Group
	7,  // 9: orm.compiler.v1.QueryNode.having:type_name -> orm.compiler.v1.Group
	5,  // 10: orm.compiler.v1.QueryNode.joins:type_name -> orm.compiler.v1.Join
	6,  // 11: orm.compiler.v1.QueryNode.relations:type_name -> orm.compiler.v1.Relation
	12, // 12: orm.compiler.v1.QueryNode.order:type_name -> orm.compiler.v1.Order
	13, // 13: orm.compiler.v1.QueryNode.group_by_expression:type_name -> orm.compiler.v1.GroupExpression
	14, // 14: orm.compiler.v1.QueryNode.limit:type_name -> orm.compiler.v1.Limit
	15, // 15: orm.compiler.v1.QueryNode.if_parent:type_name -> orm.compiler.v1.IfParent
	1,  // 16: orm.compiler.v1.Projection.mode:type_name -> orm.compiler.v1.Projection.Mode
	32, // 17: orm.compiler.v1.Projection.aliases:type_name -> orm.compiler.v1.Projection.AliasesEntry
	33, // 18: orm.compiler.v1.Projection.expressions:type_name -> orm.compiler.v1.Projection.ExpressionsEntry
	3,  // 19: orm.compiler.v1.Join.query:type_name -> orm.compiler.v1.QueryNode
	3,  // 20: orm.compiler.v1.Relation.query:type_name -> orm.compiler.v1.QueryNode
	8,  // 21: orm.compiler.v1.Group.items:type_name -> orm.compiler.v1.Item
	10, // 22: orm.compiler.v1.Item.predicate:type_name -> orm.compiler.v1.Predicate
	7,  // 23: orm.compiler.v1.Item.group:type_name -> orm.compiler.v1.Group
	9,  // 24: orm.compiler.v1.Item.navigation:type_name -> orm.compiler.v1.Navigation
	7,  // 25: orm.compiler.v1.Navigation.group:type_name -> orm.compiler.v1.Group
	11, // 26: orm.compiler.v1.Predicate.reference:type_name -> orm.compiler.v1.ColumnReference
	20, // 27: orm.compiler.v1.CompileResponse.plan:type_name -> orm.compiler.v1.Plan
	29, // 28: orm.compiler.v1.CompileResponse.error:type_name -> orm.compiler.v1.CompileError
	0,  // 29: orm.compiler.v1.Plan.kind:type_name -> orm.compiler.v1.QueryKind
	21, // 30: orm.compiler.v1.Plan.steps:type_name -> orm.compiler.v1.PlanStep
	22, // 31: orm.compiler.v1.PlanStep.binds:type_name -> orm.compiler.v1.BindSlot
	26, // 32: orm.compiler.v1.PlanStep.assemble:type_name -> orm.compiler.v1.Assemble
	24, // 33: orm.compiler.v1.PlanStep.parent:type_name -> orm.compiler.v1.ParentReference
	25, // 34: orm.compiler.v1.ParentReference.if_parent:type_name -> orm.compiler.v1.ParentCondition
	23, // 35: orm.compiler.v1.ParentReference.keys:type_name -> orm.compiler.v1.KeyReference
	27, // 36: orm.compiler.v1.Assemble.columns:type_name -> orm.compiler.v1.OutputColumn
	28, // 37: orm.compiler.v1.Assemble.children:type_name -> orm.compiler.v1.Child
	23, // 38: orm.compiler.v1.Assemble.key:type_name -> orm.compiler.v1.KeyReference
	26, // 39: orm.compiler.v1.Child.assemble:type_name -> orm.compiler.v1.Assemble
	23, // 40: orm.compiler.v1.Child.parent_keys:type_name -> orm.compiler.v1.KeyReference
	23, // 41: orm.compiler.v1.Child.child_keys:type_name -> orm.compiler.v1.KeyReference
	23, // 42: orm.compiler.v1.Child.key:type_name -> orm.compiler.v1.KeyReference
	2,  // 43: orm.compiler.v1.CompilerService.Compile:input_type -> orm.compiler.v1.CompileRequest
	30, // 44: orm.compiler.v1.CompilerService.GetMetadata:input_type -> orm.compiler.v1.GetMetadataRequest
	19, // 45: orm.compiler.v1.CompilerService.Compile:output_type -> orm.compiler.v1.CompileResponse
	31, // 46: orm.compiler.v1.CompilerService.GetMetadata:output_type -> orm.compiler.v1.GetMetadataResponse
	45, // [45:47] is the sub-list for method output_type
	43, // [43:45] is the sub-list for method input_type
	43, // [43:43] is the sub-list for extension type_name
	43, // [43:43] is the sub-list for extension extendee
	0,  // [0:43] is the sub-list for field type_name
}

func init() { file_proto_orm_compiler_v1_compiler_proto_init() }
func file_proto_orm_compiler_v1_compiler_proto_init() {
	if File_proto_orm_compiler_v1_compiler_proto != nil {
		return
	}
	file_proto_orm_compiler_v1_compiler_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_orm_compiler_v1_compiler_proto_msgTypes[6].OneofWrappers = []any{
		(*Item_Predicate)(nil),
		(*Item_Group)(nil),
		(*Item_Navigation)(nil),
	}
	file_proto_orm_compiler_v1_compiler_proto_msgTypes[8].OneofWrappers = []any{}
	file_proto_orm_compiler_v1_compiler_proto_msgTypes[14].OneofWrappers = []any{}
	file_proto_orm_compiler_v1_compiler_proto_msgTypes[17].OneofWrappers = []any{
		(*CompileResponse_Plan)(nil),
		(*CompileResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orm_compiler_v1_compiler_proto_rawDesc), len(file_proto_orm_compiler_v1_compiler_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orm_compiler_v1_compiler_proto_goTypes,
		DependencyIndexes: file_proto_orm_compiler_v1_compiler_proto_depIdxs,
		EnumInfos:         file_proto_orm_compiler_v1_compiler_proto_enumTypes,
		MessageInfos:      file_proto_orm_compiler_v1_compiler_proto_msgTypes,
	}.Build()
	File_proto_orm_compiler_v1_compiler_proto = out.File
	file_proto_orm_compiler_v1_compiler_proto_goTypes = nil
	file_proto_orm_compiler_v1_compiler_proto_depIdxs = nil
}
