<?php
declare(strict_types=1);
// The shared 2000-table, 60000-column, 10000-foreign-key document from
// tests/dbspec/stress.mjs: parse and emit times, emit(parse(doc)) === doc and
// two identical emissions, under the configured memory_limit.
require __DIR__ . '/autoload.php';

$started = hrtime(true);
echo 'RUN dbspec_stress memoryLimit=' . ini_get('memory_limit') . "\n";
$root = dirname(__DIR__, 3);
$process = proc_open(['node', "$root/tests/dbspec/stress.mjs"], [1 => ['pipe', 'w'], 2 => ['pipe', 'w']], $pipes);
if (!is_resource($process)) {
    throw new RuntimeException('node tests/dbspec/stress.mjs did not start');
}
$text = stream_get_contents($pipes[1]);
$errors = stream_get_contents($pipes[2]);
fclose($pipes[1]);
fclose($pipes[2]);
$status = proc_close($process);
if ($status !== 0 || $text === false || $text === '') {
    throw new RuntimeException("node tests/dbspec/stress.mjs failed with status $status: $errors");
}
echo 'STEP generated bytes=' . strlen($text) . ' elapsedMs=' . ((hrtime(true) - $started) / 1e6) . "\n";

$parseStarted = hrtime(true);
$result = Orm\Dbspec\Dbspec::parse($text, []);
$parseMs = (hrtime(true) - $parseStarted) / 1e6;
if ($result->document === null) {
    $first = array_slice($result->diagnostics, 0, 5);
    throw new RuntimeException('Stress document rejected: ' . implode('; ', array_map(static fn($d) => "{$d->line}:{$d->column} {$d->rule} {$d->message}", $first)));
}
$document = $result->document;
if (count($document->tables) !== 2000) {
    throw new RuntimeException('Stress document table count ' . count($document->tables));
}
$columns = 0;
$foreignKeys = 0;
foreach ($document->tables as $table) {
    $columns += count($table->columns);
    $foreignKeys += count($table->foreignKeys);
}
if ($columns !== 60000 || $foreignKeys !== 10000) {
    throw new RuntimeException("Stress document has $columns columns and $foreignKeys foreign keys");
}
echo "STEP parsed parseMs=$parseMs\n";

$emitStarted = hrtime(true);
$first = Orm\Dbspec\Dbspec::emit($document);
$emitMs = (hrtime(true) - $emitStarted) / 1e6;
$second = Orm\Dbspec\Dbspec::emit($document);
if ($first !== $text) {
    throw new RuntimeException('emit(parse(doc)) differs from the stress document');
}
if ($second !== $first) {
    throw new RuntimeException('Two emissions differ');
}
echo "STEP emitted emitMs=$emitMs\n";

$elapsed = (hrtime(true) - $started) / 1e6;
// The test's own deadline guards a hang; the parse budget is recorded from
// the first measurement in the checklist, not asserted here before it exists.
if ($elapsed > 60000) {
    throw new RuntimeException("dbspec_stress deadline of 60 s exceeded ($elapsed ms)");
}
echo "PASS dbspec_stress parseMs=$parseMs emitMs=$emitMs peakBytes=" . memory_get_peak_usage(true) . ' memoryLimit=' . ini_get('memory_limit') . " elapsedMs=$elapsed\n";
