<?php
declare(strict_types=1);
// The shared 2000-table, 60000-column, 10000-foreign-key document from
// tests/dbspec/stress.mjs: parse and emit times, emit(parse(doc)) === doc and
// two identical emissions, under the configured memory_limit.
require __DIR__ . '/autoload.php';
require_once __DIR__ . '/case_clock.php';

$started = caseClockStart();
echo 'RUN dbspec_stress memoryLimit=' . ini_get('memory_limit') . "\n";
$root = dirname(__DIR__, 3);
$process = proc_open(['node', "$root/tests/dbspec/stress.mjs"], [1 => ['pipe', 'w'], 2 => ['pipe', 'w']], $pipes);
if (!is_resource($process)) {
    throw new RuntimeException('node tests/dbspec/stress.mjs did not start');
}
$text = stream_get_contents($pipes[1]);
$errors = stream_get_contents($pipes[2]);
fclose($pipes[1]);
fclose($pipes[2]);
$status = proc_close($process);
if ($status !== 0 || $text === false || $text === '') {
    throw new RuntimeException("node tests/dbspec/stress.mjs failed with status $status: $errors");
}
echo 'STEP generated bytes=' . strlen($text) . ' wallMs=' . caseClockElapsed($started)[1] . "\n";

$parses = [];
for ($i = 0; $i < 5; $i++) {
    $result = null;
    $parseStarted = caseClockStart();
    $result = Orm\Dbspec\Dbspec::parse($text, []);
    [$parseCpuMs, $parseWallMs] = caseClockElapsed($parseStarted);
    echo "STEP parse cpuMs=$parseCpuMs wallMs=$parseWallMs\n";
    $parses[] = $parseCpuMs;
}
sort($parses);
$parseMs = $parses[2];
if ($result->document === null) {
    $first = array_slice($result->diagnostics, 0, 5);
    throw new RuntimeException('Stress document rejected: ' . implode('; ', array_map(static fn($d) => "{$d->line}:{$d->column} {$d->rule} {$d->message}", $first)));
}
$document = $result->document;
if (count($document->tables) !== 2000) {
    throw new RuntimeException('Stress document table count ' . count($document->tables));
}
$columns = 0;
$foreignKeys = 0;
foreach ($document->tables as $table) {
    $columns += count($table->columns);
    $foreignKeys += count($table->foreignKeys);
}
if ($columns !== 60000 || $foreignKeys !== 10000) {
    throw new RuntimeException("Stress document has $columns columns and $foreignKeys foreign keys");
}
echo "STEP parsed cpu minMs={$parses[0]} medianMs=$parseMs maxMs={$parses[4]}\n";

$emitStarted = caseClockStart();
$first = Orm\Dbspec\Dbspec::emit($document);
$emitMs = caseClockElapsed($emitStarted)[0];
$second = Orm\Dbspec\Dbspec::emit($document);
if ($first !== $text) {
    throw new RuntimeException('emit(parse(doc)) differs from the stress document');
}
if ($second !== $first) {
    throw new RuntimeException('Two emissions differ');
}
echo "STEP emitted emitMs=$emitMs\n";

[$cpuMs, $wallMs] = caseClockElapsed($started);
// The parse budget is docs/dbspec.md, "Verification": the median CPU time of a parse.
$parseBudgetMs = 400;
if ($parseMs > $parseBudgetMs) {
    throw new RuntimeException("dbspec_stress median parse CPU of $parseMs ms exceeds the $parseBudgetMs ms budget");
}
if ($cpuMs > 60000) {
    throw new RuntimeException("dbspec_stress CPU deadline of 60 s exceeded ($cpuMs ms CPU, $wallMs ms wall)");
}
echo "PASS dbspec_stress parseMs=$parseMs emitMs=$emitMs peakBytes=" . memory_get_peak_usage(true) . ' memoryLimit=' . ini_get('memory_limit') . " cpuMs=$cpuMs wallMs=$wallMs\n";
