<?php
declare(strict_types=1);
// The shared 2000-table, 60000-column, 10000-foreign-key document from
// tests/dbspec/stress.mjs: parse and emit times, emit(parse(doc)) === doc and
// two identical emissions, under the configured memory_limit.
require __DIR__ . '/autoload.php';
require_once __DIR__ . '/case_clock.php';

// stress case의 CPU 한도는 60 s다. 문서 생성(node process 하나), parse 다섯 번, emit 두 번을 담는다.
$clock = cpuCaseBegin('dbspec_stress', 60.0);
$started = $clock[0];
testcase_step('memoryLimit=' . ini_get('memory_limit'));
$root = dirname(__DIR__, 3);
$process = proc_open(['node', "$root/tests/dbspec/stress.mjs"], [1 => ['pipe', 'w'], 2 => ['pipe', 'w']], $pipes);
if (!is_resource($process)) {
    throw new RuntimeException('node tests/dbspec/stress.mjs did not start');
}
$text = stream_get_contents($pipes[1]);
$errors = stream_get_contents($pipes[2]);
fclose($pipes[1]);
fclose($pipes[2]);
$status = proc_close($process);
if ($status !== 0 || $text === false || $text === '') {
    throw new RuntimeException("node tests/dbspec/stress.mjs failed with status $status: $errors");
}
testcase_step('generated bytes=' . strlen($text));

$parses = [];
for ($i = 0; $i < 5; $i++) {
    $result = null;
    $parseStarted = caseClockStart();
    $result = Orm\Dbspec\Dbspec::parse($text, []);
    [$parseCpuMs, $parseWallMs] = caseClockElapsed($parseStarted);
    testcase_step("parse cpuMs=$parseCpuMs wallMs=$parseWallMs");
    $parses[] = $parseCpuMs;
}
sort($parses);
$parseMs = $parses[2];
if ($result->document === null) {
    $first = array_slice($result->diagnostics, 0, 5);
    throw new RuntimeException('Stress document rejected: ' . implode('; ', array_map(static fn($d) => "{$d->line}:{$d->column} {$d->rule} {$d->message}", $first)));
}
$document = $result->document;
if (count($document->tables) !== 2000) {
    throw new RuntimeException('Stress document table count ' . count($document->tables));
}
$columns = 0;
$foreignKeys = 0;
foreach ($document->tables as $table) {
    $columns += count($table->columns);
    $foreignKeys += count($table->foreignKeys);
}
if ($columns !== 60000 || $foreignKeys !== 10000) {
    throw new RuntimeException("Stress document has $columns columns and $foreignKeys foreign keys");
}
testcase_step("parsed cpu minMs={$parses[0]} medianMs=$parseMs maxMs={$parses[4]}");

$emitStarted = caseClockStart();
$first = Orm\Dbspec\Dbspec::emit($document);
$emitMs = caseClockElapsed($emitStarted)[0];
$second = Orm\Dbspec\Dbspec::emit($document);
if ($first !== $text) {
    throw new RuntimeException('emit(parse(doc)) differs from the stress document');
}
if ($second !== $first) {
    throw new RuntimeException('Two emissions differ');
}
testcase_step("emitted emitMs=$emitMs");

// The parse budget is docs/dbspec.md, "Verification": the median CPU time of a parse.
$parseBudgetMs = 400;
if ($parseMs > $parseBudgetMs) {
    throw new RuntimeException("dbspec_stress median parse CPU of $parseMs ms exceeds the $parseBudgetMs ms budget");
}
testcase_step("parseMs=$parseMs emitMs=$emitMs peakBytes=" . memory_get_peak_usage(true));
cpuCaseEnd('dbspec_stress', $clock);
