// Code generated by ormgen; DO NOT EDIT.

package model

import (
	"time"

	"github.com/polyspec/orm/clients/go/orm"
)

var _ time.Time

// AccountProjectModel is a account_project model or row.
type AccountProjectModel struct {
	m           *orm.Core
	fAccountSeq int64
	fProjectSeq int64
}

var accountProjectEntity = &orm.Entity{Name: "account_project", Schema: ormSchema, New: func(c *orm.Core) orm.Model { x := &AccountProjectModel{m: c}; c.Bind(x); return x },
	Assign: func(m orm.Model, name string, v any) bool { return m.(*AccountProjectModel).assign(name, v) },
	Value:  func(m orm.Model, name string) (any, bool) { return m.(*AccountProjectModel).value(name) },
	Collect: func(keys []orm.Key, items map[orm.Key]*orm.Core, fetched map[orm.Key]any) any {
		return orm.CollectOf[*AccountProjectModel](keys, items, fetched)
	},
}

// AccountProject creates a account_project model.
func AccountProject() *AccountProjectModel {
	return accountProjectEntity.New(orm.NewCore(accountProjectEntity)).(*AccountProjectModel)
}

func (x *AccountProjectModel) Orm_() *orm.Core { return x.m }

// MarshalJSON writes the row values in order.
func (x *AccountProjectModel) MarshalJSON() ([]byte, error) { return x.m.MarshalJSON() }

// ToArray returns the row values.
func (x *AccountProjectModel) ToArray() map[string]any { return x.m.ToArray() }

func (x *AccountProjectModel) assign(name string, v any) bool {
	switch name {
	case "account_seq":
		x.fAccountSeq = orm.AsInt64(v)
	case "project_seq":
		x.fProjectSeq = orm.AsInt64(v)
	default:
		return false
	}
	return true
}

func (x *AccountProjectModel) value(name string) (any, bool) {
	switch name {
	case "account_seq":
		return x.fAccountSeq, true
	case "project_seq":
		return x.fProjectSeq, true
	}
	return nil, false
}

// Connect sets the connection.
func (x *AccountProjectModel) Connect(db *orm.DB) *AccountProjectModel { x.m.Connect(db); return x }

// And joins the next condition with AND, opens an AND group with a callback,
// or places the conditions of a joined model.
func (x *AccountProjectModel) And(args ...any) *AccountProjectModel { return x.connector("and", args) }

// Or joins the next condition with OR, opens an OR group with a callback, or
// places the conditions of a joined model.
func (x *AccountProjectModel) Or(args ...any) *AccountProjectModel { return x.connector("or", args) }

func (x *AccountProjectModel) connector(conn string, args []any) *AccountProjectModel {
	if len(args) == 1 {
		if fn, ok := args[0].(func(*AccountProjectModel)); ok {
			g := accountProjectEntity.New(x.m.Group()).(*AccountProjectModel)
			fn(g)
			x.m.AddGroup(conn, g.m)
			return x
		}
	}
	x.m.Connector(conn, args)
	return x
}

// Raw adds a raw first condition.
func (x *AccountProjectModel) Raw(sql string, binds ...any) *AccountProjectModel {
	x.m.Raw("", sql, binds)
	return x
}

// AndRaw adds a raw condition joined with AND.
func (x *AccountProjectModel) AndRaw(sql string, binds ...any) *AccountProjectModel {
	x.m.Raw("and", sql, binds)
	return x
}

// OrRaw adds a raw condition joined with OR.
func (x *AccountProjectModel) OrRaw(sql string, binds ...any) *AccountProjectModel {
	x.m.Raw("or", sql, binds)
	return x
}

// On sets the join ON conditions.
func (x *AccountProjectModel) On(fn func(*AccountProjectModel)) *AccountProjectModel {
	g := accountProjectEntity.New(x.m.Group()).(*AccountProjectModel)
	fn(g)
	x.m.On(g.m)
	return x
}

// Relation attaches one related row loaded by a separate query.
func (x *AccountProjectModel) Relation(child orm.Model) *AccountProjectModel {
	x.m.Relation(false, child)
	return x
}

// Relations attaches related rows loaded by a separate query.
func (x *AccountProjectModel) Relations(child orm.Model) *AccountProjectModel {
	x.m.Relation(true, child)
	return x
}

// Get returns the first matching row, or nil.
func (x *AccountProjectModel) Get() (*AccountProjectModel, error) { return oneAccountProject(x.m) }

func oneAccountProject(c *orm.Core) (*AccountProjectModel, error) {
	m, err := c.Get()
	if m == nil {
		return nil, err
	}
	return m.(*AccountProjectModel), err
}

// Gets returns the matching rows.
func (x *AccountProjectModel) Gets() (*orm.Collection[*AccountProjectModel], error) {
	return orm.Gets[*AccountProjectModel](x.m)
}

// GetCount returns the number of matching rows.
func (x *AccountProjectModel) GetCount() (int64, error) { return x.m.GetCount() }

// GetsCount returns grouped rows with row_count.
func (x *AccountProjectModel) GetsCount() (*orm.Collection[*AccountProjectModel], error) {
	return orm.GetsCount[*AccountProjectModel](x.m)
}

// GetSum returns the sum of the column selected with Sum<Col>.
func (x *AccountProjectModel) GetSum() (float64, error) { return x.m.GetSum() }

// GetAvg returns the average of the column selected with Avg<Col>.
func (x *AccountProjectModel) GetAvg() (float64, error) { return x.m.GetAvg() }

// GetsPage returns one page of matching rows.
func (x *AccountProjectModel) GetsPage(page, perPage int) (*orm.Page[*AccountProjectModel], error) {
	return orm.GetsPage[*AccountProjectModel](x.m, page, perPage)
}

// GetQuery returns the statement of Gets without executing it.
func (x *AccountProjectModel) GetQuery() (*orm.Statement, error) { return x.m.GetQuery() }

// Create inserts the row and returns the created row.
func (x *AccountProjectModel) Create() (*AccountProjectModel, error) {
	m, err := x.m.Create()
	if err != nil {
		return nil, err
	}
	return m.(*AccountProjectModel), nil
}

// Creates inserts rows in one transaction and returns the inserted row count.
func (x *AccountProjectModel) Creates(rows []*AccountProjectModel) (int64, error) {
	return orm.Creates(x.m, rows)
}

// Update writes the changed columns; Update(true) requires an unchanged updated time.
func (x *AccountProjectModel) Update(optimistic ...bool) (*AccountProjectModel, error) {
	if err := x.m.Update(optimistic); err != nil {
		return nil, err
	}
	return x, nil
}

// Save updates the row when its primary key is known, otherwise creates it.
func (x *AccountProjectModel) Save() (*AccountProjectModel, error) {
	m, err := x.m.Save()
	if err != nil {
		return nil, err
	}
	return m.(*AccountProjectModel), nil
}

// Delete deletes the row; Delete(true) first deletes loaded related rows.
func (x *AccountProjectModel) Delete(recursive ...bool) error { return x.m.Delete(recursive) }

// Duplication sets the duplicate-key update of the next Create.
func (x *AccountProjectModel) Duplication(m *AccountProjectModel) *AccountProjectModel {
	x.m.Duplication(m)
	return x
}

// Limit sets the row range.
func (x *AccountProjectModel) Limit(offset, count int) *AccountProjectModel {
	x.m.Limit(offset, count)
	return x
}

// OrderByRandom orders rows randomly.
func (x *AccountProjectModel) OrderByRandom() *AccountProjectModel { x.m.OrderByRandom(); return x }

// OrderByRaw appends a raw order expression.
func (x *AccountProjectModel) OrderByRaw(sql string) *AccountProjectModel {
	x.m.OrderByRaw(sql)
	return x
}

// GroupByRaw appends a raw grouping expression.
func (x *AccountProjectModel) GroupByRaw(sql string) *AccountProjectModel {
	x.m.GroupByRaw(sql)
	return x
}

// RemoveAllColumns keeps only primary and foreign keys.
func (x *AccountProjectModel) RemoveAllColumns() *AccountProjectModel {
	x.m.RemoveAllColumns()
	return x
}

// AddAllColumns selects every column.
func (x *AccountProjectModel) AddAllColumns() *AccountProjectModel { x.m.AddAllColumns(); return x }

// ParentNode merges the related row into the parent row.
func (x *AccountProjectModel) ParentNode() *AccountProjectModel { x.m.ParentNode(); return x }

// GroupLimit limits related rows per parent.
func (x *AccountProjectModel) GroupLimit(n int) *AccountProjectModel { x.m.GroupLimit(n); return x }

// DeleteLock excludes the relation from recursive delete.
func (x *AccountProjectModel) DeleteLock() *AccountProjectModel { x.m.DeleteLock(); return x }

// FetchKey computes the collection key of each row.
func (x *AccountProjectModel) FetchKey(fn func(*AccountProjectModel) any) *AccountProjectModel {
	x.m.FetchKey(func(m orm.Model) any { return fn(m.(*AccountProjectModel)) })
	return x
}

// FetchValue computes a value for each loaded row.
func (x *AccountProjectModel) FetchValue(fn func(*AccountProjectModel) any) *AccountProjectModel {
	x.m.FetchValue(func(m orm.Model) any { return fn(m.(*AccountProjectModel)) })
	return x
}

// ForUpdate locks the selected rows for update inside a transaction.
func (x *AccountProjectModel) ForUpdate() *AccountProjectModel { x.m.Lock("update"); return x }

// ForShare locks the selected rows for share inside a transaction.
func (x *AccountProjectModel) ForShare() *AccountProjectModel { x.m.Lock("share"); return x }

// ForUpdateNoWait locks for update without waiting.
func (x *AccountProjectModel) ForUpdateNoWait() *AccountProjectModel {
	x.m.Lock("update_nowait")
	return x
}

// ForShareNoWait locks for share without waiting.
func (x *AccountProjectModel) ForShareNoWait() *AccountProjectModel {
	x.m.Lock("share_nowait")
	return x
}

// GetAccountSeq returns account_seq.
func (x *AccountProjectModel) GetAccountSeq() int64 { return x.fAccountSeq }

// SetAccountSeq sets account_seq.
func (x *AccountProjectModel) SetAccountSeq(v int64) *AccountProjectModel {
	x.fAccountSeq = v
	x.m.Set("account_seq", v)
	return x
}

func (x *AccountProjectModel) SetRawAccountSeq(sql string, binds ...any) *AccountProjectModel {
	x.m.SetRaw("account_seq", sql, binds)
	return x
}
func (x *AccountProjectModel) AddColumnAccountSeq() *AccountProjectModel {
	x.m.AddColumn("account_seq")
	return x
}
func (x *AccountProjectModel) RemoveColumnAccountSeq() *AccountProjectModel {
	x.m.RemoveColumn("account_seq")
	return x
}
func (x *AccountProjectModel) GroupByAccountSeq() *AccountProjectModel {
	x.m.GroupBy("account_seq")
	return x
}
func (x *AccountProjectModel) KeyNameAccountSeq() *AccountProjectModel {
	x.m.KeyName("account_seq")
	return x
}
func (x *AccountProjectModel) OrderByAccountSeqAsc(fn ...orm.Func) *AccountProjectModel {
	x.m.OrderBy("account_seq", false, fn)
	return x
}
func (x *AccountProjectModel) OrderByAccountSeqDesc(fn ...orm.Func) *AccountProjectModel {
	x.m.OrderBy("account_seq", true, fn)
	return x
}
func (x *AccountProjectModel) PlusAccountSeq(n int64) *AccountProjectModel {
	x.m.Plus("account_seq", n)
	return x
}
func (x *AccountProjectModel) MinusAccountSeq(n int64) *AccountProjectModel {
	x.m.Minus("account_seq", n)
	return x
}
func (x *AccountProjectModel) SumAccountSeq() *AccountProjectModel {
	x.m.Aggregate("sum", "account_seq")
	return x
}
func (x *AccountProjectModel) AvgAccountSeq() *AccountProjectModel {
	x.m.Aggregate("avg", "account_seq")
	return x
}

// GetProjectSeq returns project_seq.
func (x *AccountProjectModel) GetProjectSeq() int64 { return x.fProjectSeq }

// SetProjectSeq sets project_seq.
func (x *AccountProjectModel) SetProjectSeq(v int64) *AccountProjectModel {
	x.fProjectSeq = v
	x.m.Set("project_seq", v)
	return x
}

func (x *AccountProjectModel) SetRawProjectSeq(sql string, binds ...any) *AccountProjectModel {
	x.m.SetRaw("project_seq", sql, binds)
	return x
}
func (x *AccountProjectModel) AddColumnProjectSeq() *AccountProjectModel {
	x.m.AddColumn("project_seq")
	return x
}
func (x *AccountProjectModel) RemoveColumnProjectSeq() *AccountProjectModel {
	x.m.RemoveColumn("project_seq")
	return x
}
func (x *AccountProjectModel) GroupByProjectSeq() *AccountProjectModel {
	x.m.GroupBy("project_seq")
	return x
}
func (x *AccountProjectModel) KeyNameProjectSeq() *AccountProjectModel {
	x.m.KeyName("project_seq")
	return x
}
func (x *AccountProjectModel) OrderByProjectSeqAsc(fn ...orm.Func) *AccountProjectModel {
	x.m.OrderBy("project_seq", false, fn)
	return x
}
func (x *AccountProjectModel) OrderByProjectSeqDesc(fn ...orm.Func) *AccountProjectModel {
	x.m.OrderBy("project_seq", true, fn)
	return x
}
func (x *AccountProjectModel) PlusProjectSeq(n int64) *AccountProjectModel {
	x.m.Plus("project_seq", n)
	return x
}
func (x *AccountProjectModel) MinusProjectSeq(n int64) *AccountProjectModel {
	x.m.Minus("project_seq", n)
	return x
}
func (x *AccountProjectModel) SumProjectSeq() *AccountProjectModel {
	x.m.Aggregate("sum", "project_seq")
	return x
}
func (x *AccountProjectModel) AvgProjectSeq() *AccountProjectModel {
	x.m.Aggregate("avg", "project_seq")
	return x
}
