// Code generated by ormgen; DO NOT EDIT.

package model

import (
	"time"

	"github.com/polyspec/orm/clients/go/orm"
)

var _ time.Time

// BattleModel is a battle model or row.
type BattleModel struct {
	m                      *orm.Core
	fSeq                   int64
	fName                  string
	fDescription           *string
	fCreatedTs             time.Time
	fUpdatedTs             time.Time
	fIsClose               bool
	fIsDisplay             bool
	fDisplayStartDt        *time.Time
	fDisplayEndDt          *time.Time
	fIsAllday              bool
	fTargetTeamPlayerCount int64
	fSuccessCount          int64
	fPlayerCount           int64
	fReadCount             int64
	fCoverUrl              *string
	fUserSeq               int64
	fServiceSeq            int64
	fServiceModuleSeq      int64
	fServiceMemberSeq      int64
	fStartDt               time.Time
	fEndDt                 time.Time
	fUuid                  *string
	fIsSinglePlay          bool
	fLikeCount             int64
	fAesKeyVersion         int32
	fAesHexEmail           *string
	fEmailBlindIndex       *string
	fAesHexPhone           *string
	fPhoneBlindIndex       *string
	fPrice                 *float64
	fIp                    *string
	fGzExtend              any
	fJsonSetting           any
	fJsonsTags             any
	fBase64Extra           any
	fSerializeData         any
}

var battleEntity = &orm.Entity{Name: "battle", Schema: ormSchema, New: func(c *orm.Core) orm.Model { x := &BattleModel{m: c}; c.Bind(x); return x },
	Assign: func(m orm.Model, name string, v any) bool { return m.(*BattleModel).assign(name, v) },
	Value:  func(m orm.Model, name string) (any, bool) { return m.(*BattleModel).value(name) },
	Collect: func(keys []orm.Key, items map[orm.Key]*orm.Core, fetched map[orm.Key]any) any {
		return orm.CollectOf[*BattleModel](keys, items, fetched)
	},
}

// Battle creates a battle model.
func Battle() *BattleModel { return battleEntity.New(orm.NewCore(battleEntity)).(*BattleModel) }

func (x *BattleModel) Orm_() *orm.Core { return x.m }

// MarshalJSON writes the row values in order.
func (x *BattleModel) MarshalJSON() ([]byte, error) { return x.m.MarshalJSON() }

// ToArray returns the row values.
func (x *BattleModel) ToArray() map[string]any { return x.m.ToArray() }

func (x *BattleModel) assign(name string, v any) bool {
	switch name {
	case "seq":
		x.fSeq = orm.AsInt64(v)
	case "name":
		x.fName = orm.AsString(v)
	case "description":
		if v == nil {
			x.fDescription = nil
		} else {
			t := orm.AsString(v)
			x.fDescription = &t
		}
	case "created_ts":
		x.fCreatedTs = orm.AsTime(v)
	case "updated_ts":
		x.fUpdatedTs = orm.AsTime(v)
	case "is_close":
		x.fIsClose = orm.AsBool(v)
	case "is_display":
		x.fIsDisplay = orm.AsBool(v)
	case "display_start_dt":
		if v == nil {
			x.fDisplayStartDt = nil
		} else {
			t := orm.AsTime(v)
			x.fDisplayStartDt = &t
		}
	case "display_end_dt":
		if v == nil {
			x.fDisplayEndDt = nil
		} else {
			t := orm.AsTime(v)
			x.fDisplayEndDt = &t
		}
	case "is_allday":
		x.fIsAllday = orm.AsBool(v)
	case "target_team_player_count":
		x.fTargetTeamPlayerCount = orm.AsInt64(v)
	case "success_count":
		x.fSuccessCount = orm.AsInt64(v)
	case "player_count":
		x.fPlayerCount = orm.AsInt64(v)
	case "read_count":
		x.fReadCount = orm.AsInt64(v)
	case "cover_url":
		if v == nil {
			x.fCoverUrl = nil
		} else {
			t := orm.AsString(v)
			x.fCoverUrl = &t
		}
	case "user_seq":
		x.fUserSeq = orm.AsInt64(v)
	case "service_seq":
		x.fServiceSeq = orm.AsInt64(v)
	case "service_module_seq":
		x.fServiceModuleSeq = orm.AsInt64(v)
	case "service_member_seq":
		x.fServiceMemberSeq = orm.AsInt64(v)
	case "start_dt":
		x.fStartDt = orm.AsTime(v)
	case "end_dt":
		x.fEndDt = orm.AsTime(v)
	case "uuid":
		if v == nil {
			x.fUuid = nil
		} else {
			t := orm.AsString(v)
			x.fUuid = &t
		}
	case "is_single_play":
		x.fIsSinglePlay = orm.AsBool(v)
	case "like_count":
		x.fLikeCount = orm.AsInt64(v)
	case "aes_key_version":
		x.fAesKeyVersion = int32(orm.AsInt64(v))
	case "aes_hex_email":
		if v == nil {
			x.fAesHexEmail = nil
		} else {
			t := orm.AsString(v)
			x.fAesHexEmail = &t
		}
	case "email_blind_index":
		if v == nil {
			x.fEmailBlindIndex = nil
		} else {
			t := orm.AsString(v)
			x.fEmailBlindIndex = &t
		}
	case "aes_hex_phone":
		if v == nil {
			x.fAesHexPhone = nil
		} else {
			t := orm.AsString(v)
			x.fAesHexPhone = &t
		}
	case "phone_blind_index":
		if v == nil {
			x.fPhoneBlindIndex = nil
		} else {
			t := orm.AsString(v)
			x.fPhoneBlindIndex = &t
		}
	case "price":
		if v == nil {
			x.fPrice = nil
		} else {
			t := orm.AsFloat64(v)
			x.fPrice = &t
		}
	case "ip":
		if v == nil {
			x.fIp = nil
		} else {
			t := orm.AsString(v)
			x.fIp = &t
		}
	case "gz_extend":
		x.fGzExtend = v
	case "json_setting":
		x.fJsonSetting = v
	case "jsons_tags":
		x.fJsonsTags = v
	case "base64_extra":
		x.fBase64Extra = v
	case "serialize_data":
		x.fSerializeData = v
	default:
		return false
	}
	return true
}

func (x *BattleModel) value(name string) (any, bool) {
	switch name {
	case "seq":
		return x.fSeq, true
	case "name":
		return x.fName, true
	case "description":
		if x.fDescription == nil {
			return nil, true
		}
		return *x.fDescription, true
	case "created_ts":
		return x.fCreatedTs, true
	case "updated_ts":
		return x.fUpdatedTs, true
	case "is_close":
		return x.fIsClose, true
	case "is_display":
		return x.fIsDisplay, true
	case "display_start_dt":
		if x.fDisplayStartDt == nil {
			return nil, true
		}
		return *x.fDisplayStartDt, true
	case "display_end_dt":
		if x.fDisplayEndDt == nil {
			return nil, true
		}
		return *x.fDisplayEndDt, true
	case "is_allday":
		return x.fIsAllday, true
	case "target_team_player_count":
		return x.fTargetTeamPlayerCount, true
	case "success_count":
		return x.fSuccessCount, true
	case "player_count":
		return x.fPlayerCount, true
	case "read_count":
		return x.fReadCount, true
	case "cover_url":
		if x.fCoverUrl == nil {
			return nil, true
		}
		return *x.fCoverUrl, true
	case "user_seq":
		return x.fUserSeq, true
	case "service_seq":
		return x.fServiceSeq, true
	case "service_module_seq":
		return x.fServiceModuleSeq, true
	case "service_member_seq":
		return x.fServiceMemberSeq, true
	case "start_dt":
		return x.fStartDt, true
	case "end_dt":
		return x.fEndDt, true
	case "uuid":
		if x.fUuid == nil {
			return nil, true
		}
		return *x.fUuid, true
	case "is_single_play":
		return x.fIsSinglePlay, true
	case "like_count":
		return x.fLikeCount, true
	case "aes_key_version":
		return x.fAesKeyVersion, true
	case "aes_hex_email":
		if x.fAesHexEmail == nil {
			return nil, true
		}
		return *x.fAesHexEmail, true
	case "email_blind_index":
		if x.fEmailBlindIndex == nil {
			return nil, true
		}
		return *x.fEmailBlindIndex, true
	case "aes_hex_phone":
		if x.fAesHexPhone == nil {
			return nil, true
		}
		return *x.fAesHexPhone, true
	case "phone_blind_index":
		if x.fPhoneBlindIndex == nil {
			return nil, true
		}
		return *x.fPhoneBlindIndex, true
	case "price":
		if x.fPrice == nil {
			return nil, true
		}
		return *x.fPrice, true
	case "ip":
		if x.fIp == nil {
			return nil, true
		}
		return *x.fIp, true
	case "gz_extend":
		return x.fGzExtend, true
	case "json_setting":
		return x.fJsonSetting, true
	case "jsons_tags":
		return x.fJsonsTags, true
	case "base64_extra":
		return x.fBase64Extra, true
	case "serialize_data":
		return x.fSerializeData, true
	}
	return nil, false
}

// Connect sets the connection.
func (x *BattleModel) Connect(db *orm.DB) *BattleModel { x.m.Connect(db); return x }

// And joins the next condition with AND, opens an AND group with a callback,
// or places the conditions of a joined model.
func (x *BattleModel) And(args ...any) *BattleModel { return x.connector("and", args) }

// Or joins the next condition with OR, opens an OR group with a callback, or
// places the conditions of a joined model.
func (x *BattleModel) Or(args ...any) *BattleModel { return x.connector("or", args) }

func (x *BattleModel) connector(conn string, args []any) *BattleModel {
	if len(args) == 1 {
		if fn, ok := args[0].(func(*BattleModel)); ok {
			g := battleEntity.New(x.m.Group()).(*BattleModel)
			fn(g)
			x.m.AddGroup(conn, g.m)
			return x
		}
	}
	x.m.Connector(conn, args)
	return x
}

// Raw adds a raw first condition.
func (x *BattleModel) Raw(sql string, binds ...any) *BattleModel { x.m.Raw("", sql, binds); return x }

// AndRaw adds a raw condition joined with AND.
func (x *BattleModel) AndRaw(sql string, binds ...any) *BattleModel {
	x.m.Raw("and", sql, binds)
	return x
}

// OrRaw adds a raw condition joined with OR.
func (x *BattleModel) OrRaw(sql string, binds ...any) *BattleModel {
	x.m.Raw("or", sql, binds)
	return x
}

// On sets the join ON conditions.
func (x *BattleModel) On(fn func(*BattleModel)) *BattleModel {
	g := battleEntity.New(x.m.Group()).(*BattleModel)
	fn(g)
	x.m.On(g.m)
	return x
}

// Relation attaches one related row loaded by a separate query.
func (x *BattleModel) Relation(child orm.Model) *BattleModel { x.m.Relation(false, child); return x }

// Relations attaches related rows loaded by a separate query.
func (x *BattleModel) Relations(child orm.Model) *BattleModel { x.m.Relation(true, child); return x }

// Get returns the first matching row. It returns orm.CodeNoRows when no row matches.
func (x *BattleModel) Get() (*BattleModel, error) { return oneBattle(x.m) }

func oneBattle(c *orm.Core) (*BattleModel, error) {
	m, err := c.Get()
	if m == nil {
		return nil, err
	}
	return m.(*BattleModel), err
}

// Gets returns the matching rows.
func (x *BattleModel) Gets() (*orm.Collection[*BattleModel], error) {
	return orm.Gets[*BattleModel](x.m)
}

// GetCount returns the number of matching rows.
func (x *BattleModel) GetCount() (int64, error) { return x.m.GetCount() }

// GetsCount returns grouped rows with row_count.
func (x *BattleModel) GetsCount() (*orm.Collection[*BattleModel], error) {
	return orm.GetsCount[*BattleModel](x.m)
}

// GetSum returns the sum of the column selected with Sum<Col>.
func (x *BattleModel) GetSum() (float64, error) { return x.m.GetSum() }

// GetAvg returns the average of the column selected with Avg<Col>.
func (x *BattleModel) GetAvg() (float64, error) { return x.m.GetAvg() }

// GetsPage returns one page of matching rows.
func (x *BattleModel) GetsPage(page, perPage int) (*orm.Page[*BattleModel], error) {
	return orm.GetsPage[*BattleModel](x.m, page, perPage)
}

// GetQuery returns the statement of Gets without executing it.
func (x *BattleModel) GetQuery() (*orm.Statement, error) { return x.m.GetQuery() }

// Create inserts the row and returns the created row.
func (x *BattleModel) Create() (*BattleModel, error) {
	m, err := x.m.Create()
	if err != nil {
		return nil, err
	}
	return m.(*BattleModel), nil
}

// Creates inserts rows in one transaction and returns the inserted row count.
func (x *BattleModel) Creates(rows []*BattleModel) (int64, error) { return orm.Creates(x.m, rows) }

// Update writes the changed columns; Update(true) requires an unchanged updated time.
func (x *BattleModel) Update(optimistic ...bool) (*BattleModel, error) {
	if err := x.m.Update(optimistic); err != nil {
		return nil, err
	}
	return x, nil
}

// Save updates the row when its primary key is known, otherwise creates it.
func (x *BattleModel) Save() (*BattleModel, error) {
	m, err := x.m.Save()
	if err != nil {
		return nil, err
	}
	return m.(*BattleModel), nil
}

// Delete deletes the row; Delete(true) first deletes loaded related rows.
func (x *BattleModel) Delete(recursive ...bool) error { return x.m.Delete(recursive) }

// Duplication sets the duplicate-key update of the next Create.
func (x *BattleModel) Duplication(m *BattleModel) *BattleModel { x.m.Duplication(m); return x }

// Limit sets the row range.
func (x *BattleModel) Limit(offset, count int) *BattleModel { x.m.Limit(offset, count); return x }

// OrderByRandom orders rows randomly.
func (x *BattleModel) OrderByRandom() *BattleModel { x.m.OrderByRandom(); return x }

// OrderByRaw appends a raw order expression.
func (x *BattleModel) OrderByRaw(sql string) *BattleModel { x.m.OrderByRaw(sql); return x }

// GroupByRaw appends a raw grouping expression.
func (x *BattleModel) GroupByRaw(sql string) *BattleModel { x.m.GroupByRaw(sql); return x }

// RemoveAllColumns keeps only primary and foreign keys.
func (x *BattleModel) RemoveAllColumns() *BattleModel { x.m.RemoveAllColumns(); return x }

// AddAllColumns selects every column.
func (x *BattleModel) AddAllColumns() *BattleModel { x.m.AddAllColumns(); return x }

// ParentNode merges the related row into the parent row.
func (x *BattleModel) ParentNode() *BattleModel { x.m.ParentNode(); return x }

// GroupLimit limits related rows per parent.
func (x *BattleModel) GroupLimit(n int) *BattleModel { x.m.GroupLimit(n); return x }

// DeleteLock excludes the relation from recursive delete.
func (x *BattleModel) DeleteLock() *BattleModel { x.m.DeleteLock(); return x }

// FetchKey computes the collection key of each row.
func (x *BattleModel) FetchKey(fn func(*BattleModel) any) *BattleModel {
	x.m.FetchKey(func(m orm.Model) any { return fn(m.(*BattleModel)) })
	return x
}

// FetchValue computes a value for each loaded row.
func (x *BattleModel) FetchValue(fn func(*BattleModel) any) *BattleModel {
	x.m.FetchValue(func(m orm.Model) any { return fn(m.(*BattleModel)) })
	return x
}

// ForUpdate locks the selected rows for update inside a transaction.
func (x *BattleModel) ForUpdate() *BattleModel { x.m.Lock("update"); return x }

// ForShare locks the selected rows for share inside a transaction.
func (x *BattleModel) ForShare() *BattleModel { x.m.Lock("share"); return x }

// ForUpdateNoWait locks for update without waiting.
func (x *BattleModel) ForUpdateNoWait() *BattleModel { x.m.Lock("update_nowait"); return x }

// ForShareNoWait locks for share without waiting.
func (x *BattleModel) ForShareNoWait() *BattleModel { x.m.Lock("share_nowait"); return x }

// GetSeq returns seq.
func (x *BattleModel) GetSeq() int64 { return x.fSeq }

// SetSeq sets seq.
func (x *BattleModel) SetSeq(v int64) *BattleModel { x.fSeq = v; x.m.Set("seq", v); return x }

func (x *BattleModel) SetRawSeq(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("seq", sql, binds)
	return x
}
func (x *BattleModel) AddColumnSeq() *BattleModel    { x.m.AddColumn("seq"); return x }
func (x *BattleModel) RemoveColumnSeq() *BattleModel { x.m.RemoveColumn("seq"); return x }
func (x *BattleModel) GroupBySeq() *BattleModel      { x.m.GroupBy("seq"); return x }
func (x *BattleModel) KeyNameSeq() *BattleModel      { x.m.KeyName("seq"); return x }
func (x *BattleModel) OrderBySeqAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("seq", false, fn)
	return x
}
func (x *BattleModel) OrderBySeqDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("seq", true, fn)
	return x
}
func (x *BattleModel) PlusSeq(n int64) *BattleModel  { x.m.Plus("seq", n); return x }
func (x *BattleModel) MinusSeq(n int64) *BattleModel { x.m.Minus("seq", n); return x }
func (x *BattleModel) SumSeq() *BattleModel          { x.m.Aggregate("sum", "seq"); return x }
func (x *BattleModel) AvgSeq() *BattleModel          { x.m.Aggregate("avg", "seq"); return x }

// GetName returns name.
func (x *BattleModel) GetName() string { return x.fName }

// SetName sets name.
func (x *BattleModel) SetName(v string) *BattleModel { x.fName = v; x.m.Set("name", v); return x }

func (x *BattleModel) SetRawName(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("name", sql, binds)
	return x
}
func (x *BattleModel) AddColumnName() *BattleModel    { x.m.AddColumn("name"); return x }
func (x *BattleModel) RemoveColumnName() *BattleModel { x.m.RemoveColumn("name"); return x }
func (x *BattleModel) GroupByName() *BattleModel      { x.m.GroupBy("name"); return x }
func (x *BattleModel) KeyNameName() *BattleModel      { x.m.KeyName("name"); return x }
func (x *BattleModel) OrderByNameAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("name", false, fn)
	return x
}
func (x *BattleModel) OrderByNameDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("name", true, fn)
	return x
}

// GetDescription returns description.
func (x *BattleModel) GetDescription() *string { return x.fDescription }

// SetDescription sets description; nil stores NULL.
func (x *BattleModel) SetDescription(v *string) *BattleModel {
	x.fDescription = v
	if v == nil {
		x.m.SetNull("description")
	} else {
		x.m.Set("description", *v)
	}
	return x
}

func (x *BattleModel) SetRawDescription(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("description", sql, binds)
	return x
}
func (x *BattleModel) AddColumnDescription() *BattleModel { x.m.AddColumn("description"); return x }
func (x *BattleModel) RemoveColumnDescription() *BattleModel {
	x.m.RemoveColumn("description")
	return x
}
func (x *BattleModel) GroupByDescription() *BattleModel { x.m.GroupBy("description"); return x }
func (x *BattleModel) KeyNameDescription() *BattleModel { x.m.KeyName("description"); return x }
func (x *BattleModel) OrderByDescriptionAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("description", false, fn)
	return x
}
func (x *BattleModel) OrderByDescriptionDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("description", true, fn)
	return x
}

// GetCreatedTs returns created_ts.
func (x *BattleModel) GetCreatedTs() time.Time { return x.fCreatedTs }

// SetCreatedTs sets created_ts.
func (x *BattleModel) SetCreatedTs(v time.Time) *BattleModel {
	x.fCreatedTs = v
	x.m.Set("created_ts", v)
	return x
}

func (x *BattleModel) SetRawCreatedTs(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("created_ts", sql, binds)
	return x
}
func (x *BattleModel) AddColumnCreatedTs() *BattleModel    { x.m.AddColumn("created_ts"); return x }
func (x *BattleModel) RemoveColumnCreatedTs() *BattleModel { x.m.RemoveColumn("created_ts"); return x }
func (x *BattleModel) GroupByCreatedTs() *BattleModel      { x.m.GroupBy("created_ts"); return x }
func (x *BattleModel) KeyNameCreatedTs() *BattleModel      { x.m.KeyName("created_ts"); return x }
func (x *BattleModel) OrderByCreatedTsAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("created_ts", false, fn)
	return x
}
func (x *BattleModel) OrderByCreatedTsDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("created_ts", true, fn)
	return x
}

// GetUpdatedTs returns updated_ts.
func (x *BattleModel) GetUpdatedTs() time.Time { return x.fUpdatedTs }

// SetUpdatedTs sets updated_ts.
func (x *BattleModel) SetUpdatedTs(v time.Time) *BattleModel {
	x.fUpdatedTs = v
	x.m.Set("updated_ts", v)
	return x
}

func (x *BattleModel) SetRawUpdatedTs(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("updated_ts", sql, binds)
	return x
}
func (x *BattleModel) AddColumnUpdatedTs() *BattleModel    { x.m.AddColumn("updated_ts"); return x }
func (x *BattleModel) RemoveColumnUpdatedTs() *BattleModel { x.m.RemoveColumn("updated_ts"); return x }
func (x *BattleModel) GroupByUpdatedTs() *BattleModel      { x.m.GroupBy("updated_ts"); return x }
func (x *BattleModel) KeyNameUpdatedTs() *BattleModel      { x.m.KeyName("updated_ts"); return x }
func (x *BattleModel) OrderByUpdatedTsAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("updated_ts", false, fn)
	return x
}
func (x *BattleModel) OrderByUpdatedTsDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("updated_ts", true, fn)
	return x
}

// GetIsClose returns is_close.
func (x *BattleModel) GetIsClose() bool { return x.fIsClose }

// SetIsClose sets is_close.
func (x *BattleModel) SetIsClose(v bool) *BattleModel {
	x.fIsClose = v
	x.m.Set("is_close", v)
	return x
}

func (x *BattleModel) SetRawIsClose(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("is_close", sql, binds)
	return x
}
func (x *BattleModel) AddColumnIsClose() *BattleModel    { x.m.AddColumn("is_close"); return x }
func (x *BattleModel) RemoveColumnIsClose() *BattleModel { x.m.RemoveColumn("is_close"); return x }
func (x *BattleModel) GroupByIsClose() *BattleModel      { x.m.GroupBy("is_close"); return x }
func (x *BattleModel) KeyNameIsClose() *BattleModel      { x.m.KeyName("is_close"); return x }
func (x *BattleModel) OrderByIsCloseAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("is_close", false, fn)
	return x
}
func (x *BattleModel) OrderByIsCloseDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("is_close", true, fn)
	return x
}

// GetIsDisplay returns is_display.
func (x *BattleModel) GetIsDisplay() bool { return x.fIsDisplay }

// SetIsDisplay sets is_display.
func (x *BattleModel) SetIsDisplay(v bool) *BattleModel {
	x.fIsDisplay = v
	x.m.Set("is_display", v)
	return x
}

func (x *BattleModel) SetRawIsDisplay(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("is_display", sql, binds)
	return x
}
func (x *BattleModel) AddColumnIsDisplay() *BattleModel    { x.m.AddColumn("is_display"); return x }
func (x *BattleModel) RemoveColumnIsDisplay() *BattleModel { x.m.RemoveColumn("is_display"); return x }
func (x *BattleModel) GroupByIsDisplay() *BattleModel      { x.m.GroupBy("is_display"); return x }
func (x *BattleModel) KeyNameIsDisplay() *BattleModel      { x.m.KeyName("is_display"); return x }
func (x *BattleModel) OrderByIsDisplayAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("is_display", false, fn)
	return x
}
func (x *BattleModel) OrderByIsDisplayDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("is_display", true, fn)
	return x
}

// GetDisplayStartDt returns display_start_dt.
func (x *BattleModel) GetDisplayStartDt() *time.Time { return x.fDisplayStartDt }

// SetDisplayStartDt sets display_start_dt; nil stores NULL.
func (x *BattleModel) SetDisplayStartDt(v *time.Time) *BattleModel {
	x.fDisplayStartDt = v
	if v == nil {
		x.m.SetNull("display_start_dt")
	} else {
		x.m.Set("display_start_dt", *v)
	}
	return x
}

func (x *BattleModel) SetRawDisplayStartDt(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("display_start_dt", sql, binds)
	return x
}
func (x *BattleModel) AddColumnDisplayStartDt() *BattleModel {
	x.m.AddColumn("display_start_dt")
	return x
}
func (x *BattleModel) RemoveColumnDisplayStartDt() *BattleModel {
	x.m.RemoveColumn("display_start_dt")
	return x
}
func (x *BattleModel) GroupByDisplayStartDt() *BattleModel { x.m.GroupBy("display_start_dt"); return x }
func (x *BattleModel) KeyNameDisplayStartDt() *BattleModel { x.m.KeyName("display_start_dt"); return x }
func (x *BattleModel) OrderByDisplayStartDtAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("display_start_dt", false, fn)
	return x
}
func (x *BattleModel) OrderByDisplayStartDtDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("display_start_dt", true, fn)
	return x
}

// GetDisplayEndDt returns display_end_dt.
func (x *BattleModel) GetDisplayEndDt() *time.Time { return x.fDisplayEndDt }

// SetDisplayEndDt sets display_end_dt; nil stores NULL.
func (x *BattleModel) SetDisplayEndDt(v *time.Time) *BattleModel {
	x.fDisplayEndDt = v
	if v == nil {
		x.m.SetNull("display_end_dt")
	} else {
		x.m.Set("display_end_dt", *v)
	}
	return x
}

func (x *BattleModel) SetRawDisplayEndDt(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("display_end_dt", sql, binds)
	return x
}
func (x *BattleModel) AddColumnDisplayEndDt() *BattleModel { x.m.AddColumn("display_end_dt"); return x }
func (x *BattleModel) RemoveColumnDisplayEndDt() *BattleModel {
	x.m.RemoveColumn("display_end_dt")
	return x
}
func (x *BattleModel) GroupByDisplayEndDt() *BattleModel { x.m.GroupBy("display_end_dt"); return x }
func (x *BattleModel) KeyNameDisplayEndDt() *BattleModel { x.m.KeyName("display_end_dt"); return x }
func (x *BattleModel) OrderByDisplayEndDtAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("display_end_dt", false, fn)
	return x
}
func (x *BattleModel) OrderByDisplayEndDtDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("display_end_dt", true, fn)
	return x
}

// GetIsAllday returns is_allday.
func (x *BattleModel) GetIsAllday() bool { return x.fIsAllday }

// SetIsAllday sets is_allday.
func (x *BattleModel) SetIsAllday(v bool) *BattleModel {
	x.fIsAllday = v
	x.m.Set("is_allday", v)
	return x
}

func (x *BattleModel) SetRawIsAllday(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("is_allday", sql, binds)
	return x
}
func (x *BattleModel) AddColumnIsAllday() *BattleModel    { x.m.AddColumn("is_allday"); return x }
func (x *BattleModel) RemoveColumnIsAllday() *BattleModel { x.m.RemoveColumn("is_allday"); return x }
func (x *BattleModel) GroupByIsAllday() *BattleModel      { x.m.GroupBy("is_allday"); return x }
func (x *BattleModel) KeyNameIsAllday() *BattleModel      { x.m.KeyName("is_allday"); return x }
func (x *BattleModel) OrderByIsAlldayAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("is_allday", false, fn)
	return x
}
func (x *BattleModel) OrderByIsAlldayDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("is_allday", true, fn)
	return x
}

// GetTargetTeamPlayerCount returns target_team_player_count.
func (x *BattleModel) GetTargetTeamPlayerCount() int64 { return x.fTargetTeamPlayerCount }

// SetTargetTeamPlayerCount sets target_team_player_count.
func (x *BattleModel) SetTargetTeamPlayerCount(v int64) *BattleModel {
	x.fTargetTeamPlayerCount = v
	x.m.Set("target_team_player_count", v)
	return x
}

func (x *BattleModel) SetRawTargetTeamPlayerCount(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("target_team_player_count", sql, binds)
	return x
}
func (x *BattleModel) AddColumnTargetTeamPlayerCount() *BattleModel {
	x.m.AddColumn("target_team_player_count")
	return x
}
func (x *BattleModel) RemoveColumnTargetTeamPlayerCount() *BattleModel {
	x.m.RemoveColumn("target_team_player_count")
	return x
}
func (x *BattleModel) GroupByTargetTeamPlayerCount() *BattleModel {
	x.m.GroupBy("target_team_player_count")
	return x
}
func (x *BattleModel) KeyNameTargetTeamPlayerCount() *BattleModel {
	x.m.KeyName("target_team_player_count")
	return x
}
func (x *BattleModel) OrderByTargetTeamPlayerCountAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("target_team_player_count", false, fn)
	return x
}
func (x *BattleModel) OrderByTargetTeamPlayerCountDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("target_team_player_count", true, fn)
	return x
}
func (x *BattleModel) PlusTargetTeamPlayerCount(n int64) *BattleModel {
	x.m.Plus("target_team_player_count", n)
	return x
}
func (x *BattleModel) MinusTargetTeamPlayerCount(n int64) *BattleModel {
	x.m.Minus("target_team_player_count", n)
	return x
}
func (x *BattleModel) SumTargetTeamPlayerCount() *BattleModel {
	x.m.Aggregate("sum", "target_team_player_count")
	return x
}
func (x *BattleModel) AvgTargetTeamPlayerCount() *BattleModel {
	x.m.Aggregate("avg", "target_team_player_count")
	return x
}

// GetSuccessCount returns success_count.
func (x *BattleModel) GetSuccessCount() int64 { return x.fSuccessCount }

// SetSuccessCount sets success_count.
func (x *BattleModel) SetSuccessCount(v int64) *BattleModel {
	x.fSuccessCount = v
	x.m.Set("success_count", v)
	return x
}

func (x *BattleModel) SetRawSuccessCount(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("success_count", sql, binds)
	return x
}
func (x *BattleModel) AddColumnSuccessCount() *BattleModel { x.m.AddColumn("success_count"); return x }
func (x *BattleModel) RemoveColumnSuccessCount() *BattleModel {
	x.m.RemoveColumn("success_count")
	return x
}
func (x *BattleModel) GroupBySuccessCount() *BattleModel { x.m.GroupBy("success_count"); return x }
func (x *BattleModel) KeyNameSuccessCount() *BattleModel { x.m.KeyName("success_count"); return x }
func (x *BattleModel) OrderBySuccessCountAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("success_count", false, fn)
	return x
}
func (x *BattleModel) OrderBySuccessCountDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("success_count", true, fn)
	return x
}
func (x *BattleModel) PlusSuccessCount(n int64) *BattleModel { x.m.Plus("success_count", n); return x }
func (x *BattleModel) MinusSuccessCount(n int64) *BattleModel {
	x.m.Minus("success_count", n)
	return x
}
func (x *BattleModel) SumSuccessCount() *BattleModel { x.m.Aggregate("sum", "success_count"); return x }
func (x *BattleModel) AvgSuccessCount() *BattleModel { x.m.Aggregate("avg", "success_count"); return x }

// GetPlayerCount returns player_count.
func (x *BattleModel) GetPlayerCount() int64 { return x.fPlayerCount }

// SetPlayerCount sets player_count.
func (x *BattleModel) SetPlayerCount(v int64) *BattleModel {
	x.fPlayerCount = v
	x.m.Set("player_count", v)
	return x
}

func (x *BattleModel) SetRawPlayerCount(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("player_count", sql, binds)
	return x
}
func (x *BattleModel) AddColumnPlayerCount() *BattleModel { x.m.AddColumn("player_count"); return x }
func (x *BattleModel) RemoveColumnPlayerCount() *BattleModel {
	x.m.RemoveColumn("player_count")
	return x
}
func (x *BattleModel) GroupByPlayerCount() *BattleModel { x.m.GroupBy("player_count"); return x }
func (x *BattleModel) KeyNamePlayerCount() *BattleModel { x.m.KeyName("player_count"); return x }
func (x *BattleModel) OrderByPlayerCountAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("player_count", false, fn)
	return x
}
func (x *BattleModel) OrderByPlayerCountDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("player_count", true, fn)
	return x
}
func (x *BattleModel) PlusPlayerCount(n int64) *BattleModel  { x.m.Plus("player_count", n); return x }
func (x *BattleModel) MinusPlayerCount(n int64) *BattleModel { x.m.Minus("player_count", n); return x }
func (x *BattleModel) SumPlayerCount() *BattleModel          { x.m.Aggregate("sum", "player_count"); return x }
func (x *BattleModel) AvgPlayerCount() *BattleModel          { x.m.Aggregate("avg", "player_count"); return x }

// GetReadCount returns read_count.
func (x *BattleModel) GetReadCount() int64 { return x.fReadCount }

// SetReadCount sets read_count.
func (x *BattleModel) SetReadCount(v int64) *BattleModel {
	x.fReadCount = v
	x.m.Set("read_count", v)
	return x
}

func (x *BattleModel) SetRawReadCount(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("read_count", sql, binds)
	return x
}
func (x *BattleModel) AddColumnReadCount() *BattleModel    { x.m.AddColumn("read_count"); return x }
func (x *BattleModel) RemoveColumnReadCount() *BattleModel { x.m.RemoveColumn("read_count"); return x }
func (x *BattleModel) GroupByReadCount() *BattleModel      { x.m.GroupBy("read_count"); return x }
func (x *BattleModel) KeyNameReadCount() *BattleModel      { x.m.KeyName("read_count"); return x }
func (x *BattleModel) OrderByReadCountAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("read_count", false, fn)
	return x
}
func (x *BattleModel) OrderByReadCountDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("read_count", true, fn)
	return x
}
func (x *BattleModel) PlusReadCount(n int64) *BattleModel  { x.m.Plus("read_count", n); return x }
func (x *BattleModel) MinusReadCount(n int64) *BattleModel { x.m.Minus("read_count", n); return x }
func (x *BattleModel) SumReadCount() *BattleModel          { x.m.Aggregate("sum", "read_count"); return x }
func (x *BattleModel) AvgReadCount() *BattleModel          { x.m.Aggregate("avg", "read_count"); return x }

// GetCoverUrl returns cover_url.
func (x *BattleModel) GetCoverUrl() *string { return x.fCoverUrl }

// SetCoverUrl sets cover_url; nil stores NULL.
func (x *BattleModel) SetCoverUrl(v *string) *BattleModel {
	x.fCoverUrl = v
	if v == nil {
		x.m.SetNull("cover_url")
	} else {
		x.m.Set("cover_url", *v)
	}
	return x
}

func (x *BattleModel) SetRawCoverUrl(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("cover_url", sql, binds)
	return x
}
func (x *BattleModel) AddColumnCoverUrl() *BattleModel    { x.m.AddColumn("cover_url"); return x }
func (x *BattleModel) RemoveColumnCoverUrl() *BattleModel { x.m.RemoveColumn("cover_url"); return x }
func (x *BattleModel) GroupByCoverUrl() *BattleModel      { x.m.GroupBy("cover_url"); return x }
func (x *BattleModel) KeyNameCoverUrl() *BattleModel      { x.m.KeyName("cover_url"); return x }
func (x *BattleModel) OrderByCoverUrlAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("cover_url", false, fn)
	return x
}
func (x *BattleModel) OrderByCoverUrlDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("cover_url", true, fn)
	return x
}

// GetUserSeq returns user_seq.
func (x *BattleModel) GetUserSeq() int64 { return x.fUserSeq }

// SetUserSeq sets user_seq.
func (x *BattleModel) SetUserSeq(v int64) *BattleModel {
	x.fUserSeq = v
	x.m.Set("user_seq", v)
	return x
}

func (x *BattleModel) SetRawUserSeq(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("user_seq", sql, binds)
	return x
}
func (x *BattleModel) AddColumnUserSeq() *BattleModel    { x.m.AddColumn("user_seq"); return x }
func (x *BattleModel) RemoveColumnUserSeq() *BattleModel { x.m.RemoveColumn("user_seq"); return x }
func (x *BattleModel) GroupByUserSeq() *BattleModel      { x.m.GroupBy("user_seq"); return x }
func (x *BattleModel) KeyNameUserSeq() *BattleModel      { x.m.KeyName("user_seq"); return x }
func (x *BattleModel) OrderByUserSeqAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("user_seq", false, fn)
	return x
}
func (x *BattleModel) OrderByUserSeqDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("user_seq", true, fn)
	return x
}
func (x *BattleModel) PlusUserSeq(n int64) *BattleModel  { x.m.Plus("user_seq", n); return x }
func (x *BattleModel) MinusUserSeq(n int64) *BattleModel { x.m.Minus("user_seq", n); return x }
func (x *BattleModel) SumUserSeq() *BattleModel          { x.m.Aggregate("sum", "user_seq"); return x }
func (x *BattleModel) AvgUserSeq() *BattleModel          { x.m.Aggregate("avg", "user_seq"); return x }

// GetServiceSeq returns service_seq.
func (x *BattleModel) GetServiceSeq() int64 { return x.fServiceSeq }

// SetServiceSeq sets service_seq.
func (x *BattleModel) SetServiceSeq(v int64) *BattleModel {
	x.fServiceSeq = v
	x.m.Set("service_seq", v)
	return x
}

func (x *BattleModel) SetRawServiceSeq(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("service_seq", sql, binds)
	return x
}
func (x *BattleModel) AddColumnServiceSeq() *BattleModel { x.m.AddColumn("service_seq"); return x }
func (x *BattleModel) RemoveColumnServiceSeq() *BattleModel {
	x.m.RemoveColumn("service_seq")
	return x
}
func (x *BattleModel) GroupByServiceSeq() *BattleModel { x.m.GroupBy("service_seq"); return x }
func (x *BattleModel) KeyNameServiceSeq() *BattleModel { x.m.KeyName("service_seq"); return x }
func (x *BattleModel) OrderByServiceSeqAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("service_seq", false, fn)
	return x
}
func (x *BattleModel) OrderByServiceSeqDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("service_seq", true, fn)
	return x
}
func (x *BattleModel) PlusServiceSeq(n int64) *BattleModel  { x.m.Plus("service_seq", n); return x }
func (x *BattleModel) MinusServiceSeq(n int64) *BattleModel { x.m.Minus("service_seq", n); return x }
func (x *BattleModel) SumServiceSeq() *BattleModel          { x.m.Aggregate("sum", "service_seq"); return x }
func (x *BattleModel) AvgServiceSeq() *BattleModel          { x.m.Aggregate("avg", "service_seq"); return x }

// GetServiceModuleSeq returns service_module_seq.
func (x *BattleModel) GetServiceModuleSeq() int64 { return x.fServiceModuleSeq }

// SetServiceModuleSeq sets service_module_seq.
func (x *BattleModel) SetServiceModuleSeq(v int64) *BattleModel {
	x.fServiceModuleSeq = v
	x.m.Set("service_module_seq", v)
	return x
}

func (x *BattleModel) SetRawServiceModuleSeq(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("service_module_seq", sql, binds)
	return x
}
func (x *BattleModel) AddColumnServiceModuleSeq() *BattleModel {
	x.m.AddColumn("service_module_seq")
	return x
}
func (x *BattleModel) RemoveColumnServiceModuleSeq() *BattleModel {
	x.m.RemoveColumn("service_module_seq")
	return x
}
func (x *BattleModel) GroupByServiceModuleSeq() *BattleModel {
	x.m.GroupBy("service_module_seq")
	return x
}
func (x *BattleModel) KeyNameServiceModuleSeq() *BattleModel {
	x.m.KeyName("service_module_seq")
	return x
}
func (x *BattleModel) OrderByServiceModuleSeqAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("service_module_seq", false, fn)
	return x
}
func (x *BattleModel) OrderByServiceModuleSeqDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("service_module_seq", true, fn)
	return x
}
func (x *BattleModel) PlusServiceModuleSeq(n int64) *BattleModel {
	x.m.Plus("service_module_seq", n)
	return x
}
func (x *BattleModel) MinusServiceModuleSeq(n int64) *BattleModel {
	x.m.Minus("service_module_seq", n)
	return x
}
func (x *BattleModel) SumServiceModuleSeq() *BattleModel {
	x.m.Aggregate("sum", "service_module_seq")
	return x
}
func (x *BattleModel) AvgServiceModuleSeq() *BattleModel {
	x.m.Aggregate("avg", "service_module_seq")
	return x
}

// GetServiceMemberSeq returns service_member_seq.
func (x *BattleModel) GetServiceMemberSeq() int64 { return x.fServiceMemberSeq }

// SetServiceMemberSeq sets service_member_seq.
func (x *BattleModel) SetServiceMemberSeq(v int64) *BattleModel {
	x.fServiceMemberSeq = v
	x.m.Set("service_member_seq", v)
	return x
}

func (x *BattleModel) SetRawServiceMemberSeq(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("service_member_seq", sql, binds)
	return x
}
func (x *BattleModel) AddColumnServiceMemberSeq() *BattleModel {
	x.m.AddColumn("service_member_seq")
	return x
}
func (x *BattleModel) RemoveColumnServiceMemberSeq() *BattleModel {
	x.m.RemoveColumn("service_member_seq")
	return x
}
func (x *BattleModel) GroupByServiceMemberSeq() *BattleModel {
	x.m.GroupBy("service_member_seq")
	return x
}
func (x *BattleModel) KeyNameServiceMemberSeq() *BattleModel {
	x.m.KeyName("service_member_seq")
	return x
}
func (x *BattleModel) OrderByServiceMemberSeqAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("service_member_seq", false, fn)
	return x
}
func (x *BattleModel) OrderByServiceMemberSeqDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("service_member_seq", true, fn)
	return x
}
func (x *BattleModel) PlusServiceMemberSeq(n int64) *BattleModel {
	x.m.Plus("service_member_seq", n)
	return x
}
func (x *BattleModel) MinusServiceMemberSeq(n int64) *BattleModel {
	x.m.Minus("service_member_seq", n)
	return x
}
func (x *BattleModel) SumServiceMemberSeq() *BattleModel {
	x.m.Aggregate("sum", "service_member_seq")
	return x
}
func (x *BattleModel) AvgServiceMemberSeq() *BattleModel {
	x.m.Aggregate("avg", "service_member_seq")
	return x
}

// GetStartDt returns start_dt.
func (x *BattleModel) GetStartDt() time.Time { return x.fStartDt }

// SetStartDt sets start_dt.
func (x *BattleModel) SetStartDt(v time.Time) *BattleModel {
	x.fStartDt = v
	x.m.Set("start_dt", v)
	return x
}

func (x *BattleModel) SetRawStartDt(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("start_dt", sql, binds)
	return x
}
func (x *BattleModel) AddColumnStartDt() *BattleModel    { x.m.AddColumn("start_dt"); return x }
func (x *BattleModel) RemoveColumnStartDt() *BattleModel { x.m.RemoveColumn("start_dt"); return x }
func (x *BattleModel) GroupByStartDt() *BattleModel      { x.m.GroupBy("start_dt"); return x }
func (x *BattleModel) KeyNameStartDt() *BattleModel      { x.m.KeyName("start_dt"); return x }
func (x *BattleModel) OrderByStartDtAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("start_dt", false, fn)
	return x
}
func (x *BattleModel) OrderByStartDtDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("start_dt", true, fn)
	return x
}

// GetEndDt returns end_dt.
func (x *BattleModel) GetEndDt() time.Time { return x.fEndDt }

// SetEndDt sets end_dt.
func (x *BattleModel) SetEndDt(v time.Time) *BattleModel {
	x.fEndDt = v
	x.m.Set("end_dt", v)
	return x
}

func (x *BattleModel) SetRawEndDt(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("end_dt", sql, binds)
	return x
}
func (x *BattleModel) AddColumnEndDt() *BattleModel    { x.m.AddColumn("end_dt"); return x }
func (x *BattleModel) RemoveColumnEndDt() *BattleModel { x.m.RemoveColumn("end_dt"); return x }
func (x *BattleModel) GroupByEndDt() *BattleModel      { x.m.GroupBy("end_dt"); return x }
func (x *BattleModel) KeyNameEndDt() *BattleModel      { x.m.KeyName("end_dt"); return x }
func (x *BattleModel) OrderByEndDtAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("end_dt", false, fn)
	return x
}
func (x *BattleModel) OrderByEndDtDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("end_dt", true, fn)
	return x
}

// GetUuid returns uuid.
func (x *BattleModel) GetUuid() *string { return x.fUuid }

// SetUuid sets uuid; nil stores NULL.
func (x *BattleModel) SetUuid(v *string) *BattleModel {
	x.fUuid = v
	if v == nil {
		x.m.SetNull("uuid")
	} else {
		x.m.Set("uuid", *v)
	}
	return x
}

func (x *BattleModel) SetRawUuid(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("uuid", sql, binds)
	return x
}
func (x *BattleModel) AddColumnUuid() *BattleModel    { x.m.AddColumn("uuid"); return x }
func (x *BattleModel) RemoveColumnUuid() *BattleModel { x.m.RemoveColumn("uuid"); return x }
func (x *BattleModel) GroupByUuid() *BattleModel      { x.m.GroupBy("uuid"); return x }
func (x *BattleModel) KeyNameUuid() *BattleModel      { x.m.KeyName("uuid"); return x }
func (x *BattleModel) OrderByUuidAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("uuid", false, fn)
	return x
}
func (x *BattleModel) OrderByUuidDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("uuid", true, fn)
	return x
}

// GetIsSinglePlay returns is_single_play.
func (x *BattleModel) GetIsSinglePlay() bool { return x.fIsSinglePlay }

// SetIsSinglePlay sets is_single_play.
func (x *BattleModel) SetIsSinglePlay(v bool) *BattleModel {
	x.fIsSinglePlay = v
	x.m.Set("is_single_play", v)
	return x
}

func (x *BattleModel) SetRawIsSinglePlay(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("is_single_play", sql, binds)
	return x
}
func (x *BattleModel) AddColumnIsSinglePlay() *BattleModel { x.m.AddColumn("is_single_play"); return x }
func (x *BattleModel) RemoveColumnIsSinglePlay() *BattleModel {
	x.m.RemoveColumn("is_single_play")
	return x
}
func (x *BattleModel) GroupByIsSinglePlay() *BattleModel { x.m.GroupBy("is_single_play"); return x }
func (x *BattleModel) KeyNameIsSinglePlay() *BattleModel { x.m.KeyName("is_single_play"); return x }
func (x *BattleModel) OrderByIsSinglePlayAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("is_single_play", false, fn)
	return x
}
func (x *BattleModel) OrderByIsSinglePlayDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("is_single_play", true, fn)
	return x
}

// GetLikeCount returns like_count.
func (x *BattleModel) GetLikeCount() int64 { return x.fLikeCount }

// SetLikeCount sets like_count.
func (x *BattleModel) SetLikeCount(v int64) *BattleModel {
	x.fLikeCount = v
	x.m.Set("like_count", v)
	return x
}

func (x *BattleModel) SetRawLikeCount(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("like_count", sql, binds)
	return x
}
func (x *BattleModel) AddColumnLikeCount() *BattleModel    { x.m.AddColumn("like_count"); return x }
func (x *BattleModel) RemoveColumnLikeCount() *BattleModel { x.m.RemoveColumn("like_count"); return x }
func (x *BattleModel) GroupByLikeCount() *BattleModel      { x.m.GroupBy("like_count"); return x }
func (x *BattleModel) KeyNameLikeCount() *BattleModel      { x.m.KeyName("like_count"); return x }
func (x *BattleModel) OrderByLikeCountAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("like_count", false, fn)
	return x
}
func (x *BattleModel) OrderByLikeCountDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("like_count", true, fn)
	return x
}
func (x *BattleModel) PlusLikeCount(n int64) *BattleModel  { x.m.Plus("like_count", n); return x }
func (x *BattleModel) MinusLikeCount(n int64) *BattleModel { x.m.Minus("like_count", n); return x }
func (x *BattleModel) SumLikeCount() *BattleModel          { x.m.Aggregate("sum", "like_count"); return x }
func (x *BattleModel) AvgLikeCount() *BattleModel          { x.m.Aggregate("avg", "like_count"); return x }

// GetAesKeyVersion returns aes_key_version.
func (x *BattleModel) GetAesKeyVersion() int32 { return x.fAesKeyVersion }

// SetAesKeyVersion sets aes_key_version.
func (x *BattleModel) SetAesKeyVersion(v int32) *BattleModel {
	x.fAesKeyVersion = v
	x.m.Set("aes_key_version", v)
	return x
}

func (x *BattleModel) SetRawAesKeyVersion(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("aes_key_version", sql, binds)
	return x
}
func (x *BattleModel) AddColumnAesKeyVersion() *BattleModel {
	x.m.AddColumn("aes_key_version")
	return x
}
func (x *BattleModel) RemoveColumnAesKeyVersion() *BattleModel {
	x.m.RemoveColumn("aes_key_version")
	return x
}
func (x *BattleModel) GroupByAesKeyVersion() *BattleModel { x.m.GroupBy("aes_key_version"); return x }
func (x *BattleModel) KeyNameAesKeyVersion() *BattleModel { x.m.KeyName("aes_key_version"); return x }
func (x *BattleModel) OrderByAesKeyVersionAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("aes_key_version", false, fn)
	return x
}
func (x *BattleModel) OrderByAesKeyVersionDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("aes_key_version", true, fn)
	return x
}
func (x *BattleModel) PlusAesKeyVersion(n int32) *BattleModel {
	x.m.Plus("aes_key_version", n)
	return x
}
func (x *BattleModel) MinusAesKeyVersion(n int32) *BattleModel {
	x.m.Minus("aes_key_version", n)
	return x
}
func (x *BattleModel) SumAesKeyVersion() *BattleModel {
	x.m.Aggregate("sum", "aes_key_version")
	return x
}
func (x *BattleModel) AvgAesKeyVersion() *BattleModel {
	x.m.Aggregate("avg", "aes_key_version")
	return x
}

// GetAesHexEmail returns aes_hex_email.
func (x *BattleModel) GetAesHexEmail() *string { return x.fAesHexEmail }

// SetAesHexEmail sets aes_hex_email; nil stores NULL.
func (x *BattleModel) SetAesHexEmail(v *string) *BattleModel {
	x.fAesHexEmail = v
	if v == nil {
		x.m.SetNull("aes_hex_email")
	} else {
		x.m.Set("aes_hex_email", *v)
	}
	return x
}

func (x *BattleModel) SetRawAesHexEmail(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("aes_hex_email", sql, binds)
	return x
}
func (x *BattleModel) AddColumnAesHexEmail() *BattleModel { x.m.AddColumn("aes_hex_email"); return x }
func (x *BattleModel) RemoveColumnAesHexEmail() *BattleModel {
	x.m.RemoveColumn("aes_hex_email")
	return x
}
func (x *BattleModel) GroupByAesHexEmail() *BattleModel { x.m.GroupBy("aes_hex_email"); return x }
func (x *BattleModel) KeyNameAesHexEmail() *BattleModel { x.m.KeyName("aes_hex_email"); return x }
func (x *BattleModel) OrderByAesHexEmailAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("aes_hex_email", false, fn)
	return x
}
func (x *BattleModel) OrderByAesHexEmailDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("aes_hex_email", true, fn)
	return x
}

// GetEmailBlindIndex returns email_blind_index.
func (x *BattleModel) GetEmailBlindIndex() *string { return x.fEmailBlindIndex }

// SetEmailBlindIndex sets email_blind_index; nil stores NULL.
func (x *BattleModel) SetEmailBlindIndex(v *string) *BattleModel {
	x.fEmailBlindIndex = v
	if v == nil {
		x.m.SetNull("email_blind_index")
	} else {
		x.m.Set("email_blind_index", *v)
	}
	return x
}

func (x *BattleModel) SetRawEmailBlindIndex(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("email_blind_index", sql, binds)
	return x
}
func (x *BattleModel) AddColumnEmailBlindIndex() *BattleModel {
	x.m.AddColumn("email_blind_index")
	return x
}
func (x *BattleModel) RemoveColumnEmailBlindIndex() *BattleModel {
	x.m.RemoveColumn("email_blind_index")
	return x
}
func (x *BattleModel) GroupByEmailBlindIndex() *BattleModel {
	x.m.GroupBy("email_blind_index")
	return x
}
func (x *BattleModel) KeyNameEmailBlindIndex() *BattleModel {
	x.m.KeyName("email_blind_index")
	return x
}
func (x *BattleModel) OrderByEmailBlindIndexAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("email_blind_index", false, fn)
	return x
}
func (x *BattleModel) OrderByEmailBlindIndexDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("email_blind_index", true, fn)
	return x
}

// GetAesHexPhone returns aes_hex_phone.
func (x *BattleModel) GetAesHexPhone() *string { return x.fAesHexPhone }

// SetAesHexPhone sets aes_hex_phone; nil stores NULL.
func (x *BattleModel) SetAesHexPhone(v *string) *BattleModel {
	x.fAesHexPhone = v
	if v == nil {
		x.m.SetNull("aes_hex_phone")
	} else {
		x.m.Set("aes_hex_phone", *v)
	}
	return x
}

func (x *BattleModel) SetRawAesHexPhone(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("aes_hex_phone", sql, binds)
	return x
}
func (x *BattleModel) AddColumnAesHexPhone() *BattleModel { x.m.AddColumn("aes_hex_phone"); return x }
func (x *BattleModel) RemoveColumnAesHexPhone() *BattleModel {
	x.m.RemoveColumn("aes_hex_phone")
	return x
}
func (x *BattleModel) GroupByAesHexPhone() *BattleModel { x.m.GroupBy("aes_hex_phone"); return x }
func (x *BattleModel) KeyNameAesHexPhone() *BattleModel { x.m.KeyName("aes_hex_phone"); return x }
func (x *BattleModel) OrderByAesHexPhoneAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("aes_hex_phone", false, fn)
	return x
}
func (x *BattleModel) OrderByAesHexPhoneDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("aes_hex_phone", true, fn)
	return x
}

// GetPhoneBlindIndex returns phone_blind_index.
func (x *BattleModel) GetPhoneBlindIndex() *string { return x.fPhoneBlindIndex }

// SetPhoneBlindIndex sets phone_blind_index; nil stores NULL.
func (x *BattleModel) SetPhoneBlindIndex(v *string) *BattleModel {
	x.fPhoneBlindIndex = v
	if v == nil {
		x.m.SetNull("phone_blind_index")
	} else {
		x.m.Set("phone_blind_index", *v)
	}
	return x
}

func (x *BattleModel) SetRawPhoneBlindIndex(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("phone_blind_index", sql, binds)
	return x
}
func (x *BattleModel) AddColumnPhoneBlindIndex() *BattleModel {
	x.m.AddColumn("phone_blind_index")
	return x
}
func (x *BattleModel) RemoveColumnPhoneBlindIndex() *BattleModel {
	x.m.RemoveColumn("phone_blind_index")
	return x
}
func (x *BattleModel) GroupByPhoneBlindIndex() *BattleModel {
	x.m.GroupBy("phone_blind_index")
	return x
}
func (x *BattleModel) KeyNamePhoneBlindIndex() *BattleModel {
	x.m.KeyName("phone_blind_index")
	return x
}
func (x *BattleModel) OrderByPhoneBlindIndexAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("phone_blind_index", false, fn)
	return x
}
func (x *BattleModel) OrderByPhoneBlindIndexDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("phone_blind_index", true, fn)
	return x
}

// GetPrice returns price.
func (x *BattleModel) GetPrice() *float64 { return x.fPrice }

// SetPrice sets price; nil stores NULL.
func (x *BattleModel) SetPrice(v *float64) *BattleModel {
	x.fPrice = v
	if v == nil {
		x.m.SetNull("price")
	} else {
		x.m.Set("price", *v)
	}
	return x
}

func (x *BattleModel) SetRawPrice(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("price", sql, binds)
	return x
}
func (x *BattleModel) AddColumnPrice() *BattleModel    { x.m.AddColumn("price"); return x }
func (x *BattleModel) RemoveColumnPrice() *BattleModel { x.m.RemoveColumn("price"); return x }
func (x *BattleModel) GroupByPrice() *BattleModel      { x.m.GroupBy("price"); return x }
func (x *BattleModel) KeyNamePrice() *BattleModel      { x.m.KeyName("price"); return x }
func (x *BattleModel) OrderByPriceAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("price", false, fn)
	return x
}
func (x *BattleModel) OrderByPriceDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("price", true, fn)
	return x
}
func (x *BattleModel) PlusPrice(n float64) *BattleModel  { x.m.Plus("price", n); return x }
func (x *BattleModel) MinusPrice(n float64) *BattleModel { x.m.Minus("price", n); return x }
func (x *BattleModel) SumPrice() *BattleModel            { x.m.Aggregate("sum", "price"); return x }
func (x *BattleModel) AvgPrice() *BattleModel            { x.m.Aggregate("avg", "price"); return x }

// GetIp returns ip.
func (x *BattleModel) GetIp() *string { return x.fIp }

// SetIp sets ip; nil stores NULL.
func (x *BattleModel) SetIp(v *string) *BattleModel {
	x.fIp = v
	if v == nil {
		x.m.SetNull("ip")
	} else {
		x.m.Set("ip", *v)
	}
	return x
}

func (x *BattleModel) SetRawIp(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("ip", sql, binds)
	return x
}
func (x *BattleModel) AddColumnIp() *BattleModel    { x.m.AddColumn("ip"); return x }
func (x *BattleModel) RemoveColumnIp() *BattleModel { x.m.RemoveColumn("ip"); return x }
func (x *BattleModel) GroupByIp() *BattleModel      { x.m.GroupBy("ip"); return x }
func (x *BattleModel) KeyNameIp() *BattleModel      { x.m.KeyName("ip"); return x }
func (x *BattleModel) OrderByIpAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("ip", false, fn)
	return x
}
func (x *BattleModel) OrderByIpDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("ip", true, fn)
	return x
}

// GetGzExtend returns gz_extend.
func (x *BattleModel) GetGzExtend() any { return x.fGzExtend }

// SetGzExtend sets gz_extend.
func (x *BattleModel) SetGzExtend(v any) *BattleModel {
	x.fGzExtend = v
	x.m.Set("gz_extend", v)
	return x
}

func (x *BattleModel) SetRawGzExtend(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("gz_extend", sql, binds)
	return x
}
func (x *BattleModel) AddColumnGzExtend() *BattleModel    { x.m.AddColumn("gz_extend"); return x }
func (x *BattleModel) RemoveColumnGzExtend() *BattleModel { x.m.RemoveColumn("gz_extend"); return x }
func (x *BattleModel) GroupByGzExtend() *BattleModel      { x.m.GroupBy("gz_extend"); return x }
func (x *BattleModel) KeyNameGzExtend() *BattleModel      { x.m.KeyName("gz_extend"); return x }
func (x *BattleModel) OrderByGzExtendAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("gz_extend", false, fn)
	return x
}
func (x *BattleModel) OrderByGzExtendDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("gz_extend", true, fn)
	return x
}

// GetJsonSetting returns json_setting.
func (x *BattleModel) GetJsonSetting() any { return x.fJsonSetting }

// SetJsonSetting sets json_setting.
func (x *BattleModel) SetJsonSetting(v any) *BattleModel {
	x.fJsonSetting = v
	x.m.Set("json_setting", v)
	return x
}

func (x *BattleModel) SetRawJsonSetting(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("json_setting", sql, binds)
	return x
}
func (x *BattleModel) AddColumnJsonSetting() *BattleModel { x.m.AddColumn("json_setting"); return x }
func (x *BattleModel) RemoveColumnJsonSetting() *BattleModel {
	x.m.RemoveColumn("json_setting")
	return x
}
func (x *BattleModel) GroupByJsonSetting() *BattleModel { x.m.GroupBy("json_setting"); return x }
func (x *BattleModel) KeyNameJsonSetting() *BattleModel { x.m.KeyName("json_setting"); return x }
func (x *BattleModel) OrderByJsonSettingAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("json_setting", false, fn)
	return x
}
func (x *BattleModel) OrderByJsonSettingDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("json_setting", true, fn)
	return x
}

// GetJsonsTags returns jsons_tags.
func (x *BattleModel) GetJsonsTags() any { return x.fJsonsTags }

// SetJsonsTags sets jsons_tags.
func (x *BattleModel) SetJsonsTags(v any) *BattleModel {
	x.fJsonsTags = v
	x.m.Set("jsons_tags", v)
	return x
}

func (x *BattleModel) SetRawJsonsTags(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("jsons_tags", sql, binds)
	return x
}
func (x *BattleModel) AddColumnJsonsTags() *BattleModel    { x.m.AddColumn("jsons_tags"); return x }
func (x *BattleModel) RemoveColumnJsonsTags() *BattleModel { x.m.RemoveColumn("jsons_tags"); return x }
func (x *BattleModel) GroupByJsonsTags() *BattleModel      { x.m.GroupBy("jsons_tags"); return x }
func (x *BattleModel) KeyNameJsonsTags() *BattleModel      { x.m.KeyName("jsons_tags"); return x }
func (x *BattleModel) OrderByJsonsTagsAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("jsons_tags", false, fn)
	return x
}
func (x *BattleModel) OrderByJsonsTagsDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("jsons_tags", true, fn)
	return x
}

// GetBase64Extra returns base64_extra.
func (x *BattleModel) GetBase64Extra() any { return x.fBase64Extra }

// SetBase64Extra sets base64_extra.
func (x *BattleModel) SetBase64Extra(v any) *BattleModel {
	x.fBase64Extra = v
	x.m.Set("base64_extra", v)
	return x
}

func (x *BattleModel) SetRawBase64Extra(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("base64_extra", sql, binds)
	return x
}
func (x *BattleModel) AddColumnBase64Extra() *BattleModel { x.m.AddColumn("base64_extra"); return x }
func (x *BattleModel) RemoveColumnBase64Extra() *BattleModel {
	x.m.RemoveColumn("base64_extra")
	return x
}
func (x *BattleModel) GroupByBase64Extra() *BattleModel { x.m.GroupBy("base64_extra"); return x }
func (x *BattleModel) KeyNameBase64Extra() *BattleModel { x.m.KeyName("base64_extra"); return x }
func (x *BattleModel) OrderByBase64ExtraAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("base64_extra", false, fn)
	return x
}
func (x *BattleModel) OrderByBase64ExtraDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("base64_extra", true, fn)
	return x
}

// GetSerializeData returns serialize_data.
func (x *BattleModel) GetSerializeData() any { return x.fSerializeData }

// SetSerializeData sets serialize_data.
func (x *BattleModel) SetSerializeData(v any) *BattleModel {
	x.fSerializeData = v
	x.m.Set("serialize_data", v)
	return x
}

func (x *BattleModel) SetRawSerializeData(sql string, binds ...any) *BattleModel {
	x.m.SetRaw("serialize_data", sql, binds)
	return x
}
func (x *BattleModel) AddColumnSerializeData() *BattleModel {
	x.m.AddColumn("serialize_data")
	return x
}
func (x *BattleModel) RemoveColumnSerializeData() *BattleModel {
	x.m.RemoveColumn("serialize_data")
	return x
}
func (x *BattleModel) GroupBySerializeData() *BattleModel { x.m.GroupBy("serialize_data"); return x }
func (x *BattleModel) KeyNameSerializeData() *BattleModel { x.m.KeyName("serialize_data"); return x }
func (x *BattleModel) OrderBySerializeDataAsc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("serialize_data", false, fn)
	return x
}
func (x *BattleModel) OrderBySerializeDataDesc(fn ...orm.Func) *BattleModel {
	x.m.OrderBy("serialize_data", true, fn)
	return x
}

func (x *BattleModel) ForceIndexIk() *BattleModel { x.m.ForceIndex("ik"); return x }
func (x *BattleModel) ForceIndexIxEmailBlindIndex() *BattleModel {
	x.m.ForceIndex("ix_email_blind_index")
	return x
}
func (x *BattleModel) ForceIndexIxPhoneBlindIndex() *BattleModel {
	x.m.ForceIndex("ix_phone_blind_index")
	return x
}
func (x *BattleModel) ForceIndexIxService() *BattleModel { x.m.ForceIndex("ix_service"); return x }
func (x *BattleModel) ForceIndexIxUser() *BattleModel    { x.m.ForceIndex("ix_user"); return x }

func (x *BattleModel) AddColumnReadCountAliasReadText[F ~string | orm.Func](format F) *BattleModel {
	switch f := any(format).(type) {
	case orm.Func:
		x.m.AddColumnFunc("read_count", "read_text", f)
	default:
		x.m.AddColumnFormat("read_count", "read_text", orm.AsString(f))
	}
	return x
}

func (x *BattleModel) AddColumnStartDtAliasStartMonth[F ~string | orm.Func](format F) *BattleModel {
	switch f := any(format).(type) {
	case orm.Func:
		x.m.AddColumnFunc("start_dt", "start_month", f)
	default:
		x.m.AddColumnFormat("start_dt", "start_month", orm.AsString(f))
	}
	return x
}

func (x *BattleModel) AddRawColumnDoubled(sql string, binds ...any) *BattleModel {
	x.m.AddRawColumn("doubled", sql, binds)
	return x
}

func (x *BattleModel) AesHexEmail[T0 argStringEqNull](v0 T0) *BattleModel {
	x.m.Where("", chainBattleAesHexEmail, v0)
	return x
}

func (x *BattleModel) AndAesHexEmail[T0 argStringEqNull](v0 T0) *BattleModel {
	x.m.Where("and", chainBattleAndAesHexEmail, v0)
	return x
}

func (x *BattleModel) AndBetweenReadCount[T0 argIntBetween](v0 T0) *BattleModel {
	x.m.Where("and", chainBattleAndBetweenReadCount, v0)
	return x
}

func (x *BattleModel) AndEqStartDt[T0 argTimeEq](v0 T0, compared ...any) *BattleModel {
	x.m.Where("and", chainBattleAndEqStartDt, append([]any{v0}, compared...)...)
	return x
}

func (x *BattleModel) AndGeReadCount[T0 argIntCmp](v0 T0) *BattleModel {
	x.m.Where("and", chainBattleAndGeReadCount, v0)
	return x
}

func (x *BattleModel) AndGtReadCount[T0 argIntCmp](v0 T0) *BattleModel {
	x.m.Where("and", chainBattleAndGtReadCount, v0)
	return x
}

func (x *BattleModel) AndGtStartDt[T0 argTimeCmp](v0 T0, compared ...any) *BattleModel {
	x.m.Where("and", chainBattleAndGtStartDt, append([]any{v0}, compared...)...)
	return x
}

func (x *BattleModel) AndIsClose[T0 argBoolEq](v0 T0) *BattleModel {
	x.m.Where("and", chainBattleAndIsClose, v0)
	return x
}

func (x *BattleModel) AndLbName[T0 argStringLike](v0 T0) *BattleModel {
	x.m.Where("and", chainBattleAndLbName, v0)
	return x
}

func (x *BattleModel) AndLeReadCount[T0 argIntCmp](v0 T0) *BattleModel {
	x.m.Where("and", chainBattleAndLeReadCount, v0)
	return x
}

func (x *BattleModel) AndLkName[T0 argStringLike](v0 T0) *BattleModel {
	x.m.Where("and", chainBattleAndLkName, v0)
	return x
}

func (x *BattleModel) AndLtDisplayStartDt[T0 argTimeCmp](v0 T0, compared ...any) *BattleModel {
	x.m.Where("and", chainBattleAndLtDisplayStartDt, append([]any{v0}, compared...)...)
	return x
}

func (x *BattleModel) AndLtReadCount[T0 argIntCmp](v0 T0) *BattleModel {
	x.m.Where("and", chainBattleAndLtReadCount, v0)
	return x
}

func (x *BattleModel) AndLtSeq[T0 argIntCmp](v0 T0) *BattleModel {
	x.m.Where("and", chainBattleAndLtSeq, v0)
	return x
}

func (x *BattleModel) AndLtStartDt[T0 argTimeCmp](v0 T0, compared ...any) *BattleModel {
	x.m.Where("and", chainBattleAndLtStartDt, append([]any{v0}, compared...)...)
	return x
}

func (x *BattleModel) AndNeCoverUrl[T0 argStringEqNull](v0 T0) *BattleModel {
	x.m.Where("and", chainBattleAndNeCoverUrl, v0)
	return x
}

func (x *BattleModel) AndNeIsClose[T0 argBoolEq](v0 T0) *BattleModel {
	x.m.Where("and", chainBattleAndNeIsClose, v0)
	return x
}

func (x *BattleModel) AndNeReadCount[T0 argIntEq](v0 T0) *BattleModel {
	x.m.Where("and", chainBattleAndNeReadCount, v0)
	return x
}

func (x *BattleModel) AndSeq[T0 argIntEq](v0 T0) *BattleModel {
	x.m.Where("and", chainBattleAndSeq, v0)
	return x
}

func (x *BattleModel) AndServiceSeq[T0 argIntEq](v0 T0) *BattleModel {
	x.m.Where("and", chainBattleAndServiceSeq, v0)
	return x
}

func (x *BattleModel) AndStartDt[T0 argTimeEq](v0 T0, compared ...any) *BattleModel {
	x.m.Where("and", chainBattleAndStartDt, append([]any{v0}, compared...)...)
	return x
}

func (x *BattleModel) AndSuccessCountLtSeq[T0 hasSeq](v0 T0) *BattleModel {
	x.m.Where("and", chainBattleAndSuccessCountLtSeq, v0)
	return x
}

func (x *BattleModel) AndUuid[T0 argStringEqNull](v0 T0) *BattleModel {
	x.m.Where("and", chainBattleAndUuid, v0)
	return x
}

func (x *BattleModel) BetweenReadCount[T0 argIntBetween](v0 T0) *BattleModel {
	x.m.Where("", chainBattleBetweenReadCount, v0)
	return x
}

func (x *BattleModel) CoverUrl[T0 argStringEqNull](v0 T0) *BattleModel {
	x.m.Where("", chainBattleCoverUrl, v0)
	return x
}

func (x *BattleModel) GeReadCount[T0 argIntCmp](v0 T0) *BattleModel {
	x.m.Where("", chainBattleGeReadCount, v0)
	return x
}

func (x *BattleModel) GetByName[T0 argStringEq](v0 T0) (*BattleModel, error) {
	return oneBattle(x.m.By(chainBattleGetByName, v0))
}

func (x *BattleModel) GetBySeq[T0 argIntEq](v0 T0) (*BattleModel, error) {
	return oneBattle(x.m.By(chainBattleGetBySeq, v0))
}

func (x *BattleModel) GetCountByIsClose[T0 argBoolEq](v0 T0) (int64, error) {
	return x.m.By(chainBattleGetCountByIsClose, v0).GetCount()
}

func (x *BattleModel) GetCountByServiceSeq[T0 argIntEq](v0 T0) (int64, error) {
	return x.m.By(chainBattleGetCountByServiceSeq, v0).GetCount()
}

func (x *BattleModel) GetsBySeq[T0 argIntEq](v0 T0) (*orm.Collection[*BattleModel], error) {
	return orm.Gets[*BattleModel](x.m.By(chainBattleGetsBySeq, v0))
}

func (x *BattleModel) GetsBySeqAndNeName[T0 argIntEq, T1 argStringEq](v0 T0, v1 T1) (*orm.Collection[*BattleModel], error) {
	return orm.Gets[*BattleModel](x.m.By(chainBattleGetsBySeqAndNeName, v0, v1))
}

func (x *BattleModel) GetsByServiceSeqAndIsClose[T0 argIntEq, T1 argBoolEq](v0 T0, v1 T1) (*orm.Collection[*BattleModel], error) {
	return orm.Gets[*BattleModel](x.m.By(chainBattleGetsByServiceSeqAndIsClose, v0, v1))
}

func (x *BattleModel) GtStartDt[T0 argTimeCmp](v0 T0, compared ...any) *BattleModel {
	x.m.Where("", chainBattleGtStartDt, append([]any{v0}, compared...)...)
	return x
}

func (x *BattleModel) IsClose[T0 argBoolEq](v0 T0) *BattleModel {
	x.m.Where("", chainBattleIsClose, v0)
	return x
}

func (x *BattleModel) IsDisplay[T0 argBoolEq](v0 T0) *BattleModel {
	x.m.Where("", chainBattleIsDisplay, v0)
	return x
}

func (x *BattleModel) JoinServiceMemberSeqWithSeq[C hasSeq](child C) *BattleModel {
	x.m.Join("inner", "service_member_seq", "seq", child)
	return x
}

func (x *BattleModel) JoinServiceSeqWithSeq[C hasSeq](child C) *BattleModel {
	x.m.Join("inner", "service_seq", "seq", child)
	return x
}

func (x *BattleModel) JoinUserSeqWithSeq[C hasSeq](child C) *BattleModel {
	x.m.Join("inner", "user_seq", "seq", child)
	return x
}

func (x *BattleModel) LeftJoinServiceModuleSeqWithSeq[C hasSeq](child C) *BattleModel {
	x.m.Join("left", "service_module_seq", "seq", child)
	return x
}

func (x *BattleModel) LeftJoinUserSeqWithSeq[C hasSeq](child C) *BattleModel {
	x.m.Join("left", "user_seq", "seq", child)
	return x
}

func (x *BattleModel) MatchSeqWithUserSeq() *BattleModel { x.m.Match("seq", "user_seq"); return x }

func (x *BattleModel) Name[T0 argStringEq](v0 T0) *BattleModel {
	x.m.Where("", chainBattleName, v0)
	return x
}

func (x *BattleModel) NeCoverUrl[T0 argStringEqNull](v0 T0) *BattleModel {
	x.m.Where("", chainBattleNeCoverUrl, v0)
	return x
}

func (x *BattleModel) NewLabel(v any) *BattleModel { x.m.New("label", v); return x }

func (x *BattleModel) OrIsClose[T0 argBoolEq](v0 T0) *BattleModel {
	x.m.Where("or", chainBattleOrIsClose, v0)
	return x
}

func (x *BattleModel) OrderByReadCountDescAndSeqAsc() *BattleModel {
	x.m.OrderBy("read_count", true, nil)
	x.m.OrderBy("seq", false, nil)
	return x
}

func (x *BattleModel) ReadCount[T0 argIntEq](v0 T0) *BattleModel {
	x.m.Where("", chainBattleReadCount, v0)
	return x
}

func (x *BattleModel) ReadCountGtSeq[T0 hasSeq](v0 T0) *BattleModel {
	x.m.Where("", chainBattleReadCountGtSeq, v0)
	return x
}

func (x *BattleModel) Seq[T0 argIntEq](v0 T0) *BattleModel {
	x.m.Where("", chainBattleSeq, v0)
	return x
}

func (x *BattleModel) ServiceSeq[T0 argIntEq](v0 T0) *BattleModel {
	x.m.Where("", chainBattleServiceSeq, v0)
	return x
}

func (x *BattleModel) UserSeqEqSeq[T0 hasSeq](v0 T0) *BattleModel {
	x.m.Where("", chainBattleUserSeqEqSeq, v0)
	return x
}

var chainBattleAesHexEmail = []orm.ChainKey{{Column: "aes_hex_email"}}

var chainBattleAndAesHexEmail = []orm.ChainKey{{Column: "aes_hex_email"}}

var chainBattleAndBetweenReadCount = []orm.ChainKey{{Op: "between", Column: "read_count"}}

var chainBattleAndEqStartDt = []orm.ChainKey{{Column: "start_dt"}}

var chainBattleAndGeReadCount = []orm.ChainKey{{Op: "ge", Column: "read_count"}}

var chainBattleAndGtReadCount = []orm.ChainKey{{Op: "gt", Column: "read_count"}}

var chainBattleAndGtStartDt = []orm.ChainKey{{Op: "gt", Column: "start_dt"}}

var chainBattleAndIsClose = []orm.ChainKey{{Column: "is_close"}}

var chainBattleAndLbName = []orm.ChainKey{{Op: "lb", Column: "name"}}

var chainBattleAndLeReadCount = []orm.ChainKey{{Op: "le", Column: "read_count"}}

var chainBattleAndLkName = []orm.ChainKey{{Op: "lk", Column: "name"}}

var chainBattleAndLtDisplayStartDt = []orm.ChainKey{{Op: "lt", Column: "display_start_dt"}}

var chainBattleAndLtReadCount = []orm.ChainKey{{Op: "lt", Column: "read_count"}}

var chainBattleAndLtSeq = []orm.ChainKey{{Op: "lt", Column: "seq"}}

var chainBattleAndLtStartDt = []orm.ChainKey{{Op: "lt", Column: "start_dt"}}

var chainBattleAndNeCoverUrl = []orm.ChainKey{{Op: "ne", Column: "cover_url"}}

var chainBattleAndNeIsClose = []orm.ChainKey{{Op: "ne", Column: "is_close"}}

var chainBattleAndNeReadCount = []orm.ChainKey{{Op: "ne", Column: "read_count"}}

var chainBattleAndSeq = []orm.ChainKey{{Column: "seq"}}

var chainBattleAndServiceSeq = []orm.ChainKey{{Column: "service_seq"}}

var chainBattleAndStartDt = []orm.ChainKey{{Column: "start_dt"}}

var chainBattleAndSuccessCountLtSeq = []orm.ChainKey{{Op: "lt", Column: "success_count", Compare: "seq"}}

var chainBattleAndUuid = []orm.ChainKey{{Column: "uuid"}}

var chainBattleBetweenReadCount = []orm.ChainKey{{Op: "between", Column: "read_count"}}

var chainBattleCoverUrl = []orm.ChainKey{{Column: "cover_url"}}

var chainBattleGeReadCount = []orm.ChainKey{{Op: "ge", Column: "read_count"}}

var chainBattleGetByName = []orm.ChainKey{{Column: "name"}}

var chainBattleGetBySeq = []orm.ChainKey{{Column: "seq"}}

var chainBattleGetCountByIsClose = []orm.ChainKey{{Column: "is_close"}}

var chainBattleGetCountByServiceSeq = []orm.ChainKey{{Column: "service_seq"}}

var chainBattleGetsBySeq = []orm.ChainKey{{Column: "seq"}}

var chainBattleGetsBySeqAndNeName = []orm.ChainKey{{Column: "seq"}, {Conn: "and", Op: "ne", Column: "name"}}

var chainBattleGetsByServiceSeqAndIsClose = []orm.ChainKey{{Column: "service_seq"}, {Conn: "and", Column: "is_close"}}

var chainBattleGtStartDt = []orm.ChainKey{{Op: "gt", Column: "start_dt"}}

var chainBattleIsClose = []orm.ChainKey{{Column: "is_close"}}

var chainBattleIsDisplay = []orm.ChainKey{{Column: "is_display"}}

var chainBattleName = []orm.ChainKey{{Column: "name"}}

var chainBattleNeCoverUrl = []orm.ChainKey{{Op: "ne", Column: "cover_url"}}

var chainBattleOrIsClose = []orm.ChainKey{{Column: "is_close"}}

var chainBattleReadCount = []orm.ChainKey{{Column: "read_count"}}

var chainBattleReadCountGtSeq = []orm.ChainKey{{Op: "gt", Column: "read_count", Compare: "seq"}}

var chainBattleSeq = []orm.ChainKey{{Column: "seq"}}

var chainBattleServiceSeq = []orm.ChainKey{{Column: "service_seq"}}

var chainBattleUserSeqEqSeq = []orm.ChainKey{{Column: "user_seq", Compare: "seq"}}

// GetDoubled returns the column added with AddRawColumnDoubled.
func (x *BattleModel) GetDoubled() any { return x.m.NewValue("doubled") }

// GetLabel returns the value attached with NewLabel.
func (x *BattleModel) GetLabel() any { return x.m.NewValue("label") }

// GetMembers returns the service_member relation result.
func (x *BattleModel) GetMembers() *orm.Collection[*ServiceMemberModel] {
	v, _ := x.m.Related("members").(*orm.Collection[*ServiceMemberModel])
	return v
}

// GetModule returns the service_module relation result.
func (x *BattleModel) GetModule() *ServiceModuleModel {
	v, _ := x.m.Related("module").(*ServiceModuleModel)
	return v
}

// GetOwner returns the user relation result.
func (x *BattleModel) GetOwner() *UserModel {
	v, _ := x.m.Related("owner").(*UserModel)
	return v
}

// GetOwnerService returns the service relation result.
func (x *BattleModel) GetOwnerService() *ServiceModel {
	v, _ := x.m.Related("owner_service").(*ServiceModel)
	return v
}

// GetReadText returns the column added with AddColumnReadCountAliasReadText.
func (x *BattleModel) GetReadText() any { return x.m.NewValue("read_text") }

// GetServiceMemberModel returns the service_member relation result.
func (x *BattleModel) GetServiceMemberModel() *ServiceMemberModel {
	v, _ := x.m.Related("service_member_model").(*ServiceMemberModel)
	return v
}

// GetServiceMemberModels returns the service_member relation result.
func (x *BattleModel) GetServiceMemberModels() *orm.Collection[*ServiceMemberModel] {
	v, _ := x.m.Related("service_member_models").(*orm.Collection[*ServiceMemberModel])
	return v
}

// GetServiceModel returns the service relation result.
func (x *BattleModel) GetServiceModel() *ServiceModel {
	v, _ := x.m.Related("service_model").(*ServiceModel)
	return v
}

// GetServiceModuleModel returns the service_module relation result.
func (x *BattleModel) GetServiceModuleModel() *ServiceModuleModel {
	v, _ := x.m.Related("service_module_model").(*ServiceModuleModel)
	return v
}

// GetStartMonth returns the column added with AddColumnStartDtAliasStartMonth.
func (x *BattleModel) GetStartMonth() any { return x.m.NewValue("start_month") }

// GetUserModel returns the user relation result.
func (x *BattleModel) GetUserModel() *UserModel {
	v, _ := x.m.Related("user_model").(*UserModel)
	return v
}

// GetWriter returns the user relation result.
func (x *BattleModel) GetWriter() *UserModel {
	v, _ := x.m.Related("writer").(*UserModel)
	return v
}
