// Code generated by ormgen; DO NOT EDIT.

package model

import (
	"time"

	"github.com/polyspec/orm/clients/go/orm"
)

var _ time.Time

// CompositeMembershipModel is a composite_membership model or row.
type CompositeMembershipModel struct {
	m          *orm.Core
	fTenantId  int64
	fAccountId int64
	fRole      string
}

var compositeMembershipEntity = &orm.Entity{Name: "composite_membership", Schema: ormSchema, New: func(c *orm.Core) orm.Model { x := &CompositeMembershipModel{m: c}; c.Bind(x); return x },
	Assign: func(m orm.Model, name string, v any) bool { return m.(*CompositeMembershipModel).assign(name, v) },
	Value:  func(m orm.Model, name string) (any, bool) { return m.(*CompositeMembershipModel).value(name) },
	Collect: func(keys []orm.Key, items map[orm.Key]*orm.Core, fetched map[orm.Key]any) any {
		return orm.CollectOf[*CompositeMembershipModel](keys, items, fetched)
	},
}

// CompositeMembership creates a composite_membership model.
func CompositeMembership() *CompositeMembershipModel {
	return compositeMembershipEntity.New(orm.NewCore(compositeMembershipEntity)).(*CompositeMembershipModel)
}

func (x *CompositeMembershipModel) Orm_() *orm.Core { return x.m }

// MarshalJSON writes the row values in order.
func (x *CompositeMembershipModel) MarshalJSON() ([]byte, error) { return x.m.MarshalJSON() }

// ToArray returns the row values.
func (x *CompositeMembershipModel) ToArray() map[string]any { return x.m.ToArray() }

func (x *CompositeMembershipModel) assign(name string, v any) bool {
	switch name {
	case "tenant_id":
		x.fTenantId = orm.AsInt64(v)
	case "account_id":
		x.fAccountId = orm.AsInt64(v)
	case "role":
		x.fRole = orm.AsString(v)
	default:
		return false
	}
	return true
}

func (x *CompositeMembershipModel) value(name string) (any, bool) {
	switch name {
	case "tenant_id":
		return x.fTenantId, true
	case "account_id":
		return x.fAccountId, true
	case "role":
		return x.fRole, true
	}
	return nil, false
}

// Connect sets the connection.
func (x *CompositeMembershipModel) Connect(db *orm.DB) *CompositeMembershipModel {
	x.m.Connect(db)
	return x
}

// And joins the next condition with AND, opens an AND group with a callback,
// or places the conditions of a joined model.
func (x *CompositeMembershipModel) And(args ...any) *CompositeMembershipModel {
	return x.connector("and", args)
}

// Or joins the next condition with OR, opens an OR group with a callback, or
// places the conditions of a joined model.
func (x *CompositeMembershipModel) Or(args ...any) *CompositeMembershipModel {
	return x.connector("or", args)
}

func (x *CompositeMembershipModel) connector(conn string, args []any) *CompositeMembershipModel {
	if len(args) == 1 {
		if fn, ok := args[0].(func(*CompositeMembershipModel)); ok {
			g := compositeMembershipEntity.New(x.m.Group()).(*CompositeMembershipModel)
			fn(g)
			x.m.AddGroup(conn, g.m)
			return x
		}
	}
	x.m.Connector(conn, args)
	return x
}

// Raw adds a raw first condition.
func (x *CompositeMembershipModel) Raw(sql string, binds ...any) *CompositeMembershipModel {
	x.m.Raw("", sql, binds)
	return x
}

// AndRaw adds a raw condition joined with AND.
func (x *CompositeMembershipModel) AndRaw(sql string, binds ...any) *CompositeMembershipModel {
	x.m.Raw("and", sql, binds)
	return x
}

// OrRaw adds a raw condition joined with OR.
func (x *CompositeMembershipModel) OrRaw(sql string, binds ...any) *CompositeMembershipModel {
	x.m.Raw("or", sql, binds)
	return x
}

// On sets the join ON conditions.
func (x *CompositeMembershipModel) On(fn func(*CompositeMembershipModel)) *CompositeMembershipModel {
	g := compositeMembershipEntity.New(x.m.Group()).(*CompositeMembershipModel)
	fn(g)
	x.m.On(g.m)
	return x
}

// Relation attaches one related row loaded by a separate query.
func (x *CompositeMembershipModel) Relation(child orm.Model) *CompositeMembershipModel {
	x.m.Relation(false, child)
	return x
}

// Relations attaches related rows loaded by a separate query.
func (x *CompositeMembershipModel) Relations(child orm.Model) *CompositeMembershipModel {
	x.m.Relation(true, child)
	return x
}

// Get returns the first matching row. It returns orm.CodeNoRows when no row matches.
func (x *CompositeMembershipModel) Get() (*CompositeMembershipModel, error) {
	return oneCompositeMembership(x.m)
}

func oneCompositeMembership(c *orm.Core) (*CompositeMembershipModel, error) {
	m, err := c.Get()
	if m == nil {
		return nil, err
	}
	return m.(*CompositeMembershipModel), err
}

// Gets returns the matching rows.
func (x *CompositeMembershipModel) Gets() (*orm.Collection[*CompositeMembershipModel], error) {
	return orm.Gets[*CompositeMembershipModel](x.m)
}

// GetCount returns the number of matching rows.
func (x *CompositeMembershipModel) GetCount() (int64, error) { return x.m.GetCount() }

// GetsCount returns grouped rows with row_count.
func (x *CompositeMembershipModel) GetsCount() (*orm.Collection[*CompositeMembershipModel], error) {
	return orm.GetsCount[*CompositeMembershipModel](x.m)
}

// GetSum returns the sum of the column selected with Sum<Col>.
func (x *CompositeMembershipModel) GetSum() (float64, error) { return x.m.GetSum() }

// GetAvg returns the average of the column selected with Avg<Col>.
func (x *CompositeMembershipModel) GetAvg() (float64, error) { return x.m.GetAvg() }

// GetsPage returns one page of matching rows.
func (x *CompositeMembershipModel) GetsPage(page, perPage int) (*orm.Page[*CompositeMembershipModel], error) {
	return orm.GetsPage[*CompositeMembershipModel](x.m, page, perPage)
}

// GetQuery returns the statement of Gets without executing it.
func (x *CompositeMembershipModel) GetQuery() (*orm.Statement, error) { return x.m.GetQuery() }

// Create inserts the row and returns the created row.
func (x *CompositeMembershipModel) Create() (*CompositeMembershipModel, error) {
	m, err := x.m.Create()
	if err != nil {
		return nil, err
	}
	return m.(*CompositeMembershipModel), nil
}

// Creates inserts rows in one transaction and returns the inserted row count.
func (x *CompositeMembershipModel) Creates(rows []*CompositeMembershipModel) (int64, error) {
	return orm.Creates(x.m, rows)
}

// Update writes the changed columns; Update(true) requires an unchanged updated time.
func (x *CompositeMembershipModel) Update(optimistic ...bool) (*CompositeMembershipModel, error) {
	if err := x.m.Update(optimistic); err != nil {
		return nil, err
	}
	return x, nil
}

// Save updates the row when its primary key is known, otherwise creates it.
func (x *CompositeMembershipModel) Save() (*CompositeMembershipModel, error) {
	m, err := x.m.Save()
	if err != nil {
		return nil, err
	}
	return m.(*CompositeMembershipModel), nil
}

// Delete deletes the row; Delete(true) first deletes loaded related rows.
func (x *CompositeMembershipModel) Delete(recursive ...bool) error { return x.m.Delete(recursive) }

// Duplication sets the duplicate-key update of the next Create.
func (x *CompositeMembershipModel) Duplication(m *CompositeMembershipModel) *CompositeMembershipModel {
	x.m.Duplication(m)
	return x
}

// Limit sets the row range.
func (x *CompositeMembershipModel) Limit(offset, count int) *CompositeMembershipModel {
	x.m.Limit(offset, count)
	return x
}

// OrderByRandom orders rows randomly.
func (x *CompositeMembershipModel) OrderByRandom() *CompositeMembershipModel {
	x.m.OrderByRandom()
	return x
}

// OrderByRaw appends a raw order expression.
func (x *CompositeMembershipModel) OrderByRaw(sql string) *CompositeMembershipModel {
	x.m.OrderByRaw(sql)
	return x
}

// GroupByRaw appends a raw grouping expression.
func (x *CompositeMembershipModel) GroupByRaw(sql string) *CompositeMembershipModel {
	x.m.GroupByRaw(sql)
	return x
}

// RemoveAllColumns keeps only primary and foreign keys.
func (x *CompositeMembershipModel) RemoveAllColumns() *CompositeMembershipModel {
	x.m.RemoveAllColumns()
	return x
}

// AddAllColumns selects every column.
func (x *CompositeMembershipModel) AddAllColumns() *CompositeMembershipModel {
	x.m.AddAllColumns()
	return x
}

// ParentNode merges the related row into the parent row.
func (x *CompositeMembershipModel) ParentNode() *CompositeMembershipModel { x.m.ParentNode(); return x }

// GroupLimit limits related rows per parent.
func (x *CompositeMembershipModel) GroupLimit(n int) *CompositeMembershipModel {
	x.m.GroupLimit(n)
	return x
}

// DeleteLock excludes the relation from recursive delete.
func (x *CompositeMembershipModel) DeleteLock() *CompositeMembershipModel { x.m.DeleteLock(); return x }

// FetchKey computes the collection key of each row.
func (x *CompositeMembershipModel) FetchKey(fn func(*CompositeMembershipModel) any) *CompositeMembershipModel {
	x.m.FetchKey(func(m orm.Model) any { return fn(m.(*CompositeMembershipModel)) })
	return x
}

// FetchValue computes a value for each loaded row.
func (x *CompositeMembershipModel) FetchValue(fn func(*CompositeMembershipModel) any) *CompositeMembershipModel {
	x.m.FetchValue(func(m orm.Model) any { return fn(m.(*CompositeMembershipModel)) })
	return x
}

// ForUpdate locks the selected rows for update inside a transaction.
func (x *CompositeMembershipModel) ForUpdate() *CompositeMembershipModel {
	x.m.Lock("update")
	return x
}

// ForShare locks the selected rows for share inside a transaction.
func (x *CompositeMembershipModel) ForShare() *CompositeMembershipModel { x.m.Lock("share"); return x }

// ForUpdateNoWait locks for update without waiting.
func (x *CompositeMembershipModel) ForUpdateNoWait() *CompositeMembershipModel {
	x.m.Lock("update_nowait")
	return x
}

// ForShareNoWait locks for share without waiting.
func (x *CompositeMembershipModel) ForShareNoWait() *CompositeMembershipModel {
	x.m.Lock("share_nowait")
	return x
}

// GetTenantId returns tenant_id.
func (x *CompositeMembershipModel) GetTenantId() int64 { return x.fTenantId }

// SetTenantId sets tenant_id.
func (x *CompositeMembershipModel) SetTenantId(v int64) *CompositeMembershipModel {
	x.fTenantId = v
	x.m.Set("tenant_id", v)
	return x
}

func (x *CompositeMembershipModel) SetRawTenantId(sql string, binds ...any) *CompositeMembershipModel {
	x.m.SetRaw("tenant_id", sql, binds)
	return x
}
func (x *CompositeMembershipModel) AddColumnTenantId() *CompositeMembershipModel {
	x.m.AddColumn("tenant_id")
	return x
}
func (x *CompositeMembershipModel) RemoveColumnTenantId() *CompositeMembershipModel {
	x.m.RemoveColumn("tenant_id")
	return x
}
func (x *CompositeMembershipModel) GroupByTenantId() *CompositeMembershipModel {
	x.m.GroupBy("tenant_id")
	return x
}
func (x *CompositeMembershipModel) KeyNameTenantId() *CompositeMembershipModel {
	x.m.KeyName("tenant_id")
	return x
}
func (x *CompositeMembershipModel) OrderByTenantIdAsc(fn ...orm.Func) *CompositeMembershipModel {
	x.m.OrderBy("tenant_id", false, fn)
	return x
}
func (x *CompositeMembershipModel) OrderByTenantIdDesc(fn ...orm.Func) *CompositeMembershipModel {
	x.m.OrderBy("tenant_id", true, fn)
	return x
}
func (x *CompositeMembershipModel) PlusTenantId(n int64) *CompositeMembershipModel {
	x.m.Plus("tenant_id", n)
	return x
}
func (x *CompositeMembershipModel) MinusTenantId(n int64) *CompositeMembershipModel {
	x.m.Minus("tenant_id", n)
	return x
}
func (x *CompositeMembershipModel) SumTenantId() *CompositeMembershipModel {
	x.m.Aggregate("sum", "tenant_id")
	return x
}
func (x *CompositeMembershipModel) AvgTenantId() *CompositeMembershipModel {
	x.m.Aggregate("avg", "tenant_id")
	return x
}

// GetAccountId returns account_id.
func (x *CompositeMembershipModel) GetAccountId() int64 { return x.fAccountId }

// SetAccountId sets account_id.
func (x *CompositeMembershipModel) SetAccountId(v int64) *CompositeMembershipModel {
	x.fAccountId = v
	x.m.Set("account_id", v)
	return x
}

func (x *CompositeMembershipModel) SetRawAccountId(sql string, binds ...any) *CompositeMembershipModel {
	x.m.SetRaw("account_id", sql, binds)
	return x
}
func (x *CompositeMembershipModel) AddColumnAccountId() *CompositeMembershipModel {
	x.m.AddColumn("account_id")
	return x
}
func (x *CompositeMembershipModel) RemoveColumnAccountId() *CompositeMembershipModel {
	x.m.RemoveColumn("account_id")
	return x
}
func (x *CompositeMembershipModel) GroupByAccountId() *CompositeMembershipModel {
	x.m.GroupBy("account_id")
	return x
}
func (x *CompositeMembershipModel) KeyNameAccountId() *CompositeMembershipModel {
	x.m.KeyName("account_id")
	return x
}
func (x *CompositeMembershipModel) OrderByAccountIdAsc(fn ...orm.Func) *CompositeMembershipModel {
	x.m.OrderBy("account_id", false, fn)
	return x
}
func (x *CompositeMembershipModel) OrderByAccountIdDesc(fn ...orm.Func) *CompositeMembershipModel {
	x.m.OrderBy("account_id", true, fn)
	return x
}
func (x *CompositeMembershipModel) PlusAccountId(n int64) *CompositeMembershipModel {
	x.m.Plus("account_id", n)
	return x
}
func (x *CompositeMembershipModel) MinusAccountId(n int64) *CompositeMembershipModel {
	x.m.Minus("account_id", n)
	return x
}
func (x *CompositeMembershipModel) SumAccountId() *CompositeMembershipModel {
	x.m.Aggregate("sum", "account_id")
	return x
}
func (x *CompositeMembershipModel) AvgAccountId() *CompositeMembershipModel {
	x.m.Aggregate("avg", "account_id")
	return x
}

// GetRole returns role.
func (x *CompositeMembershipModel) GetRole() string { return x.fRole }

// SetRole sets role.
func (x *CompositeMembershipModel) SetRole(v string) *CompositeMembershipModel {
	x.fRole = v
	x.m.Set("role", v)
	return x
}

func (x *CompositeMembershipModel) SetRawRole(sql string, binds ...any) *CompositeMembershipModel {
	x.m.SetRaw("role", sql, binds)
	return x
}
func (x *CompositeMembershipModel) AddColumnRole() *CompositeMembershipModel {
	x.m.AddColumn("role")
	return x
}
func (x *CompositeMembershipModel) RemoveColumnRole() *CompositeMembershipModel {
	x.m.RemoveColumn("role")
	return x
}
func (x *CompositeMembershipModel) GroupByRole() *CompositeMembershipModel {
	x.m.GroupBy("role")
	return x
}
func (x *CompositeMembershipModel) KeyNameRole() *CompositeMembershipModel {
	x.m.KeyName("role")
	return x
}
func (x *CompositeMembershipModel) OrderByRoleAsc(fn ...orm.Func) *CompositeMembershipModel {
	x.m.OrderBy("role", false, fn)
	return x
}
func (x *CompositeMembershipModel) OrderByRoleDesc(fn ...orm.Func) *CompositeMembershipModel {
	x.m.OrderBy("role", true, fn)
	return x
}

func (x *CompositeMembershipModel) TupleTenantIdWithAccountId(v0 []CompositeMembershipTenantIdWithAccountId) *CompositeMembershipModel {
	x.m.Where("", chainCompositeMembershipTupleTenantIdWithAccountId, v0)
	return x
}

var chainCompositeMembershipTupleTenantIdWithAccountId = []orm.ChainKey{{Op: "tuple", Columns: []string{"tenant_id", "account_id"}}}
