// Code generated by ormgen; DO NOT EDIT.

package model

import (
	"time"

	"github.com/polyspec/orm/clients/go/orm"
)

var _ time.Time

// SoftRecordModel is a soft_record model or row.
type SoftRecordModel struct {
	m          *orm.Core
	fSeq       int64
	fName      string
	fDeletedAt *time.Time
}

var softRecordEntity = &orm.Entity{Name: "soft_record", Schema: ormSchema, New: func(c *orm.Core) orm.Model { x := &SoftRecordModel{m: c}; c.Bind(x); return x },
	Assign: func(m orm.Model, name string, v any) bool { return m.(*SoftRecordModel).assign(name, v) },
	Value:  func(m orm.Model, name string) (any, bool) { return m.(*SoftRecordModel).value(name) },
	Collect: func(keys []orm.Key, items map[orm.Key]*orm.Core, fetched map[orm.Key]any) any {
		return orm.CollectOf[*SoftRecordModel](keys, items, fetched)
	},
}

// SoftRecord creates a soft_record model.
func SoftRecord() *SoftRecordModel {
	return softRecordEntity.New(orm.NewCore(softRecordEntity)).(*SoftRecordModel)
}

func (x *SoftRecordModel) Orm_() *orm.Core { return x.m }

// MarshalJSON writes the row values in order.
func (x *SoftRecordModel) MarshalJSON() ([]byte, error) { return x.m.MarshalJSON() }

// ToArray returns the row values.
func (x *SoftRecordModel) ToArray() map[string]any { return x.m.ToArray() }

func (x *SoftRecordModel) assign(name string, v any) bool {
	switch name {
	case "seq":
		x.fSeq = orm.AsInt64(v)
	case "name":
		x.fName = orm.AsString(v)
	case "deleted_at":
		if v == nil {
			x.fDeletedAt = nil
		} else {
			t := orm.AsTime(v)
			x.fDeletedAt = &t
		}
	default:
		return false
	}
	return true
}

func (x *SoftRecordModel) value(name string) (any, bool) {
	switch name {
	case "seq":
		return x.fSeq, true
	case "name":
		return x.fName, true
	case "deleted_at":
		if x.fDeletedAt == nil {
			return nil, true
		}
		return *x.fDeletedAt, true
	}
	return nil, false
}

// Connect sets the connection.
func (x *SoftRecordModel) Connect(db *orm.DB) *SoftRecordModel { x.m.Connect(db); return x }

// And joins the next condition with AND, opens an AND group with a callback,
// or places the conditions of a joined model.
func (x *SoftRecordModel) And(args ...any) *SoftRecordModel { return x.connector("and", args) }

// Or joins the next condition with OR, opens an OR group with a callback, or
// places the conditions of a joined model.
func (x *SoftRecordModel) Or(args ...any) *SoftRecordModel { return x.connector("or", args) }

func (x *SoftRecordModel) connector(conn string, args []any) *SoftRecordModel {
	if len(args) == 1 {
		if fn, ok := args[0].(func(*SoftRecordModel)); ok {
			g := softRecordEntity.New(x.m.Group()).(*SoftRecordModel)
			fn(g)
			x.m.AddGroup(conn, g.m)
			return x
		}
	}
	x.m.Connector(conn, args)
	return x
}

// Raw adds a raw first condition.
func (x *SoftRecordModel) Raw(sql string, binds ...any) *SoftRecordModel {
	x.m.Raw("", sql, binds)
	return x
}

// AndRaw adds a raw condition joined with AND.
func (x *SoftRecordModel) AndRaw(sql string, binds ...any) *SoftRecordModel {
	x.m.Raw("and", sql, binds)
	return x
}

// OrRaw adds a raw condition joined with OR.
func (x *SoftRecordModel) OrRaw(sql string, binds ...any) *SoftRecordModel {
	x.m.Raw("or", sql, binds)
	return x
}

// On sets the join ON conditions.
func (x *SoftRecordModel) On(fn func(*SoftRecordModel)) *SoftRecordModel {
	g := softRecordEntity.New(x.m.Group()).(*SoftRecordModel)
	fn(g)
	x.m.On(g.m)
	return x
}

// Relation attaches one related row loaded by a separate query.
func (x *SoftRecordModel) Relation(child orm.Model) *SoftRecordModel {
	x.m.Relation(false, child)
	return x
}

// Relations attaches related rows loaded by a separate query.
func (x *SoftRecordModel) Relations(child orm.Model) *SoftRecordModel {
	x.m.Relation(true, child)
	return x
}

// Get returns the first matching row, or nil.
func (x *SoftRecordModel) Get() (*SoftRecordModel, error) { return oneSoftRecord(x.m) }

func oneSoftRecord(c *orm.Core) (*SoftRecordModel, error) {
	m, err := c.Get()
	if m == nil {
		return nil, err
	}
	return m.(*SoftRecordModel), err
}

// Gets returns the matching rows.
func (x *SoftRecordModel) Gets() (*orm.Collection[*SoftRecordModel], error) {
	return orm.Gets[*SoftRecordModel](x.m)
}

// GetCount returns the number of matching rows.
func (x *SoftRecordModel) GetCount() (int64, error) { return x.m.GetCount() }

// GetsCount returns grouped rows with row_count.
func (x *SoftRecordModel) GetsCount() (*orm.Collection[*SoftRecordModel], error) {
	return orm.GetsCount[*SoftRecordModel](x.m)
}

// GetSum returns the sum of the column selected with Sum<Col>.
func (x *SoftRecordModel) GetSum() (float64, error) { return x.m.GetSum() }

// GetAvg returns the average of the column selected with Avg<Col>.
func (x *SoftRecordModel) GetAvg() (float64, error) { return x.m.GetAvg() }

// GetsPage returns one page of matching rows.
func (x *SoftRecordModel) GetsPage(page, perPage int) (*orm.Page[*SoftRecordModel], error) {
	return orm.GetsPage[*SoftRecordModel](x.m, page, perPage)
}

// GetQuery returns the statement of Gets without executing it.
func (x *SoftRecordModel) GetQuery() (*orm.Statement, error) { return x.m.GetQuery() }

// Create inserts the row and returns the created row.
func (x *SoftRecordModel) Create() (*SoftRecordModel, error) {
	m, err := x.m.Create()
	if err != nil {
		return nil, err
	}
	return m.(*SoftRecordModel), nil
}

// Creates inserts rows in one transaction and returns the inserted row count.
func (x *SoftRecordModel) Creates(rows []*SoftRecordModel) (int64, error) {
	return orm.Creates(x.m, rows)
}

// Update writes the changed columns; Update(true) requires an unchanged updated time.
func (x *SoftRecordModel) Update(optimistic ...bool) (*SoftRecordModel, error) {
	if err := x.m.Update(optimistic); err != nil {
		return nil, err
	}
	return x, nil
}

// Save updates the row when its primary key is known, otherwise creates it.
func (x *SoftRecordModel) Save() (*SoftRecordModel, error) {
	m, err := x.m.Save()
	if err != nil {
		return nil, err
	}
	return m.(*SoftRecordModel), nil
}

// Delete deletes the row; Delete(true) first deletes loaded related rows.
func (x *SoftRecordModel) Delete(recursive ...bool) error { return x.m.Delete(recursive) }

// Duplication sets the duplicate-key update of the next Create.
func (x *SoftRecordModel) Duplication(m *SoftRecordModel) *SoftRecordModel {
	x.m.Duplication(m)
	return x
}

// Limit sets the row range.
func (x *SoftRecordModel) Limit(offset, count int) *SoftRecordModel {
	x.m.Limit(offset, count)
	return x
}

// OrderByRandom orders rows randomly.
func (x *SoftRecordModel) OrderByRandom() *SoftRecordModel { x.m.OrderByRandom(); return x }

// OrderByRaw appends a raw order expression.
func (x *SoftRecordModel) OrderByRaw(sql string) *SoftRecordModel { x.m.OrderByRaw(sql); return x }

// GroupByRaw appends a raw grouping expression.
func (x *SoftRecordModel) GroupByRaw(sql string) *SoftRecordModel { x.m.GroupByRaw(sql); return x }

// RemoveAllColumns keeps only primary and foreign keys.
func (x *SoftRecordModel) RemoveAllColumns() *SoftRecordModel { x.m.RemoveAllColumns(); return x }

// AddAllColumns selects every column.
func (x *SoftRecordModel) AddAllColumns() *SoftRecordModel { x.m.AddAllColumns(); return x }

// ParentNode merges the related row into the parent row.
func (x *SoftRecordModel) ParentNode() *SoftRecordModel { x.m.ParentNode(); return x }

// GroupLimit limits related rows per parent.
func (x *SoftRecordModel) GroupLimit(n int) *SoftRecordModel { x.m.GroupLimit(n); return x }

// DeleteLock excludes the relation from recursive delete.
func (x *SoftRecordModel) DeleteLock() *SoftRecordModel { x.m.DeleteLock(); return x }

// FetchKey computes the collection key of each row.
func (x *SoftRecordModel) FetchKey(fn func(*SoftRecordModel) any) *SoftRecordModel {
	x.m.FetchKey(func(m orm.Model) any { return fn(m.(*SoftRecordModel)) })
	return x
}

// FetchValue computes a value for each loaded row.
func (x *SoftRecordModel) FetchValue(fn func(*SoftRecordModel) any) *SoftRecordModel {
	x.m.FetchValue(func(m orm.Model) any { return fn(m.(*SoftRecordModel)) })
	return x
}

// ForUpdate locks the selected rows for update inside a transaction.
func (x *SoftRecordModel) ForUpdate() *SoftRecordModel { x.m.Lock("update"); return x }

// ForShare locks the selected rows for share inside a transaction.
func (x *SoftRecordModel) ForShare() *SoftRecordModel { x.m.Lock("share"); return x }

// ForUpdateNoWait locks for update without waiting.
func (x *SoftRecordModel) ForUpdateNoWait() *SoftRecordModel { x.m.Lock("update_nowait"); return x }

// ForShareNoWait locks for share without waiting.
func (x *SoftRecordModel) ForShareNoWait() *SoftRecordModel { x.m.Lock("share_nowait"); return x }

// GetSeq returns seq.
func (x *SoftRecordModel) GetSeq() int64 { return x.fSeq }

// SetSeq sets seq.
func (x *SoftRecordModel) SetSeq(v int64) *SoftRecordModel { x.fSeq = v; x.m.Set("seq", v); return x }

func (x *SoftRecordModel) SetRawSeq(sql string, binds ...any) *SoftRecordModel {
	x.m.SetRaw("seq", sql, binds)
	return x
}
func (x *SoftRecordModel) AddColumnSeq() *SoftRecordModel    { x.m.AddColumn("seq"); return x }
func (x *SoftRecordModel) RemoveColumnSeq() *SoftRecordModel { x.m.RemoveColumn("seq"); return x }
func (x *SoftRecordModel) GroupBySeq() *SoftRecordModel      { x.m.GroupBy("seq"); return x }
func (x *SoftRecordModel) KeyNameSeq() *SoftRecordModel      { x.m.KeyName("seq"); return x }
func (x *SoftRecordModel) OrderBySeqAsc(fn ...orm.Func) *SoftRecordModel {
	x.m.OrderBy("seq", false, fn)
	return x
}
func (x *SoftRecordModel) OrderBySeqDesc(fn ...orm.Func) *SoftRecordModel {
	x.m.OrderBy("seq", true, fn)
	return x
}
func (x *SoftRecordModel) PlusSeq(n int64) *SoftRecordModel  { x.m.Plus("seq", n); return x }
func (x *SoftRecordModel) MinusSeq(n int64) *SoftRecordModel { x.m.Minus("seq", n); return x }
func (x *SoftRecordModel) SumSeq() *SoftRecordModel          { x.m.Aggregate("sum", "seq"); return x }
func (x *SoftRecordModel) AvgSeq() *SoftRecordModel          { x.m.Aggregate("avg", "seq"); return x }

// GetName returns name.
func (x *SoftRecordModel) GetName() string { return x.fName }

// SetName sets name.
func (x *SoftRecordModel) SetName(v string) *SoftRecordModel {
	x.fName = v
	x.m.Set("name", v)
	return x
}

func (x *SoftRecordModel) SetRawName(sql string, binds ...any) *SoftRecordModel {
	x.m.SetRaw("name", sql, binds)
	return x
}
func (x *SoftRecordModel) AddColumnName() *SoftRecordModel    { x.m.AddColumn("name"); return x }
func (x *SoftRecordModel) RemoveColumnName() *SoftRecordModel { x.m.RemoveColumn("name"); return x }
func (x *SoftRecordModel) GroupByName() *SoftRecordModel      { x.m.GroupBy("name"); return x }
func (x *SoftRecordModel) KeyNameName() *SoftRecordModel      { x.m.KeyName("name"); return x }
func (x *SoftRecordModel) OrderByNameAsc(fn ...orm.Func) *SoftRecordModel {
	x.m.OrderBy("name", false, fn)
	return x
}
func (x *SoftRecordModel) OrderByNameDesc(fn ...orm.Func) *SoftRecordModel {
	x.m.OrderBy("name", true, fn)
	return x
}

// GetDeletedAt returns deleted_at.
func (x *SoftRecordModel) GetDeletedAt() *time.Time { return x.fDeletedAt }

// SetDeletedAt sets deleted_at; nil stores NULL.
func (x *SoftRecordModel) SetDeletedAt(v *time.Time) *SoftRecordModel {
	x.fDeletedAt = v
	if v == nil {
		x.m.SetNull("deleted_at")
	} else {
		x.m.Set("deleted_at", *v)
	}
	return x
}

func (x *SoftRecordModel) SetRawDeletedAt(sql string, binds ...any) *SoftRecordModel {
	x.m.SetRaw("deleted_at", sql, binds)
	return x
}
func (x *SoftRecordModel) AddColumnDeletedAt() *SoftRecordModel {
	x.m.AddColumn("deleted_at")
	return x
}
func (x *SoftRecordModel) RemoveColumnDeletedAt() *SoftRecordModel {
	x.m.RemoveColumn("deleted_at")
	return x
}
func (x *SoftRecordModel) GroupByDeletedAt() *SoftRecordModel { x.m.GroupBy("deleted_at"); return x }
func (x *SoftRecordModel) KeyNameDeletedAt() *SoftRecordModel { x.m.KeyName("deleted_at"); return x }
func (x *SoftRecordModel) OrderByDeletedAtAsc(fn ...orm.Func) *SoftRecordModel {
	x.m.OrderBy("deleted_at", false, fn)
	return x
}
func (x *SoftRecordModel) OrderByDeletedAtDesc(fn ...orm.Func) *SoftRecordModel {
	x.m.OrderBy("deleted_at", true, fn)
	return x
}
