// Code generated by ormgen; DO NOT EDIT.

package model

import (
	"time"

	"github.com/polyspec/orm/clients/go/orm"
)

var _ time.Time

// UserModel is a user model or row.
type UserModel struct {
	m     *orm.Core
	fSeq  int64
	fName string
}

var userEntity = &orm.Entity{Name: "user", Schema: ormSchema, New: func(c *orm.Core) orm.Model { x := &UserModel{m: c}; c.Bind(x); return x },
	Assign: func(m orm.Model, name string, v any) bool { return m.(*UserModel).assign(name, v) },
	Value:  func(m orm.Model, name string) (any, bool) { return m.(*UserModel).value(name) },
	Collect: func(keys []orm.Key, items map[orm.Key]*orm.Core, fetched map[orm.Key]any) any {
		return orm.CollectOf[*UserModel](keys, items, fetched)
	},
}

// User creates a user model.
func User() *UserModel { return userEntity.New(orm.NewCore(userEntity)).(*UserModel) }

func (x *UserModel) Orm_() *orm.Core { return x.m }

// MarshalJSON writes the row values in order.
func (x *UserModel) MarshalJSON() ([]byte, error) { return x.m.MarshalJSON() }

// ToArray returns the row values.
func (x *UserModel) ToArray() map[string]any { return x.m.ToArray() }

func (x *UserModel) assign(name string, v any) bool {
	switch name {
	case "seq":
		x.fSeq = orm.AsInt64(v)
	case "name":
		x.fName = orm.AsString(v)
	default:
		return false
	}
	return true
}

func (x *UserModel) value(name string) (any, bool) {
	switch name {
	case "seq":
		return x.fSeq, true
	case "name":
		return x.fName, true
	}
	return nil, false
}

// Connect sets the connection.
func (x *UserModel) Connect(db *orm.DB) *UserModel { x.m.Connect(db); return x }

// And joins the next condition with AND, opens an AND group with a callback,
// or places the conditions of a joined model.
func (x *UserModel) And(args ...any) *UserModel { return x.connector("and", args) }

// Or joins the next condition with OR, opens an OR group with a callback, or
// places the conditions of a joined model.
func (x *UserModel) Or(args ...any) *UserModel { return x.connector("or", args) }

func (x *UserModel) connector(conn string, args []any) *UserModel {
	if len(args) == 1 {
		if fn, ok := args[0].(func(*UserModel)); ok {
			g := userEntity.New(x.m.Group()).(*UserModel)
			fn(g)
			x.m.AddGroup(conn, g.m)
			return x
		}
	}
	x.m.Connector(conn, args)
	return x
}

// Raw adds a raw first condition.
func (x *UserModel) Raw(sql string, binds ...any) *UserModel { x.m.Raw("", sql, binds); return x }

// AndRaw adds a raw condition joined with AND.
func (x *UserModel) AndRaw(sql string, binds ...any) *UserModel { x.m.Raw("and", sql, binds); return x }

// OrRaw adds a raw condition joined with OR.
func (x *UserModel) OrRaw(sql string, binds ...any) *UserModel { x.m.Raw("or", sql, binds); return x }

// On sets the join ON conditions.
func (x *UserModel) On(fn func(*UserModel)) *UserModel {
	g := userEntity.New(x.m.Group()).(*UserModel)
	fn(g)
	x.m.On(g.m)
	return x
}

// Relation attaches one related row loaded by a separate query.
func (x *UserModel) Relation(child orm.Model) *UserModel { x.m.Relation(false, child); return x }

// Relations attaches related rows loaded by a separate query.
func (x *UserModel) Relations(child orm.Model) *UserModel { x.m.Relation(true, child); return x }

// Get returns the first matching row. It returns orm.CodeNoRows when no row matches.
func (x *UserModel) Get() (*UserModel, error) { return oneUser(x.m) }

func oneUser(c *orm.Core) (*UserModel, error) {
	m, err := c.Get()
	if m == nil {
		return nil, err
	}
	return m.(*UserModel), err
}

// Gets returns the matching rows.
func (x *UserModel) Gets() (*orm.Collection[*UserModel], error) { return orm.Gets[*UserModel](x.m) }

// GetCount returns the number of matching rows.
func (x *UserModel) GetCount() (int64, error) { return x.m.GetCount() }

// GetsCount returns grouped rows with row_count.
func (x *UserModel) GetsCount() (*orm.Collection[*UserModel], error) {
	return orm.GetsCount[*UserModel](x.m)
}

// GetSum returns the sum of the column selected with Sum<Col>.
func (x *UserModel) GetSum() (float64, error) { return x.m.GetSum() }

// GetAvg returns the average of the column selected with Avg<Col>.
func (x *UserModel) GetAvg() (float64, error) { return x.m.GetAvg() }

// GetsPage returns one page of matching rows.
func (x *UserModel) GetsPage(page, perPage int) (*orm.Page[*UserModel], error) {
	return orm.GetsPage[*UserModel](x.m, page, perPage)
}

// GetQuery returns the statement of Gets without executing it.
func (x *UserModel) GetQuery() (*orm.Statement, error) { return x.m.GetQuery() }

// Create inserts the row and returns the created row.
func (x *UserModel) Create() (*UserModel, error) {
	m, err := x.m.Create()
	if err != nil {
		return nil, err
	}
	return m.(*UserModel), nil
}

// Creates inserts rows in one transaction and returns the inserted row count.
func (x *UserModel) Creates(rows []*UserModel) (int64, error) { return orm.Creates(x.m, rows) }

// Update writes the changed columns; Update(true) requires an unchanged updated time.
func (x *UserModel) Update(optimistic ...bool) (*UserModel, error) {
	if err := x.m.Update(optimistic); err != nil {
		return nil, err
	}
	return x, nil
}

// Save updates the row when its primary key is known, otherwise creates it.
func (x *UserModel) Save() (*UserModel, error) {
	m, err := x.m.Save()
	if err != nil {
		return nil, err
	}
	return m.(*UserModel), nil
}

// Delete deletes the row; Delete(true) first deletes loaded related rows.
func (x *UserModel) Delete(recursive ...bool) error { return x.m.Delete(recursive) }

// Duplication sets the duplicate-key update of the next Create.
func (x *UserModel) Duplication(m *UserModel) *UserModel { x.m.Duplication(m); return x }

// Limit sets the row range.
func (x *UserModel) Limit(offset, count int) *UserModel { x.m.Limit(offset, count); return x }

// OrderByRandom orders rows randomly.
func (x *UserModel) OrderByRandom() *UserModel { x.m.OrderByRandom(); return x }

// OrderByRaw appends a raw order expression.
func (x *UserModel) OrderByRaw(sql string) *UserModel { x.m.OrderByRaw(sql); return x }

// GroupByRaw appends a raw grouping expression.
func (x *UserModel) GroupByRaw(sql string) *UserModel { x.m.GroupByRaw(sql); return x }

// RemoveAllColumns keeps only primary and foreign keys.
func (x *UserModel) RemoveAllColumns() *UserModel { x.m.RemoveAllColumns(); return x }

// AddAllColumns selects every column.
func (x *UserModel) AddAllColumns() *UserModel { x.m.AddAllColumns(); return x }

// ParentNode merges the related row into the parent row.
func (x *UserModel) ParentNode() *UserModel { x.m.ParentNode(); return x }

// GroupLimit limits related rows per parent.
func (x *UserModel) GroupLimit(n int) *UserModel { x.m.GroupLimit(n); return x }

// DeleteLock excludes the relation from recursive delete.
func (x *UserModel) DeleteLock() *UserModel { x.m.DeleteLock(); return x }

// FetchKey computes the collection key of each row.
func (x *UserModel) FetchKey(fn func(*UserModel) any) *UserModel {
	x.m.FetchKey(func(m orm.Model) any { return fn(m.(*UserModel)) })
	return x
}

// FetchValue computes a value for each loaded row.
func (x *UserModel) FetchValue(fn func(*UserModel) any) *UserModel {
	x.m.FetchValue(func(m orm.Model) any { return fn(m.(*UserModel)) })
	return x
}

// ForUpdate locks the selected rows for update inside a transaction.
func (x *UserModel) ForUpdate() *UserModel { x.m.Lock("update"); return x }

// ForShare locks the selected rows for share inside a transaction.
func (x *UserModel) ForShare() *UserModel { x.m.Lock("share"); return x }

// ForUpdateNoWait locks for update without waiting.
func (x *UserModel) ForUpdateNoWait() *UserModel { x.m.Lock("update_nowait"); return x }

// ForShareNoWait locks for share without waiting.
func (x *UserModel) ForShareNoWait() *UserModel { x.m.Lock("share_nowait"); return x }

// GetSeq returns seq.
func (x *UserModel) GetSeq() int64 { return x.fSeq }

// SetSeq sets seq.
func (x *UserModel) SetSeq(v int64) *UserModel { x.fSeq = v; x.m.Set("seq", v); return x }

func (x *UserModel) SetRawSeq(sql string, binds ...any) *UserModel {
	x.m.SetRaw("seq", sql, binds)
	return x
}
func (x *UserModel) AddColumnSeq() *UserModel                 { x.m.AddColumn("seq"); return x }
func (x *UserModel) RemoveColumnSeq() *UserModel              { x.m.RemoveColumn("seq"); return x }
func (x *UserModel) GroupBySeq() *UserModel                   { x.m.GroupBy("seq"); return x }
func (x *UserModel) KeyNameSeq() *UserModel                   { x.m.KeyName("seq"); return x }
func (x *UserModel) OrderBySeqAsc(fn ...orm.Func) *UserModel  { x.m.OrderBy("seq", false, fn); return x }
func (x *UserModel) OrderBySeqDesc(fn ...orm.Func) *UserModel { x.m.OrderBy("seq", true, fn); return x }
func (x *UserModel) PlusSeq(n int64) *UserModel               { x.m.Plus("seq", n); return x }
func (x *UserModel) MinusSeq(n int64) *UserModel              { x.m.Minus("seq", n); return x }
func (x *UserModel) SumSeq() *UserModel                       { x.m.Aggregate("sum", "seq"); return x }
func (x *UserModel) AvgSeq() *UserModel                       { x.m.Aggregate("avg", "seq"); return x }

// GetName returns name.
func (x *UserModel) GetName() string { return x.fName }

// SetName sets name.
func (x *UserModel) SetName(v string) *UserModel { x.fName = v; x.m.Set("name", v); return x }

func (x *UserModel) SetRawName(sql string, binds ...any) *UserModel {
	x.m.SetRaw("name", sql, binds)
	return x
}
func (x *UserModel) AddColumnName() *UserModel    { x.m.AddColumn("name"); return x }
func (x *UserModel) RemoveColumnName() *UserModel { x.m.RemoveColumn("name"); return x }
func (x *UserModel) GroupByName() *UserModel      { x.m.GroupBy("name"); return x }
func (x *UserModel) KeyNameName() *UserModel      { x.m.KeyName("name"); return x }
func (x *UserModel) OrderByNameAsc(fn ...orm.Func) *UserModel {
	x.m.OrderBy("name", false, fn)
	return x
}
func (x *UserModel) OrderByNameDesc(fn ...orm.Func) *UserModel {
	x.m.OrderBy("name", true, fn)
	return x
}

func (x *UserModel) AddColumnNameAliasUpperName[F ~string | orm.Func](format F) *UserModel {
	switch f := any(format).(type) {
	case orm.Func:
		x.m.AddColumnFunc("name", "upper_name", f)
	default:
		x.m.AddColumnFormat("name", "upper_name", orm.AsString(f))
	}
	return x
}

func (x *UserModel) AddColumnReadTotal(fn func(*UserModel) orm.Model) *UserModel {
	x.m.AddColumnSub("read_total", func(m orm.Model) orm.Model { return fn(m.(*UserModel)) })
	return x
}

func (x *UserModel) AddRawColumnDoubled(sql string, binds ...any) *UserModel {
	x.m.AddRawColumn("doubled", sql, binds)
	return x
}

func (x *UserModel) AliasOwner() *UserModel { x.m.Alias("Owner"); return x }

func (x *UserModel) AliasWriter() *UserModel { x.m.Alias("Writer"); return x }

func (x *UserModel) MatchUserSeqWithSeq() *UserModel { x.m.Match("user_seq", "seq"); return x }

func (x *UserModel) Name[T0 argStringEq](v0 T0) *UserModel {
	x.m.Where("", chainUserName, v0)
	return x
}

func (x *UserModel) NeName[T0 argStringEq](v0 T0) *UserModel {
	x.m.Where("", chainUserNeName, v0)
	return x
}

func (x *UserModel) Seq[T0 argIntEq](v0 T0) *UserModel {
	x.m.Where("", chainUserSeq, v0)
	return x
}

var chainUserName = []orm.ChainKey{{Column: "name"}}

var chainUserNeName = []orm.ChainKey{{Op: "ne", Column: "name"}}

var chainUserSeq = []orm.ChainKey{{Column: "seq"}}

// GetBattleModels returns the battle relation result.
func (x *UserModel) GetBattleModels() *orm.Collection[*BattleModel] {
	v, _ := x.m.Related("battle_models").(*orm.Collection[*BattleModel])
	return v
}

// GetDoubled returns the column added with AddRawColumnDoubled.
func (x *UserModel) GetDoubled() any { return x.m.NewValue("doubled") }

// GetReadTotal returns the column added with AddColumnReadTotal.
func (x *UserModel) GetReadTotal() any { return x.m.NewValue("read_total") }

// GetUpperName returns the column added with AddColumnNameAliasUpperName.
func (x *UserModel) GetUpperName() any { return x.m.NewValue("upper_name") }
