<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/orm/compiler/v1/compiler.proto

namespace Orm\Compiler\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>orm.compiler.v1.Child</code>
 */
class Child extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string relation = 1;</code>
     */
    protected $relation = '';
    /**
     * Generated from protobuf field <code>string kind = 2;</code>
     */
    protected $kind = '';
    /**
     * Generated from protobuf field <code>uint32 step = 3;</code>
     */
    protected $step = 0;
    /**
     * Generated from protobuf field <code>bool flatten = 10;</code>
     */
    protected $flatten = false;
    /**
     * Generated from protobuf field <code>bool cascade = 11;</code>
     */
    protected $cascade = false;
    /**
     * Generated from protobuf field <code>.orm.compiler.v1.Assemble assemble = 12;</code>
     */
    protected $assemble = null;
    /**
     * Generated from protobuf field <code>repeated .orm.compiler.v1.KeyReference parent_keys = 13;</code>
     */
    private $parent_keys;
    /**
     * Generated from protobuf field <code>repeated .orm.compiler.v1.KeyReference child_keys = 14;</code>
     */
    private $child_keys;
    /**
     * Generated from protobuf field <code>repeated .orm.compiler.v1.KeyReference key = 15;</code>
     */
    private $key;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $relation
     *     @type string $kind
     *     @type int $step
     *     @type bool $flatten
     *     @type bool $cascade
     *     @type \Orm\Compiler\V1\Assemble $assemble
     *     @type \Orm\Compiler\V1\KeyReference[] $parent_keys
     *     @type \Orm\Compiler\V1\KeyReference[] $child_keys
     *     @type \Orm\Compiler\V1\KeyReference[] $key
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Orm\Compiler\V1\Compiler::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string relation = 1;</code>
     * @return string
     */
    public function getRelation()
    {
        return $this->relation;
    }

    /**
     * Generated from protobuf field <code>string relation = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRelation(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->relation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string kind = 2;</code>
     * @return string
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * Generated from protobuf field <code>string kind = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKind(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 step = 3;</code>
     * @return int
     */
    public function getStep()
    {
        return $this->step;
    }

    /**
     * Generated from protobuf field <code>uint32 step = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setStep(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->step = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool flatten = 10;</code>
     * @return bool
     */
    public function getFlatten()
    {
        return $this->flatten;
    }

    /**
     * Generated from protobuf field <code>bool flatten = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setFlatten(bool $var)
    {
        $this->flatten = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool cascade = 11;</code>
     * @return bool
     */
    public function getCascade()
    {
        return $this->cascade;
    }

    /**
     * Generated from protobuf field <code>bool cascade = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setCascade(bool $var)
    {
        $this->cascade = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.orm.compiler.v1.Assemble assemble = 12;</code>
     * @return \Orm\Compiler\V1\Assemble|null
     */
    public function getAssemble()
    {
        return $this->assemble;
    }

    public function hasAssemble()
    {
        return isset($this->assemble);
    }

    public function clearAssemble()
    {
        unset($this->assemble);
    }

    /**
     * Generated from protobuf field <code>.orm.compiler.v1.Assemble assemble = 12;</code>
     * @param \Orm\Compiler\V1\Assemble $var
     * @return $this
     */
    public function setAssemble(\Orm\Compiler\V1\Assemble|null $var)
    {
        $this->assemble = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .orm.compiler.v1.KeyReference parent_keys = 13;</code>
     * @return RepeatedField<\Orm\Compiler\V1\KeyReference>
     */
    public function getParentKeys()
    {
        return $this->parent_keys;
    }

    /**
     * Generated from protobuf field <code>repeated .orm.compiler.v1.KeyReference parent_keys = 13;</code>
     * @param \Orm\Compiler\V1\KeyReference[] $var
     * @return $this
     */
    public function setParentKeys(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Orm\Compiler\V1\KeyReference::class);
        $this->parent_keys = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .orm.compiler.v1.KeyReference child_keys = 14;</code>
     * @return RepeatedField<\Orm\Compiler\V1\KeyReference>
     */
    public function getChildKeys()
    {
        return $this->child_keys;
    }

    /**
     * Generated from protobuf field <code>repeated .orm.compiler.v1.KeyReference child_keys = 14;</code>
     * @param \Orm\Compiler\V1\KeyReference[] $var
     * @return $this
     */
    public function setChildKeys(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Orm\Compiler\V1\KeyReference::class);
        $this->child_keys = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .orm.compiler.v1.KeyReference key = 15;</code>
     * @return RepeatedField<\Orm\Compiler\V1\KeyReference>
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>repeated .orm.compiler.v1.KeyReference key = 15;</code>
     * @param \Orm\Compiler\V1\KeyReference[] $var
     * @return $this
     */
    public function setKey(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Orm\Compiler\V1\KeyReference::class);
        $this->key = $arr;

        return $this;
    }

}
