<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/orm/compiler/v1/compiler.proto

namespace Orm\Compiler\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>orm.compiler.v1.CompileRequest</code>
 */
class CompileRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 ir_version = 1;</code>
     */
    protected $ir_version = 0;
    /**
     * Generated from protobuf field <code>string schema_hash = 2;</code>
     */
    protected $schema_hash = '';
    /**
     * Generated from protobuf field <code>.orm.compiler.v1.QueryKind kind = 3;</code>
     */
    protected $kind = 0;
    /**
     * Generated from protobuf field <code>.orm.compiler.v1.QueryNode root = 4;</code>
     */
    protected $root = null;
    /**
     * Generated from protobuf field <code>repeated .orm.compiler.v1.Assignment set = 5;</code>
     */
    private $set;
    /**
     * Generated from protobuf field <code>repeated .orm.compiler.v1.Assignment on_duplicate = 6;</code>
     */
    private $on_duplicate;
    /**
     * Generated from protobuf field <code>.orm.compiler.v1.Optimistic optimistic = 7;</code>
     */
    protected $optimistic = null;
    /**
     * Generated from protobuf field <code>.orm.compiler.v1.Raw raw = 8;</code>
     */
    protected $raw = null;
    /**
     * Generated from protobuf field <code>uint32 parameter_count = 9;</code>
     */
    protected $parameter_count = 0;
    /**
     * Generated from protobuf field <code>string aggregate = 10;</code>
     */
    protected $aggregate = '';
    /**
     * Generated from protobuf field <code>bool debug = 11;</code>
     */
    protected $debug = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $ir_version
     *     @type string $schema_hash
     *     @type int $kind
     *     @type \Orm\Compiler\V1\QueryNode $root
     *     @type \Orm\Compiler\V1\Assignment[] $set
     *     @type \Orm\Compiler\V1\Assignment[] $on_duplicate
     *     @type \Orm\Compiler\V1\Optimistic $optimistic
     *     @type \Orm\Compiler\V1\Raw $raw
     *     @type int $parameter_count
     *     @type string $aggregate
     *     @type bool $debug
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Orm\Compiler\V1\Compiler::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 ir_version = 1;</code>
     * @return int
     */
    public function getIrVersion()
    {
        return $this->ir_version;
    }

    /**
     * Generated from protobuf field <code>uint32 ir_version = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setIrVersion(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->ir_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string schema_hash = 2;</code>
     * @return string
     */
    public function getSchemaHash()
    {
        return $this->schema_hash;
    }

    /**
     * Generated from protobuf field <code>string schema_hash = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSchemaHash(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->schema_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.orm.compiler.v1.QueryKind kind = 3;</code>
     * @return int one of the values in {@see \Orm\Compiler\V1\QueryKind}
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * Generated from protobuf field <code>.orm.compiler.v1.QueryKind kind = 3;</code>
     * @param int $var one of the values in {@see \Orm\Compiler\V1\QueryKind}
     * @return $this
     */
    public function setKind(int $var)
    {
        GPBUtil::checkEnum($var, \Orm\Compiler\V1\QueryKind::class);
        $this->kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.orm.compiler.v1.QueryNode root = 4;</code>
     * @return \Orm\Compiler\V1\QueryNode|null
     */
    public function getRoot()
    {
        return $this->root;
    }

    public function hasRoot()
    {
        return isset($this->root);
    }

    public function clearRoot()
    {
        unset($this->root);
    }

    /**
     * Generated from protobuf field <code>.orm.compiler.v1.QueryNode root = 4;</code>
     * @param \Orm\Compiler\V1\QueryNode $var
     * @return $this
     */
    public function setRoot(\Orm\Compiler\V1\QueryNode|null $var)
    {
        $this->root = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .orm.compiler.v1.Assignment set = 5;</code>
     * @return RepeatedField<\Orm\Compiler\V1\Assignment>
     */
    public function getSet()
    {
        return $this->set;
    }

    /**
     * Generated from protobuf field <code>repeated .orm.compiler.v1.Assignment set = 5;</code>
     * @param \Orm\Compiler\V1\Assignment[] $var
     * @return $this
     */
    public function setSet(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Orm\Compiler\V1\Assignment::class);
        $this->set = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .orm.compiler.v1.Assignment on_duplicate = 6;</code>
     * @return RepeatedField<\Orm\Compiler\V1\Assignment>
     */
    public function getOnDuplicate()
    {
        return $this->on_duplicate;
    }

    /**
     * Generated from protobuf field <code>repeated .orm.compiler.v1.Assignment on_duplicate = 6;</code>
     * @param \Orm\Compiler\V1\Assignment[] $var
     * @return $this
     */
    public function setOnDuplicate(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Orm\Compiler\V1\Assignment::class);
        $this->on_duplicate = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.orm.compiler.v1.Optimistic optimistic = 7;</code>
     * @return \Orm\Compiler\V1\Optimistic|null
     */
    public function getOptimistic()
    {
        return $this->optimistic;
    }

    public function hasOptimistic()
    {
        return isset($this->optimistic);
    }

    public function clearOptimistic()
    {
        unset($this->optimistic);
    }

    /**
     * Generated from protobuf field <code>.orm.compiler.v1.Optimistic optimistic = 7;</code>
     * @param \Orm\Compiler\V1\Optimistic $var
     * @return $this
     */
    public function setOptimistic(\Orm\Compiler\V1\Optimistic|null $var)
    {
        $this->optimistic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.orm.compiler.v1.Raw raw = 8;</code>
     * @return \Orm\Compiler\V1\Raw|null
     */
    public function getRaw()
    {
        return $this->raw;
    }

    public function hasRaw()
    {
        return isset($this->raw);
    }

    public function clearRaw()
    {
        unset($this->raw);
    }

    /**
     * Generated from protobuf field <code>.orm.compiler.v1.Raw raw = 8;</code>
     * @param \Orm\Compiler\V1\Raw $var
     * @return $this
     */
    public function setRaw(\Orm\Compiler\V1\Raw|null $var)
    {
        $this->raw = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 parameter_count = 9;</code>
     * @return int
     */
    public function getParameterCount()
    {
        return $this->parameter_count;
    }

    /**
     * Generated from protobuf field <code>uint32 parameter_count = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setParameterCount(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->parameter_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string aggregate = 10;</code>
     * @return string
     */
    public function getAggregate()
    {
        return $this->aggregate;
    }

    /**
     * Generated from protobuf field <code>string aggregate = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setAggregate(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->aggregate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool debug = 11;</code>
     * @return bool
     */
    public function getDebug()
    {
        return $this->debug;
    }

    /**
     * Generated from protobuf field <code>bool debug = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setDebug(bool $var)
    {
        $this->debug = $var;

        return $this;
    }

}
