<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/orm/compiler/v1/compiler.proto

namespace Orm\Compiler\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>orm.compiler.v1.GroupExpression</code>
 */
class GroupExpression extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string expression = 1;</code>
     */
    protected $expression = '';
    /**
     * Generated from protobuf field <code>string alias = 2;</code>
     */
    protected $alias = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $expression
     *     @type string $alias
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Orm\Compiler\V1\Compiler::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string expression = 1;</code>
     * @return string
     */
    public function getExpression()
    {
        return $this->expression;
    }

    /**
     * Generated from protobuf field <code>string expression = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setExpression(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->expression = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string alias = 2;</code>
     * @return string
     */
    public function getAlias()
    {
        return $this->alias;
    }

    /**
     * Generated from protobuf field <code>string alias = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAlias(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->alias = $var;

        return $this;
    }

}
