<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/orm/compiler/v1/compiler.proto

namespace Orm\Compiler\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>orm.compiler.v1.Group</code>
 */
class Group extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string connector = 1;</code>
     */
    protected $connector = '';
    /**
     * Generated from protobuf field <code>repeated .orm.compiler.v1.Item items = 2;</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $connector
     *     @type \Orm\Compiler\V1\Item[] $items
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Orm\Compiler\V1\Compiler::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string connector = 1;</code>
     * @return string
     */
    public function getConnector()
    {
        return $this->connector;
    }

    /**
     * Generated from protobuf field <code>string connector = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setConnector(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->connector = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .orm.compiler.v1.Item items = 2;</code>
     * @return RepeatedField<\Orm\Compiler\V1\Item>
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .orm.compiler.v1.Item items = 2;</code>
     * @param \Orm\Compiler\V1\Item[] $var
     * @return $this
     */
    public function setItems(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Orm\Compiler\V1\Item::class);
        $this->items = $arr;

        return $this;
    }

}
