<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/orm/compiler/v1/compiler.proto

namespace Orm\Compiler\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>orm.compiler.v1.Navigation</code>
 */
class Navigation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string connector = 1;</code>
     */
    protected $connector = '';
    /**
     * Generated from protobuf field <code>string relation = 2;</code>
     */
    protected $relation = '';
    /**
     * Generated from protobuf field <code>.orm.compiler.v1.Group group = 3;</code>
     */
    protected $group = null;
    /**
     * Generated from protobuf field <code>string mode = 4;</code>
     */
    protected $mode = '';
    /**
     * Generated from protobuf field <code>string count_operator = 5;</code>
     */
    protected $count_operator = '';
    /**
     * Generated from protobuf field <code>optional uint32 count_parameter = 6;</code>
     */
    protected $count_parameter = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $connector
     *     @type string $relation
     *     @type \Orm\Compiler\V1\Group $group
     *     @type string $mode
     *     @type string $count_operator
     *     @type int $count_parameter
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Orm\Compiler\V1\Compiler::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string connector = 1;</code>
     * @return string
     */
    public function getConnector()
    {
        return $this->connector;
    }

    /**
     * Generated from protobuf field <code>string connector = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setConnector(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->connector = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string relation = 2;</code>
     * @return string
     */
    public function getRelation()
    {
        return $this->relation;
    }

    /**
     * Generated from protobuf field <code>string relation = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRelation(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->relation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.orm.compiler.v1.Group group = 3;</code>
     * @return \Orm\Compiler\V1\Group|null
     */
    public function getGroup()
    {
        return $this->group;
    }

    public function hasGroup()
    {
        return isset($this->group);
    }

    public function clearGroup()
    {
        unset($this->group);
    }

    /**
     * Generated from protobuf field <code>.orm.compiler.v1.Group group = 3;</code>
     * @param \Orm\Compiler\V1\Group $var
     * @return $this
     */
    public function setGroup(\Orm\Compiler\V1\Group|null $var)
    {
        $this->group = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mode = 4;</code>
     * @return string
     */
    public function getMode()
    {
        return $this->mode;
    }

    /**
     * Generated from protobuf field <code>string mode = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMode(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->mode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string count_operator = 5;</code>
     * @return string
     */
    public function getCountOperator()
    {
        return $this->count_operator;
    }

    /**
     * Generated from protobuf field <code>string count_operator = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCountOperator(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->count_operator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 count_parameter = 6;</code>
     * @return int
     */
    public function getCountParameter()
    {
        return isset($this->count_parameter) ? $this->count_parameter : 0;
    }

    public function hasCountParameter()
    {
        return isset($this->count_parameter);
    }

    public function clearCountParameter()
    {
        unset($this->count_parameter);
    }

    /**
     * Generated from protobuf field <code>optional uint32 count_parameter = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setCountParameter(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->count_parameter = $var;

        return $this;
    }

}
