<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/orm/compiler/v1/compiler.proto

namespace Orm\Compiler\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>orm.compiler.v1.Order</code>
 */
class Order extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string column = 1;</code>
     */
    protected $column = '';
    /**
     * Generated from protobuf field <code>string expression = 2;</code>
     */
    protected $expression = '';
    /**
     * Generated from protobuf field <code>bool descending = 3;</code>
     */
    protected $descending = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $column
     *     @type string $expression
     *     @type bool $descending
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Orm\Compiler\V1\Compiler::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string column = 1;</code>
     * @return string
     */
    public function getColumn()
    {
        return $this->column;
    }

    /**
     * Generated from protobuf field <code>string column = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setColumn(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->column = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string expression = 2;</code>
     * @return string
     */
    public function getExpression()
    {
        return $this->expression;
    }

    /**
     * Generated from protobuf field <code>string expression = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setExpression(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->expression = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool descending = 3;</code>
     * @return bool
     */
    public function getDescending()
    {
        return $this->descending;
    }

    /**
     * Generated from protobuf field <code>bool descending = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setDescending(bool $var)
    {
        $this->descending = $var;

        return $this;
    }

}
