<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/orm/compiler/v1/compiler.proto

namespace Orm\Compiler\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>orm.compiler.v1.Predicate</code>
 */
class Predicate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string connector = 1;</code>
     */
    protected $connector = '';
    /**
     * Generated from protobuf field <code>string column = 2;</code>
     */
    protected $column = '';
    /**
     * Generated from protobuf field <code>string operator = 3;</code>
     */
    protected $operator = '';
    /**
     * Generated from protobuf field <code>optional uint32 parameter = 4;</code>
     */
    protected $parameter = null;
    /**
     * Generated from protobuf field <code>repeated uint32 parameters = 5;</code>
     */
    private $parameters;
    /**
     * Generated from protobuf field <code>.orm.compiler.v1.ColumnReference reference = 6;</code>
     */
    protected $reference = null;
    /**
     * Generated from protobuf field <code>string expression = 7;</code>
     */
    protected $expression = '';
    /**
     * Generated from protobuf field <code>repeated string match_columns = 8;</code>
     */
    private $match_columns;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $connector
     *     @type string $column
     *     @type string $operator
     *     @type int $parameter
     *     @type int[] $parameters
     *     @type \Orm\Compiler\V1\ColumnReference $reference
     *     @type string $expression
     *     @type string[] $match_columns
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Orm\Compiler\V1\Compiler::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string connector = 1;</code>
     * @return string
     */
    public function getConnector()
    {
        return $this->connector;
    }

    /**
     * Generated from protobuf field <code>string connector = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setConnector(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->connector = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string column = 2;</code>
     * @return string
     */
    public function getColumn()
    {
        return $this->column;
    }

    /**
     * Generated from protobuf field <code>string column = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setColumn(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->column = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string operator = 3;</code>
     * @return string
     */
    public function getOperator()
    {
        return $this->operator;
    }

    /**
     * Generated from protobuf field <code>string operator = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOperator(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->operator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 parameter = 4;</code>
     * @return int
     */
    public function getParameter()
    {
        return isset($this->parameter) ? $this->parameter : 0;
    }

    public function hasParameter()
    {
        return isset($this->parameter);
    }

    public function clearParameter()
    {
        unset($this->parameter);
    }

    /**
     * Generated from protobuf field <code>optional uint32 parameter = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setParameter(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->parameter = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 parameters = 5;</code>
     * @return RepeatedField<int>
     */
    public function getParameters()
    {
        return $this->parameters;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 parameters = 5;</code>
     * @param int[] $var
     * @return $this
     */
    public function setParameters(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->parameters = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.orm.compiler.v1.ColumnReference reference = 6;</code>
     * @return \Orm\Compiler\V1\ColumnReference|null
     */
    public function getReference()
    {
        return $this->reference;
    }

    public function hasReference()
    {
        return isset($this->reference);
    }

    public function clearReference()
    {
        unset($this->reference);
    }

    /**
     * Generated from protobuf field <code>.orm.compiler.v1.ColumnReference reference = 6;</code>
     * @param \Orm\Compiler\V1\ColumnReference $var
     * @return $this
     */
    public function setReference(\Orm\Compiler\V1\ColumnReference|null $var)
    {
        $this->reference = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string expression = 7;</code>
     * @return string
     */
    public function getExpression()
    {
        return $this->expression;
    }

    /**
     * Generated from protobuf field <code>string expression = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setExpression(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->expression = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string match_columns = 8;</code>
     * @return RepeatedField<string>
     */
    public function getMatchColumns()
    {
        return $this->match_columns;
    }

    /**
     * Generated from protobuf field <code>repeated string match_columns = 8;</code>
     * @param string[] $var
     * @return $this
     */
    public function setMatchColumns(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->match_columns = $arr;

        return $this;
    }

}
