<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/orm/compiler/v1/compiler.proto

namespace Orm\Compiler\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>orm.compiler.v1.QueryKind</code>
 */
class QueryKind
{
    /**
     * Generated from protobuf enum <code>QUERY_KIND_UNSPECIFIED = 0;</code>
     */
    const QUERY_KIND_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>QUERY_KIND_ONE = 1;</code>
     */
    const QUERY_KIND_ONE = 1;
    /**
     * Generated from protobuf enum <code>QUERY_KIND_ALL = 2;</code>
     */
    const QUERY_KIND_ALL = 2;
    /**
     * Generated from protobuf enum <code>QUERY_KIND_COUNT = 3;</code>
     */
    const QUERY_KIND_COUNT = 3;
    /**
     * Generated from protobuf enum <code>QUERY_KIND_GROUP_COUNT = 4;</code>
     */
    const QUERY_KIND_GROUP_COUNT = 4;
    /**
     * Generated from protobuf enum <code>QUERY_KIND_COUNT_DISTINCT = 5;</code>
     */
    const QUERY_KIND_COUNT_DISTINCT = 5;
    /**
     * Generated from protobuf enum <code>QUERY_KIND_SUM = 6;</code>
     */
    const QUERY_KIND_SUM = 6;
    /**
     * Generated from protobuf enum <code>QUERY_KIND_AVG = 7;</code>
     */
    const QUERY_KIND_AVG = 7;
    /**
     * Generated from protobuf enum <code>QUERY_KIND_MIN = 8;</code>
     */
    const QUERY_KIND_MIN = 8;
    /**
     * Generated from protobuf enum <code>QUERY_KIND_MAX = 9;</code>
     */
    const QUERY_KIND_MAX = 9;
    /**
     * Generated from protobuf enum <code>QUERY_KIND_PAGINATE = 10;</code>
     */
    const QUERY_KIND_PAGINATE = 10;
    /**
     * Generated from protobuf enum <code>QUERY_KIND_INSERT = 11;</code>
     */
    const QUERY_KIND_INSERT = 11;
    /**
     * Generated from protobuf enum <code>QUERY_KIND_UPDATE = 12;</code>
     */
    const QUERY_KIND_UPDATE = 12;
    /**
     * Generated from protobuf enum <code>QUERY_KIND_DELETE = 13;</code>
     */
    const QUERY_KIND_DELETE = 13;
    /**
     * Generated from protobuf enum <code>QUERY_KIND_RAW = 14;</code>
     */
    const QUERY_KIND_RAW = 14;

    private static $valueToName = [
        self::QUERY_KIND_UNSPECIFIED => 'QUERY_KIND_UNSPECIFIED',
        self::QUERY_KIND_ONE => 'QUERY_KIND_ONE',
        self::QUERY_KIND_ALL => 'QUERY_KIND_ALL',
        self::QUERY_KIND_COUNT => 'QUERY_KIND_COUNT',
        self::QUERY_KIND_GROUP_COUNT => 'QUERY_KIND_GROUP_COUNT',
        self::QUERY_KIND_COUNT_DISTINCT => 'QUERY_KIND_COUNT_DISTINCT',
        self::QUERY_KIND_SUM => 'QUERY_KIND_SUM',
        self::QUERY_KIND_AVG => 'QUERY_KIND_AVG',
        self::QUERY_KIND_MIN => 'QUERY_KIND_MIN',
        self::QUERY_KIND_MAX => 'QUERY_KIND_MAX',
        self::QUERY_KIND_PAGINATE => 'QUERY_KIND_PAGINATE',
        self::QUERY_KIND_INSERT => 'QUERY_KIND_INSERT',
        self::QUERY_KIND_UPDATE => 'QUERY_KIND_UPDATE',
        self::QUERY_KIND_DELETE => 'QUERY_KIND_DELETE',
        self::QUERY_KIND_RAW => 'QUERY_KIND_RAW',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}
