// ormgen ddl: manifest → CREATE TABLE statements for one dialect (docs/dialects.md).
//
//	ormgen ddl --schema schema/schema.json --dialect mysql|postgres|sqlite --out bench/sql/battle.pg.sql
//
// Types come from the canonical manifest types (plus the raw MySQL type where it
// carries precision); indexes, unique keys and fulltext indexes are emitted as the
// dialect supports them. Data seeding stays with the bench scripts.
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/polyspec/orm/engine/schema"
)

func ddlCmd(args []string) {
	fs := flag.NewFlagSet("ddl", flag.ExitOnError)
	schemaPath := fs.String("schema", "", "schema.json (required)")
	dialect := fs.String("dialect", "mysql", "mysql|postgres|sqlite")
	out := fs.String("out", "", "output file (required)")
	fs.Parse(args)
	if *schemaPath == "" || *out == "" {
		fmt.Fprintln(os.Stderr, "usage: ormgen ddl --schema schema/schema.json --dialect mysql|postgres|sqlite --out <file.sql>")
		os.Exit(2)
	}
	js, err := os.ReadFile(*schemaPath)
	if err != nil {
		fail(err)
	}
	m, err := schema.Load(js)
	if err != nil {
		fail(err)
	}
	text, err := renderDDL(m, *dialect)
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(*out, []byte(text), 0o644); err != nil {
		fail(err)
	}
	fmt.Fprintf(os.Stderr, "ormgen: %d tables (%s) → %s\n", len(m.Order), *dialect, *out)
}

func renderDDL(m *schema.Manifest, dialect string) (string, error) {
	q := func(s string) string { return "`" + s + "`" }
	if dialect != "mysql" {
		q = func(s string) string { return `"` + s + `"` }
	}
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("-- generated by ormgen ddl (%s) from schema_hash %s\n", dialect, m.SchemaHash))
	for _, name := range m.Order {
		e := m.Entities[name]
		sb.WriteString(fmt.Sprintf("\nDROP TABLE IF EXISTS %s;\nCREATE TABLE %s (\n", q(e.Table), q(e.Table)))
		var lines []string
		for _, c := range e.Columns {
			t, err := ddlType(c, dialect)
			if err != nil {
				return "", fmt.Errorf("%s.%s: %w", e.Table, c.Name, err)
			}
			line := "  " + q(c.Name) + " " + t
			if !c.Nullable {
				line += " NOT NULL"
			}
			if c.Default != nil {
				switch {
				case *c.Default == "now" && dialect == "sqlite":
					// text timestamps with six fraction digits, the form the executor binds and compares
					line += " DEFAULT (strftime('%Y-%m-%d %H:%M:%f', 'now') || '000')"
				case *c.Default == "now":
					line += " DEFAULT CURRENT_TIMESTAMP"
					if dialect == "mysql" && c.Precision > 0 {
						line += fmt.Sprintf("(%d)", c.Precision)
					}
				case *c.Default == "null":
					line += " DEFAULT NULL"
				case isNumber(*c.Default) && c.Type == "bool" && dialect == "postgres":
					if *c.Default == "0" {
						line += " DEFAULT false"
					} else {
						line += " DEFAULT true"
					}
				case isNumber(*c.Default):
					line += " DEFAULT " + *c.Default
				default:
					line += " DEFAULT '" + strings.Trim(*c.Default, "'") + "'"
				}
			}
			if c.OnUpdate && dialect == "mysql" {
				line += " ON UPDATE CURRENT_TIMESTAMP"
				if c.Precision > 0 {
					line += fmt.Sprintf("(%d)", c.Precision)
				}
			}
			if c.Auto && dialect == "mysql" {
				line += " AUTO_INCREMENT"
			}
			if c.Auto && dialect == "postgres" {
				line += " GENERATED BY DEFAULT AS IDENTITY"
			}
			lines = append(lines, line)
		}
		pk := make([]string, len(e.PK))
		for i, c := range e.PK {
			pk[i] = q(c)
		}
		if dialect == "sqlite" && len(e.PK) == 1 && e.Auto == e.PK[0] {
			// SQLite: the rowid alias must be declared inline
			for i, l := range lines {
				if strings.HasPrefix(l, "  "+q(e.PK[0])+" ") {
					lines[i] = "  " + q(e.PK[0]) + " INTEGER PRIMARY KEY AUTOINCREMENT"
				}
			}
		} else {
			lines = append(lines, "  PRIMARY KEY ("+strings.Join(pk, ", ")+")")
		}
		for _, uk := range e.Unique {
			lines = append(lines, "  UNIQUE ("+joinQuoted(uk, q)+")")
		}
		if dialect == "mysql" {
			for ixName, cols := range e.Indexes {
				lines = append(lines, "  KEY "+q(ixName)+" ("+joinQuoted(cols, q)+")")
			}
			for _, cols := range e.Fulltext {
				lines = append(lines, "  FULLTEXT KEY "+q("ft_"+strings.Join(cols, "_"))+" ("+joinQuoted(cols, q)+")")
			}
		}
		sb.WriteString(strings.Join(lines, ",\n") + "\n)")
		if dialect == "mysql" {
			sb.WriteString(" ENGINE=InnoDB DEFAULT CHARSET=utf8mb4")
		}
		sb.WriteString(";\n")
		if dialect != "mysql" {
			for ixName, cols := range e.Indexes {
				sb.WriteString(fmt.Sprintf("CREATE INDEX %s ON %s (%s);\n", q(e.Table+"_"+ixName), q(e.Table), joinQuoted(cols, q)))
			}
			if dialect == "postgres" {
				for _, cols := range e.Fulltext {
					doc := make([]string, len(cols))
					for i, c := range cols {
						doc[i] = "coalesce(" + q(c) + ", '')"
					}
					sb.WriteString(fmt.Sprintf("CREATE INDEX %s ON %s USING GIN (to_tsvector('simple', %s));\n", q(e.Table+"_ft_"+strings.Join(cols, "_")), q(e.Table), strings.Join(doc, " || ' ' || ")))
				}
			}
		}
	}
	return sb.String(), nil
}

// renderCreateDDL is the apply-safe form used by migrate. It never drops a
// table and makes both tables and standalone indexes idempotent.
func renderCreateDDL(m *schema.Manifest, dialect string) (string, error) {
	s, err := renderDDL(m, dialect)
	if err != nil {
		return "", err
	}
	lines := strings.Split(s, "\n")
	out := make([]string, 0, len(lines))
	for _, line := range lines {
		if strings.HasPrefix(line, "DROP TABLE IF EXISTS ") {
			continue
		}
		line = strings.Replace(line, "CREATE TABLE `", "CREATE TABLE IF NOT EXISTS `", 1)
		line = strings.Replace(line, `CREATE TABLE "`, `CREATE TABLE IF NOT EXISTS "`, 1)
		line = strings.Replace(line, "CREATE INDEX `", "CREATE INDEX IF NOT EXISTS `", 1)
		line = strings.Replace(line, `CREATE INDEX "`, `CREATE INDEX IF NOT EXISTS "`, 1)
		out = append(out, line)
	}
	return strings.Join(out, "\n"), nil
}

func joinQuoted(cols []string, q func(string) string) string {
	out := make([]string, len(cols))
	for i, c := range cols {
		out[i] = q(c)
	}
	return strings.Join(out, ", ")
}

// ddlType maps a canonical column to the dialect's storage type. The raw MySQL
// type is used for MySQL so precision/length survive; the others map canonically.
func ddlType(c *schema.Col, dialect string) (string, error) {
	if dialect == "mysql" && c.Raw != "" {
		t := strings.ReplaceAll(c.Raw, "_", ",")
		if c.Unsigned && !strings.Contains(t, "unsigned") {
			t += " unsigned"
		}
		return t, nil
	}
	prec := func(n int) string {
		if n > 0 {
			return fmt.Sprintf("(%d)", n)
		}
		return ""
	}
	switch dialect {
	case "postgres":
		switch c.Type {
		case "i32":
			return "integer", nil
		case "i64":
			return "bigint", nil
		case "f64":
			return "double precision", nil
		case "decimal":
			return fmt.Sprintf("numeric(%d,%d)", c.Precision, c.Scale), nil
		case "bool":
			return "boolean", nil
		case "string", "enum":
			if c.Len > 0 {
				return fmt.Sprintf("varchar(%d)", c.Len), nil
			}
			return "text", nil
		case "text":
			return "text", nil
		case "bytes":
			return "bytea", nil
		case "date":
			return "date", nil
		case "time":
			return "time", nil
		case "datetime":
			return "timestamp" + prec(c.Precision), nil
		case "json":
			return "jsonb", nil
		case "inet":
			return "inet", nil
		}
	case "sqlite":
		switch c.Type {
		case "i32", "i64", "bool":
			return "INTEGER", nil
		case "f64", "decimal":
			return "REAL", nil
		case "bytes", "inet":
			return "BLOB", nil
		default:
			return "TEXT", nil
		}
	}
	return "", fmt.Errorf("no %s type for %s", dialect, c.Type)
}

// ddlColumn renders one column without table-level constraints. Migration
// generation uses the same type mapping as full DDL generation.
func ddlColumn(c *schema.Col, dialect string, quote func(string) string) (string, error) {
	t, err := ddlType(c, dialect)
	if err != nil {
		return "", err
	}
	line := quote(c.Name) + " " + t
	if !c.Nullable {
		line += " NOT NULL"
	}
	if c.Default != nil {
		switch {
		case *c.Default == "now" && dialect == "sqlite":
			line += " DEFAULT (strftime('%Y-%m-%d %H:%M:%f', 'now') || '000')"
		case *c.Default == "now":
			line += " DEFAULT CURRENT_TIMESTAMP"
			if dialect == "mysql" && c.Precision > 0 {
				line += fmt.Sprintf("(%d)", c.Precision)
			}
		case *c.Default == "null":
			line += " DEFAULT NULL"
		case isNumber(*c.Default) && c.Type == "bool" && dialect == "postgres":
			if *c.Default == "0" {
				line += " DEFAULT false"
			} else {
				line += " DEFAULT true"
			}
		case isNumber(*c.Default):
			line += " DEFAULT " + *c.Default
		default:
			line += " DEFAULT '" + strings.Trim(*c.Default, "'") + "'"
		}
	}
	if c.OnUpdate && dialect == "mysql" {
		line += " ON UPDATE CURRENT_TIMESTAMP"
		if c.Precision > 0 {
			line += fmt.Sprintf("(%d)", c.Precision)
		}
	}
	if c.Auto && dialect == "mysql" {
		line += " AUTO_INCREMENT"
	}
	if c.Auto && dialect == "postgres" {
		line += " GENERATED BY DEFAULT AS IDENTITY"
	}
	return line, nil
}
