// ormgen ddl: manifest → CREATE TABLE statements for one dialect (docs/dialects.md).
//
//	ormgen ddl --schema schema/schema.json --dialect mysql|postgres|sqlite --out bench/sql/battle.pg.sql
//
// Types come from the canonical manifest types (plus the raw MySQL type where it
// carries precision); indexes, unique keys and fulltext indexes are emitted as the
// dialect supports them. Data seeding stays with the bench scripts.
package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/polyspec/orm/engine/schema"
)

func ddlCmd(args []string) {
	fs := flag.NewFlagSet("ddl", flag.ExitOnError)
	schemaPath := fs.String("schema", "", "schema.json (required)")
	dialect := fs.String("dialect", "mysql", "mysql|postgres|sqlite")
	out := fs.String("out", "", "output file (required)")
	fs.Parse(args)
	if *schemaPath == "" || *out == "" {
		fmt.Fprintln(os.Stderr, "usage: ormgen ddl --schema schema/schema.json --dialect mysql|postgres|sqlite --out <file.sql>")
		os.Exit(2)
	}
	m, err := loadSchemaSource(*schemaPath, *dialect)
	if err != nil {
		fail(err)
	}
	text, err := renderDDL(m, *dialect)
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(*out, []byte(text), 0o644); err != nil {
		fail(err)
	}
	fmt.Fprintf(os.Stderr, "ormgen: %d tables (%s) → %s\n", len(m.Order), *dialect, *out)
}

func renderDDL(m *schema.Manifest, dialect string) (string, error) {
	q := func(s string) string { return quoteQualified("`", s) }
	if dialect != "mysql" {
		q = func(s string) string { return quoteQualified(`"`, ddlTable(s, dialect)) }
	}
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("-- generated by ormgen ddl (%s) from schema_hash %s\n", dialect, m.SchemaHash))
	metadata, err := manifestMetadata(m)
	if err != nil {
		return "", fmt.Errorf("encode schema metadata: %w", err)
	}
	sb.WriteString(metadata)
	if dialect == "sqlite" {
		sb.WriteString("CREATE TABLE IF NOT EXISTS orm_schema_comments (table_name TEXT NOT NULL, column_name TEXT NOT NULL, comment TEXT NOT NULL, PRIMARY KEY (table_name, column_name));\n")
	}
	if dialect == "postgres" {
		for _, name := range ddlSchemas(m) {
			sb.WriteString("CREATE SCHEMA IF NOT EXISTS " + q(name) + ";\n")
		}
	}
	order, err := ddlEntityOrder(m)
	if err != nil {
		return "", err
	}
	for i := len(order) - 1; i >= 0; i-- {
		e := m.Entities[order[i]]
		sb.WriteString(fmt.Sprintf("\nDROP TABLE IF EXISTS %s;\n", q(ddlTable(e.Table, dialect))))
	}
	position := make(map[string]int, len(order))
	for i, name := range order {
		position[name] = i
	}
	type deferredForeignKey struct {
		table string
		fk    diffForeignKey
	}
	var deferred []deferredForeignKey
	for current, name := range order {
		e := m.Entities[name]
		sb.WriteString(fmt.Sprintf("\nCREATE TABLE %s (\n", q(ddlTable(e.Table, dialect))))
		var lines []string
		for _, c := range e.Columns {
			t, err := ddlType(c, dialect)
			if err != nil {
				return "", fmt.Errorf("%s.%s: %w", e.Table, c.Name, err)
			}
			line := "  " + q(c.Name) + " " + t
			if !c.Nullable {
				line += " NOT NULL"
			}
			if c.Default != nil {
				switch {
				case *c.Default == "now" && dialect == "sqlite":
					// text timestamps with six fraction digits, the form the executor binds and compares
					line += " DEFAULT (strftime('%Y-%m-%d %H:%M:%f', 'now') || '000')"
				case *c.Default == "now":
					line += " DEFAULT CURRENT_TIMESTAMP"
					if dialect == "mysql" && c.Precision > 0 {
						line += fmt.Sprintf("(%d)", c.Precision)
					}
				case *c.Default == "null":
					line += " DEFAULT NULL"
				case isNumber(*c.Default) && c.Type == "bool" && dialect == "postgres":
					if *c.Default == "0" {
						line += " DEFAULT false"
					} else {
						line += " DEFAULT true"
					}
				case isNumber(*c.Default):
					line += " DEFAULT " + *c.Default
				default:
					line += " DEFAULT '" + strings.Trim(*c.Default, "'") + "'"
				}
			}
			if c.OnUpdate && dialect == "mysql" {
				line += " ON UPDATE CURRENT_TIMESTAMP"
				if c.Precision > 0 {
					line += fmt.Sprintf("(%d)", c.Precision)
				}
			}
			if c.Auto && dialect == "mysql" {
				line += " AUTO_INCREMENT"
			}
			if c.Auto && dialect == "postgres" {
				line += " GENERATED BY DEFAULT AS IDENTITY"
			}
			if c.Comment != "" && dialect == "mysql" {
				line += " COMMENT '" + sqlQuote(c.Comment) + "'"
			}
			lines = append(lines, line)
		}
		pk := make([]string, len(e.PK))
		for i, c := range e.PK {
			pk[i] = q(c)
		}
		if dialect == "sqlite" && len(e.PK) == 1 && e.Auto == e.PK[0] {
			// SQLite: the rowid alias must be declared inline
			for i, l := range lines {
				if strings.HasPrefix(l, "  "+q(e.PK[0])+" ") {
					lines[i] = "  " + q(e.PK[0]) + " INTEGER PRIMARY KEY AUTOINCREMENT"
				}
			}
		} else {
			lines = append(lines, "  PRIMARY KEY ("+strings.Join(pk, ", ")+")")
		}
		for _, uk := range e.Unique {
			lines = append(lines, "  CONSTRAINT "+q("uq_"+ddlBase(e.Table)+"_"+strings.Join(uk, "_"))+" UNIQUE ("+joinQuoted(uk, q)+")")
		}
		for _, fk := range sortedForeignKeys(m, e) {
			target, ok := foreignKeyTargetEntity(m, fk.target)
			if ok && dialect != "sqlite" && position[target.Name] > current {
				deferred = append(deferred, deferredForeignKey{table: e.Table, fk: fk})
				continue
			}
			lines = append(lines, "  "+foreignKeyClause(fk, m, dialect, q))
		}
		for _, check := range e.Checks {
			expr, err := quotedCheckExpression(check.Expr, q)
			if err != nil {
				return "", fmt.Errorf("%s check %s: %w", e.Table, check.Name, err)
			}
			lines = append(lines, "  CONSTRAINT "+q(check.Name)+" CHECK ("+expr+")")
		}
		if dialect == "mysql" {
			for _, ixName := range sortedIndexNames(e.Indexes) {
				cols := e.Indexes[ixName]
				lines = append(lines, "  KEY "+q(ixName)+" ("+joinQuoted(cols, q)+")")
			}
			for _, cols := range e.Fulltext {
				lines = append(lines, "  FULLTEXT KEY "+q("ft_"+strings.Join(cols, "_"))+" ("+joinQuoted(cols, q)+")")
			}
		}
		sb.WriteString(strings.Join(lines, ",\n") + "\n)")
		if dialect == "mysql" {
			sb.WriteString(" ENGINE=InnoDB DEFAULT CHARSET=utf8mb4")
		}
		sb.WriteString(";\n")
		if e.Comment != "" {
			if dialect == "mysql" {
				sb.WriteString("ALTER TABLE " + q(e.Table) + " COMMENT = '" + sqlQuote(e.Comment) + "';\n")
			} else if dialect == "postgres" {
				sb.WriteString("COMMENT ON TABLE " + q(e.Table) + " IS '" + sqlQuote(e.Comment) + "';\n")
			} else {
				sb.WriteString("INSERT OR REPLACE INTO orm_schema_comments (table_name, column_name, comment) VALUES ('" + sqlQuote(e.Table) + "', '', '" + sqlQuote(e.Comment) + "');\n")
			}
		}
		for _, c := range e.Columns {
			if c.Comment == "" {
				continue
			}
			if dialect == "postgres" {
				sb.WriteString("COMMENT ON COLUMN " + q(e.Table) + "." + q(c.Name) + " IS '" + sqlQuote(c.Comment) + "';\n")
			} else if dialect == "sqlite" {
				sb.WriteString("INSERT OR REPLACE INTO orm_schema_comments (table_name, column_name, comment) VALUES ('" + sqlQuote(e.Table) + "', '" + sqlQuote(c.Name) + "', '" + sqlQuote(c.Comment) + "');\n")
			}
		}
		if dialect != "mysql" {
			for _, ixName := range sortedIndexNames(e.Indexes) {
				cols := e.Indexes[ixName]
				sb.WriteString(fmt.Sprintf("CREATE INDEX %s ON %s (%s);\n", q(ddlBase(e.Table)+"_"+ixName), q(e.Table), joinQuoted(cols, q)))
			}
			if dialect == "postgres" {
				for _, cols := range e.Fulltext {
					doc := make([]string, len(cols))
					for i, c := range cols {
						doc[i] = "coalesce(" + q(c) + ", '')"
					}
					sb.WriteString(fmt.Sprintf("CREATE INDEX %s ON %s USING GIN (to_tsvector('simple', %s));\n", q(ddlBase(e.Table)+"_ft_"+strings.Join(cols, "_")), q(e.Table), strings.Join(doc, " || ' ' || ")))
				}
			}
		}
	}
	for _, item := range deferred {
		sb.WriteString("ALTER TABLE " + q(item.table) + " ADD " + foreignKeyClause(item.fk, m, dialect, q) + ";\n")
	}
	for _, entityName := range m.Immutable {
		e := m.Entities[entityName]
		if e == nil {
			continue
		}
		if dialect == "postgres" {
			function := e.Table + "_immutable_reject"
			trigger := ddlBase(e.Table) + "_immutable"
			sb.WriteString("\nCREATE OR REPLACE FUNCTION " + q(function) + "() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'immutable table: " + sqlQuote(e.Table) + "'; END; $$;\n")
			sb.WriteString("DROP TRIGGER IF EXISTS " + q(trigger) + " ON " + q(e.Table) + ";\n")
			sb.WriteString("CREATE TRIGGER " + q(trigger) + " BEFORE UPDATE OR DELETE OR TRUNCATE ON " + q(e.Table) + " FOR EACH STATEMENT EXECUTE FUNCTION " + q(function) + "();\n")
		} else if dialect == "sqlite" {
			base := ddlBase(e.Table) + "_immutable"
			for _, event := range []string{"update", "delete"} {
				trigger := base + "_" + event
				sb.WriteString("\nDROP TRIGGER IF EXISTS " + q(trigger) + ";\n")
				sb.WriteString("CREATE TRIGGER " + q(trigger) + " BEFORE " + strings.ToUpper(event) + " ON " + q(e.Table) + " BEGIN SELECT RAISE(ABORT, 'immutable table: " + sqlQuote(e.Table) + "'); END;\n")
			}
		} else {
			return "", fmt.Errorf("immutable table %s is supported only for postgres and sqlite", e.Table)
		}
	}
	return sb.String(), nil
}

func foreignKeyTargetEntity(m *schema.Manifest, target string) (*schema.Entity, bool) {
	if entity, ok := m.Entities[target]; ok {
		return entity, true
	}
	for _, entity := range m.Entities {
		if entity.Table == target {
			return entity, true
		}
	}
	return nil, false
}

func ddlTable(table, dialect string) string {
	if dialect == "sqlite" {
		parts := strings.Split(table, ".")
		return parts[len(parts)-1]
	}
	return table
}

func ddlBase(table string) string {
	parts := strings.Split(table, ".")
	return parts[len(parts)-1]
}

func ddlSchemas(m *schema.Manifest) []string {
	seen := map[string]bool{}
	var result []string
	for _, name := range m.Order {
		parts := strings.Split(m.Entities[name].Table, ".")
		if len(parts) != 2 || seen[parts[0]] {
			continue
		}
		seen[parts[0]] = true
		result = append(result, parts[0])
	}
	sort.Strings(result)
	return result
}

func quoteQualified(quote, name string) string {
	parts := strings.Split(name, ".")
	for i := range parts {
		parts[i] = quote + strings.ReplaceAll(parts[i], quote, quote+quote) + quote
	}
	return strings.Join(parts, ".")
}

func sortedIndexNames(indexes map[string][]string) []string {
	names := make([]string, 0, len(indexes))
	for name := range indexes {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// ddlEntityOrder returns a stable parent-before-child order for inline foreign
// keys. Cycles require deferred constraints, which this DDL form cannot apply
// idempotently on all supported databases.
func ddlEntityOrder(m *schema.Manifest) ([]string, error) {
	position := make(map[string]int, len(m.Order))
	for i, name := range m.Order {
		position[name] = i
	}
	names := append([]string(nil), m.Order...)
	for name := range m.Entities {
		if _, ok := position[name]; !ok {
			position[name] = len(position)
			names = append(names, name)
		}
	}
	sort.SliceStable(names, func(i, j int) bool { return position[names[i]] < position[names[j]] })
	state := map[string]uint8{}
	result := make([]string, 0, len(names))
	var visit func(string) error
	visit = func(name string) error {
		switch state[name] {
		case 1:
			return fmt.Errorf("foreign key cycle includes %s; deferred cyclic constraints are required", name)
		case 2:
			return nil
		}
		state[name] = 1
		e := m.Entities[name]
		deps := map[string]bool{}
		for _, c := range e.Columns {
			if c.Ref != nil && c.Ref.Entity != name && m.Entities[c.Ref.Entity] != nil {
				deps[c.Ref.Entity] = true
			}
		}
		for _, rel := range e.Relations {
			if rel.ForeignKey && rel.Target != name && m.Entities[rel.Target] != nil {
				deps[rel.Target] = true
			}
		}
		orderedDeps := make([]string, 0, len(deps))
		for dep := range deps {
			orderedDeps = append(orderedDeps, dep)
		}
		sort.Slice(orderedDeps, func(i, j int) bool { return position[orderedDeps[i]] < position[orderedDeps[j]] })
		for _, dep := range orderedDeps {
			if err := visit(dep); err != nil {
				return err
			}
		}
		state[name] = 2
		result = append(result, name)
		return nil
	}
	for _, name := range names {
		if err := visit(name); err != nil {
			return nil, err
		}
	}
	return result, nil
}

func relationMatchesColumnReference(e *schema.Entity, rel *schema.Rel) bool {
	if rel == nil || len(rel.Keys) == 0 {
		return false
	}
	for _, key := range rel.Keys {
		var column *schema.Col
		for _, candidate := range e.Columns {
			if candidate.Name == key.Local {
				column = candidate
				break
			}
		}
		if column == nil || column.Ref == nil || column.Ref.Entity != rel.Target || column.Ref.Column != key.Target {
			return false
		}
	}
	return true
}

func sortedForeignKeys(m *schema.Manifest, e *schema.Entity) []diffForeignKey {
	byColumn := entityForeignKeys(m, e)
	keys := make([]string, 0, len(byColumn))
	for key := range byColumn {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	out := make([]diffForeignKey, 0, len(keys))
	for _, key := range keys {
		out = append(out, byColumn[key])
	}
	return out
}

func sqlQuote(s string) string { return strings.ReplaceAll(s, "'", "''") }

// renderCreateDDL is the apply-safe form used by migrate. It never drops a
// table and makes both tables and standalone indexes idempotent.
func renderCreateDDL(m *schema.Manifest, dialect string) (string, error) {
	s, err := renderDDL(m, dialect)
	if err != nil {
		return "", err
	}
	lines := strings.Split(s, "\n")
	out := make([]string, 0, len(lines))
	for _, line := range lines {
		if strings.HasPrefix(line, "DROP TABLE IF EXISTS ") {
			continue
		}
		line = strings.Replace(line, "CREATE TABLE `", "CREATE TABLE IF NOT EXISTS `", 1)
		line = strings.Replace(line, `CREATE TABLE "`, `CREATE TABLE IF NOT EXISTS "`, 1)
		line = strings.Replace(line, "CREATE INDEX `", "CREATE INDEX IF NOT EXISTS `", 1)
		line = strings.Replace(line, `CREATE INDEX "`, `CREATE INDEX IF NOT EXISTS "`, 1)
		out = append(out, line)
	}
	return strings.Join(out, "\n"), nil
}

func joinQuoted(cols []string, q func(string) string) string {
	out := make([]string, len(cols))
	for i, c := range cols {
		out[i] = q(c)
	}
	return strings.Join(out, ", ")
}

// ddlType maps a canonical column to the dialect's storage type. The raw MySQL
// type is used for MySQL so precision/length survive; the others map canonically.
func ddlType(c *schema.Col, dialect string) (string, error) {
	if dialect == "mysql" && c.Raw != "" {
		t := strings.ReplaceAll(c.Raw, "_", ",")
		if c.Unsigned && !strings.Contains(t, "unsigned") {
			t += " unsigned"
		}
		return t, nil
	}
	prec := func(n int) string {
		if n > 0 {
			return fmt.Sprintf("(%d)", n)
		}
		return ""
	}
	switch dialect {
	case "postgres":
		switch c.Type {
		case "i32":
			return "integer", nil
		case "i64":
			return "bigint", nil
		case "f64":
			return "double precision", nil
		case "decimal":
			return fmt.Sprintf("numeric(%d,%d)", c.Precision, c.Scale), nil
		case "bool":
			return "boolean", nil
		case "string", "enum":
			if strings.EqualFold(c.Raw, "uuid") {
				return "uuid", nil
			}
			if c.Len > 0 {
				return fmt.Sprintf("varchar(%d)", c.Len), nil
			}
			return "text", nil
		case "text":
			return "text", nil
		case "bytes":
			return "bytea", nil
		case "date":
			return "date", nil
		case "time":
			return "time", nil
		case "datetime":
			return "timestamp" + prec(c.Precision) + " with time zone", nil
		case "json":
			return "jsonb", nil
		case "inet":
			return "inet", nil
		case "point":
			return "point", nil
		}
	case "sqlite":
		switch c.Type {
		case "i32", "i64", "bool":
			return "INTEGER", nil
		case "f64", "decimal":
			return "REAL", nil
		case "bytes", "inet":
			return "BLOB", nil
		case "point":
			return "TEXT", nil
		default:
			return "TEXT", nil
		}
	}
	return "", fmt.Errorf("no %s type for %s", dialect, c.Type)
}

// ddlColumn renders one column without table-level constraints. Migration
// generation uses the same type mapping as full DDL generation.
func ddlColumn(c *schema.Col, dialect string, quote func(string) string) (string, error) {
	t, err := ddlType(c, dialect)
	if err != nil {
		return "", err
	}
	line := quote(c.Name) + " " + t
	if !c.Nullable {
		line += " NOT NULL"
	}
	if c.Default != nil {
		switch {
		case *c.Default == "now" && dialect == "sqlite":
			line += " DEFAULT (strftime('%Y-%m-%d %H:%M:%f', 'now') || '000')"
		case *c.Default == "now":
			line += " DEFAULT CURRENT_TIMESTAMP"
			if dialect == "mysql" && c.Precision > 0 {
				line += fmt.Sprintf("(%d)", c.Precision)
			}
		case *c.Default == "null":
			line += " DEFAULT NULL"
		case isNumber(*c.Default) && c.Type == "bool" && dialect == "postgres":
			if *c.Default == "0" {
				line += " DEFAULT false"
			} else {
				line += " DEFAULT true"
			}
		case isNumber(*c.Default):
			line += " DEFAULT " + *c.Default
		default:
			line += " DEFAULT '" + strings.Trim(*c.Default, "'") + "'"
		}
	}
	if c.OnUpdate && dialect == "mysql" {
		line += " ON UPDATE CURRENT_TIMESTAMP"
		if c.Precision > 0 {
			line += fmt.Sprintf("(%d)", c.Precision)
		}
	}
	if c.Auto && dialect == "mysql" {
		line += " AUTO_INCREMENT"
	}
	if c.Auto && dialect == "postgres" {
		line += " GENERATED BY DEFAULT AS IDENTITY"
	}
	return line, nil
}

func quotedCheckExpression(expr string, quote func(string) string) (string, error) {
	var out strings.Builder
	for len(expr) > 0 {
		start := strings.IndexByte(expr, '`')
		if start < 0 {
			out.WriteString(expr)
			break
		}
		out.WriteString(expr[:start])
		rest := expr[start+1:]
		end := strings.IndexByte(rest, '`')
		if end < 0 {
			return "", fmt.Errorf("CHECK expression has an unterminated backtick identifier")
		}
		name := rest[:end]
		if name == "" || strings.ContainsAny(name, "`\x00") {
			return "", fmt.Errorf("CHECK expression has an invalid backtick identifier")
		}
		out.WriteString(quote(name))
		expr = rest[end+1:]
	}
	return out.String(), nil
}
