package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/polyspec/orm/engine/schema"
)

type schemaChange struct {
	sql         string
	destructive bool
}

func diffCmd(args []string) {
	fs := flag.NewFlagSet("diff", flag.ExitOnError)
	fromPath := fs.String("from", "", "previous schema.json (required)")
	toPath := fs.String("to", "", "new schema.json (required)")
	dialect := fs.String("dialect", "mysql", "mysql|postgres|sqlite")
	out := fs.String("out", "", "output file (required)")
	allow := fs.Bool("allow-destructive", false, "allow table/column removal and type changes")
	fs.Parse(args)
	if *fromPath == "" || *toPath == "" || *out == "" {
		fmt.Fprintln(os.Stderr, "usage: ormgen diff --from old.json --to new.json --dialect mysql|postgres|sqlite --out <file.sql> [--allow-destructive]")
		os.Exit(2)
	}
	from, err := loadManifestFile(*fromPath)
	if err != nil {
		fail(err)
	}
	to, err := loadManifestFile(*toPath)
	if err != nil {
		fail(err)
	}
	text, err := renderDiff(from, to, *dialect, *allow)
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(*out, []byte(text), 0o644); err != nil {
		fail(err)
	}
}

func loadManifestFile(path string) (*schema.Manifest, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	return schema.Load(b)
}

func renderDiff(from, to *schema.Manifest, dialect string, allowDestructive bool) (string, error) {
	if dialect != "mysql" && dialect != "postgres" && dialect != "sqlite" {
		return "", fmt.Errorf("unknown dialect %q", dialect)
	}
	quote := func(s string) string { return `"` + s + `"` }
	if dialect == "mysql" {
		quote = func(s string) string { return "`" + s + "`" }
	}
	changes := make([]schemaChange, 0)
	allNames := map[string]bool{}
	for n := range from.Entities {
		allNames[n] = true
	}
	for n := range to.Entities {
		allNames[n] = true
	}
	names := make([]string, 0, len(allNames))
	for n := range allNames {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, name := range names {
		oldEnt, oldOK := from.Entities[name]
		newEnt, newOK := to.Entities[name]
		switch {
		case !oldOK:
			one := &schema.Manifest{SchemaHash: to.SchemaHash, Order: []string{name}, Entities: map[string]*schema.Entity{name: newEnt}}
			create, err := renderDDL(one, dialect)
			if err != nil {
				return "", err
			}
			create = removeDropStatement(create)
			changes = append(changes, schemaChange{sql: strings.TrimSpace(create)})
		case !newOK:
			changes = append(changes, schemaChange{sql: "DROP TABLE " + quote(oldEnt.Table) + ";", destructive: true})
		default:
			if oldEnt.Table != newEnt.Table {
				return "", fmt.Errorf("table rename %s -> %s requires explicit migration", oldEnt.Table, newEnt.Table)
			}
			oldCols, newCols := map[string]*schema.Col{}, map[string]*schema.Col{}
			for _, c := range oldEnt.Columns {
				oldCols[c.Name] = c
			}
			for _, c := range newEnt.Columns {
				newCols[c.Name] = c
			}
			cols := map[string]bool{}
			for c := range oldCols {
				cols[c] = true
			}
			for c := range newCols {
				cols[c] = true
			}
			colNames := make([]string, 0, len(cols))
			for c := range cols {
				colNames = append(colNames, c)
			}
			sort.Strings(colNames)
			for _, col := range colNames {
				o, ook := oldCols[col]
				n, nok := newCols[col]
				switch {
				case !ook:
					def, err := ddlColumn(n, dialect, quote)
					if err != nil {
						return "", err
					}
					changes = append(changes, schemaChange{sql: fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s;", quote(newEnt.Table), def)})
				case !nok:
					changes = append(changes, schemaChange{sql: fmt.Sprintf("ALTER TABLE %s DROP COLUMN %s;", quote(oldEnt.Table), quote(col)), destructive: true})
				case columnChanged(o, n):
					def, err := ddlColumn(n, dialect, quote)
					if err != nil {
						return "", err
					}
					stmt, err := alterColumn(newEnt.Table, def, dialect, quote)
					if err != nil {
						return "", err
					}
					changes = append(changes, schemaChange{sql: stmt, destructive: true})
				}
			}
		}
	}
	for _, c := range changes {
		if c.destructive && !allowDestructive {
			return "", fmt.Errorf("destructive schema change requires --allow-destructive: %s", c.sql)
		}
	}
	var b strings.Builder
	fmt.Fprintf(&b, "-- generated by ormgen diff (%s) from %s to %s\n", dialect, from.SchemaHash, to.SchemaHash)
	if len(changes) == 0 {
		b.WriteString("-- no changes\n")
	}
	for _, c := range changes {
		b.WriteString(c.sql)
		b.WriteByte('\n')
	}
	return b.String(), nil
}

func removeDropStatement(s string) string {
	lines := strings.Split(s, "\n")
	var out []string
	for _, line := range lines {
		if !strings.HasPrefix(line, "DROP TABLE IF EXISTS ") && !strings.HasPrefix(line, "-- generated by") {
			out = append(out, line)
		}
	}
	return strings.Join(out, "\n")
}

func columnChanged(a, b *schema.Col) bool {
	return a.Type != b.Type || a.Raw != b.Raw || a.Nullable != b.Nullable || colDefault(a) != colDefault(b) || a.Auto != b.Auto || a.OnUpdate != b.OnUpdate || a.Unsigned != b.Unsigned || a.Len != b.Len || a.Precision != b.Precision || a.Scale != b.Scale
}

func colDefault(c *schema.Col) string {
	if c.Default == nil {
		return ""
	}
	return *c.Default
}

func alterColumn(table, def, dialect string, quote func(string) string) (string, error) {
	switch dialect {
	case "mysql":
		return fmt.Sprintf("ALTER TABLE %s MODIFY COLUMN %s;", quote(table), def), nil
	case "postgres":
		return fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s TYPE %s;", quote(table), strings.Fields(def)[0], strings.Fields(def)[1]), nil
	case "sqlite":
		return "", fmt.Errorf("sqlite does not support deterministic ALTER COLUMN; recreate the table explicitly")
	default:
		return "", fmt.Errorf("unknown dialect %q", dialect)
	}
}
