package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/polyspec/orm/engine/schema"
)

func tsType(c *schema.Col) string {
	var t string
	if len(appStyles(c)) > 0 {
		t = "unknown"
	} else {
		switch c.Type {
		case "i32", "i64", "f64", "decimal":
			t = "number"
		case "bool":
			t = "boolean"
		case "date", "datetime":
			t = "string | Date"
		case "point":
			t = "Point"
		default:
			t = "string"
		}
	}
	if c.Nullable {
		t += " | null"
	}
	return t
}

func tsPredicateType(c goCol) string {
	if len(c.Styles) > 0 {
		return "unknown"
	}
	switch c.ColType {
	case "i32", "i64", "f64", "decimal":
		return "number"
	case "bool":
		return "boolean"
	case "date", "datetime":
		return "string | Date"
	case "point":
		return "Point"
	default:
		return "string"
	}
}

func tsString(s string) string {
	return "'" + strings.NewReplacer("\\", "\\\\", "'", "\\'", "\n", "\\n", "\r", "\\r").Replace(s) + "'"
}

func tsMethod(s string) string {
	p := pascal(s)
	if p == "" {
		return p
	}
	return strings.ToLower(p[:1]) + p[1:]
}

func genTypeScript(m *schema.Manifest, outDir string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by ormgen; DO NOT EDIT.\n")
	b.WriteString("import { ColumnReference, QueryCore, WhereCore } from '../builder.js';\n")
	b.WriteString("import { Collection, Page, Row, registerRow } from '../model.js';\n")
	b.WriteString("import { registerSchemaHash } from '../registry.js';\n")
	b.WriteString("import type { Point } from '../codec.js';\n\n")
	b.WriteString("import type { AesKeyring, AesRotationStatus, StreamResult } from '../index.js';\n")
	b.WriteString("import { OrmError } from '../runtime_error.js';\n\n")
	b.WriteString("import type { ")
	for i, entity := range m.Order {
		if i > 0 {
			b.WriteString(", ")
		}
		name := pascal(entity)
		fmt.Fprintf(&b, "%sInterface, %sRowInterface", name, name)
	}
	b.WriteString(" } from './interfaces.js';\n\n")
	fmt.Fprintf(&b, "export const SCHEMA_HASH = %s;\nregisterSchemaHash(SCHEMA_HASH);\n\n", tsString(m.SchemaHash))

	for _, name := range m.Order {
		e := m.Entities[name]
		ge := buildGoEntity(m, e)
		fmt.Fprintf(&b, "export interface %sKey {", ge.Type)
		for _, key := range ge.PKCols {
			fmt.Fprintf(&b, " readonly %s:%s;", tsMethod(key.Name), tsType(e.Column(key.Name)))
		}
		b.WriteString(" }\n")
		fmt.Fprintf(&b, "export class %sRow extends Row implements %sRowInterface {\n", ge.Type, ge.Type)
		fmt.Fprintf(&b, "  public static override entity(): string { return %s; }\n", tsString(ge.Name))
		pkNames := make([]string, len(ge.PKNames))
		for i, key := range ge.PKNames {
			pkNames[i] = tsString(key)
		}
		fmt.Fprintf(&b, "  public static override primaryKeys(): readonly string[] { return [%s]; }\n", strings.Join(pkNames, ","))
		if ge.UpdatedTs != "" {
			fmt.Fprintf(&b, "  public static override versionColumn(): string { return %s; }\n", tsString(ge.UpdatedTs))
		}
		b.WriteString("  public static override columns(): Readonly<Record<string,string>> { return {")
		for i, c := range e.Columns {
			if i > 0 {
				b.WriteString(",")
			}
			kind := c.Type
			if len(appStyles(c)) > 0 {
				kind = "styled"
			}
			fmt.Fprintf(&b, "%s:%s", tsString(c.Name), tsString(kind))
		}
		b.WriteString("}; }\n")
		for i, c := range e.Columns {
			field, typ := pascal(c.Name), tsType(c)
			fmt.Fprintf(&b, "  public get%s(fallback?: %s): %s { const value=this.column(%s); return (value ?? fallback ?? null) as %s; }\n", field, typ, typ, tsString(c.Name), typ)
			if !c.Auto && !ge.Cols[i].Managed {
				styles := appStyles(c)
				if len(styles) > 0 {
					quoted := make([]string, len(styles))
					for i, style := range styles {
						quoted[i] = tsString(style)
					}
					fmt.Fprintf(&b, "  public set%s(value: %s): this { return this.setStyledColumn(%s,value,[%s]); }\n", field, typ, tsString(c.Name), strings.Join(quoted, ","))
				} else {
					fmt.Fprintf(&b, "  public set%s(value: %s): this { return this.setColumn(%s,value); }\n", field, typ, tsString(c.Name))
				}
			}
		}
		for _, rel := range ge.Rels {
			if rel.Kind == "one" {
				fmt.Fprintf(&b, "  public get%s(): %sRow | null { return this.relation(%s); }\n", rel.Method, rel.TargetType, tsString(rel.Name))
			} else {
				fmt.Fprintf(&b, "  public get%s(): Collection<%sRow> { return this.relation(%s) ?? new Collection(); }\n", rel.Method, rel.TargetType, tsString(rel.Name))
			}
		}
		b.WriteString("}\n\n")
	}

	for _, name := range m.Order {
		e := m.Entities[name]
		ge := buildGoEntity(m, e)
		pkNames := make([]string, len(ge.PKNames))
		for i, key := range ge.PKNames {
			pkNames[i] = tsString(key)
		}
		fmt.Fprintf(&b, "export class %sColumns {\n", ge.Type)
		for _, c := range e.Columns {
			fmt.Fprintf(&b, "  public static %s(): ColumnReference { return new ColumnReference(%s); }\n", tsMethod(c.Name), tsString(c.Name))
		}
		b.WriteString("}\n\n")

		fmt.Fprintf(&b, "export class %sWhere {\n  public constructor(private readonly core: WhereCore) {}\n", ge.Type)
		fmt.Fprintf(&b, "  public or(): this { this.core.or(); return this; }\n  public and(callback: (where: %sWhere) => void): this { this.core.and(core=>callback(new %sWhere(core))); return this; }\n", ge.Type, ge.Type)
		b.WriteString("  public expr(sql: string, values: readonly unknown[] = []): this { this.core.expression(sql,values); return this; }\n")
		writeTSPredicates(&b, ge, "this.core")
		for _, rel := range ge.Rels {
			fmt.Fprintf(&b, "  public %s(callback: (where: %sWhere) => void): this { this.core.navigate(%s,core=>callback(new %sWhere(core))); return this; }\n", tsMethod(rel.Name), rel.TargetType, tsString(rel.Name), rel.TargetType)
		}
		b.WriteString("}\n\n")

		fmt.Fprintf(&b, "export class %sQuery extends QueryCore implements %sInterface {\n  public constructor() { super(%s); }\n", ge.Type, ge.Type, tsString(ge.Name))
		if len(ge.AESCols) > 0 {
			fmt.Fprintf(&b, "  public aesStatus(keyring: AesKeyring): Promise<AesRotationStatus> { return this.binding.resolve().aesStatus({table:%s,primaryKeys:[%s],versionColumn:%s,columns:[]},keyring); }\n", tsString(ge.Table), strings.Join(pkNames, ","), tsString(ge.AESVersion))
			fmt.Fprintf(&b, "  public rotateAES(keyring: AesKeyring): Promise<number> { return this.binding.resolve().rotateAESRows({table:%s,primaryKeys:[%s],versionColumn:%s,columns:[", tsString(ge.Table), strings.Join(pkNames, ","), tsString(ge.AESVersion))
			for i, c := range ge.AESCols {
				if i > 0 {
					b.WriteString(",")
				}
				styles := make([]string, len(c.Styles))
				for j, style := range c.Styles {
					styles[j] = tsString(style)
				}
				fmt.Fprintf(&b, "{name:%s,styles:[%s]}", tsString(c.Name), strings.Join(styles, ","))
			}
			b.WriteString("]},keyring); }\n")
		}
		if ge.Scope != "" {
			fmt.Fprintf(&b, "  public override scope(value: %s): this { return super.scope(value); }\n", tsType(e.Column(ge.Scope)))
		}
		fmt.Fprintf(&b, "  public and(callback: (where: %sWhere) => void): this { this.whereCore().and(core=>callback(new %sWhere(core))); return this; }\n", ge.Type, ge.Type)
		fmt.Fprintf(&b, "  public on(callback: (where: %sWhere) => void): this { return this.onGroup(core=>callback(new %sWhere(core))); }\n  public where(callback: (where: %sWhere) => void): this { callback(new %sWhere(this.whereCore())); return this; }\n  public having(callback: (where: %sWhere) => void): this { return this.havingGroup(core=>callback(new %sWhere(core))); }\n", ge.Type, ge.Type, ge.Type, ge.Type, ge.Type, ge.Type)
		writeTSPredicates(&b, ge, "this")
		b.WriteString("  public expr(sql: string, values: readonly unknown[] = []): this { return this.expression(sql,values); }\n  public selectExpr(alias: string, expression: string): this { return this.selectExpression(alias,expression); }\n  public orderByExpr(expression: string, descending = false): this { return this.orderByExpression(expression,descending); }\n  public groupByExpr(expression: string, alias: string): this { return this.groupByExpression(expression,alias); }\n  public keyByFn(selector: (row: unknown) => number|string|bigint): this { return this.keyByFunction(selector); }\n")
		for _, c := range ge.Cols {
			typ := tsType(e.Column(c.Name))
			fmt.Fprintf(&b, "  public select%s(): this { return this.select(%s); }\n  public omit%s(): this { return this.omit(%s); }\n", c.Field, tsString(c.Name), c.Field, tsString(c.Name))
			fmt.Fprintf(&b, "  public orderBy%sAsc(): this { return this.orderBy(%s); }\n  public orderBy%sDesc(): this { return this.orderBy(%s,true); }\n", c.Field, tsString(c.Name), c.Field, tsString(c.Name))
			fmt.Fprintf(&b, "  public groupBy%s(): this { return this.groupBy(%s); }\n  public keyBy%s(): this { return this.keyBy(%s); }\n", c.Field, tsString(c.Name), c.Field, tsString(c.Name))
			if c.Managed {
				continue
			}
			if len(c.Styles) > 0 {
				styles := make([]string, len(c.Styles))
				for i, style := range c.Styles {
					styles[i] = tsString(style)
				}
				fmt.Fprintf(&b, "  public set%s(value: %s): this { return this.setEncoded(%s,value,[%s]); }\n  public onDuplicateSet%s(value: %s): this { return this.duplicateEncoded(%s,value,[%s]); }\n", c.Field, typ, tsString(c.Name), strings.Join(styles, ","), c.Field, typ, tsString(c.Name), strings.Join(styles, ","))
			} else {
				fmt.Fprintf(&b, "  public set%s(value: %s): this { return this.set(%s,value); }\n  public onDuplicateSet%s(value: %s): this { return this.duplicate(%s,value); }\n", c.Field, typ, tsString(c.Name), c.Field, typ, tsString(c.Name))
			}
			fmt.Fprintf(&b, "  public set%sExpr(expression: string, values: readonly unknown[] = []): this { return this.setExpression(%s,expression,values); }\n  public onDuplicateSet%sExpr(expression: string, values: readonly unknown[] = []): this { return this.duplicateExpression(%s,expression,values); }\n", c.Field, tsString(c.Name), c.Field, tsString(c.Name))
			if c.Nullable {
				fmt.Fprintf(&b, "  public set%sNull(): this { return this.setNull(%s); }\n", c.Field, tsString(c.Name))
			}
		}
		for _, c := range ge.Numeric {
			fmt.Fprintf(&b, "  public plus%s(value: number): this { return this.plus(%s,value); }\n  public minus%s(value: number): this { return this.minus(%s,value); }\n", c.Field, tsString(c.Name), c.Field, tsString(c.Name))
			fmt.Fprintf(&b, "  public onDuplicatePlus%s(value: number): this { return this.duplicatePlus(%s,value); }\n  public onDuplicateMinus%s(value: number): this { return this.duplicateMinus(%s,value); }\n", c.Field, tsString(c.Name), c.Field, tsString(c.Name))
			fmt.Fprintf(&b, "  public async sum%s(): Promise<number | null> { this.request.ir.agg=%s; const value=await this.terminal('sum'); return value===null?null:Number(value); }\n  public async avg%s(): Promise<number | null> { this.request.ir.agg=%s; const value=await this.terminal('avg'); return value===null?null:Number(value); }\n", c.Field, tsString(c.Name), c.Field, tsString(c.Name))
		}
		for _, c := range ge.Aggs {
			fmt.Fprintf(&b, "  public async min%s(): Promise<unknown> { this.request.ir.agg=%s; return this.terminal('min'); }\n  public async max%s(): Promise<unknown> { this.request.ir.agg=%s; return this.terminal('max'); }\n  public async countDistinct%s(): Promise<number> { this.request.ir.agg=%s; return Number(await this.terminal('count_distinct')); }\n", c.Field, tsString(c.Name), c.Field, tsString(c.Name), c.Field, tsString(c.Name))
		}
		for _, c := range ge.ParentCols {
			fmt.Fprintf(&b, "  public ifParent%sEq(value: unknown): this { return this.ifParent(%s,value); }\n", c.Field, tsString(c.Name))
		}
		b.WriteString("  public onDuplicateSetAll(skip: readonly string[] = []): this { return this.duplicateAll(skip); }\n  public async rawAll(): Promise<Array<Record<string,unknown>>> { return await this.terminal('raw') as Array<Record<string,unknown>>; }\n")
		for _, rel := range ge.Rels {
			fmt.Fprintf(&b, "  public %s(callback: (where: %sWhere) => void): this { this.whereCore().navigate(%s,core=>callback(new %sWhere(core))); return this; }\n", tsMethod(rel.Name), rel.TargetType, tsString(rel.Name), rel.TargetType)
		}
		for _, rel := range ge.Rels {
			suffix := rel.Suffix
			fmt.Fprintf(&b, "  public join%s(child: %sQuery): this { return this.attachJoin(%s,child,'inner'); }\n", suffix, rel.TargetType, tsString(rel.Name))
			fmt.Fprintf(&b, "  public leftJoin%s(child: %sQuery): this { return this.attachJoin(%s,child,'left'); }\n", suffix, rel.TargetType, tsString(rel.Name))
			method := "relation"
			if rel.Kind == "many" {
				method = "relations"
			}
			fmt.Fprintf(&b, "  public %s%s(child: %sQuery): this { return this.attachRelation(%s,child); }\n", method, suffix, rel.TargetType, tsString(rel.Name))
		}
		b.WriteString("  private resolveRelation(child: QueryCore, expected?: 'one'|'many'): string { const entity=child.request.ir.entity; const link=child.linkSelection; const candidates=this.relationDefinitions().filter(value=>value.target===entity&&(!expected||value.kind===expected)&&(!link||(value.left===link.parentKey&&value.right===link.childKey))); if(candidates.length!==1) throw new OrmError('IR_INVALID', `relation from ${this.request.ir.entity} to ${entity} is ${candidates.length===0?'not declared':'ambiguous'}; select a key pair`); return candidates[0]!.name; }\n")
		b.WriteString("  private relationDefinitions(): ReadonlyArray<{name:string;kind:'one'|'many';target:string;left:string;right:string}> { return [")
		for i, rel := range ge.Rels {
			if i > 0 {
				b.WriteString(",")
			}
			fmt.Fprintf(&b, "{name:%s,kind:%s,target:%s,left:%s,right:%s}", tsString(rel.Name), tsString(rel.Kind), tsString(rel.Target), tsString(rel.Left), tsString(rel.Right))
		}
		b.WriteString("]; }\n")
		b.WriteString("  public join(child: QueryCore): this { return this.attachJoin(this.resolveRelation(child),child,'inner'); }\n  public leftJoin(child: QueryCore): this { return this.attachJoin(this.resolveRelation(child),child,'left'); }\n  public relation(child: QueryCore): this { return this.attachRelation(this.resolveRelation(child,'one'),child); }\n  public relations(child: QueryCore): this { return this.attachRelation(this.resolveRelation(child,'many'),child); }\n")
		for _, link := range ge.Links {
			fmt.Fprintf(&b, "  public %s(): this { return this.matchKeys(%s,%s); }\n  public %s(): this { return this.matchKeys(%s,%s); }\n", tsMethod(link.Match), tsString(link.Left), tsString(link.Right), tsMethod(link.On), tsString(link.Left), tsString(link.Right))
		}
		b.WriteString("  public async get(): Promise<" + ge.Type + "Row | null> { return await this.terminal('one') as " + ge.Type + "Row | null; }\n")
		b.WriteString("  public async gets(): Promise<Collection<" + ge.Type + "Row>> { const rows=await this.terminal('all') as Collection<" + ge.Type + "Row>; return this.keySelector?rows.rekey(row=>this.keySelector!(row) as number|string|bigint):rows; }\n")
		b.WriteString("  public async stream(visitor: (row: " + ge.Type + "Row) => boolean | Promise<boolean>): Promise<StreamResult> { return this.streamRows<" + ge.Type + "Row>(visitor); }\n")
		b.WriteString("  public async getCount(): Promise<number> { return Number(await this.terminal('count')); }\n")
		b.WriteString("  public async getsCount(): Promise<Collection<" + ge.Type + "Row>> { return await this.terminal('group_count') as Collection<" + ge.Type + "Row>; }\n")
		if ge.Auto {
			fmt.Fprintf(&b, "  public async insert(): Promise<%sRow | null> { const database=this.binding.resolve(); const key=await this.insertKey(); return new %sQuery().using(database).predicate(%s,'eq',key).get(); }\n", ge.Type, ge.Type, tsString(ge.PK))
		} else {
			fmt.Fprintf(&b, "  public async insert(): Promise<%sRow | null> { const database=this.binding.resolve(); const keys=this.assignedKeyValues([%s]); await this.insertKey(); const query=new %sQuery().using(database);", ge.Type, strings.Join(pkNames, ","), ge.Type)
			for i, key := range ge.PKNames {
				fmt.Fprintf(&b, " query.predicate(%s,'eq',keys[%d]);", tsString(key), i)
			}
			b.WriteString(" return query.get(); }\n")
		}
		fmt.Fprintf(&b, "  public async save(): Promise<%sRow | null> { const database=this.binding.resolve(); const keys=await this.saveKeys([%s]); const query=new %sQuery().using(database);", ge.Type, strings.Join(pkNames, ","), ge.Type)
		for i, key := range ge.PKNames {
			fmt.Fprintf(&b, " query.predicate(%s,'eq',keys[%d]);", tsString(key), i)
		}
		b.WriteString(" return query.get(); }\n")
		b.WriteString("  public async update(): Promise<number> { return this.writeAffected('update'); }\n  public async delete(): Promise<number> { return this.writeAffected('delete'); }\n  public async sql(): Promise<{sql:string;binds:unknown[]}> { return this.statement(); }\n")
		b.WriteString("  public async paginate(page: number, per: number): Promise<Page<" + ge.Type + "Row>> { if(!Number.isSafeInteger(page)||page<1||!Number.isSafeInteger(per)||per<1) throw new OrmError('IR_INVALID','paginate requires page >= 1 and per > 0'); const saved=this.request.ir.limit; this.limit((page-1)*per,per); const result=await this.terminal('paginate') as {rows: unknown;total:number}; this.request.ir.limit=saved; const items=result.rows instanceof Collection?result.rows:new Collection<" + ge.Type + "Row>(); return new Page(items,result.total,Math.ceil(result.total/per),page,per); }\n")
		for _, c := range ge.EqCols {
			typ := tsPredicateType(c)
			field := c.Field
			fmt.Fprintf(&b, "  public async getBy%s(value: %s): Promise<%sRow | null> { this.predicate(%s,'eq',value); return this.get(); }\n", field, typ, ge.Type, tsString(c.Name))
			fmt.Fprintf(&b, "  public async getsBy%s(value: %s): Promise<Collection<%sRow>> { this.predicate(%s,'eq',value); return this.gets(); }\n", field, typ, ge.Type, tsString(c.Name))
			fmt.Fprintf(&b, "  public async getCountBy%s(value: %s): Promise<number> { this.predicate(%s,'eq',value); return this.getCount(); }\n", field, typ, tsString(c.Name))
		}
		if len(ge.PKCols) > 1 {
			fmt.Fprintf(&b, "  public async getBy%s(", ge.PKMethod)
			for i, col := range ge.PKCols {
				if i > 0 {
					b.WriteString(",")
				}
				fmt.Fprintf(&b, "value%d:%s", i, tsType(e.Column(col.Name)))
			}
			fmt.Fprintf(&b, "): Promise<%sRow | null> {", ge.Type)
			for i, col := range ge.PKCols {
				fmt.Fprintf(&b, " this.predicate(%s,'eq',value%d);", tsString(col.Name), i)
			}
			b.WriteString(" return this.get(); }\n")
		}
		b.WriteString("}\n")
		fmt.Fprintf(&b, "export function %s(): %sQuery { return new %sQuery(); }\n", ge.Type, ge.Type, ge.Type)
		fmt.Fprintf(&b, "registerRow(%s,%sRow);\n\n", tsString(ge.Name), ge.Type)
	}
	output := append(bytes.TrimRight(b.Bytes(), "\n"), '\n')
	return os.WriteFile(filepath.Join(outDir, "entities.ts"), output, 0o644)
}

func writeTSPredicates(b *bytes.Buffer, ge goEntity, target string) {
	for _, p := range ge.Preds {
		args := make([]string, p.Arity)
		vals := make([]string, p.Arity)
		for i := range args {
			args[i] = fmt.Sprintf("value%d: unknown", i)
			vals[i] = fmt.Sprintf("value%d", i)
		}
		fmt.Fprintf(b, "  public %s(%s): this { %s.expression(%s,[%s]); return this; }\n", tsMethod(p.Name), strings.Join(args, ","), target, tsString(p.Expr), strings.Join(vals, ","))
	}
	for _, c := range ge.Cols {
		typ := tsPredicateType(c)
		for _, op := range c.Ops {
			method := tsMethod(c.Name) + op.Suffix
			switch op.Kind {
			case "one":
				fmt.Fprintf(b, "  public %s(value: %s): this { %s.predicate(%s,%s,value); return this; }\n", method, typ, target, tsString(c.Name), tsString(op.Op))
			case "list":
				fmt.Fprintf(b, "  public %s(values: readonly (%s)[]): this { %s.predicateList(%s,%s,values); return this; }\n", method, typ, target, tsString(c.Name), tsString(op.Op))
			case "pair":
				fmt.Fprintf(b, "  public %s(low: %s, high: %s): this { %s.predicateList(%s,%s,[low,high]); return this; }\n", method, typ, typ, target, tsString(c.Name), tsString(op.Op))
			case "none":
				fmt.Fprintf(b, "  public %s(): this { %s.predicateNull(%s,%s); return this; }\n", method, target, tsString(c.Name), tsString(op.Op))
			}
			if op.Op == "eq" {
				fmt.Fprintf(b, "  public %s(value: %s): this { return this.%s(value); }\n", tsMethod(c.Name), typ, method)
			}
		}
		for _, op := range c.ColOps {
			fmt.Fprintf(b, "  public %s(reference: ColumnReference): this { %s.predicateColumn(%s,%s,reference); return this; }\n", tsMethod(c.Name)+op.Suffix, target, tsString(c.Name), tsString(op.Op))
		}
	}
	for _, cols := range ge.Fulltext {
		fields := make([]string, len(cols))
		for i, c := range cols {
			fields[i] = tsString(c)
		}
		base := strings.Join(func() []string {
			x := make([]string, len(cols))
			for i, c := range cols {
				x[i] = pascal(c)
			}
			return x
		}(), "With")
		fmt.Fprintf(b, "  public %sMatch(value: string): this { %s.match([%s],value); return this; }\n", tsMethod(base), target, strings.Join(fields, ","))
		fmt.Fprintf(b, "  public %sMatchBoolean(value: string): this { %s.match([%s],value,true); return this; }\n", tsMethod(base), target, strings.Join(fields, ","))
	}
}
