package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/maxkwon/orm/engine/schema"
)

// PHP generator: one file per entity in namespace App\Orm (configurable later),
// against clients/php/src. Same grammar as Go: column-first operators, or(),
// and(fn), relation/relations/join/leftJoin, on/where, one/all/count/paginate/insert.

func camel(s string) string {
	p := pascal(s)
	if p == "" {
		return p
	}
	return strings.ToLower(p[:1]) + p[1:]
}

func phpType(c *schema.Col) string {
	switch c.Type {
	case "i32", "i64":
		return "int"
	case "f64", "decimal":
		return "float"
	case "bool":
		return "bool"
	default:
		return "string"
	}
}

type phpEntity struct {
	goEntity
	Namespace string
}

var phpTmpl = template.Must(template.New("php").Funcs(template.FuncMap{
	"pascal": pascal, "camel": camel,
	"phpType": func(t string) string { return t },
	"ftName": func(cols []string) string {
		parts := make([]string, len(cols))
		for i, c := range cols {
			parts[i] = pascal(c)
		}
		return strings.Join(parts, "With")
	},
	"phpList": func(cols []string) string {
		q := make([]string, len(cols))
		for i, c := range cols {
			q[i] = fmt.Sprintf("'%s'", c)
		}
		return strings.Join(q, ", ")
	},
	"lower": strings.ToLower,
}).Parse(`<?php
// Code generated by ormgen; DO NOT EDIT.
declare(strict_types=1);

namespace {{.Namespace}};

use Orm\Collection;
use Orm\Db;
use Orm\Page;
use Orm\Q;
use Orm\Row;
use Orm\W;

/** One row of {{.Table}}. */
final class {{.Type}}Row extends Row
{
    public static function entity(): string { return '{{.Name}}'; }
    public static function pk(): string { return '{{.PK}}'; }
    public static function columns(): array
    {
        return [{{range $i, $c := .Cols}}{{if $i}}, {{end}}'{{$c.Name}}' => '{{$c.ColType}}'{{end}}];
    }
{{range .Cols}}
    public function get{{.Field}}(mixed $default = null): {{if .Nullable}}?{{end}}{{.PhpType}}
    {
        $v = $this->col('{{.Name}}');
        return $v === null ? $default : $v;
    }
{{- if not .Auto}}
    public function set{{.Field}}({{if .Nullable}}?{{end}}{{.PhpType}} $v): static { return $this->setCol('{{.Name}}', $v); }
{{- end}}
{{end}}
{{- range .Rels}}
{{- if eq .Kind "one"}}
    public function get{{.Method}}(): ?{{.TargetType}}Row { return $this->relation('{{.Name}}'); }
{{- else}}
    public function get{{.Method}}(): Collection { return $this->relation('{{.Name}}') ?? new Collection(); }
{{- end}}
{{- end}}
}

/** Where builder for {{.Table}}: predicates, or(), and(fn), relation navigation. */
final class {{.Type}}Where
{
    public function __construct(private W $w) {}

    public function or(): static { $this->w->orConn(); return $this; }
    public function and(\Closure $fn): static { $g = &$this->w->group(); $fn(new self(new W($this->w->req, $g))); return $this; }
    public function expr(string $frag, array $binds = []): static { $this->w->expr($frag, $binds); return $this; }
{{- range .Rels}}
    public function {{camel .Name}}(\Closure $fn): static { $g = &$this->w->nav('{{.Name}}'); $fn(new {{.TargetType}}Where(new W($this->w->req, $g))); return $this; }
{{- end}}
{{range .Cols}}{{$c := .}}{{range .Ops}}
{{- if eq .Kind "one"}}
    public function {{camel $c.Name}}{{.Suffix}}({{$c.PhpType}} $v): static { $this->w->pred('{{$c.Name}}', '{{.Op}}', $v); return $this; }
{{- else if eq .Kind "list"}}
    public function {{camel $c.Name}}{{.Suffix}}(array $vs): static { $this->w->predList('{{$c.Name}}', '{{.Op}}', array_values($vs)); return $this; }
{{- else if eq .Kind "pair"}}
    public function {{camel $c.Name}}{{.Suffix}}({{$c.PhpType}} $lo, {{$c.PhpType}} $hi): static { $this->w->predList('{{$c.Name}}', '{{.Op}}', [$lo, $hi]); return $this; }
{{- else}}
    public function {{camel $c.Name}}{{.Suffix}}(): static { $this->w->predNull('{{$c.Name}}', '{{.Op}}'); return $this; }
{{- end}}
{{- end}}{{end}}
{{- range .Fulltext}}
    public function {{camel (ftName .)}}Match(string $v): static { $this->w->match([{{phpList .}}], false, $v); return $this; }
    public function {{camel (ftName .)}}MatchBoolean(string $v): static { $this->w->match([{{phpList .}}], true, $v); return $this; }
{{- end}}
}

/** Query over {{.Table}}: new {{.Type}} → chain → terminal($db). */
final class {{.Type}} extends Q
{
    public function __construct() { parent::__construct('{{.Name}}'); }

    // ---- WHERE ----
    public function or(): static { $this->orConn(); return $this; }
    public function and(\Closure $fn): static { $g = &$this->w()->group(); $fn(new {{.Type}}Where(new W($this->req, $g))); return $this; }
    public function expr(string $frag, array $binds = []): static { $this->w()->expr($frag, $binds); return $this; }
{{- range .Rels}}
    public function {{camel .Name}}(\Closure $fn): static { $g = &$this->w()->nav('{{.Name}}'); $fn(new {{.TargetType}}Where(new W($this->req, $g))); return $this; }
{{- end}}
{{range .Cols}}{{$c := .}}{{range .Ops}}
{{- if eq .Kind "one"}}
    public function {{camel $c.Name}}{{.Suffix}}({{$c.PhpType}} $v): static { $this->w()->pred('{{$c.Name}}', '{{.Op}}', $v); return $this; }
{{- else if eq .Kind "list"}}
    public function {{camel $c.Name}}{{.Suffix}}(array $vs): static { $this->w()->predList('{{$c.Name}}', '{{.Op}}', array_values($vs)); return $this; }
{{- else if eq .Kind "pair"}}
    public function {{camel $c.Name}}{{.Suffix}}({{$c.PhpType}} $lo, {{$c.PhpType}} $hi): static { $this->w()->predList('{{$c.Name}}', '{{.Op}}', [$lo, $hi]); return $this; }
{{- else}}
    public function {{camel $c.Name}}{{.Suffix}}(): static { $this->w()->predNull('{{$c.Name}}', '{{.Op}}'); return $this; }
{{- end}}
{{- end}}{{end}}
{{- range .Fulltext}}
    public function {{camel (ftName .)}}Match(string $v): static { $this->w()->match([{{phpList .}}], false, $v); return $this; }
    public function {{camel (ftName .)}}MatchBoolean(string $v): static { $this->w()->match([{{phpList .}}], true, $v); return $this; }
{{- end}}

    // ---- join children: on() = ON, where() = parent WHERE group ----
    public function on(\Closure $fn): static { $fn(new {{.Type}}Where($this->onW())); return $this; }
    public function where(\Closure $fn): static { $fn(new {{.Type}}Where($this->w())); return $this; }
{{range .Rels}}
    public function join{{.Method}}({{.TargetType}} $child): static { $this->join('{{.Name}}', 'inner', $child); return $this; }
    public function leftJoin{{.Method}}({{.TargetType}} $child): static { $this->join('{{.Name}}', 'left', $child); return $this; }
{{- if eq .Kind "one"}}
    public function relation{{.Method}}({{.TargetType}} $child): static { $this->relation('{{.Name}}', $child); return $this; }
{{- else}}
    public function relations{{.Method}}({{.TargetType}} $child): static { $this->relation('{{.Name}}', $child); return $this; }
{{- end}}
{{- end}}

    // ---- columns ----
    public function selectAll(): static { $c = &$this->columns(); $c['mode'] = 'all'; return $this; }
    public function selectNone(): static { $c = &$this->columns(); $c['mode'] = 'none'; return $this; }
    public function selectExpr(string $name, string $frag): static { $c = &$this->columns(); $c['expr'][$name] = $frag; return $this; }
{{- range .Cols}}
    public function select{{.Field}}(): static { $c = &$this->columns(); $c['add'][] = '{{.Name}}'; return $this; }
    public function unselect{{.Field}}(): static { $c = &$this->columns(); $c['remove'][] = '{{.Name}}'; return $this; }
    public function select{{.Field}}As(string $name): static { $c = &$this->columns(); $c['as'][$name] = '{{.Name}}'; return $this; }
{{- end}}

    // ---- order, group, limit ----
{{- range .Cols}}
    public function orderBy{{.Field}}Asc(): static { $this->order('{{.Name}}', false); return $this; }
    public function orderBy{{.Field}}Desc(): static { $this->order('{{.Name}}', true); return $this; }
    public function groupBy{{.Field}}(): static { $this->node['group_by'][] = '{{.Name}}'; return $this; }
    public function keyBy{{.Field}}(): static { $this->node['key_by'] = '{{.Name}}'; return $this; }
{{- end}}
    public function orderByExpr(string $frag, bool $desc = false): static { $this->orderExpr($frag, $desc); return $this; }
    public function limit(int $offset, int $count): static { $this->node['limit'] = ['offset' => $offset, 'count' => $count]; return $this; }
    public function distinct(): static { $this->node['distinct'] = true; return $this; }
{{- range .Indexes}}
    public function forceIndex{{pascal .}}(): static { $this->node['force_index'] = '{{.}}'; return $this; }
{{- end}}

    // ---- relation-child options ----
    public function flatten(): static { $this->node['flatten'] = true; return $this; }
    public function limitPerParent(int $n): static { $this->node['limit_per_parent'] = $n; return $this; }
    public function dropChildKey(): static { $this->node['drop_child_key'] = true; return $this; }
{{- range .ParentCols}}{{if eq .ColType "i32" "i64" "bool" "string" "enum"}}
    public function ifParent{{.Field}}Eq({{.PhpType}} $v): static { $this->ifParent('{{.Name}}', $v); return $this; }
{{- end}}{{end}}

    // ---- insert draft ----
{{- range .Cols}}{{if not .Auto}}
    public function set{{.Field}}({{if .Nullable}}?{{end}}{{.PhpType}} $v): static { $this->set('{{.Name}}', $v); return $this; }
    public function set{{.Field}}Expr(string $frag, array $binds = []): static { $this->setExpr('{{.Name}}', $frag, $binds); return $this; }
{{- end}}{{end}}
{{- range .Numeric}}
    public function plus{{.Field}}({{.PhpType}} $v): static { $this->plus('{{.Name}}', $v); return $this; }
    public function minus{{.Field}}({{.PhpType}} $v): static { $this->minus('{{.Name}}', $v); return $this; }
{{- end}}

    // ---- terminals ----
    public function one(Db $db): ?{{.Type}}Row
    {
        $rows = $this->runQuery($db, 'one');
        return $rows->data === [] ? null : {{.Type}}Row::fromRow($rows->data[0], $rows->asm, $rows);
    }

    public function all(Db $db): Collection
    {
        return Collection::fromRows($this->runQuery($db, 'all'), {{.Type}}Row::class);
    }

    public function count(Db $db): int { return (int) $this->runScalar($db, 'count'); }
{{- range .Numeric}}
    public function sum{{.Field}}(Db $db): float { return (float) $this->runScalar($db, 'sum', '{{.Name}}'); }
    public function avg{{.Field}}(Db $db): float { return (float) $this->runScalar($db, 'avg', '{{.Name}}'); }
{{- end}}

    public function paginate(Db $db, int $page, int $per): Page
    {
        [$rows, $total] = $this->runPaginate($db, $page, $per);
        return new Page(Collection::fromRows($rows, {{.Type}}Row::class), $total, intdiv($total + $per - 1, $per), max(1, $page), $per);
    }

    public function insert(Db $db): ?{{.Type}}Row
    {
        $id = $this->runInsert($db);
{{- if .Auto}}
        return (new {{.Type}})->{{camel .PK}}Eq((int) $id)->one($db);
{{- else}}
        return null;
{{- end}}
    }

    public function oneBy{{pascal .PK}}(Db $db, {{.PKPhp}} $v): ?{{.Type}}Row { return $this->{{camel .PK}}Eq($v)->one($db); }
}
`))

type phpCol struct {
	goCol
	PhpType string
}

type phpTmplData struct {
	Name, Type, Table, PK, PKPhp, Namespace string
	Auto                                    bool
	Cols                                    []phpCol
	Numeric                                 []phpCol
	ParentCols                              []phpCol
	Rels                                    []goRel
	Indexes                                 []string
	Fulltext                                [][]string
}

func genPHP(m *schema.Manifest, outDir, namespace string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	var boot bytes.Buffer
	boot.WriteString("<?php\n// Code generated by ormgen; DO NOT EDIT.\ndeclare(strict_types=1);\n\nnamespace " + namespace + ";\n\nuse Orm\\Registry;\n\n")
	for _, name := range m.Order {
		e := m.Entities[name]
		ge := buildGoEntity(m, e)
		d := phpTmplData{Name: ge.Name, Type: ge.Type, Table: ge.Table, PK: ge.PK, Auto: ge.Auto, Namespace: namespace, Rels: ge.Rels, Indexes: ge.Indexes, Fulltext: ge.Fulltext}
		for _, c := range ge.Cols {
			pc := phpCol{goCol: c, PhpType: phpType(e.Column(c.Name))}
			d.Cols = append(d.Cols, pc)
			if c.Name == ge.PK {
				d.PKPhp = pc.PhpType
			}
		}
		for _, c := range ge.ParentCols {
			d.ParentCols = append(d.ParentCols, phpCol{goCol: c, PhpType: phpType(m.Entities[parentOf(m, e, c.Name)].Column(c.Name))})
		}
		for _, c := range ge.Numeric {
			d.Numeric = append(d.Numeric, phpCol{goCol: c, PhpType: phpType(e.Column(c.Name))})
		}
		var buf bytes.Buffer
		if err := phpTmpl.Execute(&buf, d); err != nil {
			return fmt.Errorf("%s: %w", name, err)
		}
		if err := os.WriteFile(filepath.Join(outDir, ge.Type+".php"), buf.Bytes(), 0o644); err != nil {
			return err
		}
		fmt.Fprintf(&boot, "Registry::register('%s', %sRow::class);\n", name, ge.Type)
	}
	return os.WriteFile(filepath.Join(outDir, "bootstrap.php"), boot.Bytes(), 0o644)
}
