package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/maxkwon/orm/engine/schema"
)

// Rust generator: crate `gen` with one module per entity, against clients/rust/orm.
// Same grammar as Go/PHP (docs/dsl.md), snake_case rendering.

var rustReserved = map[string]bool{"as": true, "break": true, "const": true, "continue": true, "crate": true, "else": true, "enum": true, "extern": true, "false": true, "fn": true, "for": true, "if": true, "impl": true, "in": true, "let": true, "loop": true, "match": true, "mod": true, "move": true, "mut": true, "pub": true, "ref": true, "return": true, "self": true, "Self": true, "static": true, "struct": true, "super": true, "trait": true, "true": true, "type": true, "unsafe": true, "use": true, "where": true, "while": true, "async": true, "await": true, "dyn": true}

func rustIdent(s string) string {
	if rustReserved[s] {
		return s + "_"
	}
	return s
}

func rustType(c *schema.Col) string {
	switch c.Type {
	case "i32":
		return "i32"
	case "i64":
		return "i64"
	case "f64", "decimal":
		return "f64"
	case "bool":
		return "bool"
	case "datetime":
		return "chrono::NaiveDateTime"
	case "date":
		return "chrono::NaiveDate"
	default:
		return "String"
	}
}

// rustArg is the parameter type accepted by predicate/setter methods.
func rustArg(t string) string {
	if t == "String" {
		return "impl Into<String>"
	}
	return t
}

func rustFrom(t string) string {
	switch t {
	case "i32":
		return "v.as_i64() as i32"
	case "i64":
		return "v.as_i64()"
	case "f64":
		return "v.as_f64()"
	case "bool":
		return "v.as_bool()"
	case "chrono::NaiveDateTime":
		return "v.as_datetime()"
	case "chrono::NaiveDate":
		return "v.as_date()"
	}
	return "v.as_string()"
}

type rustCol struct {
	goCol
	RType, Arg, From, Ident string
}

type rustData struct {
	Name, Type, Table, PK, PKType string
	Auto                          bool
	Cols                          []rustCol
	Numeric                       []rustCol
	Rels                          []rustRel
	Indexes                       []string
	Fulltext                      [][]string
	UpdatedTs                     string
}

type rustRel struct {
	Name, Ident, Target, TargetType, Kind string
}

var rustTmpl = template.Must(template.New("rust").Funcs(template.FuncMap{
	"pascal": pascal, "ident": rustIdent, "lower": strings.ToLower,
	"snakeOp": func(s string) string { return strings.ToLower(s) },
	"ftName": func(cols []string) string { return strings.Join(cols, "_with_") },
	"rsList": func(cols []string) string {
		q := make([]string, len(cols))
		for i, c := range cols {
			q[i] = fmt.Sprintf("%q", c)
		}
		return strings.Join(q, ", ")
	},
	"opSnake": func(suffix string) string {
		// Eq → eq, NotEq → not_eq, IsNotNull → is_not_null
		var b strings.Builder
		for i, r := range suffix {
			if r >= 'A' && r <= 'Z' {
				if i > 0 {
					b.WriteByte('_')
				}
				b.WriteRune(r + 32)
			} else {
				b.WriteRune(r)
			}
		}
		return b.String()
	},
}).Parse(`// Code generated by ormgen; DO NOT EDIT.
#![allow(clippy::all, dead_code, unused_imports, non_snake_case)]

use orm::builder::{Q, W};
use orm::db::{self, Exec};
use orm::value::{Param, Val};
use orm::{Collection, Key, Page, Result};

/// One row of {{.Table}}.
#[derive(Debug, Clone, Default)]
pub struct {{.Type}}Row {
{{- range .Cols}}
    pub {{.Ident}}: {{if .Nullable}}Option<{{.RType}}>{{else}}{{.RType}}{{end}},
{{- end}}
{{- range .Rels}}
{{- if eq .Kind "one"}}
    pub {{.Ident}}_: Option<Box<super::{{.Target}}::{{.TargetType}}Row>>,
{{- else}}
    pub {{.Ident}}_: Collection<super::{{.Target}}::{{.TargetType}}Row>,
{{- end}}
{{- end}}
    dirty: Vec<(&'static str, Param)>,
    loaded: bool,
}

impl {{.Type}}Row {
    pub const ENTITY: &'static str = {{printf "%q" .Name}};
    pub const PK: &'static str = {{printf "%q" .PK}};

    pub(crate) fn from_row(vals: &[Val], a: &orm::plan::Assemble) -> Self {
        let mut r = Self::default();
        r.loaded = true;
        for c in &a.columns {
            let v = &vals[c.index];
            match c.name.as_str() {
{{- range .Cols}}
                {{printf "%q" .Name}} => r.{{.Ident}} = {{if .Nullable}}if v.is_null() { None } else { Some({{.From}}) }{{else}}{{.From}}{{end}},
{{- end}}
                _ => {}
            }
        }
        for ch in &a.children {
            if ch.kind != "join" { continue; }
            match ch.rel.as_str() {
{{- range .Rels}}
{{- if eq .Kind "one"}}
                {{printf "%q" .Name}} => if db::join_present(vals, &ch.assemble) { r.{{.Ident}}_ = Some(Box::new(super::{{.Target}}::{{.TargetType}}Row::from_row(vals, &ch.assemble))); },
{{- end}}
{{- end}}
                _ => {}
            }
        }
        r
    }
{{range .Rels}}
{{- if eq .Kind "one"}}
    pub fn {{.Ident}}(&self) -> Option<&super::{{.Target}}::{{.TargetType}}Row> { self.{{.Ident}}_.as_deref() }
{{- else}}
    pub fn {{.Ident}}(&self) -> &Collection<super::{{.Target}}::{{.TargetType}}Row> { &self.{{.Ident}}_ }
{{- end}}
{{- end}}
{{range .Cols}}{{if not .Auto}}
    pub fn set_{{.Ident}}(&mut self, v: {{if .Nullable}}Option<{{.Arg}}>{{else}}{{.Arg}}{{end}}) -> &mut Self {
        {{if .Nullable}}let v: Option<{{.RType}}> = v.map(|x| x.into());{{else}}let v: {{.RType}} = v.into();{{end}}
        self.{{.Ident}} = v.clone();
        self.dirty.retain(|(c, _)| *c != {{printf "%q" .Name}});
        self.dirty.push(({{printf "%q" .Name}}, v.into()));
        self
    }
{{- end}}{{end}}

    fn write_req(&self, kind: &str) -> Q {
        let mut q = Q::new(super::schema_hash(), Self::ENTITY);
        q.req.ir.kind = kind.into();
        q
    }

    /// UPDATE the columns changed through set_*.
    pub async fn update(&mut self, ex: &impl Exec) -> Result<()> {
        self.update_inner(ex, false).await
    }
{{- if .UpdatedTs}}

    /// UPDATE with optimistic locking on {{.UpdatedTs}}; fails with OptimisticLock when the row changed.
    pub async fn update_optimistic(&mut self, ex: &impl Exec) -> Result<()> {
        self.update_inner(ex, true).await
    }
{{- end}}

    async fn update_inner(&mut self, ex: &impl Exec, optimistic: bool) -> Result<()> {
        if !self.loaded { return Err(orm::Error::Config("update on a row that was not loaded".into())); }
        if self.dirty.is_empty() { return Ok(()); }
        let mut q = self.write_req("update");
        for (c, v) in self.dirty.drain(..) { q.set(c, v); }
        let pk: Param = self.{{.PK}}.clone().into();
        q.w().pred(Self::PK, "eq", pk);
{{- if .UpdatedTs}}
        if optimistic {
            let p = q.req.p(self.{{.UpdatedTs}}.clone());
            q.req.ir.optimistic = Some(orm::ir::Optimist { column: {{printf "%q" .UpdatedTs}}.into(), p });
        }
{{- else}}
        let _ = optimistic;
{{- end}}
        db::write(ex, &mut q.req, "update").await.map(|_| ())
    }

    pub async fn delete(&self, ex: &impl Exec) -> Result<()> {
        if !self.loaded { return Err(orm::Error::Config("delete on a row that was not loaded".into())); }
        let mut q = self.write_req("delete");
        let pk: Param = self.{{.PK}}.clone().into();
        q.w().pred(Self::PK, "eq", pk);
        db::write(ex, &mut q.req, "delete").await.map(|_| ())
    }
}

/// Where builder for {{.Table}}.
pub struct {{.Type}}Where<'a> { w: W<'a> }

impl<'a> {{.Type}}Where<'a> {
    pub fn or(mut self) -> Self { self.w.or(); self }
    pub fn and(mut self, f: impl FnOnce({{.Type}}Where<'_>) -> {{.Type}}Where<'_>) -> Self { self.w.and(|w| { let inner = {{.Type}}Where { w: W { req: w.req, g: w.g, pending_or: false } }; let _ = f(inner); }); self }
    pub fn expr(mut self, frag: &str, binds: Vec<Param>) -> Self { self.w.expr(frag, binds); self }
{{- range .Rels}}
    pub fn {{.Ident}}(mut self, f: impl FnOnce(super::{{.Target}}::{{.TargetType}}Where<'_>) -> super::{{.Target}}::{{.TargetType}}Where<'_>) -> Self { self.w.nav({{printf "%q" .Name}}, |w| { let _ = f(super::{{.Target}}::{{.TargetType}}Where::wrap(w)); }); self }
{{- end}}
    pub(crate) fn wrap(w: &'a mut W<'_>) -> {{.Type}}Where<'a> { unimplemented!() }
{{range .Cols}}{{$c := .}}{{range .Ops}}
{{- if eq .Kind "one"}}
    pub fn {{$c.Ident}}_{{opSnake .Suffix}}(mut self, v: {{$c.Arg}}) -> Self { self.w.pred({{printf "%q" $c.Name}}, {{printf "%q" .Op}}, {{if eq $c.RType "String"}}v.into(){{else}}v{{end}}); self }
{{- else if eq .Kind "list"}}
    pub fn {{$c.Ident}}_{{opSnake .Suffix}}(mut self, vs: Vec<{{$c.RType}}>) -> Self { self.w.pred_list({{printf "%q" $c.Name}}, {{printf "%q" .Op}}, vs.into_iter().map(Into::into).collect()); self }
{{- else if eq .Kind "pair"}}
    pub fn {{$c.Ident}}_{{opSnake .Suffix}}(mut self, lo: {{$c.RType}}, hi: {{$c.RType}}) -> Self { self.w.pred_list({{printf "%q" $c.Name}}, {{printf "%q" .Op}}, vec![lo.into(), hi.into()]); self }
{{- else}}
    pub fn {{$c.Ident}}_{{opSnake .Suffix}}(mut self) -> Self { self.w.pred_null({{printf "%q" $c.Name}}, {{printf "%q" .Op}}); self }
{{- end}}
{{- end}}{{end}}
{{- range .Fulltext}}
    pub fn {{ftName .}}_match(mut self, v: &str) -> Self { self.w.match_(&[{{rsList .}}], false, v); self }
    pub fn {{ftName .}}_match_boolean(mut self, v: &str) -> Self { self.w.match_(&[{{rsList .}}], true, v); self }
{{- end}}
}
`))

func genRust(m *schema.Manifest, outDir string) error {
	_ = rustTmpl
	return fmt.Errorf("rust generator: template under construction (see gen_rust.go)")
}

var _ = bytes.NewBuffer
var _ = os.WriteFile
var _ = filepath.Join
