// Code generated by ormgen; DO NOT EDIT.
import { CORE, Model, registerModel, type CodecValue, type Collection, type ColumnFunction, type EntityDef, type JsonValue, StyledValue, type ValueFunction } from '../../index.js';

/** The manifest text of the dbspec document set the models were generated from. */
export const MANIFEST_TEXT = `dbspec 1 decimal_schema

table decimal_case {
  seq i64
  amount decimal(13,4)
  large_value decimal(16,0) null
  primary key (seq)
}
`;

export const MANIFEST_HASH = 'sha256:07c7949c292fab2c05a9fbf22100dd1f39267cbfe0a94e1067adcda44838e890';

const model = registerModel(MANIFEST_TEXT, MANIFEST_HASH);

/** A decimal_case model or row. */
export class DecimalCase extends Model {
  public static readonly entity: EntityDef = { model, entity: model.entities.get('decimal_case')!, create: core => new DecimalCase(core) };
  public getSeq(): number { return this[CORE].column('seq') as number; }
  public setSeq(value: number): this { this[CORE].setValue('seq', value); return this; }
  public setRawSeq(sql: string, ...binds: unknown[]): this { this[CORE].putSet({ column: 'seq', raw: { sql, binds } }); return this; }
  public addColumnSeq(): this { this[CORE].addColumn('seq'); return this; }
  public removeColumnSeq(): this { this[CORE].removeColumn('seq'); return this; }
  public groupBySeq(): this { this[CORE].groupBy.push('seq'); return this; }
  public keyNameSeq(): this { this[CORE].keyName = 'seq'; return this; }
  public orderBySeqAsc(...fn: ColumnFunction[]): this { this[CORE].orderBy('seq', false, fn); return this; }
  public orderBySeqDesc(...fn: ColumnFunction[]): this { this[CORE].orderBy('seq', true, fn); return this; }
  public plusSeq(n: number): this { this[CORE].putSet({ column: 'seq', value: n, plus: true }); return this; }
  public minusSeq(n: number): this { this[CORE].putSet({ column: 'seq', value: n, minus: true }); return this; }
  public sumSeq(): this { this[CORE].aggregate('sum', 'seq'); return this; }
  public avgSeq(): this { this[CORE].aggregate('avg', 'seq'); return this; }
  public getAmount(): string { return this[CORE].column('amount') as string; }
  public setAmount(value: string): this { this[CORE].setValue('amount', value); return this; }
  public setRawAmount(sql: string, ...binds: unknown[]): this { this[CORE].putSet({ column: 'amount', raw: { sql, binds } }); return this; }
  public addColumnAmount(): this { this[CORE].addColumn('amount'); return this; }
  public removeColumnAmount(): this { this[CORE].removeColumn('amount'); return this; }
  public groupByAmount(): this { this[CORE].groupBy.push('amount'); return this; }
  public keyNameAmount(): this { this[CORE].keyName = 'amount'; return this; }
  public orderByAmountAsc(...fn: ColumnFunction[]): this { this[CORE].orderBy('amount', false, fn); return this; }
  public orderByAmountDesc(...fn: ColumnFunction[]): this { this[CORE].orderBy('amount', true, fn); return this; }
  public plusAmount(n: number): this { this[CORE].putSet({ column: 'amount', value: n, plus: true }); return this; }
  public minusAmount(n: number): this { this[CORE].putSet({ column: 'amount', value: n, minus: true }); return this; }
  public sumAmount(): this { this[CORE].aggregate('sum', 'amount'); return this; }
  public avgAmount(): this { this[CORE].aggregate('avg', 'amount'); return this; }
  public getLargeValue(): string | null { return this[CORE].column('large_value') as string | null; }
  public setLargeValue(value: string | null): this { this[CORE].setValue('large_value', value); return this; }
  public setRawLargeValue(sql: string, ...binds: unknown[]): this { this[CORE].putSet({ column: 'large_value', raw: { sql, binds } }); return this; }
  public addColumnLargeValue(): this { this[CORE].addColumn('large_value'); return this; }
  public removeColumnLargeValue(): this { this[CORE].removeColumn('large_value'); return this; }
  public groupByLargeValue(): this { this[CORE].groupBy.push('large_value'); return this; }
  public keyNameLargeValue(): this { this[CORE].keyName = 'large_value'; return this; }
  public orderByLargeValueAsc(...fn: ColumnFunction[]): this { this[CORE].orderBy('large_value', false, fn); return this; }
  public orderByLargeValueDesc(...fn: ColumnFunction[]): this { this[CORE].orderBy('large_value', true, fn); return this; }
  public plusLargeValue(n: number): this { this[CORE].putSet({ column: 'large_value', value: n, plus: true }); return this; }
  public minusLargeValue(n: number): this { this[CORE].putSet({ column: 'large_value', value: n, minus: true }); return this; }
  public sumLargeValue(): this { this[CORE].aggregate('sum', 'large_value'); return this; }
  public avgLargeValue(): this { this[CORE].aggregate('avg', 'large_value'); return this; }
}
export interface DecimalCase {
  seq(v0: number | readonly (number)[] | ValueFunction | Model): this;
}
