// Code generated by ormgen errors from docs/errors.yaml; DO NOT EDIT.

package orm

// Error codes shared by the engine and every executor (docs/errors.yaml).
const (
	CodeVersionMismatch       = "VERSION_MISMATCH"       // engine: ir_version the engine does not speak
	CodeSchemaHashMismatch    = "SCHEMA_HASH_MISMATCH"   // engine: client generated from another schema.json than the engine loaded
	CodeSchemaInvalid         = "SCHEMA_INVALID"         // engine: schema.json failed validation at load
	CodeDialectUnknown        = "DIALECT_UNKNOWN"        // engine
	CodeIrInvalid             = "IR_INVALID"             // engine: structural: missing fields, wrong combination, param index out of range
	CodeCapabilityUnsupported = "CAPABILITY_UNSUPPORTED" // engine: requested operation is not supported by the selected dialect
	CodeEntityUnknown         = "ENTITY_UNKNOWN"         // engine
	CodeColumnUnknown         = "COLUMN_UNKNOWN"         // engine
	CodeRelationUnknown       = "RELATION_UNKNOWN"       // engine
	CodeIndexUnknown          = "INDEX_UNKNOWN"          // engine: force_index name not declared
	CodeColumnAliasConflict   = "COLUMN_ALIAS_CONFLICT"  // engine: select<Col>As name collides with a column
	CodeOperatorUnknown       = "OPERATOR_UNKNOWN"       // engine
	CodeFunctionUnknown       = "FUNCTION_UNKNOWN"       // engine: ORM function name outside the column or value function catalog
	CodeOperatorNotAllowed    = "OPERATOR_NOT_ALLOWED"   // engine: op not valid for the column's type/style (ir.OpAllowed)
	CodeOrAtGroupStart        = "OR_AT_GROUP_START"      // engine: or() as the first item of a group
	CodeEmptyIn               = "EMPTY_IN"               // engine: in()/notIn() with no values
	CodeEntityNotJoined       = "ENTITY_NOT_JOINED"      // engine: joined placement or column reference to a join missing from this statement
	CodeLimitInRelation       = "LIMIT_IN_RELATION"      // engine: limit() on a relation child (use limitPerParent)
	CodeNoRows                = "NO_ROWS"                // executor: strict one-row query matched no row
	CodeOptimisticLock        = "OPTIMISTIC_LOCK"        // executor: updateOptimistic matched no row (updated_ts changed)
	CodeCodecDecode           = "CODEC_DECODE"           // executor: styled column bytes could not be decoded (docs/codec.md)
	CodeCodecEncode           = "CODEC_ENCODE"           // executor
	CodeCodecUnsupported      = "CODEC_UNSUPPORTED"      // executor: PHP objects/references in serialize, unknown style
	CodeConfig                = "CONFIG"                 // executor: missing secret, bad DSN/paths, transaction misuse
	CodeCanceled              = "CANCELED"               // executor: the statement stopped before it finished: its context or abort signal was cancelled, or a timeout bound expired (statement timeout, transaction timeoutMs, SQLite busy_timeout)
	CodeInternal              = "INTERNAL"               // executor
	CodeLockNotAvailable      = "LOCK_NOT_AVAILABLE"     // driver: a NOWAIT lock could not be acquired immediately
	CodeDeadlock              = "DEADLOCK"               // driver: MySQL 1213 / SQLSTATE 40001 / PostgreSQL 40P01 / SQLite LOCKED; retries require TransactionOptions
	CodeDuplicateKey          = "DUPLICATE_KEY"          // driver: MySQL 1062 / SQLSTATE 23000
	CodeForeignKey            = "FOREIGN_KEY"            // driver: MySQL 1451/1452 / PostgreSQL 23503 / SQLite 787/1811
	CodeConstraint            = "CONSTRAINT"             // driver: MySQL 3819/4025 / PostgreSQL 23514 / SQLite 275
	CodeReadOnly              = "READ_ONLY"              // driver: a write rejected because the server or connection is read-only: MySQL 1290/1792 / PostgreSQL 25006 / SQLite 8 and its extended codes
)
