// Code generated by ormgen errors from docs/errors.yaml; DO NOT EDIT.

package orm

// Error codes shared by the engine and every executor (docs/errors.yaml).
const (
	CodeVersionMismatch = "VERSION_MISMATCH" // engine: ir_version the engine does not speak
	CodeSchemaHashMismatch = "SCHEMA_HASH_MISMATCH" // engine: client generated from another schema.json than the engine loaded
	CodeSchemaInvalid = "SCHEMA_INVALID" // engine: schema.json failed validation at load
	CodeSchemaNotLoaded = "SCHEMA_NOT_LOADED" // engine: wasm/ffi: orm_compile before orm_load
	CodeDialectUnknown = "DIALECT_UNKNOWN" // engine
	CodeFrameInvalid = "FRAME_INVALID" // engine: ormd: bad length-prefixed frame
	CodeOpUnknown = "OP_UNKNOWN" // engine: ormd: unknown op
	CodeIrInvalid = "IR_INVALID" // engine: structural: missing fields, wrong combination, param index out of range
	CodeCapabilityUnsupported = "CAPABILITY_UNSUPPORTED" // engine: requested operation is not supported by the selected dialect
	CodeEntityUnknown = "ENTITY_UNKNOWN" // engine
	CodeColumnUnknown = "COLUMN_UNKNOWN" // engine
	CodeRelationUnknown = "RELATION_UNKNOWN" // engine
	CodeIndexUnknown = "INDEX_UNKNOWN" // engine: force_index name not declared
	CodeColumnAliasConflict = "COLUMN_ALIAS_CONFLICT" // engine: select<Col>As name collides with a column
	CodeOperatorUnknown = "OPERATOR_UNKNOWN" // engine
	CodeOperatorNotAllowed = "OPERATOR_NOT_ALLOWED" // engine: op not valid for the column's type/style (ir.OpAllowed)
	CodeOrAtGroupStart = "OR_AT_GROUP_START" // engine: or() as the first item of a group
	CodeEmptyIn = "EMPTY_IN" // engine: in()/notIn() with no values
	CodeEntityNotJoined = "ENTITY_NOT_JOINED" // engine: nav into a relation that was not joined in this statement
	CodeLimitInRelation = "LIMIT_IN_RELATION" // engine: limit() on a relation child (use limitPerParent)
	CodeCursorInvalid = "CURSOR_INVALID" // engine: keyset cursor version, order, or typed value is invalid
	CodeOptimisticLock = "OPTIMISTIC_LOCK" // executor: updateOptimistic matched no row (updated_ts changed)
	CodeCodecDecode = "CODEC_DECODE" // executor: styled column bytes could not be decoded (docs/codec.md)
	CodeCodecEncode = "CODEC_ENCODE" // executor
	CodeCodecUnsupported = "CODEC_UNSUPPORTED" // executor: PHP objects/references in serialize, unknown style
	CodeConfig = "CONFIG" // executor: missing secret, bad DSN/paths, transaction misuse
	CodeInternal = "INTERNAL" // executor
	CodeDeadlock = "DEADLOCK" // driver: MySQL 1213 / SQLSTATE 40001; retries require TransactionOptions
	CodeDuplicateKey = "DUPLICATE_KEY" // driver: MySQL 1062 / SQLSTATE 23000
)
