<?php
// Code generated by ormgen errors from docs/errors.yaml; DO NOT EDIT.
declare(strict_types=1);

namespace Orm;

/** Error codes shared by the engine and every executor (docs/errors.yaml). */
final class Code
{
    /** engine: ir_version the engine does not speak */
    public const VERSION_MISMATCH = 'VERSION_MISMATCH';
    /** engine: client generated from another schema.json than the engine loaded */
    public const SCHEMA_HASH_MISMATCH = 'SCHEMA_HASH_MISMATCH';
    /** engine: schema.json failed validation at load */
    public const SCHEMA_INVALID = 'SCHEMA_INVALID';
    /** engine */
    public const DIALECT_UNKNOWN = 'DIALECT_UNKNOWN';
    /** engine: structural: missing fields, wrong combination, param index out of range */
    public const IR_INVALID = 'IR_INVALID';
    /** engine: requested operation is not supported by the selected dialect */
    public const CAPABILITY_UNSUPPORTED = 'CAPABILITY_UNSUPPORTED';
    /** engine */
    public const ENTITY_UNKNOWN = 'ENTITY_UNKNOWN';
    /** engine */
    public const COLUMN_UNKNOWN = 'COLUMN_UNKNOWN';
    /** engine */
    public const RELATION_UNKNOWN = 'RELATION_UNKNOWN';
    /** engine: force_index name not declared */
    public const INDEX_UNKNOWN = 'INDEX_UNKNOWN';
    /** engine: select<Col>As name collides with a column */
    public const COLUMN_ALIAS_CONFLICT = 'COLUMN_ALIAS_CONFLICT';
    /** engine */
    public const OPERATOR_UNKNOWN = 'OPERATOR_UNKNOWN';
    /** engine: ORM function name outside the column or value function catalog */
    public const FUNCTION_UNKNOWN = 'FUNCTION_UNKNOWN';
    /** engine: op not valid for the column's type/style (ir.OpAllowed) */
    public const OPERATOR_NOT_ALLOWED = 'OPERATOR_NOT_ALLOWED';
    /** engine: or() as the first item of a group */
    public const OR_AT_GROUP_START = 'OR_AT_GROUP_START';
    /** engine: in()/notIn() with no values */
    public const EMPTY_IN = 'EMPTY_IN';
    /** engine: joined placement or column reference to a join missing from this statement */
    public const ENTITY_NOT_JOINED = 'ENTITY_NOT_JOINED';
    /** engine: limit() on a relation child (use limitPerParent) */
    public const LIMIT_IN_RELATION = 'LIMIT_IN_RELATION';
    /** executor: strict one-row query matched no row */
    public const NO_ROWS = 'NO_ROWS';
    /** executor: updateOptimistic matched no row (updated_ts changed) */
    public const OPTIMISTIC_LOCK = 'OPTIMISTIC_LOCK';
    /** executor: styled column bytes could not be decoded (docs/codec.md) */
    public const CODEC_DECODE = 'CODEC_DECODE';
    /** executor */
    public const CODEC_ENCODE = 'CODEC_ENCODE';
    /** executor: PHP objects/references in serialize, unknown style */
    public const CODEC_UNSUPPORTED = 'CODEC_UNSUPPORTED';
    /** executor: missing secret, bad DSN/paths, transaction misuse */
    public const CONFIG = 'CONFIG';
    /** executor: the statement stopped before it finished: its context or abort signal was cancelled, or a timeout bound expired (statement timeout, transaction timeoutMs) */
    public const CANCELED = 'CANCELED';
    /** executor */
    public const INTERNAL = 'INTERNAL';
    /** driver: MySQL 1213 / SQLSTATE 40001; retries require TransactionOptions */
    public const DEADLOCK = 'DEADLOCK';
    /** driver: MySQL 1062 / SQLSTATE 23000 */
    public const DUPLICATE_KEY = 'DUPLICATE_KEY';
    /** driver: MySQL 1451/1452 / PostgreSQL 23503 / SQLite 787/1811 */
    public const FOREIGN_KEY = 'FOREIGN_KEY';
    /** driver: MySQL 3819/4025 / PostgreSQL 23514 / SQLite 275 */
    public const CONSTRAINT = 'CONSTRAINT';
}
