<?php
declare(strict_types=1);

namespace Orm;

/**
 * Writes one model class per entity with typed column accessors and the model
 * metadata, plus bootstrap.php, which registers the classes. Every other
 * method name is resolved at call time by Model with the grammar of the DSL.
 */
final class Generator
{
    public const MARKER = '// Code generated by orm-gen; DO NOT EDIT.';

    /** Methods of Model; a generated method with the same name would replace one. */
    private const FIXED_METHODS = [
        'connect', '__invoke', 'and', 'or', 'not', 'andNot', 'orNot', 'on', 'relation', 'relations',
        'limit', 'orderByRandom', 'removeAllColumns', 'addAllColumns', 'parentNode', 'groupLimit',
        'deleteLock', 'fetchKey', 'fetchValue', 'forUpdate', 'forShare', 'forUpdateNoWait', 'forShareNoWait', 'duplication',
        'get', 'gets', 'getsCount', 'getCount', 'getSum', 'getAvg', 'getsPage', 'getQuery', 'create', 'creates', 'update',
        'save', 'delete', 'restore', 'deleteRow', 'connection', 'toArray', 'toJson', 'jsonSerialize', 'meta', 'readColumn', 'writeColumn',
        'registerJoins', '__call', '__clone',
    ];

    /** Column naming rules of the DSL. */
    private const RESERVED_SEGMENTS = ['and', 'or', 'with', 'gt', 'lt', 'ge', 'le', 'eq', 'ne', 'lk', 'lb', 'between', 'tuple'];
    private const RESERVED_PREFIXES = ['and', 'or', 'get', 'set', 'new', 'plus', 'minus', 'order_by', 'group_by', 'tuple', 'gt', 'lt', 'ge', 'le', 'eq', 'ne', 'lk', 'lb', 'between'];
    private const RESERVED_COLUMNS = ['and', 'or', 'not', 'get', 'gets', 'gets_page', 'get_query', 'limit', 'alias', 'connect', 'create', 'creates', 'update', 'delete', 'restore', 'save', 'on', 'random'];

    /** $m의 model을 $outDir에 생성하고 이전에 생성한 파일을 바꾼다. */
    public static function generate(RuntimeModel $m, string $outDir, string $namespace): void
    {
        $files = self::files($m, $namespace);
        if (!is_dir($outDir) && !mkdir($outDir, 0o755, true)) {
            throw new OrmException(Code::CONFIG, "cannot create $outDir");
        }
        foreach (self::generated($outDir) as $file) {
            unlink($file);
        }
        foreach ($files as $name => $body) {
            self::write("$outDir/$name", $body);
        }
    }

    /**
     * $m의 model을 쓰지 않고 생성해, $outDir의 generated 파일 중 다르거나
     * 없거나 남는 파일마다 한 줄을 경로 순서로 돌려준다.
     * @return list<string>
     */
    public static function check(RuntimeModel $m, string $outDir, string $namespace): array
    {
        $files = self::files($m, $namespace);
        $lines = [];
        foreach ($files as $name => $body) {
            $path = "$outDir/$name";
            if (!is_file($path)) {
                $lines[$path] = "missing: $path";
            } elseif (file_get_contents($path) !== $body) {
                $lines[$path] = "differs: $path";
            }
        }
        foreach (self::generated($outDir) as $path) {
            if (!array_key_exists(basename($path), $files)) {
                $lines[$path] = "extra: $path";
            }
        }
        ksort($lines, SORT_STRING);
        return array_values($lines);
    }

    /** @return list<string> the PHP files of $outDir that hold the generated marker */
    private static function generated(string $outDir): array
    {
        return array_values(array_filter(
            glob($outDir . '/*.php') ?: [],
            static fn(string $file): bool => str_contains((string) file_get_contents($file), self::MARKER),
        ));
    }

    /** @return array<string, string> the generated file bodies by file name */
    private static function files(RuntimeModel $m, string $namespace): array
    {
        foreach ($m->entities as $e) {
            foreach ($e['columns'] as $c) {
                self::checkColumnName($e['entity'], $c['name']);
            }
        }
        foreach ($m->entities as $e) {
            self::checkNames($e);
        }
        $files = [];
        $external = $m->externalText !== '';
        $boot = "<?php\n" . self::MARKER . "\ndeclare(strict_types=1);\n\nnamespace $namespace;\n\nuse Orm\\Config;\nuse Orm\\Db;\nuse Orm\\Orm;\nuse Orm\\Registry;\nuse Orm\\Schema;\n\n"
            . "/** The manifestHash of the document set the models were generated from. */\nconst MANIFEST_HASH = " . self::str($m->manifestHash) . ";\n\n"
            . "/** The manifest text of the document set the models were generated from. */\nconst MANIFEST_TEXT = " . self::str($m->manifestText) . ";\n\n"
            // 외부 문서를 쓰지 않는 set의 bootstrap은 external text를 쓰지 않으므로 그대로다.
            . ($external ? "/** The tables that the set uses from external documents, which other sets own. */\nconst EXTERNAL_TEXT = " . self::str($m->externalText) . ";\n\n" : '')
            . "/** The generated schema value: install takes it to create the tables and register the set. */\nfunction schema(): Schema\n{\n    return new Schema(MANIFEST_TEXT, MANIFEST_HASH" . ($external ? ', EXTERNAL_TEXT' : '') . ");\n}\n\n"
            . "/** Opens the database selected by the DSN URI and registers the set of these models on the connection. */\nfunction connect(string \$dsn, Config \$config): Db\n{\n    return Orm::connectSchema(\$dsn, schema(), \$config);\n}\n\n"
            . "Registry::generated(MANIFEST_HASH, MANIFEST_TEXT" . ($external ? ', EXTERNAL_TEXT' : '') . ");\n";
        foreach ($m->entities as $e) {
            $class = self::pascal($e['entity']);
            if (isset($files["$class.php"])) {
                throw new OrmException(Code::SCHEMA_INVALID, "entities {$e['entity']} and another entity generate the class $class");
            }
            $files["$class.php"] = self::model($e, $class, $namespace, $m->manifestHash);
            $boot .= "Registry::register($class::class);\n";
        }
        $files['bootstrap.php'] = $boot;
        return $files;
    }

    private static function write(string $path, string $body): void
    {
        if (file_put_contents($path, $body) === false) {
            throw new OrmException(Code::CONFIG, "cannot write $path");
        }
    }

    private static function model(array $e, string $class, string $namespace, string $hash): string
    {
        $name = $e['entity'];
        $b = "<?php\n" . self::MARKER . "\ndeclare(strict_types=1);\n\nnamespace $namespace;\n\nuse Orm\\Model;\n\n/** A $name model or row. */\nfinal class $class extends Model\n{\n";
        // meta()는 entity와 그 model을 만든 document set의 manifest_hash다.
        $b .= "    public static function meta(): array\n    {\n        return " . self::export($e + ['manifest_hash' => $hash], 2) . ";\n    }\n";
        foreach ($e['columns'] as $c) {
            $p = self::pascal($c['name']);
            $styled = RuntimeModel::styled($c);
            $t = $styled ? '\\Orm\\StyledValue' : self::type($c);
            $nt = !$styled && $c['nullable'] ? "?$t" : $t;
            $b .= "\n    public function get$p(): $nt\n    {\n        return \$this->readColumn(" . self::str($c['name']) . ");\n    }\n";
            $param = $nt;
            $value = '$v';
            if ($t === '\\DateTimeImmutable') {
                $param = $c['nullable'] ? '?\\DateTimeInterface' : '\\DateTimeInterface';
                $value = $c['nullable'] ? '$v === null ? null : \\DateTimeImmutable::createFromInterface($v)' : '\\DateTimeImmutable::createFromInterface($v)';
            }
            $b .= "\n    public function set$p($param \$v): static\n    {\n        return \$this->writeColumn(" . self::str($c['name']) . ", $value);\n    }\n";
        }
        return $b . "}\n";
    }

    /**
     * PHP 배열 literal이다. 값이 scalar이거나 scalar list뿐인 배열은 한 줄에,
     * 그 밖의 배열은 원소마다 한 줄에 쓴다.
     */
    private static function export(mixed $v, int $depth): string
    {
        if (is_bool($v)) {
            return $v ? 'true' : 'false';
        }
        if (is_int($v)) {
            return (string) $v;
        }
        if (is_string($v)) {
            return self::str($v);
        }
        if (!is_array($v)) {
            throw new OrmException(Code::INTERNAL, 'the runtime model holds a ' . get_debug_type($v));
        }
        $list = array_is_list($v);
        $item = static fn(int|string $k, mixed $x, int $d): string => ($list ? '' : self::export((string) $k, $d) . ' => ') . self::export($x, $d);
        $flat = true;
        foreach ($v as $x) {
            if (is_array($x) && ($x !== [] && (!array_is_list($x) || array_filter($x, 'is_array') !== []))) {
                $flat = false;
            }
        }
        if ($flat) {
            $parts = [];
            foreach ($v as $k => $x) {
                $parts[] = $item($k, $x, $depth + 1);
            }
            return '[' . implode(', ', $parts) . ']';
        }
        $pad = str_repeat('    ', $depth + 1);
        $out = "[\n";
        foreach ($v as $k => $x) {
            $out .= $pad . $item($k, $x, $depth + 1) . ",\n";
        }
        return $out . str_repeat('    ', $depth) . ']';
    }

    public static function pascal(string $s): string
    {
        return implode('', array_map(ucfirst(...), explode('_', $s)));
    }

    private static function camel(string $s): string
    {
        return lcfirst(self::pascal($s));
    }

    private static function str(string $s): string
    {
        return "'" . strtr($s, ['\\' => '\\\\', "'" => "\\'"]) . "'";
    }

    /** @param list<string> $items */
    private static function list(array $items): string
    {
        return '[' . implode(', ', array_map(self::str(...), $items)) . ']';
    }

    /** codec이 없는 column, 또는 aes, hex, ip stage만 가진 column의 PHP 값 type이다. */
    private static function type(array $c): string
    {
        if ($c['codec'] !== []) {
            return 'string';
        }
        return match ($c['type']) {
            'i16', 'i32', 'i64' => 'int',
            'f64' => 'float',
            'bool' => 'bool',
            'date', 'datetime' => '\\DateTimeImmutable',
            default => 'string',
        };
    }

    private static function checkColumnName(string $entity, string $n): void
    {
        $fail = static fn(string $msg): OrmException => new OrmException(Code::SCHEMA_INVALID, "$entity.$n: $msg");
        if (preg_match('/^[a-z][a-z0-9_]*$/', $n) !== 1) {
            throw $fail("column name must be snake_case: $n");
        }
        if (str_contains($n, '__')) {
            throw $fail("column name may not contain '__': $n");
        }
        foreach (explode('_', $n) as $segment) {
            if (in_array($segment, self::RESERVED_SEGMENTS, true)) {
                throw $fail("column name may not contain the segment \"$segment\": $n");
            }
        }
        if (in_array($n, self::RESERVED_COLUMNS, true)) {
            throw $fail("column name is a reserved method name: $n");
        }
        foreach (self::RESERVED_PREFIXES as $p) {
            if ($n === $p || str_starts_with($n, $p . '_')) {
                throw $fail("column name may not start with \"$p\": $n");
            }
        }
    }

    /** Rejects a column whose accessor or condition method is another method of the model. */
    private static function checkNames(array $e): void
    {
        $names = [];
        foreach (self::FIXED_METHODS as $n) {
            $names[strtolower($n)] = $n;
        }
        $fixed = $names;
        foreach ($e['columns'] as $c) {
            $p = self::pascal($c['name']);
            $derived = ['get', 'set', 'addColumn', 'removeColumn', 'groupBy', 'keyName'];
            if (RuntimeModel::numeric($c)) {
                array_push($derived, 'plus', 'minus', 'sum', 'avg');
            }
            foreach ($derived as $prefix) {
                $names[strtolower($prefix . $p)] = $prefix . $p;
            }
            $names[strtolower("orderBy{$p}Asc")] = "orderBy{$p}Asc";
            $names[strtolower("orderBy{$p}Desc")] = "orderBy{$p}Desc";
        }
        foreach ($e['indexes'] as $index => $_) {
            $names[strtolower('forceIndex' . self::pascal((string) $index))] = 'forceIndex' . self::pascal((string) $index);
        }
        foreach ($e['columns'] as $c) {
            $p = self::pascal($c['name']);
            foreach (["get$p", "set$p"] as $accessor) {
                if (isset($fixed[strtolower($accessor)])) {
                    throw new OrmException(Code::SCHEMA_INVALID, "{$e['entity']}.{$c['name']}: $accessor is a fixed model method");
                }
            }
            if (isset($names[strtolower($p)])) {
                throw new OrmException(Code::SCHEMA_INVALID, "{$e['entity']}.{$c['name']}: the condition method " . self::camel($c['name']) . ' is also the model method ' . $names[strtolower($p)]);
            }
        }
    }
}
