<?php
declare(strict_types=1);

namespace Orm;

/**
 * Renders the DDL of a schema manifest (a SchemaBuilder array) for one
 * dialect (docs/dialects.md): tables, keys, foreign keys, checks, indexes,
 * comments, and immutable-table triggers. The text embeds the manifest so a
 * DDL file is a complete schema source.
 */
final class SchemaDdl
{
    public const METADATA_PREFIX = '-- orm-schema-v1 ';
    private const SQLITE_NOW = " DEFAULT (strftime('%Y-%m-%d %H:%M:%f', 'now') || '000')";
    private const SQLITE_COMMENTS = 'CREATE TABLE IF NOT EXISTS orm_schema_comments (table_name TEXT NOT NULL, column_name TEXT NOT NULL, comment TEXT NOT NULL, PRIMARY KEY (table_name, column_name));';

    /** The `-- orm-schema-v1` line that embeds the manifest. */
    public static function metadata(array $m): string
    {
        return self::METADATA_PREFIX . rtrim(base64_encode(rtrim(SchemaBuilder::json($m), "\n")), '=') . "\n";
    }

    /** The manifest embedded in a DDL file, or null when the text has none. */
    public static function embedded(string $text, string $path): ?array
    {
        foreach (explode("\n", $text) as $line) {
            if (!str_starts_with($line, self::METADATA_PREFIX)) {
                continue;
            }
            $encoded = SchemaParser::trim(substr($line, strlen(self::METADATA_PREFIX)));
            $decoded = preg_match('/^[A-Za-z0-9+\/]*$/', $encoded) === 1 && strlen($encoded) % 4 !== 1 ? base64_decode($encoded, true) : false;
            if ($decoded === false) {
                throw new \RuntimeException("MIGRATION_SOURCE: $path: invalid orm-schema-v1 metadata");
            }
            try {
                return SchemaBuilder::load($decoded);
            } catch (\InvalidArgumentException $e) {
                throw new \RuntimeException("MIGRATION_SOURCE: $path: invalid embedded manifest: " . $e->getMessage());
            }
        }
        return null;
    }

    /** @return \Closure(string): string */
    public static function quoter(string $dialect): \Closure
    {
        return $dialect === 'mysql'
            ? static fn(string $s): string => self::quoteQualified('`', $s)
            : static fn(string $s): string => self::quoteQualified('"', self::table($s, $dialect));
    }

    /** The full DDL: drops, creates, indexes, deferred foreign keys, and triggers. */
    public static function render(array $m, string $dialect): string
    {
        $q = self::quoter($dialect);
        $sb = "-- generated by ormgen ddl ($dialect) from schema_hash {$m['schema_hash']}\n";
        $sb .= self::metadata($m);
        if ($dialect === 'sqlite') {
            $sb .= self::SQLITE_COMMENTS . "\n";
        }
        if ($dialect === 'postgres') {
            foreach (self::schemas($m) as $name) {
                $sb .= 'CREATE SCHEMA IF NOT EXISTS ' . $q($name) . ";\n";
            }
        } elseif ($dialect === 'mysql') {
            // MySQL keeps a qualified table in the database named by its schema.
            foreach (self::schemas($m) as $name) {
                $sb .= 'CREATE DATABASE IF NOT EXISTS ' . $q($name) . ";\n";
            }
        }
        $order = self::entityOrder($m);
        for ($i = count($order) - 1; $i >= 0; $i--) {
            $e = $m['entities'][$order[$i]];
            $sb .= "\nDROP TABLE IF EXISTS " . $q(self::table($e['table'], $dialect)) . ";\n";
        }
        $position = array_flip($order);
        $deferred = [];
        foreach ($order as $current => $name) {
            $e = $m['entities'][$name];
            $sb .= "\nCREATE TABLE " . $q(self::table($e['table'], $dialect)) . " (\n";
            $lines = [];
            foreach ($e['columns'] as $c) {
                try {
                    $line = '  ' . self::column($c, $dialect, $q);
                } catch (\RuntimeException $ex) {
                    throw new \RuntimeException("{$e['table']}.{$c['name']}: " . $ex->getMessage());
                }
                if ($c['comment'] !== '' && $dialect === 'mysql') {
                    $line .= " COMMENT '" . self::str($c['comment']) . "'";
                }
                $lines[] = $line;
            }
            $pk = $e['pk'] ?? [];
            if ($dialect === 'sqlite' && count($pk) === 1 && $e['auto'] === $pk[0]) {
                // SQLite: the rowid alias must be declared inline
                foreach ($lines as $i => $l) {
                    if (str_starts_with($l, '  ' . $q($pk[0]) . ' ')) {
                        $lines[$i] = '  ' . $q($pk[0]) . ' INTEGER PRIMARY KEY AUTOINCREMENT';
                    }
                }
            } else {
                $lines[] = '  PRIMARY KEY (' . implode(', ', array_map($q, $pk)) . ')';
            }
            foreach ($e['unique'] as $uk) {
                $lines[] = '  CONSTRAINT ' . $q(self::boundedIdentifier('uq_' . self::base($e['table']) . '_' . implode('_', $uk), $dialect)) . ' UNIQUE (' . self::joinQuoted($uk, $q) . ')';
            }
            foreach (self::sortedForeignKeys($m, $e, $dialect) as $fk) {
                $target = self::targetEntity($m, $fk['target']);
                if ($target !== null && $dialect !== 'sqlite' && $position[$target['name']] > $current) {
                    $deferred[] = [$e['table'], $fk];
                    continue;
                }
                $lines[] = '  ' . self::foreignKeyClause($fk, $m, $dialect, $q);
            }
            foreach ($e['checks'] as $check) {
                try {
                    $expr = self::renderedCheckExpression($check['expr'], $dialect, $q);
                } catch (\RuntimeException $ex) {
                    throw new \RuntimeException("{$e['table']} check {$check['name']}: " . $ex->getMessage());
                }
                $lines[] = '  CONSTRAINT ' . $q(self::checkName($e['table'], $check['name'], $dialect)) . ' CHECK (' . $expr . ')';
            }
            if ($dialect === 'mysql') {
                foreach (self::sortedKeys($e['indexes'] ?? []) as $ix) {
                    $lines[] = '  KEY ' . $q($ix) . ' (' . self::joinQuoted($e['indexes'][$ix], $q) . ')';
                }
                foreach ($e['fulltext'] as $cols) {
                    $lines[] = '  FULLTEXT KEY ' . $q('ft_' . implode('_', $cols)) . ' (' . self::joinQuoted($cols, $q) . ')';
                }
            }
            $sb .= implode(",\n", $lines) . "\n)";
            if ($dialect === 'mysql') {
                $sb .= ' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4';
            }
            $sb .= ";\n";
            if ($e['comment'] !== '') {
                $sb .= match ($dialect) {
                    'mysql' => 'ALTER TABLE ' . $q($e['table']) . " COMMENT = '" . self::str($e['comment']) . "';\n",
                    'postgres' => 'COMMENT ON TABLE ' . $q($e['table']) . " IS '" . self::str($e['comment']) . "';\n",
                    default => "INSERT OR REPLACE INTO orm_schema_comments (table_name, column_name, comment) VALUES ('" . self::str($e['table']) . "', '', '" . self::str($e['comment']) . "');\n",
                };
            }
            foreach ($e['columns'] as $c) {
                if ($c['comment'] === '') {
                    continue;
                }
                if ($dialect === 'postgres') {
                    $sb .= 'COMMENT ON COLUMN ' . $q($e['table']) . '.' . $q($c['name']) . " IS '" . self::str($c['comment']) . "';\n";
                } elseif ($dialect === 'sqlite') {
                    $sb .= "INSERT OR REPLACE INTO orm_schema_comments (table_name, column_name, comment) VALUES ('" . self::str($e['table']) . "', '" . self::str($c['name']) . "', '" . self::str($c['comment']) . "');\n";
                }
            }
            if ($dialect !== 'mysql') {
                foreach (self::sortedKeys($e['indexes'] ?? []) as $ix) {
                    $sb .= 'CREATE INDEX ' . $q(self::indexName($e['table'], $ix, $dialect)) . ' ON ' . $q($e['table']) . ' (' . self::joinQuoted($e['indexes'][$ix], $q) . ");\n";
                }
                if ($dialect === 'postgres') {
                    foreach ($e['fulltext'] as $cols) {
                        $doc = array_map(static fn(string $c): string => 'coalesce(' . $q($c) . ", '')", $cols);
                        $sb .= 'CREATE INDEX ' . $q(self::indexName($e['table'], 'ft_' . implode('_', $cols), $dialect)) . ' ON ' . $q($e['table'])
                            . " USING GIN (to_tsvector('simple', " . implode(" || ' ' || ", $doc) . "));\n";
                    }
                }
            }
        }
        foreach ($deferred as [$table, $fk]) {
            $sb .= 'ALTER TABLE ' . $q($table) . ' ADD ' . self::foreignKeyClause($fk, $m, $dialect, $q) . ";\n";
        }
        foreach (SchemaTriggers::objects($m, $dialect) as $o) {
            $sb .= "\n" . SchemaTriggers::text($o) . "\n";
        }
        return $sb;
    }

    /** The apply-safe form: no drops, and tables and indexes are created only when missing. */
    public static function renderCreate(array $m, string $dialect): string
    {
        $out = [];
        foreach (explode("\n", self::render($m, $dialect)) as $line) {
            if (str_starts_with($line, 'DROP TABLE IF EXISTS ')) {
                continue;
            }
            foreach (['CREATE TABLE `' => 'CREATE TABLE IF NOT EXISTS `', 'CREATE TABLE "' => 'CREATE TABLE IF NOT EXISTS "',
                'CREATE INDEX `' => 'CREATE INDEX IF NOT EXISTS `', 'CREATE INDEX "' => 'CREATE INDEX IF NOT EXISTS "'] as $from => $to) {
                $at = strpos($line, $from);
                if ($at !== false) {
                    $line = substr_replace($line, $to, $at, strlen($from));
                }
            }
            $out[] = $line;
        }
        return implode("\n", $out);
    }

    /** @return list<string> the apply-safe statements of a manifest */
    public static function createStatements(array $m, string $dialect): array
    {
        return self::splitSql(self::renderCreate($m, $dialect));
    }

    public static function table(string $table, string $dialect): string
    {
        return $dialect === 'sqlite' ? str_replace('.', '__', $table) : $table;
    }

    public static function base(string $table): string
    {
        $parts = explode('.', $table);
        return $parts[count($parts) - 1];
    }

    private static function indexName(string $table, string $index, string $dialect): string
    {
        return $dialect === 'sqlite' ? self::table($table, $dialect) . '_' . $index : self::boundedIdentifier(self::base($table) . '_' . $index, $dialect);
    }

    /**
     * MySQL CHECK constraint names are unique within a database, while the
     * schema scopes a check name to its entity. MySQL receives the name
     * ck_<table>_<name>; other dialects keep the declared name.
     */
    public static function checkName(string $table, string $name, string $dialect): string
    {
        return $dialect === 'mysql' ? self::boundedIdentifier('ck_' . self::base($table) . '_' . $name, $dialect) : $name;
    }

    /**
     * Keeps a name within the identifier limit of the dialect (MySQL 64,
     * PostgreSQL 63). A longer name is cut and receives a suffix with the
     * first 6 bytes of its SHA-256 digest in hex, so two long names do not
     * collide after the cut.
     */
    public static function boundedIdentifier(string $name, string $dialect): string
    {
        $limit = match ($dialect) {
            'mysql' => 64,
            'postgres' => 63,
            default => 0,
        };
        if ($limit === 0 || strlen($name) <= $limit) {
            return $name;
        }
        $suffix = '_' . substr(hash('sha256', $name), 0, 12);
        return substr($name, 0, $limit - strlen($suffix)) . $suffix;
    }

    /** @return list<string> */
    private static function schemas(array $m): array
    {
        $out = [];
        foreach ($m['order'] as $name) {
            $parts = explode('.', $m['entities'][$name]['table']);
            if (count($parts) === 2 && !in_array($parts[0], $out, true)) {
                $out[] = $parts[0];
            }
        }
        sort($out, SORT_STRING);
        return $out;
    }

    public static function quoteQualified(string $quote, string $name): string
    {
        return implode('.', array_map(static fn(string $p): string => $quote . str_replace($quote, $quote . $quote, $p) . $quote, explode('.', $name)));
    }

    /** @return list<string> */
    public static function sortedKeys(array $map): array
    {
        $keys = array_map('strval', array_keys($map));
        sort($keys, SORT_STRING);
        return $keys;
    }

    public static function str(string $s): string
    {
        return str_replace("'", "''", $s);
    }

    public static function joinQuoted(array $cols, \Closure $q): string
    {
        return implode(', ', array_map($q, $cols));
    }

    public static function isNumber(string $s): bool
    {
        return $s !== '' && preg_match('/^-?[0-9.]*$/', $s) === 1;
    }

    /**
     * A parent-before-child entity order for inline foreign keys.
     * @return list<string>
     */
    public static function entityOrder(array $m): array
    {
        $names = $m['order'];
        $extra = array_diff(self::sortedKeys($m['entities']), $names);
        array_push($names, ...$extra);
        $position = array_flip($names);
        $state = [];
        $result = [];
        $visit = function (string $name) use (&$visit, &$state, &$result, $m, $position): void {
            $s = $state[$name] ?? 0;
            if ($s === 1) {
                throw new \RuntimeException("foreign key cycle includes $name; deferred cyclic constraints are required");
            }
            if ($s === 2) {
                return;
            }
            $state[$name] = 1;
            $e = $m['entities'][$name];
            $deps = [];
            foreach ($e['columns'] as $c) {
                if ($c['ref'] !== null && $c['ref']['entity'] !== $name && isset($m['entities'][$c['ref']['entity']])) {
                    $deps[$c['ref']['entity']] = true;
                }
            }
            foreach ($e['relations'] ?? [] as $rel) {
                if ($rel['foreign_key'] && $rel['target'] !== $name && isset($m['entities'][$rel['target']])) {
                    $deps[$rel['target']] = true;
                }
            }
            $ordered = array_map('strval', array_keys($deps));
            usort($ordered, static fn(string $a, string $b): int => $position[$a] <=> $position[$b]);
            foreach ($ordered as $dep) {
                $visit($dep);
            }
            $state[$name] = 2;
            $result[] = $name;
        };
        foreach ($names as $name) {
            $visit($name);
        }
        return $result;
    }

    public static function targetEntity(array $m, string $target): ?array
    {
        if (isset($m['entities'][$target])) {
            return $m['entities'][$target];
        }
        foreach (self::sortedKeys($m['entities']) as $name) {
            if ($m['entities'][$name]['table'] === $target) {
                return $m['entities'][$name];
            }
        }
        return null;
    }

    public static function columnOf(array $e, string $name): ?array
    {
        foreach ($e['columns'] as $c) {
            if ($c['name'] === $name) {
                return $c;
            }
        }
        return null;
    }

    private static function relationMatchesReference(array $e, array $rel): bool
    {
        if ($rel['keys'] === []) {
            return false;
        }
        foreach ($rel['keys'] as $key) {
            $c = self::columnOf($e, $key['local']);
            if ($c === null || $c['ref'] === null || $c['ref']['entity'] !== $rel['target'] || $c['ref']['column'] !== $key['target']) {
                return false;
            }
        }
        return true;
    }

    /**
     * The foreign keys of an entity keyed by column list.
     * @return array<string, array{name: string, columns: list<string>, target: string, target_columns: list<string>, on_delete: string, deferred: bool}>
     */
    public static function foreignKeys(array $m, array $e, string $dialect = ''): array
    {
        $out = [];
        $consumed = [];
        $relations = $e['relations'] ?? [];
        foreach (self::sortedKeys($relations) as $rn) {
            $rel = $relations[$rn];
            if ($rel['kind'] !== 'one' || (!$rel['foreign_key'] && !self::relationMatchesReference($e, $rel))) {
                continue;
            }
            $columns = [];
            $targets = [];
            $valid = $rel['keys'] !== [];
            foreach ($rel['keys'] as $key) {
                if (self::columnOf($e, $key['local']) === null) {
                    $valid = false;
                    break;
                }
                $columns[] = $key['local'];
                $targets[] = $key['target'];
            }
            if (!$valid) {
                continue;
            }
            $out[implode("\x1f", $columns)] = ['name' => self::boundedIdentifier('fk_' . $e['table'] . '_' . implode('_', $columns), $dialect), 'columns' => $columns, 'target' => $rel['target'],
                'target_columns' => $targets, 'on_delete' => $rel['on_delete'], 'deferred' => false];
            foreach ($columns as $column) {
                $consumed[$column] = true;
            }
        }
        foreach ($e['columns'] as $c) {
            if ($c['ref'] === null || isset($consumed[$c['name']])) {
                continue;
            }
            $out[$c['name']] = ['name' => self::boundedIdentifier('fk_' . $e['table'] . '_' . $c['name'], $dialect), 'columns' => [$c['name']], 'target' => $c['ref']['entity'],
                'target_columns' => [$c['ref']['column']], 'on_delete' => '', 'deferred' => false];
        }
        foreach ($m['external_fks'] as $fk) {
            if ($fk['entity'] !== $e['name']) {
                continue;
            }
            $name = $fk['name'] !== '' ? $fk['name'] : self::boundedIdentifier('fk_' . str_replace('.', '_', $e['table']) . '_' . implode('_', $fk['columns']), $dialect);
            $matched = false;
            foreach (self::sortedKeys($out) as $key) {
                $existing = $out[$key];
                $target = isset($m['entities'][$existing['target']]) ? $m['entities'][$existing['target']]['table'] : $existing['target'];
                if ($target === $fk['target_table'] && $existing['columns'] === $fk['columns'] && $existing['target_columns'] === $fk['target_columns']) {
                    $out[$key]['name'] = $name;
                    $out[$key]['deferred'] = $fk['deferred'];
                    $matched = true;
                    break;
                }
            }
            if ($matched) {
                continue;
            }
            $key = 'external:' . implode("\x1f", $fk['columns']) . "\x1e" . $fk['target_table'];
            $out[$key] = ['name' => $name, 'columns' => $fk['columns'], 'target' => $fk['target_table'], 'target_columns' => $fk['target_columns'],
                'on_delete' => $fk['on_delete'], 'deferred' => $fk['deferred']];
        }
        return $out;
    }

    /** @return list<array> */
    public static function sortedForeignKeys(array $m, array $e, string $dialect = ''): array
    {
        $byColumn = self::foreignKeys($m, $e, $dialect);
        return array_map(static fn(string $k): array => $byColumn[$k], self::sortedKeys($byColumn));
    }

    public static function foreignKeyClause(array $fk, array $m, string $dialect, \Closure $q): string
    {
        $target = isset($m['entities'][$fk['target']]) ? $m['entities'][$fk['target']]['table'] : $fk['target'];
        $stmt = 'CONSTRAINT ' . $q(self::boundedIdentifier(str_replace('.', '_', $fk['name']), $dialect)) . ' FOREIGN KEY (' . implode(', ', array_map($q, $fk['columns'])) . ') REFERENCES '
            . $q($target) . ' (' . implode(', ', array_map($q, $fk['target_columns'])) . ')';
        $stmt .= match ($fk['on_delete']) {
            'cascade' => ' ON DELETE CASCADE',
            'setnull' => ' ON DELETE SET NULL',
            default => ' ON DELETE RESTRICT',
        };
        if ($fk['deferred'] && ($dialect === 'postgres' || $dialect === 'sqlite')) {
            $stmt .= ' DEFERRABLE INITIALLY DEFERRED';
        }
        return $stmt;
    }

    /** The storage type of a column; MySQL keeps the declared type. */
    public const MYSQL_UUID = 'char(36)';
    public const MYSQL_JSONTEXT = 'longtext';

    public static function type(array $c, string $dialect): string
    {
        if ($dialect === 'mysql' && $c['raw'] !== '') {
            if (strcasecmp($c['raw'], 'uuid') === 0) {
                // MySQL has no uuid type; clients bind uuid values as text.
                return self::MYSQL_UUID;
            }
            if ($c['type'] === 'jsontext') {
                // jsontext keeps the stored text, which a document type would normalize.
                return self::MYSQL_JSONTEXT;
            }
            if ($c['type'] === 'enum') {
                // MySQL takes the enum values as string literals.
                return 'enum(' . implode(',', array_map(static fn(string $v): string => "'" . self::str($v) . "'", $c['enum'])) . ')';
            }
            $t = str_replace('_', ',', $c['raw']);
            if ($c['unsigned'] && !str_contains($t, 'unsigned')) {
                $t .= ' unsigned';
            }
            return $t;
        }
        $prec = static fn(int $n): string => $n > 0 ? "($n)" : '';
        if ($dialect === 'postgres') {
            $t = match ($c['type']) {
                'i32' => 'integer',
                'i64' => 'bigint',
                'f64' => 'double precision',
                'decimal' => "numeric({$c['precision']},{$c['scale']})",
                'bool' => 'boolean',
                'string', 'enum' => strcasecmp($c['raw'], 'uuid') === 0 ? 'uuid' : ($c['len'] > 0 ? "varchar({$c['len']})" : 'text'),
                'text' => 'text',
                'bytes' => 'bytea',
                'date' => 'date',
                'time' => 'time',
                'datetime' => 'timestamp' . $prec($c['precision']) . ' with time zone',
                // json keeps the stored text, so object member order survives.
                'jsontext' => 'text',
                'inet' => 'inet',
                'point' => 'point',
                default => null,
            };
            if ($t !== null) {
                return $t;
            }
        } elseif ($dialect === 'sqlite') {
            return match ($c['type']) {
                'i32', 'i64', 'bool' => 'INTEGER',
                'f64', 'decimal' => 'REAL',
                'bytes', 'inet' => 'BLOB',
                default => 'TEXT',
            };
        }
        throw new \RuntimeException("no $dialect type for {$c['type']}");
    }

    /** One column definition without table-level constraints or comments. */
    public static function column(array $c, string $dialect, \Closure $q): string
    {
        $type = self::type($c, $dialect);
        $line = $q($c['name']) . ' ' . $type;
        if (!$c['nullable']) {
            $line .= ' NOT NULL';
        }
        if ($c['default'] !== null) {
            $line .= ' DEFAULT ' . self::defaultExpression($c, $type, $dialect);
        }
        if ($c['on_update'] && $dialect === 'mysql') {
            $line .= ' ON UPDATE CURRENT_TIMESTAMP' . ($c['precision'] > 0 ? "({$c['precision']})" : '');
        }
        if ($c['auto'] && $dialect === 'mysql') {
            $line .= ' AUTO_INCREMENT';
        }
        if ($c['auto'] && $dialect === 'postgres') {
            $line .= ' GENERATED BY DEFAULT AS IDENTITY';
        }
        return $line;
    }

    /** A default value as an ALTER COLUMN SET DEFAULT expression. */
    public static function defaultValue(array $c, string $dialect): string
    {
        if ($c['default'] === null) {
            throw new \RuntimeException("column {$c['name']} has no default");
        }
        return self::defaultExpression($c, self::type($c, $dialect), $dialect);
    }

    /**
     * A column default. MySQL accepts a literal default for TEXT, BLOB, JSON,
     * and geometry columns only in the expression form DEFAULT (value).
     */
    public static function defaultExpression(array $c, string $type, string $dialect): string
    {
        $v = $c['default'];
        if ($v === 'now' && $dialect === 'sqlite') {
            // text timestamps with six fraction digits, the form the executor binds and compares
            return "(strftime('%Y-%m-%d %H:%M:%f', 'now') || '000')";
        }
        if ($v === 'now') {
            return $dialect === 'mysql' && $c['precision'] > 0 ? "CURRENT_TIMESTAMP({$c['precision']})" : 'CURRENT_TIMESTAMP';
        }
        if ($v === 'null') {
            return 'NULL';
        }
        if ($c['type'] === 'bool') {
            // MySQL BOOLEAN is TINYINT(1) and strict mode rejects a quoted
            // default; SQLite stores the value as INTEGER 0/1.
            $value = strtolower(trim($v, "'\""));
            $truthy = $value === '1' || $value === 'true';
            if ($dialect === 'postgres') {
                return $truthy ? 'true' : 'false';
            }
            return $truthy ? '1' : '0';
        }
        $expr = self::isNumber($v) ? $v : "'" . self::str(trim($v, "'")) . "'";
        if ($dialect === 'mysql' && preg_match('/text|blob|json|geometry|point|linestring|polygon/', strtolower($type)) === 1) {
            return '(' . $expr . ')';
        }
        return $expr;
    }

    /**
     * A CHECK expression for the dialect. MySQL rejects a CASE expression
     * with predicate branches as a CHECK definition, so MySQL receives
     * (expr) <> 0; NULL stays UNKNOWN and the CHECK accepts it.
     */
    public static function renderedCheckExpression(string $expr, string $dialect, \Closure $q): string
    {
        $rendered = self::checkExpression($expr, $q);
        return $dialect === 'mysql' ? '(' . $rendered . ') <> 0' : $rendered;
    }

    /** A CHECK expression with its backtick identifiers quoted for the dialect. */
    public static function checkExpression(string $expr, \Closure $q): string
    {
        $out = '';
        while ($expr !== '') {
            $start = strpos($expr, '`');
            if ($start === false) {
                $out .= $expr;
                break;
            }
            $out .= substr($expr, 0, $start);
            $rest = substr($expr, $start + 1);
            $end = strpos($rest, '`');
            if ($end === false) {
                throw new \RuntimeException('CHECK expression has an unterminated backtick identifier');
            }
            $name = substr($rest, 0, $end);
            if ($name === '' || strpbrk($name, "`\0") !== false) {
                throw new \RuntimeException('CHECK expression has an invalid backtick identifier');
            }
            $out .= $q($name);
            $expr = substr($rest, $end + 1);
        }
        return $out;
    }

    /**
     * Splits SQL text into statements, keeping quoted, commented, and
     * dollar-quoted semicolons; leading comment lines are dropped.
     * @return list<string>
     */
    public static function splitSql(string $text): array
    {
        $out = [];
        $start = 0;
        $quote = '';
        $lineComment = false;
        $blockComment = false;
        $dollarTag = '';
        $words = [];
        $depth = 0;
        $n = strlen($text);
        $flush = static function (int $end) use (&$out, &$start, $text): void {
            $s = SchemaParser::trim(substr($text, $start, $end - $start));
            if ($s === '') {
                return;
            }
            while (str_starts_with($s, '--')) {
                $i = strpos($s, "\n");
                $s = $i === false ? '' : SchemaParser::trim(substr($s, $i + 1));
            }
            if ($s !== '') {
                $out[] = $s;
            }
        };
        for ($i = 0; $i < $n; $i++) {
            $c = $text[$i];
            if ($lineComment) {
                if ($c === "\n") {
                    $lineComment = false;
                }
                continue;
            }
            if ($blockComment) {
                if ($c === '*' && $i + 1 < $n && $text[$i + 1] === '/') {
                    $blockComment = false;
                    $i++;
                }
                continue;
            }
            if ($dollarTag !== '') {
                if (substr($text, $i, strlen($dollarTag)) === $dollarTag) {
                    $i += strlen($dollarTag) - 1;
                    $dollarTag = '';
                }
                continue;
            }
            if ($quote !== '') {
                if ($c === $quote) {
                    if ($i + 1 < $n && $text[$i + 1] === $quote) {
                        $i++;
                        continue;
                    }
                    if ($i > 0 && $text[$i - 1] === '\\' && $quote === "'") {
                        continue;
                    }
                    $quote = '';
                } elseif ($c === '\\' && $quote === "'") {
                    $i++;
                }
                continue;
            }
            if ($c === '-' && $i + 1 < $n && $text[$i + 1] === '-') {
                $lineComment = true;
                $i++;
                continue;
            }
            if ($c === '/' && $i + 1 < $n && $text[$i + 1] === '*') {
                $blockComment = true;
                $i++;
                continue;
            }
            if ($c === "'" || $c === '"' || $c === '`') {
                $quote = $c;
                continue;
            }
            if ($c === '$') {
                $end = strpos($text, '$', $i + 1);
                if ($end !== false) {
                    $candidate = substr($text, $i, $end - $i + 1);
                    if (preg_match('/^\$(?:[_a-zA-Z][_a-zA-Z0-9]*)?\$$/', $candidate) === 1) {
                        $dollarTag = $candidate;
                        $i += strlen($candidate) - 1;
                        continue;
                    }
                }
            }
            if (self::wordStart($text, $i)) {
                $end = $i;
                while ($end < $n && self::wordByte($text[$end])) {
                    $end++;
                }
                $word = strtoupper(substr($text, $i, $end - $i));
                if (count($words) < 2) {
                    $words[] = $word;
                }
                if ($words === ['CREATE', 'TRIGGER']) {
                    if ($word === 'BEGIN' || $word === 'CASE') {
                        $depth++;
                    } elseif ($word === 'END' && !in_array(strtoupper(self::nextWord($text, $end)), ['IF', 'LOOP', 'WHILE', 'REPEAT'], true) && $depth > 0) {
                        $depth--;
                    }
                }
                $i = $end - 1;
                continue;
            }
            if ($c === ';' && $depth === 0) {
                $flush($i);
                $start = $i + 1;
                $words = [];
            }
        }
        $flush($n);
        return $out;
    }

    private static function wordByte(string $b): bool
    {
        return $b === '_' || ctype_alnum($b);
    }

    private static function wordStart(string $text, int $i): bool
    {
        $b = $text[$i];
        if (!($b === '_' || ctype_alpha($b))) {
            return false;
        }
        if ($i === 0) {
            return true;
        }
        $p = $text[$i - 1];
        return !self::wordByte($p) && $p !== '$' && $p !== '.' && $p !== '@';
    }

    private static function nextWord(string $text, int $i): string
    {
        $n = strlen($text);
        while ($i < $n && in_array($text[$i], [' ', "\t", "\n", "\r"], true)) {
            $i++;
        }
        $end = $i;
        while ($end < $n && self::wordByte($text[$end])) {
            $end++;
        }
        return substr($text, $i, $end - $i);
    }
}
