//! Code generated by ormgen errors from docs/errors.yaml; DO NOT EDIT.
//! Error codes shared by the engine and every executor (docs/errors.yaml).

/// engine: ir_version the engine does not speak
pub const VERSION_MISMATCH: &str = "VERSION_MISMATCH";
/// engine: client generated from another schema.json than the engine loaded
pub const SCHEMA_HASH_MISMATCH: &str = "SCHEMA_HASH_MISMATCH";
/// engine: schema.json failed validation at load
pub const SCHEMA_INVALID: &str = "SCHEMA_INVALID";
/// engine: wasm/ffi: orm_compile before orm_load
pub const SCHEMA_NOT_LOADED: &str = "SCHEMA_NOT_LOADED";
/// engine
pub const DIALECT_UNKNOWN: &str = "DIALECT_UNKNOWN";
/// engine: ormd: bad length-prefixed frame
pub const FRAME_INVALID: &str = "FRAME_INVALID";
/// engine: ormd: unknown op
pub const OP_UNKNOWN: &str = "OP_UNKNOWN";
/// engine: structural: missing fields, wrong combination, param index out of range
pub const IR_INVALID: &str = "IR_INVALID";
/// engine: requested operation is not supported by the selected dialect
pub const CAPABILITY_UNSUPPORTED: &str = "CAPABILITY_UNSUPPORTED";
/// engine
pub const ENTITY_UNKNOWN: &str = "ENTITY_UNKNOWN";
/// engine
pub const COLUMN_UNKNOWN: &str = "COLUMN_UNKNOWN";
/// engine
pub const RELATION_UNKNOWN: &str = "RELATION_UNKNOWN";
/// engine: force_index name not declared
pub const INDEX_UNKNOWN: &str = "INDEX_UNKNOWN";
/// engine: select<Col>As name collides with a column
pub const COLUMN_ALIAS_CONFLICT: &str = "COLUMN_ALIAS_CONFLICT";
/// engine
pub const OPERATOR_UNKNOWN: &str = "OPERATOR_UNKNOWN";
/// engine: op not valid for the column's type/style (ir.OpAllowed)
pub const OPERATOR_NOT_ALLOWED: &str = "OPERATOR_NOT_ALLOWED";
/// engine: or() as the first item of a group
pub const OR_AT_GROUP_START: &str = "OR_AT_GROUP_START";
/// engine: in()/notIn() with no values
pub const EMPTY_IN: &str = "EMPTY_IN";
/// engine: nav into a relation that was not joined in this statement
pub const ENTITY_NOT_JOINED: &str = "ENTITY_NOT_JOINED";
/// engine: limit() on a relation child (use limitPerParent)
pub const LIMIT_IN_RELATION: &str = "LIMIT_IN_RELATION";
/// executor: updateOptimistic matched no row (updated_ts changed)
pub const OPTIMISTIC_LOCK: &str = "OPTIMISTIC_LOCK";
/// executor: styled column bytes could not be decoded (docs/codec.md)
pub const CODEC_DECODE: &str = "CODEC_DECODE";
/// executor
pub const CODEC_ENCODE: &str = "CODEC_ENCODE";
/// executor: PHP objects/references in serialize, unknown style
pub const CODEC_UNSUPPORTED: &str = "CODEC_UNSUPPORTED";
/// executor: missing secret, bad DSN/paths, transaction misuse
pub const CONFIG: &str = "CONFIG";
/// executor
pub const INTERNAL: &str = "INTERNAL";
/// driver: MySQL 1213 / SQLSTATE 40001; retries require TransactionOptions
pub const DEADLOCK: &str = "DEADLOCK";
/// driver: MySQL 1062 / SQLSTATE 23000
pub const DUPLICATE_KEY: &str = "DUPLICATE_KEY";
