//! Code generated by ormgen errors from docs/errors.yaml; DO NOT EDIT.
//! Error codes shared by the engine and every executor (docs/errors.yaml).

/// engine: ir_version the engine does not speak
pub const VERSION_MISMATCH: &str = "VERSION_MISMATCH";
/// engine: client generated from another schema.json than the engine loaded
pub const SCHEMA_HASH_MISMATCH: &str = "SCHEMA_HASH_MISMATCH";
/// engine: schema.json failed validation at load
pub const SCHEMA_INVALID: &str = "SCHEMA_INVALID";
/// engine
pub const DIALECT_UNKNOWN: &str = "DIALECT_UNKNOWN";
/// engine: structural: missing fields, wrong combination, param index out of range
pub const IR_INVALID: &str = "IR_INVALID";
/// engine: requested operation is not supported by the selected dialect
pub const CAPABILITY_UNSUPPORTED: &str = "CAPABILITY_UNSUPPORTED";
/// engine
pub const ENTITY_UNKNOWN: &str = "ENTITY_UNKNOWN";
/// engine
pub const COLUMN_UNKNOWN: &str = "COLUMN_UNKNOWN";
/// engine
pub const RELATION_UNKNOWN: &str = "RELATION_UNKNOWN";
/// engine: force_index name not declared
pub const INDEX_UNKNOWN: &str = "INDEX_UNKNOWN";
/// engine: select<Col>As name collides with a column
pub const COLUMN_ALIAS_CONFLICT: &str = "COLUMN_ALIAS_CONFLICT";
/// engine
pub const OPERATOR_UNKNOWN: &str = "OPERATOR_UNKNOWN";
/// engine: ORM function name outside the column or value function catalog
pub const FUNCTION_UNKNOWN: &str = "FUNCTION_UNKNOWN";
/// engine: op not valid for the column's type/style (ir.OpAllowed)
pub const OPERATOR_NOT_ALLOWED: &str = "OPERATOR_NOT_ALLOWED";
/// engine: or() as the first item of a group
pub const OR_AT_GROUP_START: &str = "OR_AT_GROUP_START";
/// engine: in()/notIn() with no values
pub const EMPTY_IN: &str = "EMPTY_IN";
/// engine: joined placement or column reference to a join missing from this statement
pub const ENTITY_NOT_JOINED: &str = "ENTITY_NOT_JOINED";
/// engine: limit() on a relation child (use limitPerParent)
pub const LIMIT_IN_RELATION: &str = "LIMIT_IN_RELATION";
/// executor: strict one-row query matched no row
pub const NO_ROWS: &str = "NO_ROWS";
/// executor: updateOptimistic matched no row (updated_ts changed)
pub const OPTIMISTIC_LOCK: &str = "OPTIMISTIC_LOCK";
/// executor: styled column bytes could not be decoded (docs/codec.md)
pub const CODEC_DECODE: &str = "CODEC_DECODE";
/// executor
pub const CODEC_ENCODE: &str = "CODEC_ENCODE";
/// executor: PHP objects/references in serialize, unknown style
pub const CODEC_UNSUPPORTED: &str = "CODEC_UNSUPPORTED";
/// executor: missing secret, bad DSN/paths, transaction misuse
pub const CONFIG: &str = "CONFIG";
/// executor: the statement stopped before it finished: its context or abort signal was cancelled, or a timeout bound expired (statement timeout, transaction timeoutMs, SQLite busy_timeout)
pub const CANCELED: &str = "CANCELED";
/// executor
pub const INTERNAL: &str = "INTERNAL";
/// driver: a NOWAIT lock could not be acquired immediately
pub const LOCK_NOT_AVAILABLE: &str = "LOCK_NOT_AVAILABLE";
/// driver: MySQL 1213 / SQLSTATE 40001 / PostgreSQL 40P01 / SQLite LOCKED; retries require TransactionOptions
pub const DEADLOCK: &str = "DEADLOCK";
/// driver: MySQL 1062 / SQLSTATE 23000
pub const DUPLICATE_KEY: &str = "DUPLICATE_KEY";
/// driver: MySQL 1451/1452 / PostgreSQL 23503 / SQLite 787/1811
pub const FOREIGN_KEY: &str = "FOREIGN_KEY";
/// driver: MySQL 3819/4025 / PostgreSQL 23514 / SQLite 275
pub const CONSTRAINT: &str = "CONSTRAINT";
/// driver: a write rejected because the server or connection is read-only: MySQL 1290/1792 / PostgreSQL 25006 / SQLite 8 and its extended codes
pub const READ_ONLY: &str = "READ_ONLY";
