// dbspec 문서 집합을 한 dialect의 문장으로 쓴다 (docs/dialects.md "Rendered statements").
// 문장의 바이트는 tests/dbspec/ddl.json과 Go 엔진(engine/dbspec/render.go)과 같다.
import { readCheck, type CheckExpr } from './check.js';
import type { DbspecAction, DbspecColumn, DbspecDefault, DbspecDocument, DbspecForeignKey, DbspecTable, DbspecType } from './model.js';

export type DbspecDialect = 'mysql' | 'postgres' | 'sqlite';

const DIALECTS: ReadonlySet<string> = new Set(['mysql', 'postgres', 'sqlite']);

function compare(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

function sorted<T>(items: readonly T[], key: (item: T) => string): T[] {
  return [...items].sort((a, b) => compare(key(a), key(b)));
}

/**
 * Orders the documents so that a used document comes before the documents
 * that use it, ties by document name. A repeated document name or a used
 * document missing from the set is an Error.
 */
function useOrder(documents: readonly DbspecDocument[]): DbspecDocument[] {
  const byName = new Map<string, DbspecDocument>();
  for (const document of documents) {
    if (byName.has(document.name)) throw new Error(`document ${document.name} appears twice in the document set`);
    byName.set(document.name, document);
  }
  const out: DbspecDocument[] = [];
  const done = new Set<string>();
  const visit = (document: DbspecDocument): void => {
    if (done.has(document.name)) return;
    done.add(document.name);
    for (const name of sorted(document.uses.map(u => u.document), n => n)) {
      const used = byName.get(name);
      if (used === undefined) throw new Error(`document ${document.name} uses document ${name}, which is not in the document set`);
      visit(used);
    }
    out.push(document);
  };
  for (const name of sorted([...byName.keys()], n => n)) visit(byName.get(name)!);
  return out;
}

class Renderer {
  constructor(readonly d: DbspecDialect) {}

  /** Quotes an identifier. */
  q(name: string): string {
    return this.d === 'mysql' ? '`' + name + '`' : '"' + name + '"';
  }

  list(names: readonly string[]): string {
    return names.map(n => this.q(n)).join(', ');
  }

  table(t: DbspecTable): string[] {
    const parts = t.columns.map(c => this.column(c));
    if (!(this.d === 'sqlite' && t.columns.some(c => c.identity))) parts.push(`PRIMARY KEY (${this.list(t.primaryKey.columns)})`);
    if (this.d !== 'sqlite') {
      for (const u of sorted(t.uniques, u => u.name)) parts.push(`CONSTRAINT ${this.q(u.name)} UNIQUE (${this.list(u.columns)})`);
    } else {
      for (const f of sorted(t.foreignKeys, f => f.name)) parts.push(this.foreignKey(f));
    }
    for (const c of t.columns) {
      const check = this.typeCheck(c);
      if (check !== '') parts.push(`CONSTRAINT ${this.q(`${t.name}$${c.name}`)} CHECK (${check})`);
    }
    for (const k of sorted(t.checks, k => k.name)) {
      parts.push(`CONSTRAINT ${this.q(k.name)} CHECK (${this.predicate(t, readCheck(k.expression, k.name))})`);
    }
    let create = `CREATE TABLE ${this.q(t.name)} (${parts.join(', ')})`;
    if (this.d === 'mysql') create += ' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin';
    const out = [create];
    if (this.d === 'sqlite') {
      for (const u of sorted(t.uniques, u => u.name)) {
        out.push(`CREATE UNIQUE INDEX ${this.q(u.name)} ON ${this.q(t.name)} (${this.list(u.columns)})`);
      }
    }
    for (const x of sorted(t.indexes, x => x.name)) {
      const columns = x.columns.map(c => this.q(c.name) + (c.descending ? ' DESC' : ''));
      out.push(`CREATE INDEX ${this.q(x.name)} ON ${this.q(t.name)} (${columns.join(', ')})`);
    }
    return out;
  }

  column(c: DbspecColumn): string {
    if (c.identity) {
      switch (this.d) {
        case 'mysql':
          return `${this.q(c.name)} BIGINT NOT NULL AUTO_INCREMENT`;
        case 'postgres':
          return `${this.q(c.name)} bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL`;
        case 'sqlite':
          return `${this.q(c.name)} INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT`;
      }
    }
    let s = `${this.q(c.name)} ${this.typeText(c.type)} ${c.nullable ? 'NULL' : 'NOT NULL'}`;
    if (c.default !== null) s += ` DEFAULT ${this.defaultText(c.type, c.default)}`;
    return s;
  }

  typeText(t: DbspecType): string {
    switch (this.d) {
      case 'mysql':
        switch (t.kind) {
          case 'i16':
            return 'SMALLINT';
          case 'i32':
            return 'INT';
          case 'i64':
            return 'BIGINT';
          case 'bool':
            return 'tinyint(1)';
          case 'decimal':
            return `DECIMAL(${t.precision},${t.scale})`;
          case 'f64':
            return 'DOUBLE';
          case 'varchar':
            return `varchar(${t.length}) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin`;
          case 'text':
            return 'LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin';
          case 'bytes':
            return 'LONGBLOB';
          case 'uuid':
            return 'char(36) CHARACTER SET ascii COLLATE ascii_bin';
          case 'date':
            return 'DATE';
          case 'time':
            return `TIME(${t.precision})`;
          case 'datetime':
            return `DATETIME(${t.precision})`;
        }
      case 'postgres':
        switch (t.kind) {
          case 'i16':
            return 'smallint';
          case 'i32':
            return 'integer';
          case 'i64':
            return 'bigint';
          case 'bool':
            return 'boolean';
          case 'decimal':
            return `numeric(${t.precision},${t.scale})`;
          case 'f64':
            return 'double precision';
          case 'varchar':
            return `varchar(${t.length}) COLLATE "C"`;
          case 'text':
            return 'text COLLATE "C"';
          case 'bytes':
            return 'bytea';
          case 'uuid':
            return 'uuid';
          case 'date':
            return 'date';
          case 'time':
            return `time(${t.precision})`;
          case 'datetime':
            return `timestamp(${t.precision})`;
        }
      case 'sqlite':
        switch (t.kind) {
          case 'i16':
            return 'smallint';
          case 'i32':
            return 'integer';
          case 'i64':
            return 'bigint';
          case 'bool':
            return 'BOOLEAN';
          case 'decimal':
            return `DECIMALINT(${t.precision},${t.scale})`;
          case 'f64':
            return 'REAL';
          case 'varchar':
            return `varchar(${t.length})`;
          case 'text':
          case 'uuid':
            return 'TEXT';
          case 'bytes':
            return 'BLOB';
          case 'date':
            return 'DATE';
          case 'time':
            return 'TIME';
          case 'datetime':
            return 'DATETIME';
        }
    }
  }

  defaultText(t: DbspecType, d: DbspecDefault): string {
    if (d.kind === 'literal') return this.literal(t, d.text);
    if (t.kind !== 'datetime') throw new Error(`default now of a ${t.kind} column`);
    const p = t.precision;
    switch (this.d) {
      case 'mysql':
        return `CURRENT_TIMESTAMP(${p})`;
      case 'postgres':
        return 'statement_timestamp()';
      case 'sqlite':
        if (p === 0) return "(strftime('%Y-%m-%d %H:%M:%S', 'now'))";
        if (p <= 3) return `(substr(strftime('%Y-%m-%d %H:%M:%f', 'now'), 1, ${20 + p}))`;
        return `(strftime('%Y-%m-%d %H:%M:%f', 'now') || '${'0'.repeat(p - 3)}')`;
    }
  }

  /** A canonical literal of a column of type t (null: no column type) in the dialect. */
  literal(t: DbspecType | null, text: string): string {
    if (text === 'true' || text === 'false') {
      if (this.d === 'postgres') return text.toUpperCase();
      return text === 'true' ? '1' : '0';
    }
    if (text.startsWith("'")) return this.d === 'mysql' ? text.replaceAll('\\', '\\\\') : text;
    if (t !== null && t.kind === 'decimal' && this.d === 'sqlite') return scaledDecimal(text);
    return text;
  }

  foreignKey(f: DbspecForeignKey): string {
    return (
      `CONSTRAINT ${this.q(f.name)} FOREIGN KEY (${this.list(f.columns)}) REFERENCES ${this.q(f.table)} ` +
      `(${this.list(f.references)}) ON DELETE ${actionText(f.onDelete)} ON UPDATE ${actionText(f.onUpdate)}`
    );
  }

  /** The renderer CHECK of a column, or '' when the dialect enforces the type itself. */
  typeCheck(c: DbspecColumn): string {
    if (c.identity) return '';
    const q = this.q(c.name);
    const t = c.type;
    if (this.d === 'mysql') {
      switch (t.kind) {
        case 'bool':
          return `${q} IN (0, 1)`;
        case 'uuid':
          return `REGEXP_LIKE(${q}, '${UUID_PATTERN}', 'c')`;
        case 'time':
          return `${q} >= '00:00:00' AND ${q} < '24:00:00'`;
        default:
          return '';
      }
    }
    if (this.d === 'postgres') return t.kind === 'time' ? `${q} < '24:00:00'` : '';
    const integer = `typeof(${q}) IN ('integer', 'null')`;
    const digits = (n: number): string => '[0-9]'.repeat(n);
    switch (t.kind) {
      case 'i16':
        return `${integer} AND ${q} BETWEEN -32768 AND 32767`;
      case 'i32':
        return `${integer} AND ${q} BETWEEN -2147483648 AND 2147483647`;
      case 'i64':
        return integer;
      case 'bool':
        return `${q} IN (0, 1)`;
      case 'decimal': {
        const limit = '9'.repeat(t.precision);
        return `${integer} AND ${q} BETWEEN -${limit} AND ${limit}`;
      }
      case 'f64':
        return `typeof(${q}) IN ('real', 'null')`;
      case 'varchar':
        return `length(${q}) <= ${t.length}`;
      case 'uuid': {
        const hex = (n: number): string => '[0-9a-f]'.repeat(n);
        return `${q} GLOB '${hex(8)}-${hex(4)}-${hex(4)}-${hex(4)}-${hex(12)}'`;
      }
      case 'date':
        return `${q} IS date(${q})`;
      case 'time': {
        if (t.precision === 0) return `${q} IS time(${q}) AND ${q} < '24:00:00'`;
        const clock = `substr(${q}, 1, 8)`;
        return (
          `length(${q}) = ${9 + t.precision} AND ${clock} IS time(${clock}) AND ${clock} < '24:00:00' AND ` +
          `substr(${q}, 9, 1) = '.' AND substr(${q}, 10) GLOB '${digits(t.precision)}'`
        );
      }
      case 'datetime': {
        if (t.precision === 0) return `length(${q}) = 19 AND ${q} IS datetime(${q}) AND substr(${q}, 12, 2) < '24'`;
        const stamp = `substr(${q}, 1, 19)`;
        return (
          `length(${q}) = ${20 + t.precision} AND ${stamp} IS datetime(${stamp}) AND substr(${q}, 12, 2) < '24' AND ` +
          `substr(${q}, 20, 1) = '.' AND substr(${q}, 21) GLOB '${digits(t.precision)}'`
        );
      }
      case 'text':
      case 'bytes':
        return '';
    }
  }

  /** A check predicate of table t in the dialect. */
  predicate(t: DbspecTable, e: CheckExpr): string {
    switch (e.kind) {
      case 'column':
        return this.q(e.name);
      case 'literal':
        throw new Error(`check literal ${e.text} of table ${t.name} is not a predicate`);
      case 'not':
        return `NOT ${this.predicate(t, e.operand)}`;
      case 'paren':
        return `(${this.predicate(t, e.inner)})`;
      case 'logical':
        return `${this.predicate(t, e.left)} ${e.op.toUpperCase()} ${this.predicate(t, e.right)}`;
      case 'compare': {
        const type = operandType(t, e.left, e.right);
        return `${this.operand(type, e.left)} ${e.op} ${this.operand(type, e.right)}`;
      }
      case 'in': {
        const type = operandType(t, e.operand, null);
        const list = e.list.map(l => this.literal(type, l)).join(', ');
        return `${this.operand(type, e.operand)}${e.negated ? ' NOT' : ''} IN (${list})`;
      }
      case 'between': {
        const type = operandType(t, e.operand, null);
        return (
          `${this.operand(type, e.operand)}${e.negated ? ' NOT' : ''} BETWEEN ` +
          `${this.operand(type, e.low)} AND ${this.operand(type, e.high)}`
        );
      }
      case 'is_null':
        return `${this.operand(null, e.operand)} IS ${e.negated ? 'NOT NULL' : 'NULL'}`;
    }
  }

  operand(type: DbspecType | null, e: CheckExpr): string {
    if (e.kind === 'column') return this.q(e.name);
    if (e.kind === 'literal') return this.literal(type, e.text);
    throw new Error(`check operand ${e.kind} is not a column or a literal`);
  }

  /** The triggers of the immutable and audit settings. */
  triggers(t: DbspecTable): string[] {
    if (t.settings === null) return [];
    const out: string[] = [];
    if (t.settings.settings.some(s => s.kind === 'immutable')) {
      const message = `table ${t.name} is immutable`;
      out.push(...this.reject(t, 'immutable_update', 'BEFORE UPDATE', message));
      out.push(...this.reject(t, 'immutable_delete', 'BEFORE DELETE', message));
    }
    for (const a of t.settings.settings) {
      if (a.kind !== 'audit') continue;
      out.push(...this.history(t, a, 'audit_insert', 'AFTER INSERT', "'insert'", 'NULL'));
      out.push(...this.history(t, a, 'audit_update', 'AFTER UPDATE', "'update'", `OLD.${this.q(a.operation)}`));
      out.push(...this.reject(t, 'audit_delete', 'BEFORE DELETE', `table ${t.name} deletes through its soft delete column`));
    }
    return out;
  }

  /** The trigger <table>$<event> whose body is one statement; PostgreSQL wraps it in a function of the same name. */
  trigger(t: DbspecTable, event: string, timing: string, body: string, rejects: boolean): string[] {
    const name = this.q(`${t.name}$${event}`);
    const on = ` ${timing} ON ${this.q(t.name)} FOR EACH ROW `;
    switch (this.d) {
      case 'mysql':
        return [`CREATE TRIGGER ${name}${on}${body}`];
      case 'postgres': {
        const end = rejects ? 'END$$' : 'RETURN NULL; END$$';
        return [
          `CREATE FUNCTION ${name}() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN ${body}; ${end}`,
          `CREATE TRIGGER ${name}${on}EXECUTE FUNCTION ${name}()`,
        ];
      }
      case 'sqlite':
        return [`CREATE TRIGGER ${name}${on}BEGIN ${body}; END`];
    }
  }

  reject(t: DbspecTable, event: string, timing: string, message: string): string[] {
    let body: string;
    switch (this.d) {
      case 'mysql':
        body = `SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '${message}'`;
        break;
      case 'postgres':
        body = `RAISE EXCEPTION '${message}'`;
        break;
      case 'sqlite':
        body = `SELECT RAISE(ABORT, '${message}')`;
        break;
    }
    return this.trigger(t, event, timing, body, true);
  }

  history(
    t: DbspecTable,
    a: { readonly into: string; readonly action: string; readonly previous: string },
    event: string,
    timing: string,
    action: string,
    previous: string,
  ): string[] {
    const columns = [this.q(a.action), this.q(a.previous), ...t.columns.map(c => this.q(c.name))];
    const values = [action, previous, ...t.columns.map(c => `NEW.${this.q(c.name)}`)];
    const body = `INSERT INTO ${this.q(a.into)} (${columns.join(', ')}) VALUES (${values.join(', ')})`;
    return this.trigger(t, event, timing, body, false);
  }
}

const UUID_PATTERN = '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$';

function actionText(a: DbspecAction): string {
  switch (a) {
    case 'restrict':
      return 'RESTRICT';
    case 'cascade':
      return 'CASCADE';
    case 'set_null':
      return 'SET NULL';
  }
}

/** A canonical decimal literal times 10^scale: its digits without the point and leading zeros. */
function scaledDecimal(text: string): string {
  const negative = text.startsWith('-');
  const digits = (negative ? text.slice(1) : text).replace('.', '').replace(/^0+/, '');
  if (digits === '') return '0';
  return negative ? '-' + digits : digits;
}

/** The type of the column among the operands; a validated comparison has at least one column. */
function operandType(t: DbspecTable, a: CheckExpr, b: CheckExpr | null): DbspecType | null {
  for (const e of [a, b]) {
    if (e === null || e.kind !== 'column') continue;
    const column = t.columns.find(c => c.name === e.name);
    if (column === undefined) throw new Error(`check column ${e.name} is not a column of table ${t.name}`);
    return column.type;
  }
  return null;
}

/**
 * Writes the statements that create the tables of a parsed document set in
 * one dialect (docs/dialects.md "Rendered statements"): documents in `use`
 * order, tables in document order. An unknown dialect is a TypeError.
 */
export function renderDbspec(documents: readonly DbspecDocument[], dialect: DbspecDialect): readonly string[] {
  if (!DIALECTS.has(dialect)) throw new TypeError(`unknown dbspec dialect ${String(dialect)}`);
  if (!Array.isArray(documents)) throw new TypeError('dbspec documents must be an array of parsed documents');
  const r = new Renderer(dialect);
  const ordered = useOrder(documents);
  const out: string[] = [];
  for (const document of ordered) for (const t of document.tables) out.push(...r.table(t));
  if (dialect !== 'sqlite') {
    for (const document of ordered) {
      for (const t of document.tables) {
        for (const f of sorted(t.foreignKeys, f => f.name)) out.push(`ALTER TABLE ${r.q(t.name)} ADD ${r.foreignKey(f)}`);
      }
    }
  }
  for (const document of ordered) for (const t of document.tables) out.push(...r.triggers(t));
  return Object.freeze(out);
}
