// ormgen errors: docs/errors.yaml → one constants file per language, so every client names the
// same codes (docs/checklist.md T5.2). The yaml is a flat list; no YAML library is needed.
//
//	ormgen errors --lang go --out clients/go/orm/codes.go
//	ormgen errors --lang php --out clients/php/src/Code.php
//	ormgen errors --lang rust --out clients/rust/orm/src/codes.rs
package ormgen

import (
	"flag"
	"fmt"
	"os"
	"strings"
)

type errCode struct{ Code, Origin, Comment string }

func readErrorCodes(path string) ([]errCode, error) {
	src, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var out []errCode
	for _, line := range strings.Split(string(src), "\n") {
		t := strings.TrimSpace(line)
		switch {
		case strings.HasPrefix(t, "- code:"):
			rest := strings.TrimSpace(strings.TrimPrefix(t, "- code:"))
			code, comment, _ := strings.Cut(rest, "#")
			out = append(out, errCode{Code: strings.TrimSpace(code), Comment: strings.TrimSpace(comment)})
		case strings.HasPrefix(t, "origin:") && len(out) > 0:
			out[len(out)-1].Origin = strings.TrimSpace(strings.TrimPrefix(t, "origin:"))
		}
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("%s: no codes found", path)
	}
	return out, nil
}

func errorsCmd(args []string) {
	fs := flag.NewFlagSet("errors", flag.ExitOnError)
	lang := fs.String("lang", "", "go|php|rust (required)")
	out := fs.String("out", "", "output file (required)")
	yaml := fs.String("yaml", "docs/errors.yaml", "error catalog")
	fs.Parse(args)
	if *lang == "" || *out == "" {
		fmt.Fprintln(os.Stderr, "usage: ormgen errors --lang go|php|rust --out <file> [--yaml docs/errors.yaml]")
		os.Exit(2)
	}
	codes, err := readErrorCodes(*yaml)
	if err != nil {
		fail(err)
	}
	var sb strings.Builder
	switch *lang {
	case "go":
		sb.WriteString("// Code generated by ormgen errors from docs/errors.yaml; DO NOT EDIT.\n\npackage orm\n\n// Error codes shared by the engine and every executor (docs/errors.yaml).\nconst (\n")
		for _, c := range codes {
			detail := strings.TrimSpace(c.Comment)
			note := c.Origin
			if detail != "" {
				note += ": " + detail
			}
			sb.WriteString(fmt.Sprintf("\tCode%s = %q // %s\n", pascal(strings.ToLower(c.Code)), c.Code, note))
		}
		sb.WriteString(")\n")
	case "php":
		sb.WriteString("<?php\n// Code generated by ormgen errors from docs/errors.yaml; DO NOT EDIT.\ndeclare(strict_types=1);\n\nnamespace Orm;\n\n/** Error codes shared by the engine and every executor (docs/errors.yaml). */\nfinal class Code\n{\n")
		for _, c := range codes {
			detail := strings.TrimSpace(c.Comment)
			note := c.Origin
			if detail != "" {
				note += ": " + detail
			}
			sb.WriteString(fmt.Sprintf("    /** %s */\n    public const %s = '%s';\n", note, c.Code, c.Code))
		}
		sb.WriteString("}\n")
	case "rust":
		sb.WriteString("//! Code generated by ormgen errors from docs/errors.yaml; DO NOT EDIT.\n//! Error codes shared by the engine and every executor (docs/errors.yaml).\n\n")
		for _, c := range codes {
			detail := strings.TrimSpace(c.Comment)
			note := c.Origin
			if detail != "" {
				note += ": " + detail
			}
			sb.WriteString(fmt.Sprintf("/// %s\npub const %s: &str = %q;\n", note, c.Code, c.Code))
		}
	default:
		fail(fmt.Errorf("unknown lang %q", *lang))
	}
	if err := os.WriteFile(*out, []byte(sb.String()), 0o644); err != nil {
		fail(err)
	}
	fmt.Fprintf(os.Stderr, "ormgen: %d codes → %s\n", len(codes), *out)
}
