package ormgen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/polyspec/orm/engine/schema"
)

// Go generator. Every model gets its fixed column methods; the methods named
// by the chain grammar are generated for the calls found in the scanned
// consumer packages (gen_go_scan.go), so the package contains exactly the
// chains the program uses.

// goModel is one entity with the usage-derived methods found so far.
type goModel struct {
	e       *schema.Entity
	typ     string // ProductModel
	ctor    string // Product
	static  map[string]bool
	methods map[string]string // name -> generated code
	getters map[string]getter
}

// getter is a usage-derived Get<Name> method.
type getter struct {
	result string // Go result type
	expr   string // body expression
	origin string
}

type goGen struct {
	m       *schema.Manifest
	out     string
	pkg     string
	models  map[string]*goModel // by entity name
	byType  map[string]*goModel // by model type name
	tuples  map[string]string   // tuple type name -> declaration
	constr  map[string]string   // constraint name -> declaration
	owners  map[string]bool     // column names used as a comparison target
	errors  []string
	pending bool
}

// GenerateGo writes the Go models of m to outDir. pkg is the package name
// (the directory name when empty); scan lists the package patterns whose model
// calls are generated.
func GenerateGo(m *schema.Manifest, outDir, pkg string, scan []string) error {
	return generateGo(m, outDir, pkg, scan)
}

func genGo(m *schema.Manifest, out string, scan []string) error { return generateGo(m, out, "", scan) }

func generateGo(m *schema.Manifest, out, pkg string, scan []string) error {
	if err := checkColumnNames(m); err != nil {
		return err
	}
	if pkg == "" {
		abs, err := filepath.Abs(out)
		if err != nil {
			return err
		}
		pkg = filepath.Base(abs)
	}
	g := &goGen{m: m, out: out, pkg: pkg, models: map[string]*goModel{}, byType: map[string]*goModel{}, tuples: map[string]string{}, constr: map[string]string{}, owners: map[string]bool{}}
	if !isIdent(g.pkg) {
		return fmt.Errorf("output directory name %q is not a Go package name", g.pkg)
	}
	for _, name := range m.Order {
		e := m.Entities[name]
		gm := &goModel{e: e, typ: pascal(name) + "Model", ctor: pascal(name), methods: map[string]string{}, getters: map[string]getter{}}
		gm.static = g.staticNames(gm)
		for _, c := range e.Columns {
			if gm.static[pascal(c.Name)] {
				return fmt.Errorf("%s.%s: the condition method %s is also a fixed method of %s", name, c.Name, pascal(c.Name), gm.typ)
			}
		}
		g.models[name] = gm
		g.byType[gm.typ] = gm
	}
	if err := os.MkdirAll(out, 0o755); err != nil {
		return err
	}
	if err := g.clean(); err != nil {
		return err
	}
	if err := g.write(); err != nil {
		return err
	}
	if len(scan) == 0 {
		return nil
	}
	return g.scan(scan)
}

func isIdent(s string) bool {
	if s == "" {
		return false
	}
	for i, r := range s {
		if !(r == '_' || r >= 'a' && r <= 'z' || i > 0 && r >= '0' && r <= '9') {
			return false
		}
	}
	return !goReserved[s]
}

var goReserved = map[string]bool{"break": true, "case": true, "chan": true, "const": true, "continue": true, "default": true, "defer": true, "else": true, "fallthrough": true, "for": true, "func": true, "go": true, "goto": true, "if": true, "import": true, "interface": true, "map": true, "package": true, "range": true, "return": true, "select": true, "struct": true, "switch": true, "type": true, "var": true}

// clean removes files generated by an earlier run.
func (g *goGen) clean() error {
	files, err := filepath.Glob(filepath.Join(g.out, "*.go"))
	if err != nil {
		return err
	}
	for _, f := range files {
		b, err := os.ReadFile(f)
		if err != nil {
			return err
		}
		if bytes.HasPrefix(b, []byte(generatedHeader)) {
			if err := os.Remove(f); err != nil {
				return err
			}
		}
	}
	return nil
}

const generatedHeader = "// Code generated by ormgen; DO NOT EDIT.\n"

// fixed per-model method names.
var fixedMethods = []string{"Orm_", "MarshalJSON", "ToArray", "Connect", "And", "Or", "Raw", "AndRaw", "OrRaw", "On", "Relation", "Relations",
	"Get", "Gets", "GetCount", "GetsCount", "GetSum", "GetAvg", "GetsPage", "GetQuery", "Create", "Creates", "Update", "Save", "Delete",
	"Duplication", "Limit", "OrderByRandom", "OrderByRaw", "GroupByRaw", "RemoveAllColumns", "AddAllColumns", "ParentNode", "GroupLimit",
	"DeleteLock", "FetchKey", "FetchValue", "ForUpdate", "ForShare", "ForUpdateNoWait", "ForShareNoWait", "AddRawColumn"}

func numeric(c *schema.Col) bool {
	return len(appStyles(c)) == 0 && (c.Type == "i32" || c.Type == "i64" || c.Type == "f64" || c.Type == "decimal")
}

func (g *goGen) staticNames(gm *goModel) map[string]bool {
	out := map[string]bool{}
	for _, n := range fixedMethods {
		out[n] = true
	}
	for _, c := range gm.e.Columns {
		p := pascal(c.Name)
		for _, prefix := range []string{"Get", "Set", "SetRaw", "AddColumn", "RemoveColumn", "GroupBy", "KeyName"} {
			out[prefix+p] = true
		}
		out["OrderBy"+p+"Asc"] = true
		out["OrderBy"+p+"Desc"] = true
		if numeric(c) {
			for _, prefix := range []string{"Plus", "Minus", "Sum", "Avg"} {
				out[prefix+p] = true
			}
		}
	}
	for name := range gm.e.Indexes {
		out["ForceIndex"+pascal(name)] = true
	}
	return out
}

// goType is the Go field type of a column.
func goType(c *schema.Col) string {
	if len(appStyles(c)) > 0 || c.Type == "jsontext" {
		return "any"
	}
	switch c.Type {
	case "i32":
		return "int32"
	case "i64":
		return "int64"
	case "f64", "decimal":
		return "float64"
	case "bool":
		return "bool"
	case "date", "datetime":
		return "time.Time"
	case "bytes":
		return "[]byte"
	case "point":
		return "orm.Point"
	}
	return "string"
}

func fieldType(c *schema.Col) string {
	t := goType(c)
	if c.Nullable && t != "any" && t != "[]byte" {
		return "*" + t
	}
	return t
}

func convert(t string) string {
	switch t {
	case "int32":
		return "int32(orm.AsInt64(v))"
	case "int64":
		return "orm.AsInt64(v)"
	case "float64":
		return "orm.AsFloat64(v)"
	case "bool":
		return "orm.AsBool(v)"
	case "time.Time":
		return "orm.AsTime(v)"
	case "orm.Point":
		return "orm.AsPoint(v)"
	case "[]byte":
		return "orm.AsBytes(v)"
	case "any":
		return "v"
	}
	return "orm.AsString(v)"
}

func field(c *schema.Col) string {
	name := "f" + pascal(c.Name)
	return name
}

func (g *goGen) write() error {
	var b bytes.Buffer
	b.WriteString(generatedHeader)
	fmt.Fprintf(&b, "\npackage %s\n\nimport (\n\t\"os\"\n\t\"time\"\n\n\t\"github.com/polyspec/orm/clients/go/orm\"\n\t\"github.com/polyspec/orm/engine\"\n\t\"github.com/polyspec/orm/engine/schema\"\n)\n\n", g.pkg)
	b.WriteString("var _ time.Time\n\n")
	fmt.Fprintf(&b, "// SchemaHash is the hash of the schema the models were generated from.\nconst SchemaHash = %q\n\nvar ormSchema = &orm.Schema{Hash: SchemaHash}\n\n", g.m.SchemaHash)
	b.WriteString(`// Connect opens the database selected by the DSN URI with the schema at
// schemaPath, which must be the schema the models were generated from.
func Connect(dsn, schemaPath string, cfg orm.Config) (*orm.DB, error) {
	js, err := os.ReadFile(schemaPath)
	if err != nil {
		return nil, err
	}
	m, err := schema.Load(js)
	if err != nil {
		return nil, err
	}
	driver, err := orm.DriverFromDSN(dsn)
	if err != nil {
		return nil, err
	}
	e, err := engine.New(m, driver)
	if err != nil {
		return nil, err
	}
	if err := orm.CheckSchemaHash(e, SchemaHash); err != nil {
		return nil, err
	}
	return orm.Open(dsn, e, cfg)
}
`)
	g.writeConstraints(&b)
	if err := writeFormatted(filepath.Join(g.out, "orm.go"), b.Bytes()); err != nil {
		return err
	}
	for _, name := range g.m.Order {
		if err := g.writeModel(g.models[name]); err != nil {
			return err
		}
	}
	return nil
}

func writeFormatted(path string, src []byte) error {
	out, err := format.Source(src)
	if err != nil {
		return fmt.Errorf("%s: %v\n%s", path, err, src)
	}
	return os.WriteFile(path, out, 0o644)
}

// value constraints

var scalarTerms = map[string][]string{
	"int":     {"~int", "~int8", "~int16", "~int32", "~int64", "~uint", "~uint8", "~uint16", "~uint32", "~uint64"},
	"float":   {"~int", "~int8", "~int16", "~int32", "~int64", "~uint", "~uint8", "~uint16", "~uint32", "~uint64", "~float32", "~float64"},
	"decimal": {"~int", "~int8", "~int16", "~int32", "~int64", "~uint", "~uint8", "~uint16", "~uint32", "~uint64", "~float32", "~float64", "~string"},
	"string":  {"~string"},
	"bool":    {"~bool"},
	"time":    {"time.Time", "~string"},
	"bytes":   {"~[]byte"},
	"point":   nil,
	"none":    nil,
}

func category(c *schema.Col) string {
	if len(appStyles(c)) > 0 || c.Type == "jsontext" {
		return "none"
	}
	switch c.Type {
	case "i32", "i64":
		return "int"
	case "f64":
		return "float"
	case "decimal":
		return "decimal"
	case "bool":
		return "bool"
	case "date", "datetime":
		return "time"
	case "bytes":
		return "bytes"
	case "point":
		return "point"
	}
	return "string"
}

func listTerms(terms []string) []string {
	var out []string
	for _, t := range terms {
		if strings.HasPrefix(t, "~") {
			out = append(out, "~[]"+t[1:])
		} else {
			out = append(out, "[]"+t)
		}
	}
	return out
}

// constraint returns the constraint name for a key shape of a column.
func (g *goGen) constraint(c *schema.Col, shape string) string {
	cat := category(c)
	name := "arg" + pascal(cat) + pascal(shape)
	if c.Nullable && shape == "eq" {
		name += "Null"
	}
	if _, ok := g.constr[name]; ok {
		return name
	}
	scalar := scalarTerms[cat]
	var terms []string
	switch shape {
	case "eq":
		terms = append(terms, scalar...)
		terms = append(terms, listTerms(scalar)...)
		terms = append(terms, "orm.Func")
		if cat != "point" && cat != "none" {
			terms = append(terms, "ormModel")
		}
		if c.Nullable {
			terms = append(terms, "orm.NullType")
		}
	case "cmp":
		terms = append(terms, scalar...)
		terms = append(terms, "orm.Func")
	case "like":
		terms = []string{"~string"}
	case "between":
		for _, t := range scalar {
			if strings.HasPrefix(t, "~") {
				terms = append(terms, "~[2]"+t[1:])
			} else {
				terms = append(terms, "[2]"+t)
			}
		}
	}
	g.constr[name] = fmt.Sprintf("type %s interface {\n\t%s\n}\n", name, strings.Join(terms, " | "))
	return name
}

func (g *goGen) ownerConstraint(column string) string {
	g.owners[column] = true
	return "has" + pascal(column)
}

func (g *goGen) writeConstraints(b *bytes.Buffer) {
	var models []string
	for _, name := range g.m.Order {
		models = append(models, "*"+g.models[name].typ)
	}
	fmt.Fprintf(b, "// ormModel is any generated model; a model value is a subquery.\ntype ormModel interface {\n\t%s\n}\n\n", strings.Join(models, " | "))
	names := make([]string, 0, len(g.constr))
	for n := range g.constr {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		b.WriteString(g.constr[n])
		b.WriteString("\n")
	}
	owners := make([]string, 0, len(g.owners))
	for c := range g.owners {
		owners = append(owners, c)
	}
	sort.Strings(owners)
	for _, c := range owners {
		var terms []string
		for _, name := range g.m.Order {
			if g.m.Entities[name].Column(c) != nil {
				terms = append(terms, "*"+g.models[name].typ)
			}
		}
		fmt.Fprintf(b, "// has%s is a model with the column %s.\ntype has%s interface {\n\t%s\n\tOrm_() *orm.Core\n}\n\n", pascal(c), c, pascal(c), strings.Join(terms, " | "))
	}
	tuples := make([]string, 0, len(g.tuples))
	for t := range g.tuples {
		tuples = append(tuples, t)
	}
	sort.Strings(tuples)
	for _, t := range tuples {
		b.WriteString(g.tuples[t])
		b.WriteString("\n")
	}
}

func (g *goGen) writeModel(gm *goModel) error {
	e := gm.e
	t, v := gm.typ, "x"
	var b bytes.Buffer
	b.WriteString(generatedHeader)
	fmt.Fprintf(&b, "\npackage %s\n\nimport (\n\t\"time\"\n\n\t\"github.com/polyspec/orm/clients/go/orm\"\n)\n\nvar _ time.Time\n\n", g.pkg)
	ent := lowerFirst(gm.ctor) + "Entity"
	fmt.Fprintf(&b, "// %s is a %s model or row.\ntype %s struct {\n\tm *orm.Core\n", t, e.Name, t)
	for _, c := range e.Columns {
		fmt.Fprintf(&b, "\t%s %s\n", field(c), fieldType(c))
	}
	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "var %s = &orm.Entity{Name: %q, Schema: ormSchema, New: func(c *orm.Core) orm.Model { x := &%s{m: c}; c.Bind(x); return x },\n", ent, e.Name, t)
	fmt.Fprintf(&b, "\tAssign: func(m orm.Model, name string, v any) bool { return m.(*%s).assign(name, v) },\n", t)
	fmt.Fprintf(&b, "\tValue: func(m orm.Model, name string) (any, bool) { return m.(*%s).value(name) },\n", t)
	fmt.Fprintf(&b, "\tCollect: func(keys []orm.Key, items map[orm.Key]*orm.Core, fetched map[orm.Key]any) any { return orm.CollectOf[*%s](keys, items, fetched) },\n}\n\n", t)
	fmt.Fprintf(&b, "// %s creates a %s model.\nfunc %s() *%s { return %s.New(orm.NewCore(%s)).(*%s) }\n\n", gm.ctor, e.Name, gm.ctor, t, ent, ent, t)
	fmt.Fprintf(&b, "func (%s *%s) Orm_() *orm.Core { return %s.m }\n\n", v, t, v)
	fmt.Fprintf(&b, "// MarshalJSON writes the row values in order.\nfunc (x *%s) MarshalJSON() ([]byte, error) { return x.m.MarshalJSON() }\n\n", t)
	fmt.Fprintf(&b, "// ToArray returns the row values.\nfunc (x *%s) ToArray() map[string]any { return x.m.ToArray() }\n\n", t)

	b.WriteString("func (x *" + t + ") assign(name string, v any) bool {\n\tswitch name {\n")
	for _, c := range e.Columns {
		gt := goType(c)
		fmt.Fprintf(&b, "\tcase %q:\n", c.Name)
		if fieldType(c) != gt {
			fmt.Fprintf(&b, "\t\tif v == nil {\n\t\t\tx.%s = nil\n\t\t} else {\n\t\t\tt := %s\n\t\t\tx.%s = &t\n\t\t}\n", field(c), convert(gt), field(c))
		} else {
			fmt.Fprintf(&b, "\t\tx.%s = %s\n", field(c), convert(gt))
		}
	}
	b.WriteString("\tdefault:\n\t\treturn false\n\t}\n\treturn true\n}\n\n")
	b.WriteString("func (x *" + t + ") value(name string) (any, bool) {\n\tswitch name {\n")
	for _, c := range e.Columns {
		fmt.Fprintf(&b, "\tcase %q:\n", c.Name)
		if fieldType(c) != goType(c) {
			fmt.Fprintf(&b, "\t\tif x.%s == nil {\n\t\t\treturn nil, true\n\t\t}\n\t\treturn *x.%s, true\n", field(c), field(c))
		} else {
			fmt.Fprintf(&b, "\t\treturn x.%s, true\n", field(c))
		}
	}
	b.WriteString("\t}\n\treturn nil, false\n}\n\n")

	fixed := (`// Connect sets the connection.
func (x *T) Connect(db *orm.DB) *T { x.m.Connect(db); return x }

// And joins the next condition with AND, opens an AND group with a callback,
// or places the conditions of a joined model.
func (x *T) And(args ...any) *T { return x.connector("and", args) }

// Or joins the next condition with OR, opens an OR group with a callback, or
// places the conditions of a joined model.
func (x *T) Or(args ...any) *T { return x.connector("or", args) }

func (x *T) connector(conn string, args []any) *T {
	if len(args) == 1 {
		if fn, ok := args[0].(func(*T)); ok {
			g := ENT.New(x.m.Group()).(*T)
			fn(g)
			x.m.AddGroup(conn, g.m)
			return x
		}
	}
	x.m.Connector(conn, args)
	return x
}

// Raw adds a raw first condition.
func (x *T) Raw(sql string, binds ...any) *T { x.m.Raw("", sql, binds); return x }

// AndRaw adds a raw condition joined with AND.
func (x *T) AndRaw(sql string, binds ...any) *T { x.m.Raw("and", sql, binds); return x }

// OrRaw adds a raw condition joined with OR.
func (x *T) OrRaw(sql string, binds ...any) *T { x.m.Raw("or", sql, binds); return x }

// On sets the join ON conditions.
func (x *T) On(fn func(*T)) *T {
	g := ENT.New(x.m.Group()).(*T)
	fn(g)
	x.m.On(g.m)
	return x
}

// Relation attaches one related row loaded by a separate query.
func (x *T) Relation(child orm.Model) *T { x.m.Relation(false, child); return x }

// Relations attaches related rows loaded by a separate query.
func (x *T) Relations(child orm.Model) *T { x.m.Relation(true, child); return x }

// Get returns the first matching row. It returns orm.CodeNoRows when no row matches.
func (x *T) Get() (*T, error) { return one(x.m) }

func one(c *orm.Core) (*T, error) {
	m, err := c.Get()
	if m == nil {
		return nil, err
	}
	return m.(*T), err
}

// Gets returns the matching rows.
func (x *T) Gets() (*orm.Collection[*T], error) { return orm.Gets[*T](x.m) }

// GetCount returns the number of matching rows.
func (x *T) GetCount() (int64, error) { return x.m.GetCount() }

// GetsCount returns grouped rows with row_count.
func (x *T) GetsCount() (*orm.Collection[*T], error) { return orm.GetsCount[*T](x.m) }

// GetSum returns the sum of the column selected with Sum<Col>.
func (x *T) GetSum() (float64, error) { return x.m.GetSum() }

// GetAvg returns the average of the column selected with Avg<Col>.
func (x *T) GetAvg() (float64, error) { return x.m.GetAvg() }

// GetsPage returns one page of matching rows.
func (x *T) GetsPage(page, perPage int) (*orm.Page[*T], error) { return orm.GetsPage[*T](x.m, page, perPage) }

// GetQuery returns the statement of Gets without executing it.
func (x *T) GetQuery() (*orm.Statement, error) { return x.m.GetQuery() }

// Create inserts the row and returns the created row.
func (x *T) Create() (*T, error) {
	m, err := x.m.Create()
	if err != nil {
		return nil, err
	}
	return m.(*T), nil
}

// Creates inserts rows in one transaction and returns the inserted row count.
func (x *T) Creates(rows []*T) (int64, error) { return orm.Creates(x.m, rows) }

// Update writes the changed columns; Update(true) requires an unchanged updated time.
func (x *T) Update(optimistic ...bool) (*T, error) {
	if err := x.m.Update(optimistic); err != nil {
		return nil, err
	}
	return x, nil
}

// Save updates the row when its primary key is known, otherwise creates it.
func (x *T) Save() (*T, error) {
	m, err := x.m.Save()
	if err != nil {
		return nil, err
	}
	return m.(*T), nil
}

// Delete deletes the row; Delete(true) first deletes loaded related rows.
func (x *T) Delete(recursive ...bool) error { return x.m.Delete(recursive) }

// Duplication sets the duplicate-key update of the next Create.
func (x *T) Duplication(m *T) *T { x.m.Duplication(m); return x }

// Limit sets the row range.
func (x *T) Limit(offset, count int) *T { x.m.Limit(offset, count); return x }

// OrderByRandom orders rows randomly.
func (x *T) OrderByRandom() *T { x.m.OrderByRandom(); return x }

// OrderByRaw appends a raw order expression.
func (x *T) OrderByRaw(sql string) *T { x.m.OrderByRaw(sql); return x }

// GroupByRaw appends a raw grouping expression.
func (x *T) GroupByRaw(sql string) *T { x.m.GroupByRaw(sql); return x }

// RemoveAllColumns keeps only primary and foreign keys.
func (x *T) RemoveAllColumns() *T { x.m.RemoveAllColumns(); return x }

// AddAllColumns selects every column.
func (x *T) AddAllColumns() *T { x.m.AddAllColumns(); return x }

// ParentNode merges the related row into the parent row.
func (x *T) ParentNode() *T { x.m.ParentNode(); return x }

// GroupLimit limits related rows per parent.
func (x *T) GroupLimit(n int) *T { x.m.GroupLimit(n); return x }

// DeleteLock excludes the relation from recursive delete.
func (x *T) DeleteLock() *T { x.m.DeleteLock(); return x }

// FetchKey computes the collection key of each row.
func (x *T) FetchKey(fn func(*T) any) *T { x.m.FetchKey(func(m orm.Model) any { return fn(m.(*T)) }); return x }

// FetchValue computes a value for each loaded row.
func (x *T) FetchValue(fn func(*T) any) *T { x.m.FetchValue(func(m orm.Model) any { return fn(m.(*T)) }); return x }

// ForUpdate locks the selected rows for update inside a transaction.
func (x *T) ForUpdate() *T { x.m.Lock("update"); return x }

// ForShare locks the selected rows for share inside a transaction.
func (x *T) ForShare() *T { x.m.Lock("share"); return x }

// ForUpdateNoWait locks for update without waiting.
func (x *T) ForUpdateNoWait() *T { x.m.Lock("update_nowait"); return x }

// ForShareNoWait locks for share without waiting.
func (x *T) ForShareNoWait() *T { x.m.Lock("share_nowait"); return x }
`)
	fixed = strings.ReplaceAll(fixed, "func one(", "func one"+gm.ctor+"(")
	fixed = strings.ReplaceAll(fixed, "return one(x.m)", "return one"+gm.ctor+"(x.m)")
	fixed = strings.ReplaceAll(fixed, "ENT", ent)
	fixed = strings.ReplaceAll(fixed, "*T", "*"+t)
	b.WriteString(fixed)
	b.WriteString("\n")

	for _, c := range e.Columns {
		p, f, gt, ft := pascal(c.Name), field(c), goType(c), fieldType(c)
		fmt.Fprintf(&b, "// Get%s returns %s.\nfunc (x *%s) Get%s() %s { return x.%s }\n\n", p, c.Name, t, p, ft, f)
		if ft != gt {
			fmt.Fprintf(&b, "// Set%s sets %s; nil stores NULL.\nfunc (x *%s) Set%s(v %s) *%s {\n\tx.%s = v\n\tif v == nil {\n\t\tx.m.SetNull(%q)\n\t} else {\n\t\tx.m.Set(%q, *v)\n\t}\n\treturn x\n}\n\n", p, c.Name, t, p, ft, t, f, c.Name, c.Name)
		} else {
			fmt.Fprintf(&b, "// Set%s sets %s.\nfunc (x *%s) Set%s(v %s) *%s { x.%s = v; x.m.Set(%q, v); return x }\n\n", p, c.Name, t, p, gt, t, f, c.Name)
		}
		fmt.Fprintf(&b, "func (x *%s) SetRaw%s(sql string, binds ...any) *%s { x.m.SetRaw(%q, sql, binds); return x }\n", t, p, t, c.Name)
		fmt.Fprintf(&b, "func (x *%s) AddColumn%s() *%s { x.m.AddColumn(%q); return x }\n", t, p, t, c.Name)
		fmt.Fprintf(&b, "func (x *%s) RemoveColumn%s() *%s { x.m.RemoveColumn(%q); return x }\n", t, p, t, c.Name)
		fmt.Fprintf(&b, "func (x *%s) GroupBy%s() *%s { x.m.GroupBy(%q); return x }\n", t, p, t, c.Name)
		fmt.Fprintf(&b, "func (x *%s) KeyName%s() *%s { x.m.KeyName(%q); return x }\n", t, p, t, c.Name)
		fmt.Fprintf(&b, "func (x *%s) OrderBy%sAsc(fn ...orm.Func) *%s { x.m.OrderBy(%q, false, fn); return x }\n", t, p, t, c.Name)
		fmt.Fprintf(&b, "func (x *%s) OrderBy%sDesc(fn ...orm.Func) *%s { x.m.OrderBy(%q, true, fn); return x }\n", t, p, t, c.Name)
		if numeric(c) {
			fmt.Fprintf(&b, "func (x *%s) Plus%s(n %s) *%s { x.m.Plus(%q, n); return x }\n", t, p, gt, t, c.Name)
			fmt.Fprintf(&b, "func (x *%s) Minus%s(n %s) *%s { x.m.Minus(%q, n); return x }\n", t, p, gt, t, c.Name)
			fmt.Fprintf(&b, "func (x *%s) Sum%s() *%s { x.m.Aggregate(\"sum\", %q); return x }\n", t, p, t, c.Name)
			fmt.Fprintf(&b, "func (x *%s) Avg%s() *%s { x.m.Aggregate(\"avg\", %q); return x }\n", t, p, t, c.Name)
		}
		b.WriteString("\n")
	}
	indexes := make([]string, 0, len(e.Indexes))
	for name := range e.Indexes {
		indexes = append(indexes, name)
	}
	sort.Strings(indexes)
	for _, name := range indexes {
		fmt.Fprintf(&b, "func (x *%s) ForceIndex%s() *%s { x.m.ForceIndex(%q); return x }\n", t, pascal(name), t, name)
	}

	names := make([]string, 0, len(gm.methods))
	for n := range gm.methods {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		b.WriteString("\n")
		b.WriteString(gm.methods[n])
	}
	getters := make([]string, 0, len(gm.getters))
	for n := range gm.getters {
		getters = append(getters, n)
	}
	sort.Strings(getters)
	for _, n := range getters {
		gt := gm.getters[n]
		fmt.Fprintf(&b, "\n// %s returns %s.\nfunc (x *%s) %s() %s { %s }\n", n, gt.origin, t, n, gt.result, gt.expr)
	}
	return writeFormatted(filepath.Join(g.out, e.Name+".go"), b.Bytes())
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

// usage-derived methods

func (g *goGen) fail(pos, format string, args ...any) {
	g.errors = append(g.errors, pos+": "+fmt.Sprintf(format, args...))
}

// addMethod records a generated method; it reports whether it is new.
func (g *goGen) addMethod(gm *goModel, name, code string) bool {
	if _, ok := gm.methods[name]; ok {
		return false
	}
	gm.methods[name] = code
	g.pending = true
	return true
}

func (g *goGen) addGetter(pos string, gm *goModel, name string, gt getter) {
	if gm.static[name] {
		g.fail(pos, "%s.%s is a fixed method; choose another name", gm.typ, name)
		return
	}
	if prev, ok := gm.getters[name]; ok {
		if prev.result != gt.result || prev.expr != gt.expr {
			g.fail(pos, "%s.%s is used for %s and for %s", gm.typ, name, prev.origin, gt.origin)
		}
		return
	}
	gm.getters[name] = gt
	g.pending = true
}

// method generates the method name of model gm; argCount is the number of
// arguments at the call site.
func (g *goGen) method(pos string, gm *goModel, name string, args []argInfo) {
	e, t := gm.e, gm.typ
	switch {
	case name == "":
		return
	case strings.HasPrefix(name, "GetsBy"), strings.HasPrefix(name, "GetBy"), strings.HasPrefix(name, "GetCountBy"):
		prefix := "GetsBy"
		if strings.HasPrefix(name, "GetBy") {
			prefix = "GetBy"
		} else if strings.HasPrefix(name, "GetCountBy") {
			prefix = "GetCountBy"
		}
		keys, err := parseChain(g.m, e, strings.TrimPrefix(name, prefix))
		if err != nil {
			g.fail(pos, "%s.%s: %v", t, name, err)
			return
		}
		params, call, ok := g.chainParams(pos, gm, name, keys, args)
		if !ok {
			return
		}
		var body, result string
		switch prefix {
		case "GetBy":
			result, body = "(*"+t+", error)", "return one"+gm.ctor+"(x.m.By("+g.keysVar(gm, name, keys)+call+"))"
		case "GetsBy":
			result, body = "(*orm.Collection[*"+t+"], error)", "return orm.Gets[*"+t+"](x.m.By("+g.keysVar(gm, name, keys)+call+"))"
		default:
			result, body = "(int64, error)", "return x.m.By("+g.keysVar(gm, name, keys)+call+").GetCount()"
		}
		g.addMethod(gm, name, fmt.Sprintf("func (x *%s) %s%s %s {\n\t%s\n}\n", t, name, params, result, body))
	case strings.HasPrefix(name, "OrderBy"):
		keys, err := parseOrder(e, strings.TrimPrefix(name, "OrderBy"))
		if err != nil {
			g.fail(pos, "%s.%s: %v", t, name, err)
			return
		}
		var body strings.Builder
		for _, k := range keys {
			fmt.Fprintf(&body, "\tx.m.OrderBy(%q, %v, nil)\n", k.column, k.desc)
		}
		g.addMethod(gm, name, fmt.Sprintf("func (x *%s) %s() *%s {\n%s\treturn x\n}\n", t, name, t, body.String()))
	case strings.HasPrefix(name, "LeftJoin"), strings.HasPrefix(name, "Join"):
		kind, rest := "inner", strings.TrimPrefix(name, "Join")
		if strings.HasPrefix(name, "LeftJoin") {
			kind, rest = "left", strings.TrimPrefix(name, "LeftJoin")
		}
		if len(args) != 1 || args[0].model == nil {
			g.fail(pos, "%s.%s takes the joined model", t, name)
			return
		}
		child := args[0].model
		left, right, err := splitPair(g.m, e, child.e, rest)
		if err != nil {
			g.fail(pos, "%s.%s: %v", t, name, err)
			return
		}
		g.addMethod(gm, name, fmt.Sprintf("func (x *%s) %s[C %s](child C) *%s { x.m.Join(%q, %q, %q, child); return x }\n", t, name, g.ownerConstraint(right), t, kind, left, right))
	case strings.HasPrefix(name, "Match"):
		left, right, err := splitPair(g.m, nil, e, strings.TrimPrefix(name, "Match"))
		if err != nil {
			g.fail(pos, "%s.%s: %v", t, name, err)
			return
		}
		g.addMethod(gm, name, fmt.Sprintf("func (x *%s) %s() *%s { x.m.Match(%q, %q); return x }\n", t, name, t, left, right))
	case strings.HasPrefix(name, "Possible") && len(name) > 8:
		col := columnName(g.m, nil, strings.TrimPrefix(name, "Possible"))
		if col == "" {
			g.fail(pos, "%s.%s: no model has the column %s", t, name, strings.TrimPrefix(name, "Possible"))
			return
		}
		g.addMethod(gm, name, fmt.Sprintf("func (x *%s) %s(v any) *%s { x.m.Possible(%q, v); return x }\n", t, name, t, col))
	case strings.HasPrefix(name, "Alias") && len(name) > 5:
		alias := strings.TrimPrefix(name, "Alias")
		g.addMethod(gm, name, fmt.Sprintf("func (x *%s) %s() *%s { x.m.Alias(%q); return x }\n", t, name, t, alias))
	case strings.HasPrefix(name, "New") && len(name) > 3:
		attr := strings.TrimPrefix(name, "New")
		if columnName(g.m, e, attr) != "" {
			g.fail(pos, "%s.%s: %s is a column; use Set%s", t, name, attr, attr)
			return
		}
		key := snake(attr)
		g.addMethod(gm, name, fmt.Sprintf("func (x *%s) %s(v any) *%s { x.m.New(%q, v); return x }\n", t, name, t, key))
		g.addGetter(pos, gm, "Get"+attr, getter{result: "any", expr: fmt.Sprintf("return x.m.NewValue(%q)", key), origin: "the value attached with " + name})
	case strings.HasPrefix(name, "AddRawColumn") && len(name) > 12:
		attr := strings.TrimPrefix(name, "AddRawColumn")
		if !g.outputName(pos, gm, attr) {
			return
		}
		key := snake(attr)
		g.addMethod(gm, name, fmt.Sprintf("func (x *%s) %s(sql string, binds ...any) *%s { x.m.AddRawColumn(%q, sql, binds); return x }\n", t, name, t, key))
		g.addGetter(pos, gm, "Get"+attr, getter{result: "any", expr: fmt.Sprintf("return x.m.NewValue(%q)", key), origin: "the column added with " + name})
	case strings.HasPrefix(name, "AddColumn") && len(name) > 9:
		rest := strings.TrimPrefix(name, "AddColumn")
		if i := strings.Index(rest, "Alias"); i > 0 {
			col := columnName(g.m, e, rest[:i])
			attr := rest[i+5:]
			if col != "" && attr != "" {
				if !g.outputName(pos, gm, attr) {
					return
				}
				key := snake(attr)
				g.addMethod(gm, name, fmt.Sprintf("func (x *%s) %s[F ~string | orm.Func](format F) *%s {\n\tswitch f := any(format).(type) {\n\tcase orm.Func:\n\t\tx.m.AddColumnFunc(%q, %q, f)\n\tdefault:\n\t\tx.m.AddColumnFormat(%q, %q, orm.AsString(f))\n\t}\n\treturn x\n}\n", t, name, t, col, key, col, key))
				g.addGetter(pos, gm, "Get"+attr, getter{result: "any", expr: fmt.Sprintf("return x.m.NewValue(%q)", key), origin: "the column added with " + name})
				return
			}
		}
		if !g.outputName(pos, gm, rest) {
			return
		}
		key := snake(rest)
		g.addMethod(gm, name, fmt.Sprintf("func (x *%s) %s(fn func(*%s) orm.Model) *%s {\n\tx.m.AddColumnSub(%q, func(m orm.Model) orm.Model { return fn(m.(*%s)) })\n\treturn x\n}\n", t, name, t, t, key, t))
		g.addGetter(pos, gm, "Get"+rest, getter{result: "any", expr: fmt.Sprintf("return x.m.NewValue(%q)", key), origin: "the column added with " + name})
	case strings.HasPrefix(name, "Get"):
		// Getters are generated from the calls that define their names.
	default:
		conn, chain := "", name
		if strings.HasPrefix(name, "And") && len(name) > 3 && isUpperAt(name, 3) {
			conn, chain = "and", name[3:]
		} else if strings.HasPrefix(name, "Or") && len(name) > 2 && isUpperAt(name, 2) {
			conn, chain = "or", name[2:]
		}
		keys, err := parseChain(g.m, e, chain)
		if err != nil {
			g.fail(pos, "%s has no method %s: %v", t, name, err)
			return
		}
		params, call, ok := g.chainParams(pos, gm, name, keys, args)
		if !ok {
			return
		}
		g.addMethod(gm, name, fmt.Sprintf("func (x *%s) %s%s *%s {\n\tx.m.Where(%q, %s%s)\n\treturn x\n}\n", t, name, params, t, conn, g.keysVar(gm, name, keys), call))
	}
}

func isUpperAt(s string, i int) bool { return s[i] >= 'A' && s[i] <= 'Z' }

func snake(s string) string {
	var b strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('_')
			}
			b.WriteRune(r + ('a' - 'A'))
			continue
		}
		b.WriteRune(r)
	}
	return b.String()
}

// outputName checks an added column or attached value name against the row
// name space of the model.
func (g *goGen) outputName(pos string, gm *goModel, name string) bool {
	if name == "" {
		g.fail(pos, "%s: an output name is required", gm.typ)
		return false
	}
	if columnName(g.m, gm.e, name) != "" {
		g.fail(pos, "%s: %s is a column name", gm.typ, name)
		return false
	}
	return true
}

func (g *goGen) keysVar(gm *goModel, name string, keys []chainKey) string {
	v := "chain" + gm.ctor + name
	var b strings.Builder
	fmt.Fprintf(&b, "var %s = []orm.ChainKey{", v)
	for _, k := range keys {
		b.WriteString("{")
		if k.conn != "" {
			fmt.Fprintf(&b, "Conn: %q, ", k.conn)
		}
		if k.op != "" {
			fmt.Fprintf(&b, "Op: %q, ", k.op)
		}
		if k.column != "" {
			fmt.Fprintf(&b, "Column: %q, ", k.column)
		}
		if len(k.columns) > 0 {
			b.WriteString("Columns: []string{")
			for i, c := range k.columns {
				if i > 0 {
					b.WriteString(", ")
				}
				b.WriteString(strconv.Quote(c))
			}
			b.WriteString("}, ")
		}
		if k.compare != "" {
			fmt.Fprintf(&b, "Compare: %q", k.compare)
		}
		b.WriteString("}, ")
	}
	b.WriteString("}\n")
	gm.methods["~"+v] = b.String()
	return v
}

// argInfo describes one argument at a call site.
type argInfo struct {
	model      *goModel // the argument is a generated model
	columnFunc bool     // the argument is an orm column function
}

// chainParams builds the generic parameter list of a chain method and the
// argument list passed to Core.Where.
func (g *goGen) chainParams(pos string, gm *goModel, name string, keys []chainKey, args []argInfo) (string, string, bool) {
	var tparams, params, call []string
	trailing := false
	for i, k := range keys {
		p := fmt.Sprintf("v%d", i)
		switch k.op {
		case "fulltext", "fulltext_boolean":
			params = append(params, p+" string")
		case "tuple", "ne_tuple":
			tt := g.tupleType(gm, k.columns)
			params = append(params, p+" []"+tt)
		default:
			c := gm.e.Column(k.column)
			var cons string
			switch {
			case k.compare != "":
				cons = g.ownerConstraint(k.compare)
			case k.op == "" || k.op == "ne":
				cons = g.constraint(c, "eq")
			case k.op == "lk" || k.op == "lb":
				cons = g.constraint(c, "like")
			case k.op == "between":
				cons = g.constraint(c, "between")
			default:
				cons = g.constraint(c, "cmp")
			}
			tp := fmt.Sprintf("T%d", i)
			tparams = append(tparams, tp+" "+cons)
			params = append(params, p+" "+tp)
			if len(keys) == 1 && functionColumn(c) && k.compare == "" && k.op != "between" {
				trailing = true
			}
		}
		call = append(call, p)
	}
	for i, a := range args {
		if a.columnFunc && (len(keys) > 1 || i > 0) {
			g.fail(pos, "%s.%s: a column function is accepted only by a single-key condition", gm.typ, name)
			return "", "", false
		}
	}
	out := ""
	if len(tparams) > 0 {
		out = "[" + strings.Join(tparams, ", ") + "]"
	}
	if trailing {
		params = append(params, "compared ...any")
		return out + "(" + strings.Join(params, ", ") + ")", ", append([]any{" + strings.Join(call, ", ") + "}, compared...)...", true
	}
	return out + "(" + strings.Join(params, ", ") + ")", ", " + strings.Join(call, ", "), true
}

// tupleType returns the generated value group type of a column combination.
func (g *goGen) tupleType(gm *goModel, columns []string) string {
	parts := make([]string, len(columns))
	for i, c := range columns {
		parts[i] = pascal(c)
	}
	name := gm.ctor + strings.Join(parts, "With")
	if _, ok := g.tuples[name]; ok {
		return name
	}
	var b strings.Builder
	fmt.Fprintf(&b, "// %s is one value group of %s.\ntype %s struct {\n", name, strings.Join(columns, ", "), name)
	for _, c := range columns {
		fmt.Fprintf(&b, "\t%s %s\n", pascal(c), goType(gm.e.Column(c)))
	}
	b.WriteString("}\n")
	g.tuples[name] = b.String()
	g.pending = true
	return name
}

// relationGetter records the getter of a relation or join result.
func (g *goGen) relationGetter(pos string, parent, child *goModel, many bool, alias string) {
	name, result := "Get"+child.ctor+"Model", "*"+child.typ
	key := child.e.Name + "_model"
	if many {
		name, result, key = "Get"+child.ctor+"Models", "*orm.Collection[*"+child.typ+"]", child.e.Name+"_models"
	}
	if alias != "" {
		name, key = "Get"+alias, snake(alias)
	}
	if many {
		result = "*orm.Collection[*" + child.typ + "]"
	}
	expr := fmt.Sprintf("v, _ := x.m.Related(%q).(%s)\n\treturn v", key, result)
	origin := "the " + child.e.Name + " relation result"
	g.addGetter(pos, parent, name, getter{result: result, expr: expr, origin: origin})
}
